objects/Accel_Application_Error__c.object
<CustomObject>
    <description>Object to store batch job logs and custom app specific errors.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Accel Application Logs</relationshipLabel>
        <relationshipName>Accel_Application_Logs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>County__c</fullName>
        <formula>Account__r.County_LU__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>County</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Execution_Details__c</fullName>
        <defaultValue>&quot; &quot;</defaultValue>
        <description>Logging for the individual job.</description>
        <inlineHelpText>Logging for the individual job.</inlineHelpText>
        <label>Execution Details</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Initiating_Job_Id__c</fullName>
        <description>The id of the job initial job. ie. if there was a batch job that fired a queueable job or other batch jobs. used the initial batch job id.</description>
        <inlineHelpText>The id of the job initial job. ie. if there was a batch job that fired a queueable job or other batch jobs. used the initial batch job id.</inlineHelpText>
        <label>Initiating Job Id</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>JobType__c</fullName>
        <defaultValue>&quot;BatchApex&quot;</defaultValue>
        <label>JobType</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Future</fullName>
                </value>
                <value>
                    <fullName>SharingRecalculation</fullName>
                </value>
                <value>
                    <fullName>ScheduledApex</fullName>
                </value>
                <value>
                    <fullName>BatchApex</fullName>
                </value>
                <value>
                    <fullName>BatchApexWorker</fullName>
                </value>
                <value>
                    <fullName>TestRequest</fullName>
                </value>
                <value>
                    <fullName>TestWorker</fullName>
                </value>
                <value>
                    <fullName>ApexToken</fullName>
                </value>
                <value>
                    <fullName>Queueable</fullName>
                </value>
                <value>
                    <fullName>MethodName</fullName>
                </value>
                <value>
                    <fullName>Type</fullName>
                </value>
                <value>
                    <fullName>Trigger</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Municipality__c</fullName>
        <formula>Account__r.MunicipalityLookup__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Municipality</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Overall_Job_Status__c</fullName>
        <label>Overall Job Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Processing</fullName>
                </value>
                <value>
                    <fullName>Success</fullName>
                </value>
                <value>
                    <fullName>Partial Success</fullName>
                </value>
                <value>
                    <fullName>Failed</fullName>
                </value>
                <value>
                    <fullName>Rolled Back</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Process_End_Date__c</fullName>
        <label>Process End Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Stack_Trace__c</fullName>
        <label>Stack Trace</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Total_Records_Processed__c</fullName>
        <defaultValue>0</defaultValue>
        <description>The amount of records we are trying to update.</description>
        <inlineHelpText>The amount of records we are trying to update.</inlineHelpText>
        <label>Total Records Processed</label>
        <precision>12</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_Records_Selected__c</fullName>
        <defaultValue>0</defaultValue>
        <description>The total number of records selected. ie. accumulative value of start query records.</description>
        <inlineHelpText>The total number of records selected. ie. accumulative value of start query records.</inlineHelpText>
        <label>Total Records Selected</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_Records_Updated__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Total total number of records for which an update succeeded</description>
        <inlineHelpText>Total total number of records for which an update succeeded</inlineHelpText>
        <label>Total Records Updated</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>User that Triggered the Error</inlineHelpText>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Accel_Application_Errors</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Accel Application Log</label>
    <nameField>
        <displayFormat>Log-{000000}</displayFormat>
        <label>Log #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Accel Application Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Account.object
<CustomObject>
    <fields>
        <fullName>County_Auto_Updated__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates the the County__c was auto updated with FCC (Federal Communication Commission) API Data. https://geo.fcc.gov/api/census/#!/block/get_block_find</description>
        <inlineHelpText>Indicates that the County__c was auto updated with FCC (Federal Communication Commission) API Data.</inlineHelpText>
        <label>County Auto Updated</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>County_LU__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Updated by Google within 1-3 seconds after creating a new account with an address or updating an account to a new address.</description>
        <inlineHelpText>Updated by Google within 1-3 seconds after creating a new account with an address or updating an account to a new address.</inlineHelpText>
        <label>County</label>
        <referenceTo>County__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>County__c</fullName>
        <description>This will be updated about 1-2 minutes after a new account is created or account has changed if there is accurate enough physical location information to determine the county.</description>
        <inlineHelpText>This will be updated about 1-2 minutes after a new account is created or account has changed if there is accurate enough physical location information to determine the county.</inlineHelpText>
        <label>County (TEXT)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Muni_Auto_Updated__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates that the backed end process upon creation or edit (always update as even on creation it doesn&apos;t run till Data.com updates the lat / long) performed an API query to google and used that to populate the muni lookup.</description>
        <inlineHelpText>Indicates that the backed end process upon creation or edit (always update as even on creation it doesn&apos;t run till Data.com updates the lat / long) performed an API query to google and used that to populate the muni lookup.</inlineHelpText>
        <label>Muni Auto Updated</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>MunicipalityLookup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Updated by Google within 1-3 seconds after creating a new account with an address or updating an account to a new address.</inlineHelpText>
        <label>Municipality</label>
        <referenceTo>Municipality__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Location</fullName>
        <active>true</active>
        <label>Location</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/County__c.object
<CustomObject>
    <description>Holds all County related info for states that Accel does gaming business with.</description>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>State</valueSetName>
        </valueSet>
    </fields>
    <label>County</label>
    <nameField>
        <label>County Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Counties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Google_Setting__mdt.object
<CustomObject>
    <description>Settings that contain data about google endpoints</description>
    <fields>
        <fullName>Email_Template_Dev_Name__c</fullName>
        <description>The Development Name (found in EmailTemplate sObject) associated with the template if email is to be sent. This is required if you turn emails on.</description>
        <inlineHelpText>The Development Name (found in EmailTemplate sObject) associated with the template if email is to be sent. This is required if you turn emails on.</inlineHelpText>
        <label>Email Template Dev Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Send_Email_On_Failure__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If checked, the usersnames to email and the email template fields must be populated as well.</description>
        <inlineHelpText>If checked, the usersnames to email and the email template fields must be populated as well.</inlineHelpText>
        <label>Send Email On Failure</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Users__c</fullName>
        <description>The SFDC Username(s), comma delimited, to send an email to.</description>
        <inlineHelpText>The SFDC Username(s), comma delimited, to send an email to.</inlineHelpText>
        <label>Usersnames to email</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Google Setting</label>
    <pluralLabel>Google Settings</pluralLabel>
</CustomObject>

objects/Location.object
<CustomObject>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <length>120</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Warehouses</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Municipality__c.object
<CustomObject>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>State</valueSetName>
        </valueSet>
    </fields>
    <label>Municipality</label>
    <nameField>
        <label>Municipality Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Municipalities</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Record_Updated_Event__e.object
<CustomObject>
    <description>A generic platform event that can be fired when a record is updated outside of the standard platform life-cycle ie. Queueable / Batchable</description>
    <fields>
        <fullName>Record_Ids__c</fullName>
        <description>A comma delimited list of record ids</description>
        <label>Record Ids</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>SObject_API_Name__c</fullName>
        <label>SObject API Name</label>
        <length>64</length>
        <type>Text</type>
    </fields>
    <label>Record Updated Event</label>
    <pluralLabel>Record Updated Events</pluralLabel>
</CustomObject>

globalValueSets/State.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>IL</fullName>
    </customValue>
    <customValue>
        <fullName>MO</fullName>
    </customValue>
    <customValue>
        <fullName>GA</fullName>
    </customValue>
    <customValue>
        <fullName>WV</fullName>
    </customValue>
    <customValue>
        <fullName>AL</fullName>
    </customValue>
    <customValue>
        <fullName>AK</fullName>
    </customValue>
    <customValue>
        <fullName>AZ</fullName>
    </customValue>
    <customValue>
        <fullName>AR</fullName>
    </customValue>
    <customValue>
        <fullName>CA</fullName>
    </customValue>
    <customValue>
        <fullName>CO</fullName>
    </customValue>
    <customValue>
        <fullName>CT</fullName>
    </customValue>
    <customValue>
        <fullName>DE</fullName>
    </customValue>
    <customValue>
        <fullName>FL</fullName>
    </customValue>
    <customValue>
        <fullName>HI</fullName>
    </customValue>
    <customValue>
        <fullName>ID</fullName>
    </customValue>
    <customValue>
        <fullName>IN</fullName>
    </customValue>
    <customValue>
        <fullName>IA</fullName>
    </customValue>
    <customValue>
        <fullName>KS</fullName>
    </customValue>
    <customValue>
        <fullName>KY</fullName>
    </customValue>
    <customValue>
        <fullName>LA</fullName>
    </customValue>
    <customValue>
        <fullName>ME</fullName>
    </customValue>
    <customValue>
        <fullName>MD</fullName>
    </customValue>
    <customValue>
        <fullName>MA</fullName>
    </customValue>
    <customValue>
        <fullName>MI</fullName>
    </customValue>
    <customValue>
        <fullName>MN</fullName>
    </customValue>
    <customValue>
        <fullName>MS</fullName>
    </customValue>
    <customValue>
        <fullName>MT</fullName>
    </customValue>
    <customValue>
        <fullName>NE</fullName>
    </customValue>
    <customValue>
        <fullName>NV</fullName>
    </customValue>
    <customValue>
        <fullName>NH</fullName>
    </customValue>
    <customValue>
        <fullName>PA</fullName>
    </customValue>
    <masterLabel>State</masterLabel>
</GlobalValueSet>

classes/QueueableMuniUpdater.cls
/**
 *
 * parameters: https://developers.google.com/maps/documentation/geocoding/overview#ReverseGeocoding
 * response: https://developers.google.com/maps/documentation/geocoding/overview#reverse-response
 */
global without sharing class QueueableMuniUpdater implements Queueable, Database.AllowsCallouts {

    @TestVisible private final static String API_KEY_MASK = '[removed_api_key]';
    @TestVisible private final static String jobName = 'QueuableMuniUpdater';
    @TestVisible private final static String LATLNG_PARAM = '&latlng=';
    @TestVisible private final static Integer MAX_ACCOUNTS_TO_PROCESS = 100;
    @TestVisible private static Boolean ROLL_IT_BACK = false;
    @TestVisible private static Boolean makeCallout = true;
    @testVisible private static Boolean doChainJob = true;
    @TestVisible private static String TEST_EMAIL_USERNAMES = '';
    @TestVisible private static Boolean SEND_EMAIL = false;

    @TestVisible private Database.SaveResult platformEventSaveResult;

    public Id jobId;

    //  Fed into the queueable via the constructor
    private Set<Id> accountIds = new Set<Id>();

    //  maintain state of internal data.
    public Map<Id, Accel_Application_Error__c> allLogsByAccountId = new Map<Id, Accel_Application_Error__c>();
    public Map<Id, AccountData> accountDataByIds = new Map<Id, AccountData>();
    private Google_Setting__mdt mdt;
    public Integer iNumAccountsWithBadData = 0;

    /**
     * No arg constructor
     */
    global QueueableMuniUpdater() {
        //
    }

    /**
     * 1 arg constructor (assumes we are not rolling back the trans.
     * @param accountIds The account Ids to process
     */
    global QueueableMuniUpdater(Set<Id> accountIds) {
        this.accountIds = accountIds;
        ROLL_IT_BACK = false;
    }

    /**
     * @param accountIds  A Set of account Ids to process
     * @param bRollItBack True if we should roll back the trans, otherwise false.
     *
     * @implNotes
     * Really we should only fire this with accountIds that have a lat/lng value but it will double check
     * on the retrieve query for this as well and discard those accounts.
     */
    global QueueableMuniUpdater(Set<Id> accountIds, boolean bRollItBack) {
        this.accountIds = accountIds;
        ROLL_IT_BACK = bRollItBack;
    }

    /**
     * Implements the queueable execute interface.
     * @param ctx The Queueable context.
     */
    global void execute(QueueableContext ctx) {
        this.jobId = ctx.getJobId();
        if (makeCallout) {
            performExecute();
        }
    }

    /**
     * Main driver in which we do the following steps:
     *
     * 1. Retrieve custom metadata for the job.
     * 2. Retrieve all account data for the account Ids.
     * 3. Call out to Google with the lat, lng on the account.
     * 4. Evaluate the Google response.
     * 5. Attempt to match the google Muni String Name against an accel Municipality__c.Name
     * 6. Update Account.Municipality_LU__c if possible.
     * 7. Insert Accel_Application_Error__c with trans information.
     * 8. Fire a Platform Event to inform clients of any updates of account data.
     * 9. Send Email (on failure only) if custom metadata is set to send email.
     */
    public void performExecute() {

        this.mdt = GoogleSvc.queryForMetadata(GoogleTransaction.GEOCODING.name());

        // Init the accountDataByIds Map with reselected Account data.
        retrieveAccounts();

        //  Perform Callout to Google with lat / long and supplements accountDataByIds Map.
        if (!accountDataByIds.isEmpty()) {
            calloutToProvider(accountDataByIds);
        }

        //  Roll through Google JSON looking for muni data, store results on main Map.
        evalGoogleJson(accountDataByIds);

        //  Match google muni with Accel muni if possible.
        storeMuniInAccountData();
        System.debug('---> final Map=' + accountDataByIds);

        //  Roll through accountDataByIds Map and update Accel accounts with Muni Id if we can.
        updateAccelAccounts();

        //  Create Accel_Application_Error__c sObjects (logs)
        createAccelLogs();

        // Fire a Platform Event to inform clients of change.
        fireAccountUpdatedPlatformEvent();

        // If setup to send emails on an error, send an email to users / template defined in custom metadata.
        if (mdt.Send_Email_On_Failure__c) {
            sendEmail();
        }
        if (doChainJob) {
            QueueableCountyUpdaterLive q = new QueueableCountyUpdaterLive(this.accountIds, false);
            System.enqueueJob(q);
        }
    }

    /**
     * Evaluate the Json Object returned by Google.
     * @param accountDataByIds xx
     */
    public void evalGoogleJson(Map<Id, AccountData> accountDataByIds) {
        //  Add logging details to the the AccountData object in accountDataByIds Map
        for (Id accountId : accountDataByIds.keySet()) {

            AccountData accountData = accountDataByIds.get(accountId);
            Account a = accountData.account;
            Accel_Application_Error__c log = allLogsByAccountId.get(a.Id);
            log.Total_Records_Processed__c = 1;

            if (accountData.calloutException == null) {
                GoogleGeoCodeJsonToApex obj = accountData.jsonObj;
                if (obj != null) {
                    String gMuni;
                    String gState;
                    Boolean foundIt = false;
                    for (GoogleGeoCodeJsonToApex.Results result : obj.results) {
                        if (foundIt) {
                            break;
                        }

                        if (result.types.contains('street_address')) {
                            for (GoogleGeoCodeJsonToApex.Address_components addr : result.address_components) {
                                if (accountData.account.ShippingState == 'PA') {
                                    // @TODO PA Hack! Fix this!
                                    if (addr.types.contains('administrative_area_level_3') && addr.types.contains('political')) {
                                        gMuni = addr.long_name;
                                        System.debug('--- found it for PA1!');
                                        accountData.googleMuniName = gMuni;
                                        foundIt = true;
                                        log.Total_Records_Selected__c = 1;
                                        break;
                                    }
                                } else {
                                    if (addr.types.contains('locality') && addr.types.contains('political')) {
                                        gMuni = addr.long_name;
                                        System.debug('--- found it!');
                                        accountData.googleMuniName = gMuni;
                                        foundIt = true;
                                        log.Total_Records_Selected__c = 1;
                                        break;
                                    }
                                }
                            }
                            //@todo again PA hacking looping through again. fix this!
                            if (!foundIt && accountData.account.ShippingState == 'PA') {
                                for (GoogleGeoCodeJsonToApex.Address_components addr : result.address_components) {
                                    if (addr.types.contains('locality') && addr.types.contains('political')) {
                                        gMuni = addr.long_name;
                                        System.debug('--- found it PA2!');
                                        accountData.googleMuniName = gMuni;
                                        foundIt = true;
                                        log.Total_Records_Selected__c = 1;
                                        break;
                                    }
                                }
                            }


                            for (GoogleGeoCodeJsonToApex.Address_components addr : result.address_components) {
                                if (addr.types.contains('administrative_area_level_1')) {
                                    gState = addr.short_name;
                                    break;
                                }
                            }
                        } else {
                            // yet another hack. @todo figure out the dynamic stuff coming from google better
                            System.debug('----> NO RESULT TYPE OF street_address looking for street_number!');
                            if (result.types.contains('administrative_area_level_3')) {
                                for (GoogleGeoCodeJsonToApex.Address_components addr : result.address_components) {
                                    if (addr.types.contains('administrative_area_level_3') && addr.types.contains('political')) {
                                        gMuni = addr.long_name;
                                        System.debug('--- found it admin level 3 (first level)');
                                        accountData.googleMuniName = gMuni;
                                        foundIt = true;
                                        log.Total_Records_Selected__c = 1;
                                        break;
                                    }
                                }
                                for (GoogleGeoCodeJsonToApex.Address_components addr : result.address_components) {
                                    if (addr.types.contains('administrative_area_level_1')) {
                                        gState = addr.short_name;
                                        break;
                                    }
                                }
                            }

                        }
                    }
                    // Prefix the Muni Name by State for later matching so that we don't run into a bad situation
                    // where w have the same muni name in muliple states. .ie IL_Carol Stream
                    if (gMuni != null) {
                        //accountData.googleMuniName = gState + '_'+accountData.googleMuniName;

                        //System.debug('----> STATE='+gState);
                        log.Execution_Details__c += '\n* Google Muni Name =' + gMuni;
                    } else {
                        log.Execution_Details__c += '\n* xxx Google could not find muni for given address xxxx';
                    }
                    accountData.log = log;
                }
            } else {
                accountData.log.Stack_Trace__c = accountData.calloutException.getStackTraceString();
            }
        }
    }
    /**
     * Find All Accel Municipalities queried from Municipality__c then match the muni
     * name retrieved from google while ensuring it's in the same state as the account.
     * Now for PA.. there is an exception where google does not suffix the muni with borough, city etc.
     * but we have them stored in Accel Municipality__c that way so we need to do our best here on a name match.
     */
    public void storeMuniInAccountData() {
        Map<String, Municipality__c> municipalitiesByName = findMunisByName();
        for (Id accountId : accountDataByIds.keySet()) {
            AccountData data = accountDataByIds.get(accountId);
            if (data.googleMuniName != null) {
                //  'PA Hack'
                data.log.Execution_Details__c += '\n=========== munis by name=' + municipalitiesByName;
                String key = data.account.ShippingState + '_' + data.googleMuniName;
                if (municipalitiesByName.containsKey(key)
                        || municipalitiesByName.containsKey(key + ' Borough')
                        || municipalitiesByName.containsKey(key + ' City')
                        || municipalitiesByName.containsKey(key + ' Township')) {
                    Municipality__c accelMuni = municipalitiesByName.get(key);
                    if (accelMuni == null) {
                        accelMuni = municipalitiesByName.get(key + ' Borough');
                    }
                    if (accelMuni == null) {
                        accelMuni = municipalitiesByName.get(key + ' Township');
                    }
                    if (accelMuni == null) {
                        accelMuni = municipalitiesByName.get(key + ' City');
                    }
                    if (accelMuni.State__c == data.account.ShippingState) {
                        data.muni = accelMuni;
                        data.log.Execution_Details__c += '\n* Found Accel Muni Id = ' + data.muni.Id;
                        data.account.MunicipalityLookup__c = data.muni.Id;
                        data.account.Muni_Auto_Updated__c = true;
                        data.performAccountUpdate = true;
                    } else {
                        data.log.Execution_Details__c += '\n* Found Muni but invalid state';
                    }
                } else {
                    data.userErrorMsg += 'Google Municipality:  ' + data.googleMuniName + ' not found in Accel Municipalities';
                    data.log.Execution_Details__c += '\n* Could not find Accel Muni Id for Google Muni ' + data.googleMuniName;
                    data.log.Overall_Job_Status__c = 'Failed';
                }
            } else {
                data.userErrorMsg += 'Google could not locate a municipality for this location';
                data.log.Execution_Details__c += '\n* ' + data.userErrorMsg;
                data.log.Overall_Job_Status__c = 'Failed';
            }
        }
    }

    /**
     * Retrieve all accounts that are to be updated via the main instance map.
     * Perform Update. set logging data on AccountData object.
     */
    public void updateAccelAccounts() {
        List<Account> accountsToUpdate = getAllAccountsToUpdate(accountDataByIds);

        if (!accountsToUpdate.isEmpty()) {
            System.debug('---> updating: ' + accountsToUpdate.size() + ' accounts');
            List<Database.SaveResult> results = Database.update(accountsToUpdate, false);
            //@todo analyze results
            for (Account account : accountsToUpdate) {
                AccountData accountData = accountDataByIds.get(account.Id);
                accountData.log.Overall_Job_Status__c = 'Success';
                accountData.log.Total_Records_Updated__c = 1;
                accountData.accountUpdateSuccess = true;
            }
        }
    }

    /**
     * Query Municipality__c with the muni names retrieved from Google.
     *
     * @return A Map of StateCode_Muni Name => Muni SFDC Id.
     */
    public Map<String, Municipality__c> findMunisByName() {
        Set<String> allMuniNames = getAllMuniNames(accountDataByIds);

        List<Municipality__c> municipalities = [
                SELECT Id,Name,State__c
                FROM Municipality__c
                WHERE Name IN :allMuniNames
        ];
        Map<String, Municipality__c> municipalitiesByName = new Map<String, Municipality__c>();
        for (Municipality__c muni : municipalities) {
            municipalitiesByName.put(muni.State__c + '_' + muni.Name, muni);
        }
        return municipalitiesByName;
    }

    /**
     * Re-query account info and add to accountDataByIds map.
     */
    public void retrieveAccounts() {

        List<Account> accounts = [
                SELECT Id, Name,County_LU__r.Name,MunicipalityLookup__r.Name,ShippingCity,ShippingState,
                         County_Auto_Updated__c,ShippingLatitude,ShippingLongitude, ShippingGeocodeAccuracy,
                        Muni_Auto_Updated__c

                             //   SELECT Id, Name,County_LU__r.Name,MunicipalityLookup__r.Name,ShippingCity,ShippingState,
                    //    County__c, County_Auto_Updated__c,ShippingLatitude,ShippingLongitude, ShippingGeocodeAccuracy,
                      //  Muni_Auto_Updated__c
                FROM Account
                WHERE ID IN :accountIds
                ORDER BY LastModifiedDate DESC
        ];
        System.debug('----> Total # of accounts using accountIds passed ..' + accounts.size());

        List<Account> accountsToSearch = new List<Account>();
        List<Account> accountsWithBadData = new List<Account>();
        Integer iUpdateCount = 0;
        for (Account account : accounts) {
            AccountData accountData = new AccountData(account);
            accountDataByIds.put(account.Id, accountData);

            if (account.ShippingLatitude != null) {
                if (iUpdateCount < MAX_ACCOUNTS_TO_PROCESS) {
                    accountsToSearch.add(account);
                    accountData.performCallout = true;
                    iUpdateCount++;
                }
            } else {
                // should not happen if this is fired from the trigger but here for safety.
                accountsWithBadData.add(account);
            }
        }
        System.debug('-----> Number of Accounts with Bad Data:' + accountsWithBadData.size());
        System.debug('-----> Number of Accounts to Process:' + accountsToSearch);

        this.iNumAccountsWithBadData += accountsWithBadData.size();
    }

    /**
     * @param accounts A List of accounts to callout with
     * @return
     */
    public void calloutToProvider(Map<Id, AccountData> accountDataByIds) {

        List<Account> allAccounts = getAllAccounts(accountDataByIds);

        Map<Account, GoogleGeoCodeJsonToApex> mAccountsToUpd = new Map<Account, GoogleGeoCodeJsonToApex>();
        Map<Account, GoogleGeoCodeJsonToApex> mFailedAccounts = new Map<Account, GoogleGeoCodeJsonToApex>();

        Http http = new Http();
        HttpRequest httpRequest = GoogleSvc.initHttpRequest(GoogleTransaction.GEOCODING);
        String baseEp = httpRequest.getEndpoint();

        for (Account account : allAccounts) {


            String jsonResponse = '';
            GoogleGeoCodeJsonToApex jsonObj;
            AccountData accountData = accountDataByIds.get(account.Id);
            Accel_Application_Error__c log = this.buildLog();

            log.Account__c = account.Id;
            if (accountData.performCallout) {
                String epSuffix = LATLNG_PARAM + account.ShippingLatitude + ',' + account.ShippingLongitude;
                httpRequest.setEndpoint(baseEp + epSuffix);

                //if (!Test.isRunningTest()) {
                try {
                    HttpResponse res = http.send(httpRequest);
                    String ep = httpRequest.getEndpoint();

                    log.Execution_Details__c += '* Request = ' + maskApiKey(ep) + '\n';
                    if (res.getStatusCode() == GoogleSvc.HTTP_OK) {
                        jsonResponse = res.getBody();
                        jsonObj = GoogleGeoCodeJsonToApex.parse(jsonResponse);
                        System.debug('---> jsonObj=' + jsonObj);
                        log.Execution_Details__c += '\n* ==== Google JSON Response =====  \n';
                        log.Execution_Details__c += JSON.serialize(jsonObj) + '\n';
                        accountData.jsonObj = jsonObj;
                    } else {
                        log.Execution_Details__c += '\n* ==== Invalid Google Response =====  \n';
                        log.Execution_Details__c += '\n* Status Code = ' + res.getStatusCode();
                        log.Overall_Job_Status__c = 'Failed';
                    }
                } catch (Exception e) {
                    System.debug(LoggingLevel.ERROR, e);
                    accountData.calloutException = e;
                    log.Overall_Job_Status__c = 'Failed';
                }
            } else {
                log.Execution_Details__c += '\n* No Callout attempted as there is no lat/long on the Account!';
                log.Overall_Job_Status__c = 'Failed';
            }
            accountData.log = log;
            accountData.jsonObj = jsonObj;
            allLogsByAccountId.put(account.Id, log);
        }
    }

    public void createAccelLogs() {
        List<Accel_Application_Error__c> allLogs = new List<Accel_Application_Error__c>(getAllLogs(accountDataByIds));
        insert allLogs;
        System.debug('--> allLogs=' + allLogs);

        for (Accel_Application_Error__c log : allLogs) {
            log.Process_End_Date__c = System.now();
        }
        update allLogs;
    }

    /**
     * Build (do not insert) an Accel_Application_Error__c sObject.
     *
     * @return  an Accel_Application_Error__c sObject.
     */
    private Accel_Application_Error__c buildLog() {
        Accel_Application_Error__c log = BatchjobSvc.buildLog(jobName);

        log.Overall_Job_Status__c = 'Processing';
        log.Total_Records_Updated__c = 0;
        log.Total_Records_Processed__c = 1;
        log.Total_Records_Selected__c = 0;
        log.Stack_Trace__c = ' ';
        log.Execution_Details__c = ' ';
        log.JobType__c = 'Queueable';
        log.User__c = UserInfo.getUserId();
        log.Initiating_Job_Id__c = this.jobId;

        return log;
    }

    /**
     *  Inner class representing all associated data to the account(s) being processed.
     */
    public class AccountData {

        public Account account;
        public Municipality__c muni;
        public Accel_Application_Error__c log;
        public GoogleGeoCodeJsonToApex jsonObj;
        public String googleMuniName;
        public Boolean performCallout = false;
        public Boolean performAccountUpdate = false;
        public Boolean accountUpdateSuccess = false;
        public Exception calloutException;

        public String userErrorMsg = '';

        public AccountData(Account acct) {
            this.account = acct;
        }
    }
    /**
     * Fire a platform event with an array of account ids so that any subscribing client
     * can be informed that the Account was updated.
     *
     * @param updatedAccounts A Map of AccountId ==> Account sObject
     */
    @TestVisible
    private void fireAccountUpdatedPlatformEvent() {

        Set<Id> accountIds = getAllSuccessfullyUpdatedAccounts(accountDataByIds).keySet();
        Record_Updated_Event__e pe = new Record_Updated_Event__e();

        List<Id> lAccountIds = new List<Id>();
        lAccountIds.addAll(accountIds);
        String sAccountIds = String.join(lAccountIds, ',');
        pe.Record_Ids__c = sAccountIds;
        pe.SObject_API_Name__c = 'Account';

        this.platformEventSaveResult = EventBus.publish(pe);
        System.debug('---> pe Save Result=' + this.platformEventSaveResult);
    }

    /**
     *
     */
    private void sendEmail() {

        String sUserNames = this.mdt.Users__c;
        Set<Id> emailWhoUserIds = new Set<Id>();

        if (Test.isRunningTest() && SEND_EMAIL) {
            sUserNames = TEST_EMAIL_USERNAMES;
            System.debug('----> in Unit Test Mode sUserNames=' + sUserNames);
        }
        if (String.isNotBlank(sUserNames)) {

            List<String> userNames = sUserNames.split(',');
            Map<Id, User> mUsersByIds = new Map<Id, User>([SELECT Id FROM User WHERE UserName IN :userNames]);

            if (!mUsersByIds.isEmpty()) {
                emailWhoUserIds.addAll(mUsersByIds.keySet());
                if (infoExistsToSendEmail(emailWhoUserIds, mdt.Email_Template_Dev_Name__c)) {
                    EmailTemplate t = [SELECT Id FROM EmailTemplate WHERE DeveloperName = :mdt.Email_Template_Dev_Name__c];

                    List<BatchjobSvc.BatchEmailData> batchEmailData = buildEmails(t.Id,accountDataByIds.values(),emailWhoUserIds);
                    List<Messaging.SendEmailResult> sendResults = BatchjobSvc.sendEmailTemplates(batchEmailData);
                    System.debug('---> sendEmailResults='+sendResults);
                }
            }
        }
    }

    /**
     * @param templateId    xx
     * @param accountDatas  xx
     * @param whoIds        xx
     *
     * @return              xx
     */
    private List<BatchjobSvc.BatchEmailData> buildEmails(Id templateId, List<AccountData> accountDatas,Set<Id> whoIds) {

        List<BatchjobSvc.BatchEmailData> batchEmails =  new List<BatchjobSvc.BatchEmailData>();

        for(AccountData accountData : accountDatas) {
            //if(!accountData.accountUpdateSuccess) {
                BatchjobSvc.BatchEmailData data = new BatchjobSvc.BatchEmailData();

                data.templateId = templateId;
                data.dynamicHtml = buildCustomHtml(accountData);
                data.log = accountData.log;
                data.whoIds = whoIds;
                batchEmails.add(data);
            //}
        }
        return batchEmails;
    }

    /**
     * @return true if we have enough info in the custom mdt to send an email, otherwise false.
     */
    private Boolean infoExistsToSendEmail(Set<Id> emailWhoUserIds, String emailTemplateDevName) {
        Boolean sendIt = false;
        sendIt = emailWhoUserIds != null && !emailWhoUserIds.isEmpty() && emailTemplateDevName != null;
        System.debug('---> enough info exists to send email? = ' + sendIt);
        return sendIt;
    }

    /**
     * @param m  A map of AccountId => AccountData
     * @return   A Set of Raw Municipality Names (not prefixed by State)
     *
     * @implNotes
     *          PA is a tough state as google only returns the prefix in it's JSON ie. Pittsburgh
     *          but PA assigns suffixes. ie. city, borough, town etc. we must append when bumping
     *          up against Accel
     */
    private Set<String> getAllMuniNames(Map<Id, AccountData> m) {
        Set<String> muniNames = new Set<String>();

        for (AccountData accountData : m.values()) {
            if (accountData.googleMuniName != null) {
                muniNames.add(accountData.googleMuniName);
                if (accountData.account.ShippingState == 'PA') {
                    muniNames.add(accountData.googleMuniName + ' city');
                    muniNames.add(accountData.googleMuniName + ' borough');
                    muniNames.add(accountData.googleMuniName + ' town');
                }
            }
        }
        return muniNames;
    }

    /**
     * @param m  A map of AccountId => AccountData
     * @return   A Set of Accel_Application_Error__c sObjects.
     */
    private Set<Accel_Application_Error__c> getAllLogs(Map<Id, AccountData> m) {
        Set<Accel_Application_Error__c> logs = new Set<Accel_Application_Error__c>();

        for (AccountData accountData : m.values()) {
            logs.add(accountData.log);
        }
        return logs;
    }

    /**
     * @param m  A map of AccountId => AccountData
     * @return   A List of Account sObjects.
     */
    private List<Account> getAllAccounts(Map<Id, AccountData> m) {
        List<Account> accounts = new List<Account>();
        for (AccountData accountData : m.values()) {
            accounts.add(accountData.account);
        }
        return accounts;
    }
    /**
     * @param m  A map of AccountId => AccountData
     * @return   A List of Account sObjects.
     */
    private List<Account> getAllAccountsToUpdate(Map<Id, AccountData> m) {
        List<Account> accounts = new List<Account>();
        for (AccountData accountData : m.values()) {
            if (accountData.performAccountUpdate) {
                Account account = accountData.account;
                accounts.add(account);
            }
        }
        return accounts;
    }

    /**
     * @param m  A map of AccountId => AccountData
     * @return   A List of Account sObjects.
     */
    private Map<Id, Account> getAllSuccessfullyUpdatedAccounts(Map<Id, AccountData> m) {
        Map<Id, Account> accountsByIds = new Map<Id, Account>();
        for (AccountData accountData : m.values()) {
            if (accountData.accountUpdateSuccess) {
                accountsByIds.put(accountData.account.Id, accountData.account);
            }
        }
        return accountsByIds;
    }

    /**
     * @param ep  The endPoint to Mask.
     * @return    A string with the api key masked.
     */
    @TestVisible
    private static String maskApiKey(String ep) {
        String key = ep.substringBetween('key=', LATLNG_PARAM);
        return ep.replace(key, API_KEY_MASK);
    }


    /**
     * Add opt in / opt out info to the email template.
     *
     * @return valid html to inject into body of the template
     */
    private String buildCustomHtml(AccountData data) {
        String html = '';
        html += '<table border="0" cellpadding="0" cellspacing="0" width="100%">';
        html += '<tbody>';
        html += '<tr>';
        html += '<td style="width:35%"><span style="font-size:12px;">Google Muni Found:</span></td>';
        html += '<td style="width:65%"><span style="font-size:12px;">' + data.googleMuniName + '</span></td>';
        html += '</tr>';
        html += '</tbody>';
        html += '</table>';
        return html;
    }

}