objects/Accel_Application_Error__c.object
<CustomObject>
    <description>Object to store batch job logs and custom app specific errors.</description>
    <fields>
        <fullName>County__c</fullName>
        <formula>Account__r.County_LU__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>County</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Job_Name__c</fullName>
        <label>Job Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Municipality__c</fullName>
        <formula>Account__r.MunicipalityLookup__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Municipality</label>
        <type>Text</type>
    </fields>
    <label>Accel Application Log</label>
    <nameField>
        <displayFormat>Log-{000000}</displayFormat>
        <label>Log #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Accel Application Logs</pluralLabel>
    <recordTypes>
        <fullName>Salesforce_Jobs</fullName>
        <active>true</active>
        <description>Queueable And Apex jobs</description>
        <label>Salesforce Jobs</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Account.object
<CustomObject>
    <fields>
        <fullName>Branding__c</fullName>
        <inlineHelpText>The brand of Account. ie. Accel Entertainment or Tom&apos;s Amusements.</inlineHelpText>
        <label>Branding</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Branding</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>County__c</fullName>
        <description>This will be updated about 1-2 minutes after a new account is created or account has changed if there is accurate enough physical location information to determine the county.</description>
        <inlineHelpText>This will be updated about 1-2 minutes after a new account is created or account has changed if there is accurate enough physical location information to determine the county.</inlineHelpText>
        <label>County (TEXT)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/County__c.object
<CustomObject>
    <description>Holds all County related info for states that Accel does gaming business with.</description>
    <fields>
        <fullName>Covaid_Region__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The Covid Region that this county is associated with. If Not Illinois, Defaults to a bucket Covid Region</inlineHelpText>
        <label>Covid Region</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Region__c.RecordType.Name</field>
                <operation>equals</operation>
                <value>Covid</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Region__c</referenceTo>
        <relationshipLabel>Counties</relationshipLabel>
        <relationshipName>Counties</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>State</valueSetName>
        </valueSet>
    </fields>
    <label>County</label>
    <nameField>
        <label>County Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Counties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Municipality__c.object
<CustomObject>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>State</valueSetName>
        </valueSet>
    </fields>
    <label>Municipality</label>
    <nameField>
        <label>Municipality Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Municipalities</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Region__c.object
<CustomObject>
    <description>Holds Region Related Info. Current Record Types = [Covid]. Can be expanded for other types of regions.  Linked to County and Accounts.</description>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>State</valueSetName>
        </valueSet>
    </fields>
    <label>Region</label>
    <nameField>
        <label>Region Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Regions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

globalValueSets/Branding.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Accel Entertainment</fullName>
        <default>true</default>
        <label>Accel Entertainment</label>
    </customValue>
    <customValue>
        <fullName>Tom&apos;s Amusements</fullName>
    </customValue>
    <masterLabel>Branding</masterLabel>
</GlobalValueSet>

globalValueSets/State.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>IL</fullName>
    </customValue>
    <customValue>
        <fullName>MO</fullName>
    </customValue>
    <customValue>
        <fullName>GA</fullName>
    </customValue>
    <customValue>
        <fullName>WV</fullName>
    </customValue>
    <customValue>
        <fullName>AL</fullName>
    </customValue>
    <customValue>
        <fullName>AK</fullName>
    </customValue>
    <customValue>
        <fullName>AZ</fullName>
    </customValue>
    <customValue>
        <fullName>AR</fullName>
    </customValue>
    <customValue>
        <fullName>CA</fullName>
    </customValue>
    <customValue>
        <fullName>CO</fullName>
    </customValue>
    <customValue>
        <fullName>CT</fullName>
    </customValue>
    <customValue>
        <fullName>DE</fullName>
    </customValue>
    <customValue>
        <fullName>FL</fullName>
    </customValue>
    <customValue>
        <fullName>HI</fullName>
    </customValue>
    <customValue>
        <fullName>ID</fullName>
    </customValue>
    <customValue>
        <fullName>IN</fullName>
    </customValue>
    <customValue>
        <fullName>IA</fullName>
    </customValue>
    <customValue>
        <fullName>KS</fullName>
    </customValue>
    <customValue>
        <fullName>KY</fullName>
    </customValue>
    <customValue>
        <fullName>LA</fullName>
    </customValue>
    <customValue>
        <fullName>ME</fullName>
    </customValue>
    <customValue>
        <fullName>MD</fullName>
    </customValue>
    <customValue>
        <fullName>MA</fullName>
    </customValue>
    <customValue>
        <fullName>MI</fullName>
    </customValue>
    <customValue>
        <fullName>MN</fullName>
    </customValue>
    <customValue>
        <fullName>MS</fullName>
    </customValue>
    <customValue>
        <fullName>MT</fullName>
    </customValue>
    <customValue>
        <fullName>NE</fullName>
    </customValue>
    <customValue>
        <fullName>NV</fullName>
    </customValue>
    <customValue>
        <fullName>NH</fullName>
    </customValue>
    <masterLabel>State</masterLabel>
</GlobalValueSet>

classes/TEST_BatchAccountBrandingUpdater.cls
@IsTest
private class TEST_BatchAccountBrandingUpdater {

    public static String ADMINUNAME = 'acceltestadmin@accel.com';
    public static User uAdmin = TestUtils.getUserForTest(ADMINUNAME);

    @testSetup
    static void setup() {

        System.runAs(uAdmin) {
            Test.startTest();

            List<Municipality__c> munis = TestUtils.createMunicipalities('muni name', 1);
            Account account = TestUtils.buildAccount('account name', munis[0].id);
            account.ShippingStreet = '4916 Main Street Unit 2';
            account.ShippingCity = 'Lisle';
            account.ShippingState = 'IL';  //  Be careful of we implement state / country picklists!
            account.ShippingPostalCode = '60532';
            account.ShippingCountry = 'US';
            account.ShippingLatitude = 41.795778000000000;
            account.ShippingLongitude = -88.075013000000000;
            insert account;

            Region__c region = new Region__c(Name= 'Region 1',State__c = 'IL');
            insert region;

            County__c county = new County__c(Name = 'DuPage',State__c = 'IL', Covaid_Region__c = region.Id);
            insert county;

            munis = TestUtils.createMunicipalities('muni GA name', 1);
            Municipality__c muni = munis[0];
            muni.State__c = 'GA';
            update muni;

            Account account2 = TestUtils.buildAccount('account name', muni.id);
            account2.ShippingStreet = '123 Spring Rd';
            account2.ShippingCity = 'Atlanta';
            account2.ShippingState = 'GA';  //  Be careful of we implement state / country picklists!
            account2.ShippingPostalCode = '30301';
            account2.ShippingCountry = 'US';
            insert account2;

            List<Account> accounts = [SELECT  Id, Branding__c FROM Account];
            for(Account accountx : accounts) {
                accountx.Branding__c = null;
            }
            update accounts;

            Test.stopTest();
        }
    }

    @IsTest
    static void test_Batch_Account_Branding_Updater_Positive() {

        System.runAs(uAdmin) {

            Test.startTest();
            BatchAccountBrandingUpdater b = new BatchAccountBrandingUpdater();
            Database.executeBatch(b,20);

            List<Account> accounts = [SELECT Id FROM Account];
            Map<Id,String> mErrorsByIds = new Map<Id,String>();
            for(Account account : accounts) {
                mErrorsByIds.put(account.Id,'Bogus error');
            }
            b.buildCsvAttachmentAllErrors('error_csv_name',mErrorsByIds);

            Test.stopTest();
        }
    }

    @IsTest
    static void test_Batch_Account_Branding_Updater_RollItBack() {
        Test.startTest();
        BatchAccountBrandingUpdater b = new BatchAccountBrandingUpdater(true);
        Database.executeBatch(b,20);
        Test.stopTest();
    }

    @IsTest
    static void test_Batch_Account_Branding_Updater_Log_Existing() {

        System.runAs(uAdmin) {

            Test.startTest();

            String jobName = 'BatchAccountBrandingUpdater';
            String rtDevName ='Salesforce_Jobs';
            Id rtId =  SObjectType.Accel_Application_Error__c.getRecordTypeInfosByDeveloperName().get(rtDevName).getRecordTypeId();
            Accel_Application_Error__c log = new Accel_Application_Error__c(RecordTypeId = rtId, Job_Name__c = jobName);
            insert log;
            BatchAccountBrandingUpdater b = new BatchAccountBrandingUpdater();
            Database.executeBatch(b,20);
            Test.stopTest();

        }
    }

}