objects/Accel_Application_Error__c.object
<CustomObject>
    <description>Object to store batch job logs and custom app specific errors.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Accel Application Logs</relationshipLabel>
        <relationshipName>Accel_Application_Logs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Execution_Details__c</fullName>
        <defaultValue>&quot; &quot;</defaultValue>
        <description>Logging for the individual job.</description>
        <inlineHelpText>Logging for the individual job.</inlineHelpText>
        <label>Execution Details</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Job_Name__c</fullName>
        <label>Job Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Accel Application Log</label>
    <nameField>
        <displayFormat>Log-{000000}</displayFormat>
        <label>Log #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Accel Application Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Asset.object
<CustomObject>
    <fields>
        <fullName>BV_Type__c</fullName>
        <description>Bill Vaildator Type</description>
        <label>BV Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>JCM</fullName>
                </value>
                <value>
                    <fullName>MEI</fullName>
                    <default>true</default>
                    <label>MEI</label>
                </value>
                <value>
                    <fullName>Small MEI</fullName>
                </value>
                <value>
                    <fullName>NV-200</fullName>
                </value>
                <value>
                    <fullName>ICT PA7</fullName>
                </value>
                <value>
                    <fullName>ICT TAO-A</fullName>
                </value>
                <value>
                    <fullName>MEI2831U</fullName>
                </value>
                <value>
                    <fullName>MEI SC Advance</fullName>
                </value>
                <value>
                    <fullName>JCM UBA10</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Meter_Reading__c.object
<CustomObject>
    <description>Example object to capture electronic meters</description>
    <fields>
        <fullName>BV_Type__c</fullName>
        <description>Asset.BV_Type__c Since the picklist on Asset was not global this must be synchronized with those values for now. Written upon creation of meter_reading__c and used by DLRS to rollup to RPS</description>
        <inlineHelpText>Asset.BV_Type__c Since the picklist on Asset was not global this must be synchronized with those values for now. Written upon creation of meter_reading__c and used by DLRS to rollup to RPS</inlineHelpText>
        <label>BV Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>JCM</fullName>
                </value>
                <value>
                    <fullName>MEI</fullName>
                </value>
                <value>
                    <fullName>Small MEI</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Route_Processing_Sheet__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Route Processing Sheet</label>
        <referenceTo>Route_Processing_Sheet__c</referenceTo>
        <relationshipLabel>Meter Readings</relationshipLabel>
        <relationshipName>Meter_Readings</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Meter Reading</label>
    <nameField>
        <displayFormat>MTR-{000000000}</displayFormat>
        <label>Meter Reading ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Meter Readings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Route_Processing_Sheet__c.object
<CustomObject>
    <description>Example digitization of the route processing sheet</description>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account DBA</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Route Processing Sheets</relationshipLabel>
        <relationshipName>Route_Processing_Sheets</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Route Processing Sheet</label>
    <nameField>
        <displayFormat>Collection-Id-{000000000}</displayFormat>
        <label>Collection ID Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Route Processing Sheets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/clBatchMeterReadingsCreationTest.cls
/**
 * Created by rnend on 8/12/2021.
 */

@IsTest
private class clBatchMeterReadingsCreationTest {
    /**
     * NOTE start / stop test merely there to reset gov limits as creating non cl data takes forever given
     * all the processors / flows and eventually will bust cpu time outs on it's own.
     */
    @TestSetup
    static void setupData() {

        Test.startTest();
        Map<String,Object> mBaseData = clTESTUTILS.createAllNonClData();
        Test.stopTest();

        Map<String,Object> mClData =  clTESTUTILS.createEnd2EndRouteData(mBaseData);
    }


    @IsTest
    static void test_exeBatch() {

        Map<Id,Route_Processing_Sheet__c> m = new Map<Id,Route_Processing_Sheet__c>([SELECT Id FROM Route_Processing_Sheet__c LIMIT 2]);
        Test.startTest();

        clBatchMeterReadingsCreation b = new clBatchMeterReadingsCreation(m.keySet());
        Database.executeBatch(b,2);

        Test.stopTest();


        Map<Id,Meter_Reading__c> mMeters = clMeterSvc.retrieveRpsMeterReadings(m.values()[0].Id);
        for(Meter_Reading__c mr : mMeters.values()) {
            System.assertEquals(mr.BV_Type__c,clTESTUTILS.ASSET_BV_TYPE_JCM);
        }
    }

    @IsTest
    static void test_exeBatch_no_assets() {

        Map<Id,Route_Processing_Sheet__c> m = new Map<Id,Route_Processing_Sheet__c>(
            [SELECT Id,Account__c FROM Route_Processing_Sheet__c LIMIT 2]
        );

        Set<Id> accountIds = new Set<Id>();
        for(Route_Processing_Sheet__c rps : m.values()) {
            accountIds.add(rps.Account__c);
        }
        List<Meter_Reading__c> mrs = [SELECT Id FROM Meter_Reading__c];
        Boolean deleteFailed = false;
        try {
            delete mrs; //  DELETE Any existing test meter readings created in the setup method.
        } catch (Exception e) {
            deleteFailed = true;
            System.debug(LoggingLevel.INFO,e);  // @todo org prevented deletes will make this crash!
        }
        List<Asset> assets = [SELECT Id FROM Asset WHERE AccountId IN :accountIds];
        delete assets; // DELETE Test Assets for locations for rps sheets in test ctx.

        Test.startTest();

        clBatchMeterReadingsCreation b = new clBatchMeterReadingsCreation(m.keySet());
        Database.executeBatch(b,2);

        Test.stopTest();


        Map<Id,Meter_Reading__c> mMeters = clMeterSvc.retrieveRpsMeterReadings(m.values()[0].Id);
        System.debug('---> meters='+mMeters);
        if(!deleteFailed) {
            System.assert(mMeters.isEmpty());
        }
    }

    @IsTest
    static void test_exeBatch_logging() {

        Map<Id,Route_Processing_Sheet__c> m = new Map<Id,Route_Processing_Sheet__c>([SELECT Id FROM Route_Processing_Sheet__c LIMIT 2]);
        Test.startTest();

        clBatchMeterReadingsCreation b = new clBatchMeterReadingsCreation(m.keySet());
        Database.executeBatch(b,2);

        Test.stopTest();

        Accel_Application_Error__c log = [
                SELECT Id,Job_Name__c,Execution_Details__c
                FROM   Accel_Application_Error__c
                WHERE  Job_Name__c = 'clBatchMetersCreation'
                AND    CreatedDate = TODAY
        ];
        System.debug('---> exelog='+log.Execution_Details__c);
        System.assert(log.Execution_Details__c.contains('RPSMeterIds'));
    }
}