objects/Accel_Application_Error__c.object
<CustomObject>
    <description>Object to store batch job logs and custom app specific errors.</description>
    <fields>
        <fullName>Municipality__c</fullName>
        <formula>Account__r.MunicipalityLookup__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Municipality</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Overall_Job_Status__c</fullName>
        <label>Overall Job Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Processing</fullName>
                </value>
                <value>
                    <fullName>Success</fullName>
                </value>
                <value>
                    <fullName>Partial Success</fullName>
                </value>
                <value>
                    <fullName>Failed</fullName>
                </value>
                <value>
                    <fullName>Rolled Back</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Accel Application Log</label>
    <nameField>
        <displayFormat>Log-{000000}</displayFormat>
        <label>Log #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Accel Application Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Municipality__c.object
<CustomObject>
    <label>Municipality</label>
    <nameField>
        <label>Municipality Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Municipalities</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/TEST_BatchSample.cls
@IsTest
private class TEST_BatchSample {

    public static String USERNAME_ADMIN = 'acceladmintest@accel.com';

    @testSetup
    static void setup() {

        Integer iNmbrOfMunis=2, iNbrOfAccountsPerMuni = 20;

        User adminUser = TestUtils.getUserForTest(USERNAME_ADMIN);

        System.runAs(adminUser) {

            List<Municipality__c> munis = TestUtils.createMunicipalities('TEST Muni', iNmbrOfMunis);
            List<Account> accounts = buildAccountsForMunis(munis,iNbrOfAccountsPerMuni);
            insert accounts;
        }
    }

    @isTest
    static void test_fireBatch_Success() {

        User adminUser = TestUtils.getUserForTest(USERNAME_ADMIN);

        System.runAs(adminUser) {
            Test.startTest();
            Integer iBatchSize = 50;

            BatchSample b = new BatchSample(iBatchSize);

            Id jobId = Database.executeBatch(b,iBatchSize);
            Test.stopTest();

            Accel_Application_Error__c log = AppLogSvc.retrieveLog(b.log.Id);
            System.debug('----> log='+log);
            System.assertEquals(log.Overall_Job_Status__c,'Success');
        }
    }
    @isTest
    static void test_fireBatch_PartialSuccess() {

        User adminUser = TestUtils.getUserForTest(USERNAME_ADMIN);

        System.runAs(adminUser) {
            Test.startTest();
            Integer iBatchSize = 50;

            BatchSample.FORCE_PARTIAL_DML_EXCEPTION = true;
            BatchSample b = new BatchSample(iBatchSize);

            Id jobId = Database.executeBatch(b,iBatchSize);
            Test.stopTest();

            Accel_Application_Error__c log = AppLogSvc.retrieveLog(b.log.Id);
            System.debug('----> log='+log);
            //System.assertEquals(log.Overall_Job_Status__c,'Success');
        }
    }
    /**
     * @param munis
     * @param iNmbrOfAccountsPerMuni
     *
     * @return
     * @todo move to TestUtils
     */
    static List<Account> buildAccountsForMunis(List<Municipality__c> munis,Integer iNmbrOfAccountsPerMuni) {
        List<Account> accounts = new List<Account>();

        for (Municipality__c muni : munis) {
            for (Integer i = 0; i < iNmbrOfAccountsPerMuni; i++) {
                Account account = TestUtils.buildAccount('Test Account ' + i, muni.Id);
                accounts.add(account);
            }
        }
        return accounts;
    }
}