objects/Accel_Application_Error__c.object
<CustomObject>
    <description>Object to store batch job logs and custom app specific errors.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Accel Application Logs</relationshipLabel>
        <relationshipName>Accel_Application_Logs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>County__c</fullName>
        <formula>Account__r.County_LU__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>County</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Job_Name__c</fullName>
        <label>Job Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Municipality__c</fullName>
        <formula>Account__r.MunicipalityLookup__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Municipality</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Overall_Job_Status__c</fullName>
        <label>Overall Job Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Processing</fullName>
                </value>
                <value>
                    <fullName>Success</fullName>
                </value>
                <value>
                    <fullName>Partial Success</fullName>
                </value>
                <value>
                    <fullName>Failed</fullName>
                </value>
                <value>
                    <fullName>Rolled Back</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Accel Application Log</label>
    <nameField>
        <displayFormat>Log-{000000}</displayFormat>
        <label>Log #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Accel Application Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Account.object
<CustomObject>
    <fields>
        <fullName>County_Auto_Updated__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates the the County__c was auto updated with FCC (Federal Communication Commission) API Data. https://geo.fcc.gov/api/census/#!/block/get_block_find</description>
        <inlineHelpText>Indicates that the County__c was auto updated with FCC (Federal Communication Commission) API Data.</inlineHelpText>
        <label>County Auto Updated</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>County__c</fullName>
        <description>This will be updated about 1-2 minutes after a new account is created or account has changed if there is accurate enough physical location information to determine the county.</description>
        <inlineHelpText>This will be updated about 1-2 minutes after a new account is created or account has changed if there is accurate enough physical location information to determine the county.</inlineHelpText>
        <label>County (TEXT)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Muni_Auto_Updated__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates that the backed end process upon creation or edit (always update as even on creation it doesn&apos;t run till Data.com updates the lat / long) performed an API query to google and used that to populate the muni lookup.</description>
        <inlineHelpText>Indicates that the backed end process upon creation or edit (always update as even on creation it doesn&apos;t run till Data.com updates the lat / long) performed an API query to google and used that to populate the muni lookup.</inlineHelpText>
        <label>Muni Auto Updated</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>MunicipalityLookup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Updated by Google within 1-3 seconds after creating a new account with an address or updating an account to a new address.</inlineHelpText>
        <label>Municipality</label>
        <referenceTo>Municipality__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/County__c.object
<CustomObject>
    <description>Holds all County related info for states that Accel does gaming business with.</description>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>State</valueSetName>
        </valueSet>
    </fields>
    <label>County</label>
    <nameField>
        <label>County Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Counties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Google_Setting__mdt.object
<CustomObject>
    <description>Settings that contain data about google endpoints</description>
    <fields>
        <fullName>Http_Method__c</fullName>
        <defaultValue>&quot;GET&quot;</defaultValue>
        <description>ie. POST,PUT,GET etc</description>
        <inlineHelpText>ie. POST,PUT,GET etc</inlineHelpText>
        <label>Http Method</label>
        <length>16</length>
        <type>Text</type>
    </fields>
    <label>Google Setting</label>
    <pluralLabel>Google Settings</pluralLabel>
</CustomObject>

objects/Municipality__c.object
<CustomObject>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>State</valueSetName>
        </valueSet>
    </fields>
    <label>Municipality</label>
    <nameField>
        <label>Municipality Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Municipalities</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

globalValueSets/State.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>IL</fullName>
    </customValue>
    <customValue>
        <fullName>MO</fullName>
    </customValue>
    <customValue>
        <fullName>GA</fullName>
    </customValue>
    <customValue>
        <fullName>WV</fullName>
    </customValue>
    <customValue>
        <fullName>AL</fullName>
    </customValue>
    <customValue>
        <fullName>AK</fullName>
    </customValue>
    <customValue>
        <fullName>AZ</fullName>
    </customValue>
    <customValue>
        <fullName>AR</fullName>
    </customValue>
    <customValue>
        <fullName>CA</fullName>
    </customValue>
    <customValue>
        <fullName>CO</fullName>
    </customValue>
    <customValue>
        <fullName>CT</fullName>
    </customValue>
    <customValue>
        <fullName>DE</fullName>
    </customValue>
    <customValue>
        <fullName>FL</fullName>
    </customValue>
    <customValue>
        <fullName>HI</fullName>
    </customValue>
    <customValue>
        <fullName>ID</fullName>
    </customValue>
    <customValue>
        <fullName>IN</fullName>
    </customValue>
    <customValue>
        <fullName>IA</fullName>
    </customValue>
    <customValue>
        <fullName>KS</fullName>
    </customValue>
    <customValue>
        <fullName>KY</fullName>
    </customValue>
    <customValue>
        <fullName>LA</fullName>
    </customValue>
    <customValue>
        <fullName>ME</fullName>
    </customValue>
    <customValue>
        <fullName>MD</fullName>
    </customValue>
    <customValue>
        <fullName>MA</fullName>
    </customValue>
    <customValue>
        <fullName>MI</fullName>
    </customValue>
    <customValue>
        <fullName>MN</fullName>
    </customValue>
    <customValue>
        <fullName>MS</fullName>
    </customValue>
    <customValue>
        <fullName>MT</fullName>
    </customValue>
    <customValue>
        <fullName>NE</fullName>
    </customValue>
    <customValue>
        <fullName>NV</fullName>
    </customValue>
    <customValue>
        <fullName>NH</fullName>
    </customValue>
    <customValue>
        <fullName>PA</fullName>
    </customValue>
    <masterLabel>State</masterLabel>
</GlobalValueSet>

classes/TEST_QueueableMuniUpdater.cls
@IsTest
private class TEST_QueueableMuniUpdater {

    public static String ADMINUNAME = 'acceltestadmin@accel.com';
    public static User uAdmin = TestUtils.getUserForTest(ADMINUNAME);

    @testSetup
    static void setup() {

        System.runAs(uAdmin) {
            Test.startTest();

            List<Municipality__c> munisIL = TestUtils.createMunicipalities('Carol Stream', 1);
            for(Municipality__c muni : munisIL) {
                muni.Name = muni.Name.replace('0','');
            }
            update munisIL;


            List<Municipality__c> munisPA = TestUtils.createMunicipalities(' Warminster Township', 1);
            munisPA.addAll(TestUtils.createMunicipalities('Brookville Borough', 1));
            munisPA.addAll(TestUtils.createMunicipalities('New Milford Township', 1));

            for(Municipality__c muni : munisPA) {
                muni.Name = muni.Name.replace('0','');
                muni.State__c = 'PA';
            }
            update munisPA;


            List<Account> accounts = new List<Account>();

            Account account = TestUtils.buildAccount('account name', munisIL[0].id);
            account.MunicipalityLookup__c = null;
            account.ShippingStreet = '4916 Main Street Unit 2';
            account.ShippingCity = 'Lisle';
            account.ShippingState = 'IL';  //  Be careful of we implement state / country picklists!
            account.ShippingPostalCode = '60532';
            account.ShippingCountry = 'US';
            account.ShippingLatitude = 41.795778000000000;
            account.ShippingLongitude = -88.075013000000000;
            account.County_Auto_Updated__c = true;
            accounts.add(account);

            Account account2 = TestUtils.buildAccount('PA Township account name', munisPA[0].id);
            account2.MunicipalityLookup__c = null;
            account2.ShippingStreet = '890 E Street Rd';
            account2.ShippingCity = 'Warminster';
            account2.ShippingState = 'PA';  //  Be careful of we implement state / country picklists!
            account2.ShippingPostalCode = '18974';
            account2.ShippingCountry = 'US';
            account2.ShippingLatitude = 40.183761000000000;
            account2.ShippingLongitude = -75.058859000000000;
            account2.County_Auto_Updated__c = true;
            accounts.add(account2);


            Account account3 = TestUtils.buildAccount('PA Borough account name', munisPA[1].id);
            account3.MunicipalityLookup__c = null;
            account3.ShippingStreet = '245 Allegheny Blvd Ste A';
            account3.ShippingCity = 'Brookville';
            account3.ShippingState = 'PA';  //  Be careful of we implement state / country picklists!
            account3.ShippingPostalCode = '15825';
            account3.ShippingCountry = 'US';
            account3.ShippingLatitude = 41.172705000000000;
            account3.ShippingLongitude = -79.100586000000000;
            account3.County_Auto_Updated__c = true;
            accounts.add(account3);

            Account account4 = TestUtils.buildAccount('PA Township street num as opposed to addy name', munisPA[2].id);
            account4.MunicipalityLookup__c = null;
            account4.ShippingStreet = '1623 Oliver Rd # Exit219';
            account4.ShippingCity = 'New Milford';
            account4.ShippingState = 'PA';  //  Be careful of we implement state / country picklists!
            account4.ShippingPostalCode = '18834';
            account4.ShippingCountry = 'US';
            account4.ShippingLatitude = 41.8673559;
            account4.ShippingLongitude = -75.6906241;
            account4.County_Auto_Updated__c = true;
            accounts.add(account4);


            insert accounts;

            Test.stopTest();
        }
    }

    @IsTest
    static void test_Queueable_Muni_Updater_Positive() {

        Account account = [
                SELECT  Id,  County_Auto_Updated__c,ShippingLatitude,ShippingLongitude,MunicipalityLookup__c
                     //   SELECT  Id, County__c, County_Auto_Updated__c,ShippingLatitude,ShippingLongitude,MunicipalityLookup__c

                FROM    Account
                WHERE ShippingStreet = '4916 Main Street Unit 2'
        ];
        System.assert(account.MunicipalityLookup__c == null);
        Set<Id> accountIds = new Set<Id>{account.Id};

        String googleResponse = TEST_GoogleGeocodeJsonToApex.testJsonValidMuni;
        Google_Setting__mdt mdt = GoogleSvc.queryForMetadata(GoogleTransaction.GEOCODING.name());
        HttpRequest httpRequest = GoogleSvc.initHttpRequest(GoogleTransaction.GEOCODING);
        String ep = httpRequest.getEndpoint() + '&latlng='+account.ShippingLatitude + ',' + account.ShippingLongitude;


        MockHttpResponseHandler.SimpleMockResponse getResp =
                new MockHttpResponseHandler.SimpleMockResponse(mdt.Http_Method__c, googleResponse);

        MockHttpResponseHandler mock = new MockHttpResponseHandler();
        System.debug('---> mock ep = ' + ep);
        mock.addResponse(ep, getResp);
        Test.setMock(HttpCalloutMock.class, mock);

        System.runAs(uAdmin) {

            Test.startTest();

            QueueableMuniUpdater qNoArgs = new QueueableMuniUpdater();
            QueueableMuniUpdater qOneArg = new QueueableMuniUpdater(accountIds);
            QueueableMuniUpdater qPrimary = new QueueableMuniUpdater(accountIds,false);

            qPrimary.performExecute();
            Test.getEventBus().deliver();

            Test.stopTest();

            Account a = [SELECT Id, MunicipalityLookup__c,Muni_Auto_Updated__c FROM Account WHERE Id = :account.Id ];
            System.assert(a.MunicipalityLookup__c != null);
            System.assert(a.Muni_Auto_Updated__c);

            Accel_Application_Error__c log = [
                    SELECT Id, Overall_Job_Status__c,Account__c
                    FROM   Accel_Application_Error__c
                    WHERE  Account__c = :account.Id
                    AND    Job_Name__c = :QueueableMuniUpdater.jobName
            ];
            System.assert(log.Overall_Job_Status__c == 'Success');
            System.assert(qPrimary.platformEventSaveResult.success);

        }
    }

    @IsTest
    static void test_Queueable_Muni_Updater_PA_Township_Positive() {

        Account account = [
                SELECT  Id, County_Auto_Updated__c,ShippingLatitude,ShippingLongitude,MunicipalityLookup__c
                     //   SELECT  Id, County__c, County_Auto_Updated__c,ShippingLatitude,ShippingLongitude,MunicipalityLookup__c

                FROM    Account
                WHERE ShippingStreet = '890 E Street Rd'
        ];
        System.assert(account.MunicipalityLookup__c == null);
        Set<Id> accountIds = new Set<Id>{account.Id};

        String googleResponse = TEST_GoogleGeocodeJsonToApex.testJsonValidMuniPATownship;
        Google_Setting__mdt mdt = GoogleSvc.queryForMetadata(GoogleTransaction.GEOCODING.name());
        HttpRequest httpRequest = GoogleSvc.initHttpRequest(GoogleTransaction.GEOCODING);
        String ep = httpRequest.getEndpoint() + '&latlng='+account.ShippingLatitude + ',' + account.ShippingLongitude;


        MockHttpResponseHandler.SimpleMockResponse getResp =
                new MockHttpResponseHandler.SimpleMockResponse(mdt.Http_Method__c, googleResponse);

        MockHttpResponseHandler mock = new MockHttpResponseHandler();
        System.debug('---> mock ep = ' + ep);
        mock.addResponse(ep, getResp);
        Test.setMock(HttpCalloutMock.class, mock);

        System.runAs(uAdmin) {

            Test.startTest();

            QueueableMuniUpdater qPrimary = new QueueableMuniUpdater(accountIds,false);

            qPrimary.performExecute();
            Test.getEventBus().deliver();

            Test.stopTest();

            Account a = [SELECT Id, MunicipalityLookup__c,Muni_Auto_Updated__c FROM Account WHERE Id = :account.Id ];
            System.assert(a.MunicipalityLookup__c != null);
            System.assert(a.Muni_Auto_Updated__c);

            Accel_Application_Error__c log = [
                    SELECT Id, Overall_Job_Status__c,Account__c
                    FROM   Accel_Application_Error__c
                    WHERE  Account__c = :account.Id
                    AND    Job_Name__c = :QueueableMuniUpdater.jobName
            ];
            System.assert(log.Overall_Job_Status__c == 'Success');
            System.assert(qPrimary.platformEventSaveResult.success);

        }
    }

    @IsTest
    static void test_Queueable_Muni_Updater_PA_Borough_Positive() {

        Account account = [
                SELECT  Id,  County_Auto_Updated__c,ShippingLatitude,ShippingLongitude,MunicipalityLookup__c
                       // SELECT  Id, County__c, County_Auto_Updated__c,ShippingLatitude,ShippingLongitude,MunicipalityLookup__c

                FROM    Account
                WHERE ShippingStreet = '245 Allegheny Blvd Ste A'
        ];
        System.assert(account.MunicipalityLookup__c == null);
        Set<Id> accountIds = new Set<Id>{account.Id};

        String googleResponse = TEST_GoogleGeocodeJsonToApex.testJsonValidMuniPABorough;
        Google_Setting__mdt mdt = GoogleSvc.queryForMetadata(GoogleTransaction.GEOCODING.name());
        HttpRequest httpRequest = GoogleSvc.initHttpRequest(GoogleTransaction.GEOCODING);
        String ep = httpRequest.getEndpoint() + '&latlng='+account.ShippingLatitude + ',' + account.ShippingLongitude;


        MockHttpResponseHandler.SimpleMockResponse getResp =
                new MockHttpResponseHandler.SimpleMockResponse(mdt.Http_Method__c, googleResponse);

        MockHttpResponseHandler mock = new MockHttpResponseHandler();
        System.debug('---> mock ep = ' + ep);
        mock.addResponse(ep, getResp);
        Test.setMock(HttpCalloutMock.class, mock);

        System.runAs(uAdmin) {

            Test.startTest();

            QueueableMuniUpdater qPrimary = new QueueableMuniUpdater(accountIds,false);

            qPrimary.performExecute();
            Test.getEventBus().deliver();

            Test.stopTest();

            Account a = [SELECT Id, MunicipalityLookup__c,Muni_Auto_Updated__c FROM Account WHERE Id = :account.Id ];
            System.assert(a.MunicipalityLookup__c != null);
            System.assert(a.Muni_Auto_Updated__c);

            Accel_Application_Error__c log = [
                    SELECT Id, Overall_Job_Status__c,Account__c
                    FROM   Accel_Application_Error__c
                    WHERE  Account__c = :account.Id
                    AND    Job_Name__c = :QueueableMuniUpdater.jobName
            ];
            System.assert(log.Overall_Job_Status__c == 'Success');
            System.assert(qPrimary.platformEventSaveResult.success);

        }
    }
    /**
     * kinda a shitty address on the account. closest we can come is street number as opposed to street address
     * JSOn shape changes.
     */
    @IsTest
    static void test_Queueable_Muni_Updater_PA_Street_Number_Positive() {

        Account account = [
                SELECT  Id,  County_Auto_Updated__c,ShippingLatitude,ShippingLongitude,MunicipalityLookup__c
                      //  SELECT  Id, County__c, County_Auto_Updated__c,ShippingLatitude,ShippingLongitude,MunicipalityLookup__c

                FROM    Account
                WHERE ShippingStreet = '1623 Oliver Rd # Exit219'
        ];
        System.assert(account.MunicipalityLookup__c == null);
        Set<Id> accountIds = new Set<Id>{account.Id};

        String googleResponse = TEST_GoogleGeocodeJsonToApex.testJsonValidMuniStreetNumber;
        Google_Setting__mdt mdt = GoogleSvc.queryForMetadata(GoogleTransaction.GEOCODING.name());
        HttpRequest httpRequest = GoogleSvc.initHttpRequest(GoogleTransaction.GEOCODING);
        String ep = httpRequest.getEndpoint() + '&latlng='+account.ShippingLatitude + ',' + account.ShippingLongitude;


        MockHttpResponseHandler.SimpleMockResponse getResp =
                new MockHttpResponseHandler.SimpleMockResponse(mdt.Http_Method__c, googleResponse);

        MockHttpResponseHandler mock = new MockHttpResponseHandler();
        System.debug('---> mock ep = ' + ep);
        mock.addResponse(ep, getResp);
        Test.setMock(HttpCalloutMock.class, mock);

        System.runAs(uAdmin) {

            Test.startTest();

            QueueableMuniUpdater qPrimary = new QueueableMuniUpdater(accountIds,false);

            qPrimary.performExecute();
            Test.getEventBus().deliver();

            Test.stopTest();

            Account a = [SELECT Id, MunicipalityLookup__c,Muni_Auto_Updated__c FROM Account WHERE Id = :account.Id ];
            System.assert(a.MunicipalityLookup__c != null);
            System.assert(a.Muni_Auto_Updated__c);

            Accel_Application_Error__c log = [
                    SELECT Id, Overall_Job_Status__c,Account__c
                    FROM   Accel_Application_Error__c
                    WHERE  Account__c = :account.Id
                    AND    Job_Name__c = :QueueableMuniUpdater.jobName
            ];
            System.assert(log.Overall_Job_Status__c == 'Success');
            System.assert(qPrimary.platformEventSaveResult.success);

        }
    }
    @IsTest
    static void test_Queueable_Muni_Gmuni_Not_Found_In_Accel() {

        Account account = [
                SELECT  Id,  County_Auto_Updated__c,ShippingLatitude,ShippingLongitude,MunicipalityLookup__c,
                        Muni_Auto_Updated__c
                               // SELECT  Id, County__c, County_Auto_Updated__c,ShippingLatitude,ShippingLongitude,MunicipalityLookup__c,
                       // Muni_Auto_Updated__c
                FROM    Account
                WHERE ShippingStreet = '4916 Main Street Unit 2'
        ];
        System.assert(account.MunicipalityLookup__c == null);
        System.assert(!account.Muni_Auto_Updated__c);
        Set<Id> accountIds = new Set<Id>{account.Id};

        String getResponse = TEST_GoogleGeocodeJsonToApex.testJsonInValidMuni;
        Google_Setting__mdt mdt = GoogleSvc.queryForMetadata(GoogleTransaction.GEOCODING.name());
        HttpRequest httpRequest = GoogleSvc.initHttpRequest(GoogleTransaction.GEOCODING);

        String ep = httpRequest.getEndpoint() + '&latlng='+account.ShippingLatitude + ',' + account.ShippingLongitude;

        MockHttpResponseHandler.SimpleMockResponse getResp =
                new MockHttpResponseHandler.SimpleMockResponse(mdt.Http_Method__c, getResponse);

        MockHttpResponseHandler mock = new MockHttpResponseHandler();
        System.debug('---> mock ep = ' + ep);
        mock.addResponse(ep, getResp);
        Test.setMock(HttpCalloutMock.class, mock);

        System.runAs(uAdmin) {

            Test.startTest();
            QueueableMuniUpdater q = new QueueableMuniUpdater(accountIds,false);
            q.performExecute();
            Test.stopTest();
        }

        Account a = [SELECT Id, MunicipalityLookup__c,Muni_Auto_Updated__c FROM Account WHERE Id = :account.Id ];
        System.assert(a.MunicipalityLookup__c == null);
        System.assert(!a.Muni_Auto_Updated__c);

        Accel_Application_Error__c log = [
                SELECT Id, Overall_Job_Status__c,Account__c
                FROM   Accel_Application_Error__c
                WHERE  Account__c = :account.Id
                AND    Job_Name__c = :QueueableMuniUpdater.jobName
        ];
        System.assert(log.Overall_Job_Status__c == 'Failed');
    }

    /**
     * if the queueable ran with an account without lat / long. make sure there is no callout.l
     */
    @IsTest
    static void test_Queueable_Muni_Bad_Data_No_Callout() {

        Account account = [
                SELECT  Id,  County_Auto_Updated__c,ShippingLatitude,ShippingLongitude,MunicipalityLookup__c,
                        Muni_Auto_Updated__c
                               // SELECT  Id, County__c, County_Auto_Updated__c,ShippingLatitude,ShippingLongitude,MunicipalityLookup__c,
                       // Muni_Auto_Updated__c
                FROM    Account
                WHERE ShippingStreet = '4916 Main Street Unit 2'
        ];
        account.ShippingLongitude = null;
        account.ShippingLatitude = null;
        update account;

        System.assert(account.MunicipalityLookup__c == null);
        System.assert(!account.Muni_Auto_Updated__c);
        Set<Id> accountIds = new Set<Id>{account.Id};

        System.runAs(uAdmin) {

            Test.startTest();
            QueueableMuniUpdater q = new QueueableMuniUpdater(accountIds,false);
            q.performExecute();
            Test.stopTest();
        }

        Account a = [SELECT Id, MunicipalityLookup__c,Muni_Auto_Updated__c FROM Account WHERE Id = :account.Id ];
        System.assert(a.MunicipalityLookup__c == null);
        System.assert(!a.Muni_Auto_Updated__c);

        Accel_Application_Error__c log = [
                SELECT Id, Overall_Job_Status__c,Account__c
                FROM   Accel_Application_Error__c
                WHERE  Account__c = :account.Id
                AND    Job_Name__c = :QueueableMuniUpdater.jobName
        ];
        System.assert(log.Overall_Job_Status__c == 'Failed');
    }

    @IsTest
    static void test_Queueable_Invalid_Http_ResponseCode() {

        Account account = [
                SELECT  Id,  County_Auto_Updated__c,ShippingLatitude,ShippingLongitude,MunicipalityLookup__c,
                        Muni_Auto_Updated__c
                               // SELECT  Id, County__c, County_Auto_Updated__c,ShippingLatitude,ShippingLongitude,MunicipalityLookup__c,
                       // Muni_Auto_Updated__c
                FROM    Account
                WHERE ShippingStreet = '4916 Main Street Unit 2'
        ];
        System.assert(account.MunicipalityLookup__c == null);
        System.assert(!account.Muni_Auto_Updated__c);

        Set<Id> accountIds = new Set<Id>{account.Id};

        String getResponse = TEST_GoogleGeocodeJsonToApex.testJsonInValidMuni;
        Google_Setting__mdt mdt = GoogleSvc.queryForMetadata(GoogleTransaction.GEOCODING.name());
        HttpRequest httpRequest = GoogleSvc.initHttpRequest(GoogleTransaction.GEOCODING);

        String ep = httpRequest.getEndpoint() + '&latlng='+account.ShippingLatitude + ',' + account.ShippingLongitude;

        MockHttpResponseHandler.SimpleMockResponse getResp =
                new MockHttpResponseHandler.SimpleMockResponse(mdt.Http_Method__c, getResponse);
        getResp.statusCode = 500;

        MockHttpResponseHandler mock = new MockHttpResponseHandler();
        System.debug('---> mock ep = ' + ep);
        mock.addResponse(ep, getResp);
        Test.setMock(HttpCalloutMock.class, mock);

        System.runAs(uAdmin) {

            Test.startTest();
            QueueableMuniUpdater q = new QueueableMuniUpdater(accountIds,false);
            q.performExecute();
            Test.stopTest();
        }

        Account a = [SELECT Id, MunicipalityLookup__c,Muni_Auto_Updated__c FROM Account WHERE Id = :account.Id ];
        System.assert(a.MunicipalityLookup__c == null);
        System.assert(!a.Muni_Auto_Updated__c);

        Accel_Application_Error__c log = [
                SELECT Id, Overall_Job_Status__c,Account__c
                FROM   Accel_Application_Error__c
                WHERE  Account__c = :account.Id
                AND    Job_Name__c = :QueueableMuniUpdater.jobName
        ];
        System.assert(log.Overall_Job_Status__c == 'Failed');
    }
    @IsTest
    static void test_Queueable_Muni_Updater_Force_CalloutException() {

        Account account = [
                SELECT  Id,  County_Auto_Updated__c,ShippingLatitude,ShippingLongitude,
                        MunicipalityLookup__c,Muni_Auto_Updated__c

                              //  SELECT  Id, County__c, County_Auto_Updated__c,ShippingLatitude,ShippingLongitude,
                      //  MunicipalityLookup__c,Muni_Auto_Updated__c

                FROM    Account
                WHERE ShippingStreet = '4916 Main Street Unit 2'
        ];
        System.assert(account.MunicipalityLookup__c == null);
        System.assert(!account.Muni_Auto_Updated__c);

        Set<Id> accountIds = new Set<Id>{account.Id};

        String googleResponse = TEST_GoogleGeocodeJsonToApex.testJsonValidMuni;
        Google_Setting__mdt mdt = GoogleSvc.queryForMetadata(GoogleTransaction.GEOCODING.name());
        HttpRequest httpRequest = GoogleSvc.initHttpRequest(GoogleTransaction.GEOCODING);
        String ep = httpRequest.getEndpoint() + '&latlng='+account.ShippingLatitude + ',' + account.ShippingLongitude;


        MockHttpResponseHandler.SimpleMockResponse getResp =
                new MockHttpResponseHandler.SimpleMockResponse(mdt.Http_Method__c, googleResponse);

        MockHttpResponseHandler mock = new MockHttpResponseHandler();
        System.debug('---> mock ep = ' + ep);
        mock.addResponse(ep, getResp);
        Test.setMock(HttpCalloutMock.class, mock);

        System.runAs(uAdmin) {

            Test.startTest();

            QueueableMuniUpdater qPrimary = new QueueableMuniUpdater(accountIds,false);

            QueueableMuniUpdater.makeCallout = false;
            System.enqueueJob(qPrimary);
            qPrimary.performExecute();

            Test.stopTest();

            Account a = [SELECT Id, MunicipalityLookup__c FROM Account WHERE Id = :account.Id ];
            System.assert(a.MunicipalityLookup__c == null);

            Accel_Application_Error__c log = [
                    SELECT Id, Overall_Job_Status__c,Account__c
                    FROM   Accel_Application_Error__c
                    WHERE  Account__c = :account.Id
                    AND    Job_Name__c = :QueueableMuniUpdater.jobName
            ];
            System.assert(log.Overall_Job_Status__c == 'Failed');
        }
    }

    @IsTest
    static void test_Queueable_Muni_Updater_Positive_SendEmail() {

        Account account = [
                SELECT  Id,  County_Auto_Updated__c,ShippingLatitude,ShippingLongitude,MunicipalityLookup__c
                      //  SELECT  Id, County__c, County_Auto_Updated__c,ShippingLatitude,ShippingLongitude,MunicipalityLookup__c

                FROM    Account
                WHERE ShippingStreet = '4916 Main Street Unit 2'
        ];
        System.assert(account.MunicipalityLookup__c == null);
        Set<Id> accountIds = new Set<Id>{account.Id};

        String googleResponse = TEST_GoogleGeocodeJsonToApex.testJsonValidMuni;
        Google_Setting__mdt mdt = GoogleSvc.queryForMetadata(GoogleTransaction.GEOCODING.name());
        HttpRequest httpRequest = GoogleSvc.initHttpRequest(GoogleTransaction.GEOCODING);
        String ep = httpRequest.getEndpoint() + '&latlng='+account.ShippingLatitude + ',' + account.ShippingLongitude;

        MockHttpResponseHandler.SimpleMockResponse getResp =
                new MockHttpResponseHandler.SimpleMockResponse(mdt.Http_Method__c, googleResponse);

        MockHttpResponseHandler mock = new MockHttpResponseHandler();
        System.debug('---> mock ep = ' + ep);
        mock.addResponse(ep, getResp);
        Test.setMock(HttpCalloutMock.class, mock);

        uAdmin = [SELECT Id, Username FROM User WHERE Id = :uAdmin.Id];

        System.runAs(uAdmin) {

            Test.startTest();

            QueueableMuniUpdater.SEND_EMAIL = TRUE;
            QueueableMuniUpdater.TEST_EMAIL_USERNAMES = uAdmin.Username;
            QueueableMuniUpdater qPrimary = new QueueableMuniUpdater(accountIds,false);

            qPrimary.performExecute();
            Test.getEventBus().deliver();

            Test.stopTest();

            Account a = [SELECT Id, MunicipalityLookup__c FROM Account WHERE Id = :account.Id ];
            System.assert(a.MunicipalityLookup__c != null);

            Accel_Application_Error__c log = [
                    SELECT Id, Overall_Job_Status__c,Account__c
                    FROM   Accel_Application_Error__c
                    WHERE  Account__c = :account.Id
                    AND    Job_Name__c = :QueueableMuniUpdater.jobName
            ];
            System.assert(log.Overall_Job_Status__c == 'Success');
            System.assert(qPrimary.platformEventSaveResult.success);
        }
    }
}