objects/Accel_Application_Error__c.object
<CustomObject>
    <description>Object to store batch job logs and custom app specific errors.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Accel Application Logs</relationshipLabel>
        <relationshipName>Accel_Application_Logs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Municipality__c</fullName>
        <formula>Account__r.MunicipalityLookup__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Municipality</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Overall_Job_Status__c</fullName>
        <label>Overall Job Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Processing</fullName>
                </value>
                <value>
                    <fullName>Success</fullName>
                </value>
                <value>
                    <fullName>Partial Success</fullName>
                </value>
                <value>
                    <fullName>Failed</fullName>
                </value>
                <value>
                    <fullName>Rolled Back</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Accel Application Log</label>
    <nameField>
        <displayFormat>Log-{000000}</displayFormat>
        <label>Log #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Accel Application Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Account.object
<CustomObject>
    <fields>
        <fullName>SweepstakesCurrOptIn__c</fullName>
        <defaultValue>false</defaultValue>
        <description>A hidden field used for Azure/Netsuite integration purposes to allows parsing of whether or not the account is currently participating in a sweepstakes based off related marketing requests, as defined by the logic included in the apex class SweepstakesUpdates</description>
        <label>SweepstakesCurrOptIn</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Batch_Job_Setting__mdt.object
<CustomObject>
    <fields>
        <fullName>Product_Names_To_Query__c</fullName>
        <description>Comma delimited string of record type developer names to use in the start method query.</description>
        <inlineHelpText>Comma delimited string of record type developer names to use in the start method query.</inlineHelpText>
        <label>Product Names To Query</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Record_Types_to_Query__c</fullName>
        <description>Comma delimited string of record type developer names to use in the start method query.</description>
        <inlineHelpText>Comma delimited string of record type developer names to use in the start method query.</inlineHelpText>
        <label>Record Types to Query</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Usernames_to_email__c</fullName>
        <description>If any send email value is checked, this must be populated with a comma delim string of sfdc usernames.</description>
        <inlineHelpText>If any send email value is checked, this must be populated with a comma delim string of sfdc usernames.</inlineHelpText>
        <label>Usernames to email</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Batch Job Setting</label>
    <pluralLabel>Batch Job Settings</pluralLabel>
</CustomObject>

objects/Marketing_Request__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Marketing Requests (Account)</relationshipLabel>
        <relationshipName>Dayna_Marketing_Tests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Cost_Share_Sent_To_Accounting__c</fullName>
        <label>Cost Share Sent To Accounting</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Location_Cost_Share_Amount__c</fullName>
        <label>Location Cost Share Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>My_Project_Name__c</fullName>
        <label>My Project Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Name_of_Person_Requesting__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Name of Person Requesting</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Dayna_Marketing_Tests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>WiFi_Network_Name__c</fullName>
        <label>WiFi Network Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>WiFi_Password__c</fullName>
        <label>WiFi Password</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Marketing Request</label>
    <nameField>
        <displayFormat>M-{000000}</displayFormat>
        <label>Unique Request ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Marketing Requests</pluralLabel>
    <recordTypes>
        <fullName>Sweepstakes</fullName>
        <active>true</active>
        <label>Sweepstakes</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Marketing_Request_Products__c.object
<CustomObject>
    <fields>
        <fullName>Account_Marketing__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account (Marketing)</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Marketing Request Products</relationshipLabel>
        <relationshipName>Marketing_Request_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Custom_Price__c</fullName>
        <label>Custom Price (Promotions Only)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Location_Cost_Share_Amount__c</fullName>
        <formula>Product__r.Location_Cost_Share_Amount__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Location Cost Share Amount(from Product)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Marketing_Product_Type__c</fullName>
        <formula>TEXT(Product__r.Marketing_Product_Type__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Marketing Product Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Marketing_Request_Type__c</fullName>
        <label>Marketing Request Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Standard</fullName>
                </value>
                <value>
                    <fullName>Standard Custom Size</fullName>
                </value>
                <value>
                    <fullName>VIP</fullName>
                </value>
                <value>
                    <fullName>Co-Op</fullName>
                </value>
                <value>
                    <fullName>Promotions</fullName>
                </value>
                <value>
                    <fullName>Digital Marketing</fullName>
                </value>
                <value>
                    <fullName>Sweepstakes</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Marketing_Request__c</fullName>
        <label>Marketing Request</label>
        <referenceTo>Marketing_Request__c</referenceTo>
        <relationshipLabel>Marketing Request Products</relationshipLabel>
        <relationshipName>Marketing_Request_Products</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <formula>IF(OR 
(Marketing_Request__r.RecordType.Name =&apos;Standard&apos;,Marketing_Request__r.RecordType.Name = &apos;Brand Ambassador Events&apos;,Marketing_Request__r.RecordType.Name =&apos;AE Player TV&apos;,Marketing_Request__r.RecordType.Name =&apos;Sweepstakes&apos;), Product__r.Price__c, 
IF(OR 
(Marketing_Request__r.RecordType.Name =&apos;Customized&apos;,Marketing_Request__r.RecordType.Name =&apos;Standard Custom Size&apos;),(Marketing_Request__r.Winning_Bid_Amount__c /Marketing_Request__r.MRP_Rollup_Count__c), 
IF 
(Marketing_Request__r.RecordType.Name =&apos;Accel Entertainment (Office Use Only)&apos;,(Marketing_Request__r.Winning_Bid_Amount__c/Marketing_Request__r.MRP_Rollup_Count__c), 
IF 
(Marketing_Request__r.RecordType.Name =&apos;Co-Op&apos;, Marketing_Request__r.Total_Quote_Amount__c/Marketing_Request__r.MRP_Rollup_Count__c,
IF(CONTAINS( Product__r.Name, &quot;Pre-Made&quot;), Product__r.Price__c ,  

 
0)))))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Product2.IsActive</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Marketing Request Products</relationshipLabel>
        <relationshipName>Marketing_Request_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Marketing Request Products</label>
    <nameField>
        <displayFormat>MRP-{00000}</displayFormat>
        <label>Marketing Request Products Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Marketing Request Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Municipality__c.object
<CustomObject>
    <label>Municipality</label>
    <nameField>
        <label>Municipality Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Municipalities</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Products (Account)</relationshipLabel>
        <relationshipName>Products2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Location_Cost_Share_Amount__c</fullName>
        <label>Location Cost Share Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Marketing_Product_Type__c</fullName>
        <label>Marketing Product Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Standard</fullName>
                </value>
                <value>
                    <fullName>Standard Custom Size</fullName>
                </value>
                <value>
                    <fullName>VIP</fullName>
                </value>
                <value>
                    <fullName>Co-Op</fullName>
                </value>
                <value>
                    <fullName>Promotions</fullName>
                </value>
                <value>
                    <fullName>Digital Marketing</fullName>
                </value>
                <value>
                    <fullName>Accel Entertainment (Office Use Only)</fullName>
                </value>
                <value>
                    <fullName>Customized</fullName>
                </value>
                <value>
                    <fullName>Sweepstakes</fullName>
                </value>
                <value>
                    <fullName>AE Player TV</fullName>
                </value>
                <value>
                    <fullName>Brand Ambassador Events</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Marketing_Request_Type__c</fullName>
        <formula>IF(AND(ISPICKVAL(Marketing_Product_Type__c,&quot;Standard&quot;),CONTAINS(Name,&quot;VIP&quot;)),&quot;VIP&quot;,
 TEXT(Marketing_Product_Type__c))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Marketing Request Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <recordTypes>
        <fullName>Marketing</fullName>
        <active>true</active>
        <label>Marketing</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/TEST_BatchSweepstakesLocUpdate.cls
@IsTest
private class TEST_BatchSweepstakesLocUpdate {

    public static String USERNAME_ADMIN = 'acceladmintest@accel.com';
    private static String MKTG_PRODUCT_TYPE = 'Sweepstakes';
    private static String MKTG_PRODUUCT_RECORD_TYPE = 'Marketing';

    @testSetup
    static void setup() {

        Integer iNmbrOfMunis=1, iNmbrOfAccountsPerMuni=3;

        User adminUser = TestUtils.getUserForTest(USERNAME_ADMIN);

        System.runAs(adminUser) {

            List<Municipality__c> munis = TestUtils.createMunicipalities('TEST Muni', iNmbrOfMunis);
            List<Account> accounts = buildAccountsForMunis(munis,iNmbrOfAccountsPerMuni);
            insert accounts;

            Batch_Job_Setting__mdt mdt = BatchjobSvc.queryForMetadata(BatchSweepstakesLocUpdate.jobName);
            List<String> rtDevNames = mdt.Record_Types_to_Query__c.split(',');
            Set<Id> rtIds = new Set<Id>();
            List<String> prodNames  = mdt.Product_Names_To_Query__c.split(',');

            List<Product2> products = new List<Product2>();

            for(String rtDevName : rtDevNames) {
                Id productRtId = Schema.SObjectType.Product2.getRecordTypeInfosByDeveloperName()
                        .get(MKTG_PRODUUCT_RECORD_TYPE).getRecordTypeId();

                Id mktgRtId = Schema.SObjectType.Marketing_Request__c.getRecordTypeInfosByDeveloperName()
                        .get(rtDevName).getRecordTypeId();

                rtIds.add(mktgRtId);

                for(String productName : prodNames) {
                    Product2 product = new Product2(
                            Name = productName, ProductCode = productName, IsActive = true,
                            Marketing_Product_Type__c = MKTG_PRODUCT_TYPE, Price__c = 50,
                            Location_Cost_Share_Amount__c = 50,
                            RecordTypeId = productRtId
                    );
                    products.add(product);
                }
            }
            insert products;

            List<Marketing_Request__c> mrs = new List<Marketing_Request__c>();
            List<Marketing_Request_Products__c> mrProducts = new List<Marketing_Request_Products__c>();

            for(Id rtId : rtIds) {

                for (Account account : accounts) {
                    Marketing_Request__c mr = new Marketing_Request__c();
                    mr.My_Project_Name__c = 'MR AE Player UT Test 1';
                    mr.Account__c = account.id;
                    mr.RecordTypeId = rtId;
                    mr.Name_of_Person_Requesting__c = adminUser.Id;
                    mr.WiFi_Network_Name__c = 'wifi net name';
                    mr.WiFi_Password__c = 'wifi pw';
                    mr.Cost_Share_Sent_To_Accounting__c = Date.today();
                    mrs.add(mr);
                }
                // add more then one marketing request for one of the accounts
                Marketing_Request__c mr2 = new Marketing_Request__c();
                mr2.My_Project_Name__c = 'MR AE Player UT Test 1';
                mr2.Account__c = accounts[0].id;
                mr2.RecordTypeId = rtId;
                mr2.Name_of_Person_Requesting__c = adminUser.Id;
                mr2.WiFi_Network_Name__c = 'wifi net name';
                mr2.WiFi_Password__c = 'wifi pw';
                mr2.Cost_Share_Sent_To_Accounting__c = Date.today();
                mrs.add(mr2);
            }
            insert mrs;


            for(Marketing_Request__c mr : mrs) {
                Marketing_Request_Products__c mrProduct = new Marketing_Request_Products__c();
                mrProduct.Marketing_Request__c = mr.Id;
                mrProduct.Marketing_Request_Type__c = MKTG_PRODUCT_TYPE;
                mrProduct.Quantity__c = 1;
                mrProduct.Custom_Price__c = 50;
                mrProduct.Account_Marketing__c = mr.Account__c;
                mrProduct.Product__c = products[0].Id;
                mrProducts.add(mrProduct);
            }
            insert mrProducts;

            System.debug(mrs);
        }
    }

    @isTest
    static void test_fireBatch_Success_Commit() {

        User adminUser = TestUtils.getUserForTest(USERNAME_ADMIN);

        System.runAs(adminUser) {
            Test.startTest();
            Integer iBatchSize = 50;
            Boolean bCommit = true, logExeMethod = true;
            String scheduledJobId = null;

            BatchSweepstakesLocUpdate b = new BatchSweepstakesLocUpdate(bCommit,iBatchSize,logExeMethod,scheduledJobId);

            Id jobId = Database.executeBatch(b,iBatchSize);
            Test.stopTest();

            Accel_Application_Error__c log = AppLogSvc.retrieveLog(b.log.Id);
            System.debug('----> log='+log);
            System.assertEquals(log.Overall_Job_Status__c,'Success');
        }
    }

    @isTest
    static void test_fireBatch_Success_FlagFalse() {

        User adminUser = TestUtils.getUserForTest(USERNAME_ADMIN);

        System.runAs(adminUser) {
            Test.startTest();

            Integer iBatchSize = 50;
            Boolean bCommit = true, logExeMethod = true;
            String scheduledJobId = null;

            List<Marketing_Request__c> marketingRequests = [
                    SELECT Id,Cost_Share_Sent_To_Accounting__c
                    FROM Marketing_Request__c
            ];
            for (Marketing_Request__c marketingRequest : marketingRequests) {
                marketingRequest.Cost_Share_Sent_To_Accounting__c = null;
            }
            update marketingRequests;

            List<Account> accounts = [
                    SELECT Id,SweepstakesCurrOptIn__c
                    FROM Account
            ];
            for (Account account : accounts) {
                account.SweepstakesCurrOptIn__c = TRUE;
            }
            update accounts;


            BatchSweepstakesLocUpdate b = new BatchSweepstakesLocUpdate(bCommit,iBatchSize,logExeMethod,scheduledJobId);

            Id jobId = Database.executeBatch(b,iBatchSize);
            Test.stopTest();

            Accel_Application_Error__c log = AppLogSvc.retrieveLog(b.log.Id);
            System.debug('----> log='+log);
            System.assertEquals(log.Overall_Job_Status__c,'Success');
        }
    }

    @isTest
    static void test_fireBatch_Success_Rollback() {

        User adminUser = TestUtils.getUserForTest(USERNAME_ADMIN);

        System.runAs(adminUser) {
            Test.startTest();
            Integer iBatchSize = 50;
            Boolean bCommit = false, logExeMethod = true;
            String scheduledJobId = null;

            BatchSweepstakesLocUpdate b = new BatchSweepstakesLocUpdate(bCommit,iBatchSize,logExeMethod,scheduledJobId);

            Id jobId = Database.executeBatch(b,iBatchSize);
            Test.stopTest();

            Accel_Application_Error__c log = AppLogSvc.retrieveLog(b.log.Id);
            System.debug('----> log='+log);
            System.assertEquals(log.Overall_Job_Status__c,'Rolled Back');

        }
    }

    @isTest
    static void test_fireBatch_ALL_DmlException() {

        User adminUser = TestUtils.getUserForTest(USERNAME_ADMIN);

        System.runAs(adminUser) {
            Test.startTest();

            Integer iBatchSize = 50;
            Boolean bCommit = true, logExeMethod = true;
            String scheduledJobId = null;
            BatchSweepstakesLocUpdate.FORCE_ALL_DML_EXCEPTION = TRUE;

            BatchSweepstakesLocUpdate b = new BatchSweepstakesLocUpdate(bCommit,iBatchSize,logExeMethod,scheduledJobId);

            Id jobId = Database.executeBatch(b,iBatchSize);
            Test.stopTest();

            Accel_Application_Error__c log = AppLogSvc.retrieveLog(b.log.Id);
            System.debug('----> log='+log);
            System.assertEquals(log.Overall_Job_Status__c,'Failed');

        }
    }

    @isTest
    static void test_fireBatch_PARTIAL_DmlException() {

        User adminUser = TestUtils.getUserForTest(USERNAME_ADMIN);

        System.runAs(adminUser) {
            Test.startTest();

            Integer iBatchSize = 50;
            Boolean bCommit = true, logExeMethod = true;
            String scheduledJobId = null;
            BatchSweepstakesLocUpdate.FORCE_PARTIAL_DML_EXCEPTION = TRUE;

            BatchSweepstakesLocUpdate b = new BatchSweepstakesLocUpdate(bCommit,iBatchSize,logExeMethod,scheduledJobId);

            Id jobId = Database.executeBatch(b,iBatchSize);
            Test.stopTest();

            Accel_Application_Error__c log = AppLogSvc.retrieveLog(b.log.Id);
            System.debug('----> log='+log);
            System.assertEquals(log.Overall_Job_Status__c,'Partial Success');

        }
    }

    @isTest
    static void test_fireBatch_Fail_SendEmail_ValidUsernames() {

        Batch_Job_Setting__mdt mdt = BatchjobSvc.queryForMetadata(BatchSweepstakesLocUpdate.jobName);

        String userName = USERNAME_ADMIN;
        if(mdt!= null && mdt.Usernames_to_email__c != null) {
            userName = mdt.Usernames_to_email__c.split(',')[0];
        }
        User adminUser = TestUtils.getUserForTest(userName);

        System.runAs(adminUser) {
            Test.startTest();
            Integer iBatchSize = 50;
            Boolean bCommit = true, logExeMethod = true;
            String scheduledJobId = null;

            BatchSweepstakesLocUpdate.FORCE_ALL_DML_EXCEPTION = true;
            BatchSweepstakesLocUpdate.SEND_EMAIL_ON_FAIL = true;
            BatchSweepstakesLocUpdate.TEST_EMAIL_USERNAMES = UserInfo.getUserName();

            BatchSweepstakesLocUpdate b = new BatchSweepstakesLocUpdate(bCommit,iBatchSize,logExeMethod,scheduledJobId);

            Id jobId = Database.executeBatch(b,iBatchSize);
            Test.stopTest();

            Accel_Application_Error__c log = AppLogSvc.retrieveLog(b.log.Id);
            System.debug('----> log='+log);
            System.assertEquals(log.Overall_Job_Status__c,'Failed');
        }
    }

    @isTest
    static void test_fireBatch_Always_SendEmail_ValidUsernames() {

        Batch_Job_Setting__mdt mdt = BatchjobSvc.queryForMetadata(BatchSweepstakesLocUpdate.jobName);

        String userName = USERNAME_ADMIN;
        if(mdt!= null && mdt.Usernames_to_email__c != null) {
            userName = mdt.Usernames_to_email__c.split(',')[0];
        }
        User adminUser = TestUtils.getUserForTest(userName);

        System.runAs(adminUser) {
            Test.startTest();
            Integer iBatchSize = 50;
            Boolean bCommit = true, logExeMethod = true;
            String scheduledJobId = null;
            BatchSweepstakesLocUpdate.SEND_EMAIL_ON_COMPLETION = true;
            BatchSweepstakesLocUpdate.TEST_EMAIL_USERNAMES = UserInfo.getUserName();

            BatchSweepstakesLocUpdate b = new BatchSweepstakesLocUpdate(bCommit,iBatchSize,logExeMethod,scheduledJobId);

            Id jobId = Database.executeBatch(b,iBatchSize);
            Test.stopTest();

            Accel_Application_Error__c log = AppLogSvc.retrieveLog(b.log.Id);
            System.debug('----> log='+log);
        }
    }

    @isTest
    static void test_fireBatch_Fail_SendEmail_InvalidUsernames() {

        User adminUser = TestUtils.getUserForTest(USERNAME_ADMIN);

        System.runAs(adminUser) {
            Test.startTest();
            Integer iBatchSize = 50;
            Boolean bCommit = true, logExeMethod = true;
            String scheduledJobId = null;

            BatchSweepstakesLocUpdate.FORCE_ALL_DML_EXCEPTION = true;
            BatchSweepstakesLocUpdate.SEND_EMAIL_ON_FAIL = true;
            BatchSweepstakesLocUpdate.TEST_EMAIL_USERNAMES = 'bogus@willnotbefound.com';

            BatchSweepstakesLocUpdate b = new BatchSweepstakesLocUpdate(bCommit,iBatchSize,logExeMethod,scheduledJobId);

            Id jobId = Database.executeBatch(b,iBatchSize);
            Test.stopTest();

            Accel_Application_Error__c log = AppLogSvc.retrieveLog(b.log.Id);
            System.debug('----> log='+log);
            System.assertEquals(log.Overall_Job_Status__c,'Failed');
        }
    }
    @isTest
    static void test_fireBatch_Fail_SendEmail_No_Usernames() {

        User adminUser = TestUtils.getUserForTest(USERNAME_ADMIN);

        System.runAs(adminUser) {
            Test.startTest();
            Integer iBatchSize = 50;
            Boolean bCommit = true, logExeMethod = true;
            String scheduledJobId = null;

            BatchSweepstakesLocUpdate.FORCE_ALL_DML_EXCEPTION = true;
            BatchSweepstakesLocUpdate.SEND_EMAIL_ON_FAIL = true;
            BatchSweepstakesLocUpdate.TEST_EMAIL_USERNAMES = null;

            BatchSweepstakesLocUpdate b = new BatchSweepstakesLocUpdate(bCommit,iBatchSize,logExeMethod,scheduledJobId);

            Id jobId = Database.executeBatch(b,iBatchSize);
            Test.stopTest();

            Accel_Application_Error__c log = AppLogSvc.retrieveLog(b.log.Id);
            System.debug('----> log='+log);
            System.assertEquals(log.Overall_Job_Status__c,'Failed');
        }
    }
   /**
    * @param munis
    * @param iNmbrOfAccountsPerMuni
    *
    * @return
    * @todo move to TestUtils
    */
    static List<Account> buildAccountsForMunis(List<Municipality__c> munis,Integer iNmbrOfAccountsPerMuni) {
        List<Account> accounts = new List<Account>();

        for (Municipality__c muni : munis) {
            for (Integer i = 0; i < iNmbrOfAccountsPerMuni; i++) {
                Account account = TestUtils.buildAccount('Test Account ' + i, muni.Id);
                accounts.add(account);
            }
        }
        return accounts;
    }
}