objects/Accel_Application_Error__c.object
<CustomObject>
    <description>Object to store batch job logs and custom app specific errors.</description>
    <fields>
        <fullName>Batch_Size__c</fullName>
        <description>The batch size that this job was requested to run with.</description>
        <inlineHelpText>The batch size that this job was requested to run with.</inlineHelpText>
        <label>Batch Size</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Execution_Details__c</fullName>
        <defaultValue>&quot; &quot;</defaultValue>
        <description>Logging for the individual job.</description>
        <inlineHelpText>Logging for the individual job.</inlineHelpText>
        <label>Execution Details</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Initiating_Job_Id__c</fullName>
        <description>The id of the job initial job. ie. if there was a batch job that fired a queueable job or other batch jobs. used the initial batch job id.</description>
        <inlineHelpText>The id of the job initial job. ie. if there was a batch job that fired a queueable job or other batch jobs. used the initial batch job id.</inlineHelpText>
        <label>Initiating Job Id</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Overall_Job_Status__c</fullName>
        <label>Overall Job Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Processing</fullName>
                </value>
                <value>
                    <fullName>Success</fullName>
                </value>
                <value>
                    <fullName>Partial Success</fullName>
                </value>
                <value>
                    <fullName>Failed</fullName>
                </value>
                <value>
                    <fullName>Rolled Back</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Process_End_Date__c</fullName>
        <label>Process End Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Stack_Trace__c</fullName>
        <label>Stack Trace</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Total_Records_Processed__c</fullName>
        <defaultValue>0</defaultValue>
        <description>The amount of records we are trying to update.</description>
        <inlineHelpText>The amount of records we are trying to update.</inlineHelpText>
        <label>Total Records Processed</label>
        <precision>12</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_Records_Selected__c</fullName>
        <defaultValue>0</defaultValue>
        <description>The total number of records selected. ie. accumulative value of start query records.</description>
        <inlineHelpText>The total number of records selected. ie. accumulative value of start query records.</inlineHelpText>
        <label>Total Records Selected</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_Records_Updated__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Total total number of records for which an update succeeded</description>
        <inlineHelpText>Total total number of records for which an update succeeded</inlineHelpText>
        <label>Total Records Updated</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Accel Application Log</label>
    <nameField>
        <displayFormat>Log-{000000}</displayFormat>
        <label>Log #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Accel Application Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Batch_Job_Setting__mdt.object
<CustomObject>
    <fields>
        <fullName>Batch_Size__c</fullName>
        <defaultValue>50</defaultValue>
        <description>The Batch Size for Database.execute</description>
        <inlineHelpText>The Batch Size for Database.execute</inlineHelpText>
        <label>Batch Size</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Log_Execute_Method__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If true. it will write logs of the execute method to Accel_Application_Error__c.Execution_Details__c otherwise it will only write job completion logs. Be careful here as if the batch size is small or there are a large number of records the field length may be exceeded.</description>
        <inlineHelpText>If true. it will write logs of the execute method to Accel_Application_Error__c.Execution_Details__c otherwise it will only write job completion logs.Be careful here as if the batch size is small or there are a large number of records the field length may</inlineHelpText>
        <label>Log Execute Method</label>
        <type>Checkbox</type>
    </fields>
    <label>Batch Job Setting</label>
    <pluralLabel>Batch Job Settings</pluralLabel>
</CustomObject>

objects/Cash_Logistics_Setting__mdt.object
<CustomObject>
    <description>All Configurable Settings for the Cash Logistics Experience Cloud</description>
    <fields>
        <fullName>Next_Cycle__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Next Cycle</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Cash Logistics Experience Cloud Setting</label>
    <pluralLabel>Cash Logistics Experience Cloud Settings</pluralLabel>
</CustomObject>

objects/Route__c.object
<CustomObject>
    <description>Example object to house routes and routing of collections</description>
    <fields>
        <fullName>Cycle_Number__c</fullName>
        <description>The position of this route to be created in the 28 day cycle (4 weeks, 7 day per week)</description>
        <label>Fill Cycle Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Route</label>
    <nameField>
        <label>Route Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Routes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/clBatchCycleNumberUpdate.cls
/**
 * clBatchCycleNumberUpdate will select Cash_Logistic_Setting__mdt.Next_Cycle__c and increment by 1.
 * If it is equal to 28. It will reset this value to 1.   (Cash logics business rule on how the data is set up)
 */
public class  clBatchCycleNumberUpdate implements  Database.Batchable<SObject>, Database.Stateful, Database.AllowsCallouts{

    public static String jobName = 'clBatchCycleNumberUpdate'; // Important as your custom mdt is keyed by this.
    public Id jobId;
    private Integer batchSize = 50;

    //  Single log file for each nightly run which will be updated throughout the process.
    public Accel_Application_Error__c log;

    //  Custom metadata used. This will normally have a developername of the name of this executing class.
    public  Batch_Job_Setting__mdt jobMdt;

    public  Cash_Logistics_Setting__mdt clSchMdt;
    public  final static String CL_SCH_MDT_DEV_NAME = 'Scheduler';

    private Integer nextCycle;

    //  Various internal stateful counters
    private Integer     iTotalRecordsSelected = 0,iNumUpdated = 0;
    private Integer     iNumProcessed = 0,iNumExeCalls = 0;

    /**
     * @param pNextCycle  The Route__c.Cycle_Number__c value passed into the constructor.
     */
    public clBatchCycleNumberUpdate(Integer pNextCycle) {
        this.nextCycle = pNextCycle;
        this.initLog();                                         //  Insert a log.
        this.jobMdt = BatchjobSvc.queryForMetadata(jobName);    //  Query Metadata for params.
        log.Execution_Details__c += '\n * Constructor:  cycle number passed = '+ pNextCycle;
    }

    public clBatchCycleNumberUpdate() {
        this.initLog();                                         //  Insert a log.
        this.jobMdt = BatchjobSvc.queryForMetadata(jobName);    //  Query Metadata for params.
        log.Execution_Details__c += '\n * Constructor:  custom mdt = '+this.jobMdt;
    }

    /**
     * @param bc  The Batchable context.
     * @return    A QueryLocator with the CL Setting.
     */
    public Database.QueryLocator start(Database.BatchableContext bc) {
        this.jobId = bc.getJobId();
        log.Initiating_Job_Id__c = this.jobId;
        log.Execution_Details__c += '\n* Start Method: Batch Size Requested ' + batchSize + '\n \n';

        Database.QueryLocator ql = Database.getQueryLocator([
                SELECT  Id,Next_Cycle__c
                FROM    Cash_Logistics_Setting__mdt
                WHERE   DeveloperName = :CL_SCH_MDT_DEV_NAME
        ]);
        return ql;
    }

    /**
     * @param bc     The Batchable ctx.
     * @param scope  A List of Mdt records (1 in this case)
     */
    public void execute(Database.BatchableContext bc, List<Cash_Logistics_Setting__mdt> scope) {

        this.iTotalRecordsSelected += scope.size();
        this.iNumExeCalls++;
        this.clSchMdt = (Cash_Logistics_Setting__mdt) scope[0];

        if(this.nextCycle == null) {
            System.debug('---> current cycle value=' + this.clSchMdt.Next_Cycle__c);
            if(Integer.valueOf(this.clSchMdt.Next_Cycle__c) == 28) {
                this.nextCycle = 1;
            } else {
                this.nextCycle = Integer.valueOf(this.clSchMdt.Next_Cycle__c) + 1;
            }
        }
        if (jobMdt != null && jobMdt.Log_Execute_Method__c) {
            log.Execution_Details__c += '\n* Current cycle number prior to update -->'+clSchMdt.Next_Cycle__c;
            log.Execution_Details__c += '\n* Cycle number that we want to update to -->'+this.nextCycle;
        }

        System.debug('---> incremented cycle value='+this.nextCycle);

        String mdtName = 'Cash_Logistics_Setting__mdt';
        String recordDevName = 'Scheduler';
        String label = 'Scheduler';
        Map<String,Object> mFields = new Map<String,Object>();
        mFields.put('Next_Cycle__c',this.nextCycle);
        this.iNumProcessed ++;

        Id jobId = clRouteProcessingSheetsController.updateCustomMetadata(mdtName,recordDevName,label,mFields);
        System.debug(LoggingLevel.INFO,'--> IN EXEC FIRING ASYNC JOB = '+jobId);
        if (jobMdt != null && jobMdt.Log_Execute_Method__c) {
            log.Execution_Details__c += '\n* firing asycn job to update custom metadata for cycle number = '+this.nextCycle;
            log.Execution_Details__c += '\n* Please view  '+ clRouteProcessingSheetsController.jobName + ' log for results';
        }
        this.iNumUpdated++;
    }

    private void initLog() {

        Accel_Application_Error__c log = BatchjobSvc.buildLog(jobName);

        log.Overall_Job_Status__c = 'Processing';
        log.Total_Records_Updated__c = 0;
        log.Total_Records_Processed__c = 0;
        log.Total_Records_Selected__c = 0;
        log.Stack_Trace__c = ' ';
        log.Batch_Size__c = this.batchSize;
        log.Execution_Details__c = ' ';
        this.log = log;
    }

    /**
     * @param bc  DB
     */
    public void finish(Database.BatchableContext bc) {
        this.writeFinalLog(log);
        System.debug(LoggingLevel.INFO, '---> in finish of batch job:' + this.jobId + ' log is:' + log);
        System.debug(LoggingLevel.INFO, '---> Status = ' + log.Overall_Job_Status__c);
    }

   /**
    *  Writes job level totals from the finish method.
    *  @param log The current Accel_Application_error__c log in ctx.
    */
    private void writeFinalLog(Accel_Application_Error__c log) {

        if (log != null) {

            log.Execution_Details__c += '\n\n==========   OVERALL Job Totals   =============== \n';
            log.Execution_Details__c += '* In finish of Batch ' + this.jobId + '\n';
            log.Process_End_Date__c = System.now();
            log.Total_Records_Selected__c = iTotalRecordsSelected;
            log.Total_Records_Processed__c = iNumProcessed;
            log.Execution_Details__c += '* Total Records Selected = '+ iTotalRecordsSelected+ '\n';
            log.Execution_Details__c += '* Total Records Processed = ' + log.Total_Records_Processed__c + '\n';
            log.Overall_Job_Status__c  = 'Success';
            insert log;
        }
    }
}