objects/Accel_Application_Error__c.object
<CustomObject>
    <description>Object to store batch job logs and custom app specific errors.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Accel Application Logs</relationshipLabel>
        <relationshipName>Accel_Application_Logs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Batch_Size__c</fullName>
        <description>The batch size that this job was requested to run with.</description>
        <inlineHelpText>The batch size that this job was requested to run with.</inlineHelpText>
        <label>Batch Size</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Execution_Details__c</fullName>
        <defaultValue>&quot; &quot;</defaultValue>
        <description>Logging for the individual job.</description>
        <inlineHelpText>Logging for the individual job.</inlineHelpText>
        <label>Execution Details</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Initiating_Job_Id__c</fullName>
        <description>The id of the job initial job. ie. if there was a batch job that fired a queueable job or other batch jobs. used the initial batch job id.</description>
        <inlineHelpText>The id of the job initial job. ie. if there was a batch job that fired a queueable job or other batch jobs. used the initial batch job id.</inlineHelpText>
        <label>Initiating Job Id</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Overall_Job_Status__c</fullName>
        <label>Overall Job Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Processing</fullName>
                </value>
                <value>
                    <fullName>Success</fullName>
                </value>
                <value>
                    <fullName>Partial Success</fullName>
                </value>
                <value>
                    <fullName>Failed</fullName>
                </value>
                <value>
                    <fullName>Rolled Back</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Process_End_Date__c</fullName>
        <label>Process End Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Stack_Trace__c</fullName>
        <label>Stack Trace</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Total_Records_Processed__c</fullName>
        <defaultValue>0</defaultValue>
        <description>The amount of records we are trying to update.</description>
        <inlineHelpText>The amount of records we are trying to update.</inlineHelpText>
        <label>Total Records Processed</label>
        <precision>12</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_Records_Selected__c</fullName>
        <defaultValue>0</defaultValue>
        <description>The total number of records selected. ie. accumulative value of start query records.</description>
        <inlineHelpText>The total number of records selected. ie. accumulative value of start query records.</inlineHelpText>
        <label>Total Records Selected</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_Records_Updated__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Total total number of records for which an update succeeded</description>
        <inlineHelpText>Total total number of records for which an update succeeded</inlineHelpText>
        <label>Total Records Updated</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Accel Application Log</label>
    <nameField>
        <displayFormat>Log-{000000}</displayFormat>
        <label>Log #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Accel Application Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Asset.object
<CustomObject>
    <fields>
        <fullName>Asset__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Asset</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Assets</relationshipLabel>
        <relationshipName>Assets4</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>BV_Type__c</fullName>
        <description>Bill Vaildator Type</description>
        <label>BV Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>JCM</fullName>
                </value>
                <value>
                    <fullName>MEI</fullName>
                    <default>true</default>
                    <label>MEI</label>
                </value>
                <value>
                    <fullName>Small MEI</fullName>
                </value>
                <value>
                    <fullName>NV-200</fullName>
                </value>
                <value>
                    <fullName>ICT PA7</fullName>
                </value>
                <value>
                    <fullName>ICT TAO-A</fullName>
                </value>
                <value>
                    <fullName>MEI2831U</fullName>
                </value>
                <value>
                    <fullName>MEI SC Advance</fullName>
                </value>
                <value>
                    <fullName>JCM UBA10</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>VGT</fullName>
        <active>true</active>
        <label>VGT</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Batch_Job_Setting__mdt.object
<CustomObject>
    <fields>
        <fullName>Batch_Size__c</fullName>
        <defaultValue>50</defaultValue>
        <description>The Batch Size for Database.execute</description>
        <inlineHelpText>The Batch Size for Database.execute</inlineHelpText>
        <label>Batch Size</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Batch Job Setting</label>
    <pluralLabel>Batch Job Settings</pluralLabel>
</CustomObject>

objects/Meter_Reading__c.object
<CustomObject>
    <description>Example object to capture electronic meters</description>
    <fields>
        <fullName>Asset__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Asset</label>
        <referenceTo>Asset</referenceTo>
        <relationshipLabel>Meter Readings</relationshipLabel>
        <relationshipName>Meter_Readings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>BV_Type__c</fullName>
        <description>Asset.BV_Type__c Since the picklist on Asset was not global this must be synchronized with those values for now. Written upon creation of meter_reading__c and used by DLRS to rollup to RPS</description>
        <inlineHelpText>Asset.BV_Type__c Since the picklist on Asset was not global this must be synchronized with those values for now. Written upon creation of meter_reading__c and used by DLRS to rollup to RPS</inlineHelpText>
        <label>BV Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>JCM</fullName>
                </value>
                <value>
                    <fullName>MEI</fullName>
                </value>
                <value>
                    <fullName>Small MEI</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Reading_Status__c</fullName>
        <defaultValue>&quot;New&quot;</defaultValue>
        <description>That status of the meter reading.. Generally this will start in In Progress unless we are inserting this meter records outside of the ui... Completion is currently when there is shapshot count &gt; 0 (image uploaded) and current lifetime case in value added. @see  MeterReadingTriggerHandler.cls</description>
        <inlineHelpText>That status of the meter reading.. Generally this will start in In Progress unless we are inserting this meter records outside of the ui... Completion is currently when there is shapshot count &gt; 0 (image uploaded) and current lifetime case in value added.</inlineHelpText>
        <label>Reading Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Cannot Collect</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Route_Processing_Sheet__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Route Processing Sheet</label>
        <referenceTo>Route_Processing_Sheet__c</referenceTo>
        <relationshipLabel>Meter Readings</relationshipLabel>
        <relationshipName>Meter_Readings</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Meter Reading</label>
    <nameField>
        <displayFormat>MTR-{000000000}</displayFormat>
        <label>Meter Reading ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Meter Readings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Route_Processing_Sheet__c.object
<CustomObject>
    <description>Example digitization of the route processing sheet</description>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account DBA</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Route Processing Sheets</relationshipLabel>
        <relationshipName>Route_Processing_Sheets</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Processing_Location__c</fullName>
        <label>Processing Location</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Processing_Location</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Route_Schedule__c</fullName>
        <label>Route Schedule</label>
        <referenceTo>Route_Schedule__c</referenceTo>
        <relationshipLabel>Route Processing Sheets</relationshipLabel>
        <relationshipName>Route_Processing_Sheets</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Collection Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Not Started</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
                <value>
                    <fullName>Skipped</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Route Processing Sheet</label>
    <nameField>
        <displayFormat>Collection-Id-{000000000}</displayFormat>
        <label>Collection ID Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Route Processing Sheets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Route_Schedule__c.object
<CustomObject>
    <description>Assignment information of a physical route&apos;s locations, collectors, vehicles, and questions for a specific day</description>
    <fields>
        <fullName>Processing_Location__c</fullName>
        <label>Processing Location</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Processing_Location</valueSetName>
        </valueSet>
    </fields>
    <label>Route Schedule</label>
    <nameField>
        <label>Route Schedule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Route Schedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Route_Schedule_Change_PE__e.object
<CustomObject>
    <fields>
        <fullName>Operation_Type__c</fullName>
        <description>[DELETE,INSERT,UPDATE,MDT_UPDATE]</description>
        <label>Operation Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Publishing_Process_Name__c</fullName>
        <label>Publishing Process Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Route_Schedule_Ids__c</fullName>
        <label>Route Schedule Ids</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ui_Message__c</fullName>
        <description>Any message that you want toasted to the User Interface</description>
        <label>Ui Message</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Route Schedule Change PE</label>
    <pluralLabel>Route Schedule Change PEs</pluralLabel>
</CustomObject>

globalValueSets/Processing_Location.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Burr Ridge</fullName>
    </customValue>
    <customValue>
        <fullName>DEV TEST 1</fullName>
    </customValue>
    <customValue>
        <fullName>Tinley Park</fullName>
    </customValue>
    <customValue>
        <fullName>Peoria</fullName>
    </customValue>
    <customValue>
        <fullName>Springfield</fullName>
    </customValue>
    <customValue>
        <fullName>CW</fullName>
    </customValue>
    <customValue>
        <fullName>Rockford</fullName>
    </customValue>
    <customValue>
        <fullName>Collinsville</fullName>
    </customValue>
    <masterLabel>Processing Location</masterLabel>
</GlobalValueSet>

classes/clBatchMeterReadingsCreation.cls
public class clBatchMeterReadingsCreation implements Database.Batchable<SObject>, Database.Stateful{

    private Set<Id> rpsIds;
    private Set<Id> rsIds = new Set<Id>();
    private Set<Id> meterReadingIds = new Set<Id>();
    private Set<String> processingLocations = new Set<String>();
    private Map<Id,Set<Id>> mRpsId_MeterIds = new Map<Id,Set<Id>>();
    private Set<Route_Processing_Sheet__c> rpsNoMeters = new Set<Route_Processing_Sheet__c>();

    public static String jobName = 'clBatchMetersCreation'; // Important as your custom mdt is keyed by this.
    public Id jobId;
    public  Batch_Job_Setting__mdt jobMdt;
    private Integer batchSize;

    //  Single log file for each nightly run which will be updated throughout the process.
    public Accel_Application_Error__c log;

    //  Various internal stateful counters
    private Integer     iTotalRecordsSelected = 0,iTotalMetersCreated = 0;
    private Integer     iTotalRecordsProcessed = 0,iNumExeCalls = 0;

    public clBatchMeterReadingsCreation(Set<Id> pRpsIds) {
        this.rpsIds = pRpsIds;
        this.initLog();
        log.Execution_Details__c += '\n * Constructor:  rps ids = ';
        if(rpsIds != null) {
            for (Id rpsId : rpsIds) {
                log.Execution_Details__c += rpsId + ',';
            }
            log.Execution_Details__c.removeEnd(',');
        }
    }

    public Database.QueryLocator start(Database.BatchableContext bc) {
        Database.QueryLocator ql = Database.getQueryLocator([
                SELECT  Id,Account__c,Route_Schedule__c,Processing_Location__c,Name
                FROM    Route_Processing_Sheet__c
                WHERE   Id IN :rpsIds
        ]);
        log.Execution_Details__c += '\n\n * Start method query rps with rpsIds=';
        for(Id rpsId : rpsIds) {
            log.Execution_Details__c += rpsId+',';
        }
        log.Execution_Details__c.removeEnd(',');

        return ql;
    }

    public void execute(Database.BatchableContext bc, List<Route_Processing_Sheet__c> scope ) {

        this.jobId = bc.getJobId();
        log.Initiating_Job_Id__c = this.jobId;
        iTotalRecordsProcessed+= scope.size();
        iTotalRecordsSelected+= scope.size();

        List<Meter_Reading__c> meterReadingsIns = new List<Meter_Reading__c>();

        Map<Id,Id> mRpsId_Account = new Map<Id,Id>();


        for (Route_Processing_Sheet__c rps : scope) {
            mRpsId_Account.put(rps.Id,rps.Account__c);
            rsIds.add(rps.Route_Schedule__c);
            processingLocations.add(rps.Processing_Location__c);
        }
        Set<String> rtDevNames = new Set<String>{'VGT'};
        Map<Id,Asset> accountMachines = AssetSvc.retrieveAccountMachines(new Set<Id>(mRpsId_Account.values()), rtDevNames);

        Map<Id,List<Asset>> mAccountId_Assets = new Map<Id,List<Asset>>();
        for(Asset asset : accountMachines.values()) {
            if(!mAccountId_Assets.containsKey(asset.AccountID)) {
                mAccountId_Assets.put(asset.AccountId,new List<Asset>{asset});
            } else {
                List<Asset> currAccountAssets = mAccountId_Assets.get(asset.AccountId);
                currAccountAssets.add(asset);
            }
        }
        for(Route_Processing_Sheet__c rps : scope) {
            if(!mRpsId_MeterIds.containsKey(rps.Id)) {
                mRpsId_MeterIds.put(rps.Id, new Set<Id>());
            }
            List<Asset> rpsAssets = mAccountId_Assets.get(rps.Account__c);
            this.iTotalRecordsProcessed++;

            if(rpsAssets != null && !rpsAssets.isEmpty()) {
                for (Asset rpsAsset : rpsAssets) {
                    Meter_Reading__c reading = new Meter_Reading__c();
                    reading.Asset__c = rpsAsset.Id;
                    reading.BV_Type__c = rpsAsset.BV_Type__c;
                    reading.Route_Processing_Sheet__c = rps.Id;
                    reading.Reading_Status__c = 'New';
                    meterReadingsIns.add(reading);
                }
            } else {
                rpsNoMeters.add(rps);
                log.Execution_Details__c += '\n * execute -  no assets found for rps: '+rps.Name;
            }
        }
        insert meterReadingsIns;

        iTotalMetersCreated += meterReadingsIns.size();
        for(Meter_Reading__c meterReading : meterReadingsIns) {
            this.meterReadingIds.add(meterReading.Id);
            Set<Id> rpsMeterIds = mRpsId_MeterIds.get(meterReading.Route_Processing_Sheet__c);
            if(rpsMeterIds != null) {
                rpsMeterIds.add(meterReading.Id);
            }
        }
    }

    public void finish(Database.BatchableContext bc) {
        log.Execution_Details__c += '* finish - Batch jobId: ' + this.jobId + '\n';
        log.Execution_Details__c += '* finish - Meteres created for processing locations ' + this.processingLocations + '\n';
        log.Execution_Details__c += '\n* finish - The following Meter Ids were inserted: ';
        if(!rpsNoMeters.isEmpty()) {
            this.sendNoMetersExistEmail(rpsNoMeters);
        }
        if(!this.meterReadingIds.isEmpty()) {
            if(!mRpsId_MeterIds.isEmpty()) {
               for(Id rpsId : mRpsId_MeterIds.keySet()) {
                   log.Execution_Details__c += '\n=== RPSID ='+rpsId;
                   Set<Id> meterIds = mRpsId_MeterIds.get(rpsId);
                   if(meterIds != null) {
                       log.Execution_Details__c += '.. RPSMeterIds=';
                       for(Id meterId : meterIds) {
                           log.Execution_Details__c += meterId +',';
                       }
                       log.Execution_Details__c.removeEnd(',');
                   }
               }
                log.Execution_Details__c +='\n';
            }
//            for (Id meterId : this.meterReadingIds) {
//                log.Execution_Details__c += meterId +',';
//            }
//            log.Execution_Details__c.removeEnd(',');
        }
        List <Route_Schedule_Change_PE__e> changePEs = new List<Route_Schedule_Change_PE__e>();

        Route_Schedule_Change_PE__e changePe    = new Route_Schedule_Change_PE__e();
        if(this.rsIds!=null && !this.rsIds.isEmpty()) {
            List<String> sRsIds = new List<String>();
            for(Id rsId : rsIds) {
                sRsIds.add(rsId);
            }
            changePe.Route_Schedule_Ids__c = String.join(sRsIds,',');
        }
        changePe.Operation_Type__c = PlatformEventSvc.DML_ACTION_INSERT;
        changePe.Ui_Message__c = rpsIds.size() + ' RPS successfully created with '+ meterReadingIds.size() + ' Meter readings!. Job is complete.';
        changePe.Status__c = 'Complete';
        changePe.Publishing_Process_Name__c = 'clBatchMeterReadingsCreation';
        changePEs.add(changePe);
        log.Execution_Details__c += '* finish - firing platform event\n';
        PlatformEventSvc.publishPlatformEvents(changePes);
        this.writeFinalLog(this.log);

    }

    private void initLog() {
        this.jobMdt = BatchjobSvc.queryForMetadata(jobName);    //  Query Metadata for params.
        Accel_Application_Error__c log = BatchjobSvc.buildLog(jobName);

        log.Overall_Job_Status__c = 'Processing';
        log.Total_Records_Updated__c = 0;
        log.Total_Records_Processed__c = 0;
        log.Total_Records_Selected__c = 0;
        log.Stack_Trace__c = ' ';
        log.Batch_Size__c = this.batchSize;
        log.Execution_Details__c = ' ';
        this.log = log;
    }

    private void writeFinalLog(Accel_Application_Error__c log) {

        if (log != null /* && log.Id != null*/) {

            log.Execution_Details__c += '* finish - writing log file.\n';
            log.Execution_Details__c += '\n\n==========   OVERALL Job Totals   =============== \n';
            log.Process_End_Date__c = System.now();
            log.Total_Records_Selected__c = iTotalRecordsSelected;
            log.Total_Records_Processed__c = iTotalRecordsProcessed;
            log.Total_Records_Updated__c = iTotalMetersCreated;
            log.Execution_Details__c += '* Total Records Selected = '+ iTotalRecordsSelected+ '\n';
            log.Execution_Details__c += '* Total Records Processed = ' + log.Total_Records_Processed__c + '\n';
            log.Execution_Details__c += '* Total Meters Created = ' + iTotalMetersCreated + '\n';
            log.Overall_Job_Status__c  = 'Success';
            insert log;
        }
    }

    public void sendNoMetersExistEmail(Set<Route_Processing_Sheet__c> rpsNoMeters) {
        String subject = 'Cash Logistics Warning  xx NO METERS CREATED XX';
        String body = '';
        body += 'clBatchMeterReadingsCreation.. jobId= '+this.jobId + '<br/>';
        body += 'No Meters Where Created For the Following RPS Sheets:<br/><br/>';
        for(Route_Processing_Sheet__c rps : rpsNoMeters) {
            body += 'RPS Name: ' + rps.Name  + ' rpsId='+rps.Id +'<br/>';
        }
        String[] emailAddys = new String[]{'rick@chicagosalesforceconsulting.com'};
        EmailSvc.sendEmail(emailAddys,subject,body);
    }
}