objects/Account.object
<CustomObject>
    <fields>
        <fullName>Accel_VGT_Live_Date__c</fullName>
        <label>Accel VGT Live Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Location_Type__c</fullName>
        <label>Accel Establishment Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Accel_Establishment_Type</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

globalValueSets/Accel_Establishment_Type.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Adult Entertainment</fullName>
    </customValue>
    <customValue>
        <fullName>American Legion</fullName>
    </customValue>
    <customValue>
        <fullName>Bar</fullName>
    </customValue>
    <customValue>
        <fullName>Bar &amp; Grill</fullName>
    </customValue>
    <customValue>
        <fullName>Bowling Alley</fullName>
    </customValue>
    <customValue>
        <fullName>C-Store</fullName>
    </customValue>
    <customValue>
        <fullName>C-Store W/O Gas</fullName>
    </customValue>
    <customValue>
        <fullName>Fraternal</fullName>
    </customValue>
    <customValue>
        <fullName>Gaming Parlor</fullName>
    </customValue>
    <customValue>
        <fullName>Golf Course</fullName>
    </customValue>
    <customValue>
        <fullName>Hotel</fullName>
    </customValue>
    <customValue>
        <fullName>Liquor Store</fullName>
    </customValue>
    <customValue>
        <fullName>OTB</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <customValue>
        <fullName>Private Club</fullName>
    </customValue>
    <customValue>
        <fullName>Recreation (Comedy,Billiards)</fullName>
    </customValue>
    <customValue>
        <fullName>Restaurant</fullName>
    </customValue>
    <customValue>
        <fullName>Truck Stop</fullName>
    </customValue>
    <customValue>
        <fullName>VFW</fullName>
    </customValue>
    <customValue>
        <fullName>Grocery Store</fullName>
    </customValue>
    <customValue>
        <fullName>Barber Shop</fullName>
        <isActive>false</isActive>
        <label>Barber Shop</label>
    </customValue>
    <customValue>
        <fullName>Bait Shop</fullName>
        <isActive>false</isActive>
        <label>Bait Shop</label>
    </customValue>
    <customValue>
        <fullName>Lounge</fullName>
        <isActive>false</isActive>
        <label>Lounge</label>
    </customValue>
    <customValue>
        <fullName>Unavailable</fullName>
        <isActive>false</isActive>
        <label>Unavailable</label>
    </customValue>
    <customValue>
        <fullName>C-Store/Liquor Store</fullName>
        <isActive>false</isActive>
        <label>C-Store/Liquor Store</label>
    </customValue>
    <masterLabel>Accel Establishment Type</masterLabel>
</GlobalValueSet>

classes/TEST_AdminSvc.cls
@IsTest
private class TEST_AdminSvc {
    public static String UNAME = 'acceltest@accel.com';

    @testSetup
    static void setup() {
        User u = TestUtils.getUserForTest(UNAME);
        System.runAs(u) {
            List<Account> accounts = new List<Account>();
            for (Integer i=0; i<20; i++) {
                Account a = TestUtils.buildAccount('TEST Admin Svc Account ' + i, null);
                a.ShippingLatitude = 44.968046;
                a.ShippingLongitude = -94.420307;
                a.Type = 'Accel Account';
                a.Accel_VGT_Live_Date__c = Date.today();
                a.Location_Type__c = 'Truck Stop';
                accounts.add(a);
            }
            insert accounts;
        }
    }

    @isTest
    static void testGetClosestAccounts_positive() {
        User u = TestUtils.getUserForTest(UNAME);
        System.runAs(u) {
            Account acc = [select id from account order by createddate desc limit 1];
            TEST.startTest();
            List<Account> closestAccounts = AdminSvc.getClosestAccounts(acc.id, 'Truck Stop');
          //  system.assert(!closestAccounts.isEmpty()); @TODO why is this not working?
            TEST.stopTest();
        }
    }
    @isTest
    static void testGetClosestAccounts_negative() {
        User u = TestUtils.getUserForTest(UNAME);
        System.runAs(u) {
            Account acc = [select id from account order by createddate desc limit 1];
            TEST.startTest();
            List<Account> closestAccounts = AdminSvc.getClosestAccounts(acc.id, '');
            system.assert(closestAccounts.isEmpty());
            TEST.stopTest();
        }
    }
}