objects/Account.object
<CustomObject>
    <fields>
        <fullName>Date__c</fullName>
        <formula>TODAY()</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Asset.object
<CustomObject>
    <fields>
        <fullName>Asset__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Asset</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Assets</relationshipLabel>
        <relationshipName>Assets4</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Model__c</fullName>
        <label>Model</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Hold_Per_Day__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Holds Per Day</relationshipLabel>
        <relationshipName>Holds_Per_Day</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Asset__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Asset</label>
        <referenceTo>Asset</referenceTo>
        <relationshipLabel>Holds Per Day</relationshipLabel>
        <relationshipName>Holds_Per_Day</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Location_Share__c</fullName>
        <formula>IF(Date__c &gt;= DATE(2020,7,1), ( Funds_In__c -  Funds_Out__c ) *0.3257, (IF(Date__c &gt;= DATE(2019,7,1), ( Funds_In__c -  Funds_Out__c ) *0.3314, ( Funds_In__c -  Funds_Out__c ) *0.3464)))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Location Share</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Net_Revenue__c</fullName>
        <formula>Funds_In__c -  Funds_Out__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Net Revenue</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Hold Per Day</label>
    <nameField>
        <displayFormat>HPD-{000000000}</displayFormat>
        <label>Hold Per Day Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Holds Per Day</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Products (Account)</relationshipLabel>
        <relationshipName>Products2</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/Accel_CommunityMachineCompController.cls
/**
 * Controller backing Accel_CommunityMachineComparisonMethod.
 */
public with sharing class Accel_CommunityMachineCompController {

    public static final String MAP_KEY_HPD_RECS = 'HPD_RECS';
    public static final String MAP_KEY_MACHINE_AVERAGES = 'PRODUCT_MACHINE_AVERAGES';
    public static final String DAILY_RECORDTYPE_NAME = 'Daily HPD';
    public static final String NO_RECORDS_FOUND_MSG = 'No records found'; //@TODO custom label
    public static final Integer DAYS_TO_GO_BACK = 30;

    /**
     * A simple sample query of HPD data.. kinda useless but just to provide an example.
     *
     * @param accountId - String account Id.
     *
     * @return a instance of responseDto containing the retrieved hpd list or error info
     * @see ResponseDto
     */
    @AuraEnabled (Cacheable=true)
    public static ResponseDto retrieveHoldPerDayByAccountLast30(String accountId) {
        //@TODO a good boy would validate incoming params including the dates.
        ResponseDto dto = new ResponseDto();
        List<Hold_Per_Day__c> holdPerDays = new List<Hold_Per_Day__c>();
        Date dStartDate = System.today() - DAYS_TO_GO_BACK;
        Date dEndDate = System.today();
        //--------- note generally I would call a service ie HpdSvc and leave business log out of the controller tied to the uti.
        //--------- this is just a simple example that is part of end to end data retrieval; examples.
        holdPerDays = [
                SELECT  id,date__c,asset__c,location_share__c, net_revenue__c,asset__r.model__c
                FROM    Hold_Per_Day__c
                WHERE   account__c = :accountId
                and     date__c >= :dStartDate
                and     date__c <= :dEndDate
                and     RecordType.Name = :DAILY_RECORDTYPE_NAME
                LIMIT   50000
        ];
        if (!holdPerDays.isEmpty()) {
            dto.isSuccess = true;
            dto.values.put(MAP_KEY_HPD_RECS, holdPerDays);
            dto.technicalMsg = 'param accountId=' + accountId;
        } else {
            dto.message = NO_RECORDS_FOUND_MSG;
            dto.isSuccess = false;
        }
        return dto;
    }
    /**
     *  Queries for machine averages over 30 days. Data on product is populuated nightly via batch jobs.
     *  All machines returned here (about 20)
     *
     * @return a instance of responseDto containing the retrieved product list or error info
     * @see ResponseDto
     */
    @AuraEnabled (Cacheable=true)
    public static ResponseDto retrieveMachineAverages() {
        ResponseDto dto = new ResponseDto();
        List<Product2> products = ProductSvc.retrieveAllMachineAverages();

        if (!products.isEmpty()) {
            dto.isSuccess = true;
            dto.values.put(MAP_KEY_MACHINE_AVERAGES, products);
        } else {
            dto.message = NO_RECORDS_FOUND_MSG;
            dto.isSuccess = false;
        }
        return dto;
    }
}