objects/Account.object
<CustomObject>
    <fields>
        <fullName>Hold_Per_Day_Total_Daily__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Based on HPD Records of Record type = Daily HPD</description>
        <inlineHelpText>Based on Monthly HPD Data</inlineHelpText>
        <label>Hold Per Day Total (Daily)</label>
        <referenceTo>Hold_Per_Day_Total__c</referenceTo>
        <relationshipLabel>Accounts (Hold Per Day Total (Daily))</relationshipLabel>
        <relationshipName>AccountsForDaily</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Hold_Per_Day_Total__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Based on HPD Records of Record type = Monthly HPD</description>
        <inlineHelpText>Based on Monthly HPD Data</inlineHelpText>
        <label>Hold Per Day Total (Monthly)</label>
        <referenceTo>Hold_Per_Day_Total__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Asset.object
<CustomObject>
    <fields>
        <fullName>Hold_Per_Day_Total__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Contains All Aggregated information for HPD Records for this Machine.</description>
        <inlineHelpText>Contains All Aggregated information for HPD Records for this Machine.</inlineHelpText>
        <label>Hold Per Day Total</label>
        <referenceTo>Hold_Per_Day_Total__c</referenceTo>
        <relationshipLabel>Assets</relationshipLabel>
        <relationshipName>Assets</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Hold_Per_Day_Total__c.object
<CustomObject>
    <description>Contains calculated information for HPD (currently only monthly)
Rolls up info for both Account(Location) and Municipality Levels (Separated by Record Type).
Fields such as TTM indicate 12 month roll-ups. all other fiels noted appropriated (4 weeks 8 weeks 12 weeks) etc.

Additional record type for future use of Machine exists as well.</description>
    <label>Hold Per Day Total</label>
    <nameField>
        <displayFormat>HPDT-{000000000}</displayFormat>
        <label>HPD Total #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Hold Per Day Totals</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/HPD_Total_Setting__mdt.object
<CustomObject>
    <description>Contains configurable parameters for HPD Totals Aggregation. (Nightly batch jobs that use SOQL aggregation to rollup data to Hold Per Day Total from Hold Per Data.</description>
    <fields>
        <fullName>HPD_Account_Types__c</fullName>
        <defaultValue>&quot;Accel Account,Competitor Account&quot;</defaultValue>
        <label>HPD Account Types</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>HPD Total Setting</label>
    <pluralLabel>HPD Total Settings</pluralLabel>
</CustomObject>

classes/BatchHpdLinkAccountRecsWithHpdTotals.cls
/**
 * Links account to newly created hold per day total reqs.
 * if a freq of 'Monthly' is passed in the constructor.. chains this same job to then do 'Daily' as well.
 */
global class BatchHpdLinkAccountRecsWithHpdTotals implements Database.Batchable<Sobject>, Database.Stateful {

    global HPD_Total_Setting__mdt hpdTotalSetting;
    global Integer iNumAccountsUpdated = 0;
    global String formattedLocalStartTimeString;
    global String formattedLocalEndTimeString;
    global String frequency = '';
    global Boolean initAssets = false;

    global BatchHpdLinkAccountRecsWithHpdTotals(String frequency, Boolean pInitAssets) {
        formattedLocalStartTimeString = DateTime.now().format();
        this.frequency = frequency;
        this.initAssets = pInitAssets;
    }
    global database.querylocator start(Database.BatchableContext bc) {
        hpdTotalSetting = CustomMetadataSvc.retrieveHpdTotalSettingsMeta(HpdSvc.ACCT_AGGREGATION_DEVNAME);
        List<String> accountTypes = hpdTotalSetting.HPD_Account_Types__c.split(',');
        return Database.getQueryLocator([
                select  id, hold_per_day_total__c, hold_per_day_total_daily__c
                from    account
                where   Type in :accountTypes
                and     (hold_per_day_total__c = null or hold_per_day_total_daily__c = null)
        ]);
    }

    global void execute(Database.BatchableContext bc, List<Account> scope) {
        List<Account> accountsUpdated = HpdStatsHelper.linkAccountsWithHdp(scope,this.frequency);
        iNumAccountsUpdated += accountsUpdated.size();
    }

    global void finish(Database.BatchableContext bc) {
        formattedLocalEndTimeString = DateTime.now().format();

        String subject = 'Accel SFDC Batch HPD Link Account to HPD '+frequency+' Total Automation process complete! ';
        String msg = '<br/>If you are receiving this email,it is because your email address was added to the HPD_Total_Setting__mdt as a valid address to receive debug emails for this job.<br/>';
        msg += '<br/>Start Time:<b> ' + formattedLocalStartTimeString + '</b>';
        msg += '<br/>End Time:<b> ' + formattedLocalEndTimeString + '</b><br/>';
        msg += '<br/> boolean initAssets:<b>'+initAssets+'</b><br/>';
        msg += '<br/># of Account Records linked for '+frequency+':<b> ' + iNumAccountsUpdated + '</b></br>';
        Id batchId;

//        if (!Test.isRunningTest() && 1 == 2 /*frequency == 'Monthly'*/) {
//            this.frequency = 'Daily';
//            BatchHpdLinkAccountRecsWithHpdTotals b = new BatchHpdLinkAccountRecsWithHpdTotals('Daily',true);
//            batchId = Database.executeBatch(b, 200);
//            msg += '<br/>Firing Batch Job again ' + batchId + ' to link ' + frequency +' account totals';
//        } else {
           if(!Test.isRunningTest() && initAssets){
                BatchHpdInitAssetRecs b = new BatchHpdInitAssetRecs();
                batchId = Database.executeBatch(b, 200);
                msg += '<br/>Firing Batch Job to init asset recs  ' + batchId ;
            }
     //   }
        List<String> emailAddys = EmailSvc.getHpdEmailNotificationAddys(HpdSvc.ACCT_AGGREGATION_DEVNAME);
        String body = msg;
        EmailSvc.sendEmail(emailAddys,subject,body);
    }
}