objects/Account.object
<CustomObject>
    <fields>
        <fullName>Accel_VGT_Live_Date__c</fullName>
        <label>Accel VGT Live Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <formula>TODAY()</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Filtered_Location_Type__c</fullName>
        <formula>CASE(text(Location_Type__c), 
&quot;Adult Entertainment&quot;, &apos;Other&apos;,
&quot;American Legion&quot;, &apos;Fraternal/VFW&apos;,
&quot;Bar&quot;, &apos;Bar&apos;,
&quot;Bar &amp; Grill&quot;, &apos;Bar&apos;,
&quot;Bowling Alley&quot;, &apos;Other&apos;,
&quot;C-Store&quot;, &apos;C-Store&apos;,
&quot;C-Store W/O Gas&quot;, &apos;C-Store&apos;,
&quot;Fraternal&quot;, &apos;Fraternal/VFW&apos;,
&quot;Gaming Parlor&quot;, &apos;Gaming Parlor&apos;,
&quot;Golf Course&quot;, &apos;Other&apos;,
&quot;Hotel&quot;, &apos;Other&apos;, 
&quot;Liquor Store&quot;, &apos;C-Store&apos;,
&quot;OTB&quot;, &apos;Other&apos;,
&quot;Private Club&quot;, &apos;Fraternal/VFW&apos;,
&quot;Recreation (Comedy,Billiards)&quot;, &apos;Other&apos;,
&quot;Restaurant&quot;, &apos;Restaurant&apos;,
&quot;Truck Stop&quot;, &apos;Truck Stop&apos;,
&quot;Grocery Store&quot;, &apos;Grocery Store&apos;,
&quot;VFW&quot;, &apos;Fraternal/VFW&apos;, null)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Filtered Location Type</label>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Location</fullName>
        <active>true</active>
        <label>Location</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Asset.object
<CustomObject>
    <fields>
        <fullName>Asset__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Asset</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Assets</relationshipLabel>
        <relationshipName>Assets4</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Model__c</fullName>
        <label>Model</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>VGT</fullName>
        <active>true</active>
        <label>VGT</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Case.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Choose the Location destination of the part, VGT, RT, etc.</description>
        <label>Location to Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Cases (Location to Name)</relationshipLabel>
        <relationshipName>Cases2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Model__c</fullName>
        <formula>Asset.Model__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Model</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Hold_Per_Day__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Holds Per Day</relationshipLabel>
        <relationshipName>Holds_Per_Day</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Asset__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Asset</label>
        <referenceTo>Asset</referenceTo>
        <relationshipLabel>Holds Per Day</relationshipLabel>
        <relationshipName>Holds_Per_Day</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Funds_In__c</fullName>
        <label>Funds In</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Machine_Location_Type__c</fullName>
        <label>Machine Location Type</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Machine_Model__c</fullName>
        <label>Machine Model</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Metric_Type__c</fullName>
        <label>Metric Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Statewide90DAverage</fullName>
                </value>
                <value>
                    <fullName>Statewide90DAveragePrevYear</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Hold Per Day</label>
    <nameField>
        <displayFormat>HPD-{000000000}</displayFormat>
        <label>Hold Per Day Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Holds Per Day</pluralLabel>
    <recordTypes>
        <fullName>Model_Metric</fullName>
        <active>true</active>
        <description>Rollup Information about a specific cabinet</description>
        <label>Model Metric</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/AggregateMachineModelMetrics.cls
global class AggregateMachineModelMetrics implements Queueable {
    @TestVisible static Time    UNIT_TEST_CURRENT_TIME_OVERRIDE     = System.now().time().addHours(2);

    global void execute(QueueableContext ctx){
        updateModelMetricHpd('Statewide90DAverage');
        updateModelMetricHpd('Statewide90DAveragePrevYear');
    }

    public void updateModelMetricHpd(String type){

        List<Hold_Per_Day__c> newAggregates = new List<Hold_Per_Day__c>();
        List<Hold_Per_Day__c> updateAggregates = new List<Hold_Per_Day__c>();

        List<String> models = new List<String>();
        List<String> locationTypes = new List<String>();
//        Boolean isHpdDarkZone = isHpdDarkZone();

        //values from formula field
        locationTypes.add('Other');
        locationTypes.add('Fraternal/VFW');
        locationTypes.add('Bar');
        locationTypes.add('C-Store');
        locationTypes.add('Gaming parlor');
        locationTypes.add('Restaurant');
        locationTypes.add('Truck Stop');
        locationTypes.add('Grocery Store');

        Date startD ;
        Date endD;

        Date mostRecentHpdDate = CommunityUtils.getMostRecentHpdDate();
        endD = (type == 'Statewide90DAverage') ? mostRecentHpdDate : Date.today().addDays(-366); //  @todo ??
        startD = (type == 'Statewide90DAverage') ? mostRecentHpdDate.addDays(-91) : Date.today().addDays(-456);//  @todo ??

/*       @todo not 100% sure what the logic is meant to do in the below.. interpreting it as.... (minus dark zone stuff):
            (a) end date:  if type = StateWide90DAverage use most recent hpd date otherwise use a date 366 days ago
            (b) start date: if type = StateWide90DAverage use most recent hpd date - 91 days..  otherwise use a date 456 days ago.*/

//        if(isHpdDarkZone){
//            endD = (type == 'Statewide90DAverage' ? Date.today().addDays(-2) : Date.today().addDays(-367));
//            startD = (type == 'Statewide90DAverage' ? Date.today().addDays(-92) : Date.today().addDays(-457));
//        }else{
//            endD = (type == 'Statewide90DAverage' ? Date.today().addDays(-1) : Date.today().addDays(-366));
//            startD = (type == 'Statewide90DAverage' ? Date.today().addDays(-91) : Date.today().addDays(-456));
//        }

        //get models from live locations
        for(AggregateResult machine : [select model__c m from asset where recordtype.name ='VGT' and account.accel_vgt_live_date__c != null and model__c != null and account.type = 'Accel Account' group by model__c]){
            models.add((String)machine.get('m'));
        }
        //get the current hpd model metric dataset
        updateAggregates = [select id, funds_in__c, machine_model__c, machine_location_type__c  from hold_per_day__c where recordtype.name = 'Model Metric' and metric_type__c = :type];

//loop through each location type
        for(String s : locationTypes){
            //for each location type loop through each model and do calcs

            for(AggregateResult ar : [select avg(funds_In__c) fundsIn, asset__r.model__c assetModel from hold_per_day__c where account__r.accel_vgt_live_date__c != null and asset__r.model__c in :models and account__r.Filtered_Location_Type__c = :s  and account__r.type = 'Accel Account' and date__c >= :startD and date__c <= :endD group by asset__r.model__c]){
                //find corresponding hpd record and either update it or send it to be created
                Integer found = 0;
                for(hold_per_day__c h : updateAggregates){
                    if(h.machine_model__c == (String)ar.get('assetModel') && h.machine_location_type__c == s){
                        //found, set int flag to true
                        found = 1;
                        //modify the hpd record average funds in
                        h.funds_in__c = (Decimal)ar.get('fundsIn');
                    }
                }
                if(found == 0){
                    //new hpd record needs to be created for that model at that location type
                    Hold_Per_Day__c newHpd = new Hold_Per_Day__c();
                    newHpd.funds_in__c = (Decimal)ar.get('fundsIn');
                    newHpd.machine_model__c = (String)ar.get('assetModel');
                    newHpd.recordtypeid = SObjectType.Hold_Per_Day__c.getRecordTypeInfosByDeveloperName().get('Model_Metric').getRecordTypeId();
                    newHpd.metric_type__c = type;
                    newHpd.machine_location_type__c = s;
                    newAggregates.add(newHpd);
                }
            }
        }
        if(newAggregates.size()>0){
            try{
                insert newAggregates;
            }catch(DmlException e){
                //hello?
            }
        }
        try{
            update updateAggregates;
        }catch(DmlException e){
            //hello?
        }
    }
//    @TestVisible
//    private static Boolean isHpdDarkZone() {
//        Boolean isHpdDarkZone;
//        if(!Test.isRunningTest()) {
//            isHpdDarkZone = CommunityUtils.isHpdDarkZone(System.now().time());
//        } else {
//            System.debug('==== unit test time='+UNIT_TEST_CURRENT_TIME_OVERRIDE);
//            isHpdDarkZone = CommunityUtils.isHpdDarkZone(UNIT_TEST_CURRENT_TIME_OVERRIDE);
//        }
//        return isHpdDarkZone;
//    }

}