objects/Account.object
<CustomObject>
    <fields>
        <fullName>Total_Applications__c</fullName>
        <label>Total Applications</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/LicenseApplication__c.object
<CustomObject>
    <fields>
        <fullName>Location_DBA__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>License_Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Total_Applications__c</fullName>
        <formula>Location_DBA__r.Total_Applications__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Total Applications</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>IGB Video Gaming</fullName>
                </value>
                <value>
                    <fullName>GLC_COAM_Class</fullName>
                    <label>GLC COAM Class B</label>
                </value>
                <value>
                    <fullName>NE Cash Device</fullName>
                </value>
                <value>
                    <fullName>DOJ</fullName>
                    <isActive>false</isActive>
                    <label>DOJ</label>
                </value>
                <value>
                    <fullName>Gaming</fullName>
                    <isActive>false</isActive>
                    <label>Gaming</label>
                </value>
                <value>
                    <fullName>Generic Application</fullName>
                    <isActive>false</isActive>
                    <label>Generic Application</label>
                </value>
                <value>
                    <fullName>Illinois Business Authorization</fullName>
                    <isActive>false</isActive>
                    <label>Illinois Business Authorization</label>
                </value>
                <value>
                    <fullName>Liquor</fullName>
                    <isActive>false</isActive>
                    <label>Liquor</label>
                </value>
                <value>
                    <fullName>Local Gaming License</fullName>
                    <isActive>false</isActive>
                    <label>Local Gaming License</label>
                </value>
                <value>
                    <fullName>Local Liquor License</fullName>
                    <isActive>false</isActive>
                    <label>Local Liquor License</label>
                </value>
                <value>
                    <fullName>State Liquor License</fullName>
                    <isActive>false</isActive>
                    <label>State Liquor License</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Application</label>
    <nameField>
        <label>Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/Test_ApplicationTrigger.cls
/**
 * Created by CedricN on 4/12/2021.
 */
@isTest
private  class Test_ApplicationTrigger {


    @testSetup

   static void testSetup(){
       // List<LicenseApplication__c> Applications = new List<LicenseApplication__c>();



                Account acct = new Account(name =' Test Account', Total_Applications__c = 0);

                insert acct;



    }

    @isTest
    static void insertApplicationCount(){

        Account act = [Select Id, Name, Total_Applications__c from Account where Name='Test Account'];

        LicenseApplication__c app = new LicenseApplication__c();

        app.type__c = 'IGB Video Gaming';
        app.Location_DBA__c = act.Id;

        if(act.Total_Applications__c >= 2 ){
            act.addError('ERROR MESSAGE');
        }

        try{
            insert app;
          //  System.debug(accUpdateList);
        }Catch(Exception e){
            System.debug('Exception :'+e.getMessage());
        }




    }



    @isTest
    static void twoApplicationCount(){

        Account act = [Select Id, Name, Total_Applications__c from Account where Name='Test Account'];

        LicenseApplication__c app = new LicenseApplication__c();

        app.type__c = 'IGB Video Gaming';
        app.Location_DBA__c = act.Id;

        LicenseApplication__c app3 = new LicenseApplication__c();

        app3.type__c = 'IGB Video Gaming';
        app3.Location_DBA__c = act.Id;

        if(act.Total_Applications__c >= 2 ){
            act.addError('ERROR MESSAGE');
        }

        try{
            insert app;

            insert app3;
            //  System.debug(accUpdateList);
        }Catch(Exception e){
            Boolean expectedExceptionThrown =  e.getMessage().contains('ERROR MESSAGE') ? true : false;
    //        System.assertEquals(expectedExceptionThrown, true);
            System.debug('Exception :'+e.getMessage());
        }




    }

    @isTest
    static void deleteApplicationCount(){

        Account ac2 = [Select Id, Name, Total_Applications__c from Account where Name='Test Account'];


        if(ac2.Total_Applications__c >= 2 ){
            ac2.addError('ERROR MESSAGE');
        }
        LicenseApplication__c app1 = new LicenseApplication__c();

        app1.type__c = 'IGB Video Gaming';
        app1.Location_DBA__c = ac2.Id;
        try{
            insert app1;
            //  System.debug(accUpdateList);
            delete app1;
        }Catch(Exception e){
            System.debug('Exception :'+e.getMessage());
        }



    }



}