objects/Account.object
<CustomObject>
    <fields>
        <fullName>Access_Time__c</fullName>
        <label>Access Time</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Collection_Contact_Name__c</fullName>
        <label>Collection Contact Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Collection_Contact_Number__c</fullName>
        <label>Collection Contact Number</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Collection_Notes__c</fullName>
        <label>Collection Notes</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>IGB_License__c</fullName>
        <externalId>true</externalId>
        <label>IGB License #</label>
        <length>18</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Location_Key_ID__c</fullName>
        <label>Location Key ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Relationship_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Relationship Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Accounts3</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Asset.object
<CustomObject>
    <fields>
        <fullName>Model__c</fullName>
        <label>Model</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Meter_Reading__c.object
<CustomObject>
    <description>Example object to capture electronic meters</description>
    <fields>
        <fullName>Collection_Date__c</fullName>
        <description>FF to the Route_Processing_Sheet__c.Collection_Date__c</description>
        <formula>Route_Processing_Sheet__r.Collection_Date__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>The collection date of the route processing sheet.</inlineHelpText>
        <label>Collection Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Model__c</fullName>
        <formula>Asset__r.Model__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Model</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Route_Processing_Sheet__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Route Processing Sheet</label>
        <referenceTo>Route_Processing_Sheet__c</referenceTo>
        <relationshipLabel>Meter Readings</relationshipLabel>
        <relationshipName>Meter_Readings</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Meter Reading</label>
    <nameField>
        <displayFormat>MTR-{000000000}</displayFormat>
        <label>Meter Reading ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Meter Readings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Route__c.object
<CustomObject>
    <description>Example object to house routes and routing of collections</description>
    <fields>
        <fullName>Collection_Date__c</fullName>
        <label>Collection Date ( Obsolete? )</label>
        <type>Date</type>
    </fields>
    <label>Route</label>
    <nameField>
        <label>Route Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Routes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Route_Processing_Sheet__c.object
<CustomObject>
    <description>Example digitization of the route processing sheet</description>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account DBA</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Route Processing Sheets</relationshipLabel>
        <relationshipName>Route_Processing_Sheets</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Collection_Date__c</fullName>
        <label>Collection Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Collector_1__c</fullName>
        <description>FF to Collector 1 User Name</description>
        <formula>Route_Schedule__r.Collector_1__r.FirstName + &apos; &apos; + Route_Schedule__r.Collector_1__r.LastName</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Collector 1 User Name</inlineHelpText>
        <label>Collector 1</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Processing_Status_Changed_By__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Fill Status Last Modified By</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Route_Processing_Sheets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Redemption_Asset__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Redemption Asset</label>
        <referenceTo>Asset</referenceTo>
        <relationshipLabel>Route Processing Sheets</relationshipLabel>
        <relationshipName>Route_Processing_Sheets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Route_Fill_Date__c</fullName>
        <description>not sure?</description>
        <inlineHelpText>not sure?</inlineHelpText>
        <label>Route Fill Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Route_Schedule__c</fullName>
        <label>Route Schedule</label>
        <referenceTo>Route_Schedule__c</referenceTo>
        <relationshipLabel>Route Processing Sheets</relationshipLabel>
        <relationshipName>Route_Processing_Sheets</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Stop_Number__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Stop Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Route Processing Sheet</label>
    <nameField>
        <displayFormat>Collection-Id-{000000000}</displayFormat>
        <label>Collection ID Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Route Processing Sheets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Route_Schedule__c.object
<CustomObject>
    <description>Assignment information of a physical route&apos;s locations, collectors, vehicles, and questions for a specific day</description>
    <fields>
        <fullName>Assigned_Driver__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Assigned Driver</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2 OR 3</booleanFilter>
            <filterItems>
                <field>User.Id</field>
                <operation>equals</operation>
                <valueField>$Source.Collector_1__c</valueField>
            </filterItems>
            <filterItems>
                <field>User.Id</field>
                <operation>equals</operation>
                <valueField>$Source.User__c</valueField>
            </filterItems>
            <filterItems>
                <field>User.Id</field>
                <operation>equals</operation>
                <valueField>$Source.Collector_3__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>Route_Schedules2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Collector_1__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Collector #1</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Route_Schedules</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Collector_3__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Admin only usage</description>
        <inlineHelpText>Admin only usage</inlineHelpText>
        <label>Collector #3</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Route_Schedules6</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Route_Fill_Date__c</fullName>
        <description>Not sure how this is used yet?</description>
        <inlineHelpText>Note sure how this is used yet?</inlineHelpText>
        <label>Route Fill Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Route__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Route to collect</description>
        <label>Route</label>
        <referenceTo>Route__c</referenceTo>
        <relationshipLabel>Route Schedules</relationshipLabel>
        <relationshipName>Route_Schedules</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Collector #2</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Route_Schedules1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Route Schedule</label>
    <nameField>
        <label>Route Schedule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Route Schedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/clRouteProcessingSheetSvc.cls
public without sharing class clRouteProcessingSheetSvc {

    public static Route_Processing_Sheet__c retrieveRouteProcessingSheet(Id rpsId) {
        Route_Processing_Sheet__c rps;
        String q = '';
        q += 'SELECT {0}, ';
        q += '       Account__r.Name,Account__r.ShippingStreet, Account__r.ShippingCity, Account__r.ShippingState, ';
        q += '       Account__r.ShippingLatitude, Account__r.ShippingLongitude,Account__r.ShippingPostalCode,';
        q += '       Route_Schedule__r.Route__c,';
        q += '       Processing_Status_Changed_By__r.Name ,Account__r.Relationship_Manager__r.Name, Account__r.Collection_Contact_Name__c, ';
        q += '       Account__r.Collection_Contact_Number__c,Account__r.Collection_Notes__c ';
        q += 'FROM   Route_Processing_Sheet__c ';
        q += 'WHERE  Id  = :rpsId ';
        String formattedQuery = String.format(q,getAllRouteProcessingSheetFields());

        List<Route_Processing_Sheet__c> routeProcessingSheets = Database.query(formattedQuery);
        if(!routeProcessingSheets.isEmpty()) {
            rps = routeProcessingSheets[0];
        }
        return rps;
    }

    public static List<Route_Processing_Sheet__c> retrieveRouteProcessingSheets( Id userId, Date collectionDate ) {
        return retrieveRouteProcessingSheets(new Set<Id>{userId}, collectionDate);
    }

    public static List<Route_Processing_Sheet__c> retrieveRouteProcessingSheetsForProcessor( String type, Id userId, Id routeScheduleId, Date collectionDate ) {
        return retrieveRouteProcessingSheetsForProcessor(type, new Set<Id>{userId}, routeScheduleId,collectionDate);
    }

    public static List<Route_Processing_Sheet__c> retrieveAllRouteProcessingSheets() {
        /*
         * 3/8/2023 Added Account__r.IGB_License__c
         * @see https://accel-entertainment.monday.com/boards/1300348967/pulses/4106517832
         */
        String q = '';
        q += 'SELECT {0} ,';
        q += '       Account__r.Name,Account__r.ShippingStreet, Account__r.ShippingCity, Account__r.ShippingState, Account__r.ShippingPostalCode, ';
        q += '       Account__r.ShippingLatitude, Account__r.ShippingLongitude,Account__r.Location_Key_ID__c, ';
        q += '       Account__r.Access_Time__c,Account__r.Relationship_Manager__r.Name, Account__r.Collection_Contact_Name__c,';
        q += '       Account__r.IGB_License__c,';
        q += '       Route_Schedule__r.Route__c,Redemption_Asset__r.Model__c,';
        q += '       Account__r.Relationship_Manager__r.Phone, Account__r.Relationship_Manager__r.MobilePhone,';
        q += '       Account__r.Collection_Contact_Number__c ,Account__r.Collection_Notes__c ';
        q += 'FROM   Route_Processing_Sheet__c ';
        q += 'ORDER BY Stop_Number__c ASC LIMIT 200';
        
        String formattedQuery = String.format(q,getAllRouteProcessingSheetFields());

        List<Route_Processing_Sheet__c> routeProcessingSheets = Database.query(formattedQuery);
        return routeProcessingSheets;
    }

    public static List<Route_Processing_Sheet__c> retrieveRouteProcessingSheets( Set<Id> userIds, Date collectionDate ) {
        System.debug('----> retrieve rps userIds='+userIds + '.. date='+collectionDate);
        /*
         * 3/8/2023 Added Account__r.IGB_License__c
         * @see https://accel-entertainment.monday.com/boards/1300348967/pulses/4106517832
         */
        String q = '';
        q += 'SELECT {0} ,';
        q += '       Account__r.Name,Account__r.ShippingStreet, Account__r.ShippingCity, Account__r.ShippingState, Account__r.ShippingPostalCode, ';
        q += '       Account__r.ShippingLatitude, Account__r.ShippingLongitude,Account__r.Location_Key_ID__c, ';
        q += '       Account__r.Access_Time__c,Account__r.Relationship_Manager__r.Name, Account__r.Collection_Contact_Name__c,';
        q += '       Account__r.IGB_License__c,';
        q += '       Route_Schedule__r.Route__c,Redemption_Asset__r.Model__c,';
        q += '       Account__r.Relationship_Manager__r.Phone,Account__r.Relationship_Manager__r.MobilePhone, ';
        q += '       Account__r.Collection_Contact_Number__c,Account__r.Collection_Notes__c ';
        q += 'FROM   Route_Processing_Sheet__c ';
        q += 'WHERE  ( ' +
                '      Route_Schedule__r.User__c               In :userIds ' +
                '      or Route_Schedule__r.Collector_1__c     In :userIds ' +
                '      or Route_Schedule__r.Assigned_Driver__c In :userIds ' +
                '      or Route_Schedule__r.Collector_3__c     In :userIds ' +
                '    ) ';
        q += 'AND    Collection_Date__c = :collectionDate ';

        q += 'ORDER BY Stop_Number__c ASC ';
        String formattedQuery = String.format(q,getAllRouteProcessingSheetFields());

        List<Route_Processing_Sheet__c> routeProcessingSheets = Database.query(formattedQuery);
        return routeProcessingSheets;
    }

    public static List<Route_Processing_Sheet__c> retrieveRouteProcessingSheetsForProcessor( String type, Set<Id> userIds, Id routeScheduleId,Date dDate ) {
        /*
         * 3/8/2023 Added Account__r.IGB_License__c
         * @see https://accel-entertainment.monday.com/boards/1300348967/pulses/4106517832
         */
        String q = '';
        q += 'SELECT {0} ,';
        q += '       Account__r.Name,Account__r.ShippingStreet, Account__r.ShippingCity, Account__r.ShippingState,  Account__r.ShippingPostalCode, ';
        q += '       Account__r.ShippingLatitude, Account__r.ShippingLongitude,Account__r.Location_Key_ID__c, ';
        q += '       Route_Schedule__r.Route__c,';
        q += '       Account__r.Access_Time__c,Account__r.Relationship_Manager__r.Name,Account__r.Collection_Contact_Name__c, ';
        q += '       Account__r.Collection_Contact_Number__c,Redemption_Asset__r.Model__c,';
        q += '       Account__r.Relationship_Manager__r.Phone,Account__r.Relationship_Manager__r.MobilePhone,Account__r.Collection_Notes__c, ';
        q += '       Account__r.IGB_License__c ';
        q += 'FROM   Route_Processing_Sheet__c ';
        q += 'WHERE  Route_Schedule__c = :routeScheduleId ';
        if(type == 'fill') {
            q += 'AND    Route_Fill_Date__c = :dDate ';
        } else {
            q += 'AND    Collection_Date__c = :dDate ';
        }

        q += 'ORDER BY Stop_Number__c ASC ';
        String formattedQuery = String.format(q,getAllRouteProcessingSheetFields());
        System.debug('---> formatted Query:'+formattedQuery);
        System.debug('---> userIds:'+userIds);
        System.debug('---> date:'+dDate);

        List<Route_Processing_Sheet__c> routeProcessingSheets = Database.query(formattedQuery);
        return routeProcessingSheets;
    }


    public static List<Route_Processing_Sheet__c> retrieveRouteProcessingSheets( Id routeScheduleId ) {
        /*
         * 3/8/2023 Added Account__r.IGB_License__c
         * @see https://accel-entertainment.monday.com/boards/1300348967/pulses/4106517832
         */
        String q = '';
        q += 'SELECT {0}, Account__r.Name, Account__r.ShippingStreet, Account__r.ShippingCity, Account__r.ShippingState, ';
        q += '       Account__r.Access_Time__c, ';
        q += '       Account__r.IGB_License__c,';
        q += '       Route_Schedule__r.Name, ';
        q += '       Redemption_Asset__r.Model__c ';
        q += 'FROM   Route_Processing_Sheet__c ';
        q += 'WHERE  Route_Schedule__c = :routeScheduleId ';
        q += 'ORDER BY Stop_Number__c ASC ';
        String formattedQuery = String.format(q,getAllRouteProcessingSheetFields());

        List<Route_Processing_Sheet__c> routeProcessingSheets = Database.query(formattedQuery);
        return routeProcessingSheets;
    }

    public static Map<String,Object> deleteScheduleRpsAndMeterRecords(Id routeScheduleId) {

        List<Route_Processing_Sheet__c> deletedRpsRecs = new List<Route_Processing_Sheet__c>();
        List<Meter_Reading__c> deletedMeterRecs =  new List<Meter_Reading__c>();

        Map<Id,Route_Processing_Sheet__c> rpsRecs = new Map<Id,Route_Processing_Sheet__c>([
                SELECT Id
                FROM   Route_Processing_Sheet__c
                WHERE  Route_Schedule__c = :routeScheduleId
        ]);
        if(!rpsRecs.isEmpty()) {
            List<Meter_Reading__c> meterReadings = [
                    SELECT Id
                    FROM   Meter_Reading__c
                    WHERE  Route_Processing_Sheet__c IN :rpsRecs.keySet()
            ];
            if(!meterReadings.isEmpty()) {
                deletedMeterRecs = meterReadings.deepClone(true);
                delete meterReadings;
            }
            deletedRpsRecs = rpsRecs.values().deepClone(true);
            delete rpsRecs.values();
        }
        return new Map<String,Object> {
                'DELETED_METER_RECS' => deletedMeterRecs,
                'DELETED_RPS_RECS' => deletedRpsRecs
        };
    }

    public static List<Meter_Reading__c> deleteScheduleMeterRecords(Id routeScheduleId) {

        List<Meter_Reading__c> deletedMeterRecs =  new List<Meter_Reading__c>();

        Map<Id,Route_Processing_Sheet__c> rpsRecs = new Map<Id,Route_Processing_Sheet__c>([
                SELECT Id
                FROM   Route_Processing_Sheet__c
                WHERE  Route_Schedule__c = :routeScheduleId
        ]);
        if(!rpsRecs.isEmpty()) {
            List<Meter_Reading__c> meterReadings = [
                    SELECT Id
                    FROM   Meter_Reading__c
                    WHERE  Route_Processing_Sheet__c IN :rpsRecs.keySet()
            ];
            if(!meterReadings.isEmpty()) {
                deletedMeterRecs = meterReadings.deepClone(true);
                delete meterReadings;
            }
        }
        return deletedMeterRecs;
    }

    @TestVisible
    private static List<String>  getAllRouteProcessingSheetFields() {
        Map<String, Schema.SObjectField> fieldsMap = Route_Processing_Sheet__c.sObjectType.getDescribe().fields.getMap();
        String sFields = String.join(new List<String>(fieldsMap.keySet()), ',');
        List<String> fields = new List<String>{sfields};
        return fields;
    }

}