objects/Account.object
<CustomObject>
    <fields>
        <fullName>Access_Time__c</fullName>
        <label>Access Time</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Location</fullName>
        <active>true</active>
        <label>Location</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Route__c.object
<CustomObject>
    <description>Example object to house routes and routing of collections</description>
    <label>Route</label>
    <nameField>
        <label>Route Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Routes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Route_Account__c.object
<CustomObject>
    <description>POC Junction Route__c &lt;----&gt; Account</description>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Account.Accel_VGT_Live_Date__c</field>
                <operation>notEqual</operation>
                <value></value>
            </filterItems>
            <infoMessage>Account should have a VGT Live Date</infoMessage>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Route Accounts</relationshipLabel>
        <relationshipName>Route_Accounts</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Collection_Type__c</fullName>
        <label>Collection Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Collection_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Replenishment_Type__c</fullName>
        <label>Replenishment Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Full Audit</fullName>
                    <default>true</default>
                    <label>Full Audit</label>
                </value>
                <value>
                    <fullName>Cash Fill</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Route__c</fullName>
        <label>Route</label>
        <referenceTo>Route__c</referenceTo>
        <relationshipLabel>Route Accounts</relationshipLabel>
        <relationshipName>Route_Accounts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Stop_Number__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Stop Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Route Account</label>
    <nameField>
        <displayFormat>RA-{00000000}</displayFormat>
        <label>RA #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Route Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Route_Schedule__c.object
<CustomObject>
    <description>Assignment information of a physical route&apos;s locations, collectors, vehicles, and questions for a specific day</description>
    <fields>
        <fullName>Route__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Route to collect</description>
        <label>Route</label>
        <referenceTo>Route__c</referenceTo>
        <relationshipLabel>Route Schedules</relationshipLabel>
        <relationshipName>Route_Schedules</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Route Schedule</label>
    <nameField>
        <label>Route Schedule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Route Schedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Route_Schedule_Account__c.object
<CustomObject>
    <description>POC Junction Route_Schedule__c &lt;----&gt; Account</description>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Account.Accel_VGT_Live_Date__c</field>
                <operation>notEqual</operation>
                <value></value>
            </filterItems>
            <infoMessage>Account Must Have A VGT Live Date</infoMessage>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Route Schedule Accounts</relationshipLabel>
        <relationshipName>Route_Schedule_Accounts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Collection_Type__c</fullName>
        <description>Used for additional fills.</description>
        <inlineHelpText>Used for additional fills.</inlineHelpText>
        <label>Collection Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Collection_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Replenishment_Type__c</fullName>
        <label>Replenishment Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Full Audit</fullName>
                    <default>true</default>
                    <label>Full Audit</label>
                </value>
                <value>
                    <fullName>Cash Fill</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Route_Schedule__c</fullName>
        <label>Route Schedule</label>
        <referenceTo>Route_Schedule__c</referenceTo>
        <relationshipLabel>Route Schedule Accounts</relationshipLabel>
        <relationshipName>Route_Schedule_Accounts</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Stop_Number__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Stop Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Route Schedule Account</label>
    <nameField>
        <displayFormat>RSA-{00000000}</displayFormat>
        <label>RSA #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Route Schedule Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

globalValueSets/Collection_Type.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Regular - RT &amp; VGT</fullName>
        <default>true</default>
        <label>Regular - RT &amp; VGT</label>
    </customValue>
    <customValue>
        <fullName>Additional Fill – RT &amp; VGT</fullName>
    </customValue>
    <customValue>
        <fullName>Additional Fill – RT Only</fullName>
    </customValue>
    <customValue>
        <fullName>Additional Fill – VGT Only</fullName>
    </customValue>
    <customValue>
        <fullName>Regular - 2nd RT</fullName>
    </customValue>
    <customValue>
        <fullName>Regular - RT Only</fullName>
    </customValue>
    <customValue>
        <fullName>Regular - VGT Only</fullName>
    </customValue>
    <customValue>
        <fullName>Regular - RT Only (Go Lives/RT swaps)</fullName>
        <isActive>false</isActive>
        <label>Regular - RT Only (Go Lives/RT swaps)</label>
    </customValue>
    <description>* Regular – RT &amp; VGT (typical collection involves changing VGT cans and swapping RT Cassettes)﻿
* Additional Fill – RT Only (this collection involves just changing RT Cassettes)﻿
* Additional Fill – VGT Only (this collection involves just swapping VGT cans)﻿
* Additional Fill – RT &amp; VGT (this collection involves changing VGT cans and swapping RT cassettes)
* Regular - 2nd RT (OLD.. not sure?)
* Regular - RT Only (NEW... not sure?)
* Regular - VGT Only (NEW.. not sure?)</description>
    <masterLabel>Collection Type</masterLabel>
</GlobalValueSet>

classes/clLocationReorderController.cls
public class clLocationReorderController {

    public final static String MAP_KEY_LOCATIONS = 'MAP_KEY_LOCATIONS';

    /**
     * @param sObjectApiName  The parent sObjectApi Name to query. [Route__c or Route_Schedule__c].
     * @param parentRecordId  The parent Id to query for children.
     *
     * @return                A list of clLocationObjects in the response map.
     */
    @AuraEnabled(Cacheable=true)
    public static ResponseDto retrieveLocations(String sObjectApiName, Id parentRecordId) {
        ResponseDto dto = new ResponseDto();
        dto.technicalMsg += '---> parentRecId='+parentRecordId+'.. sObj='+sObjectApiName;

        List<clLocation> clLocations = new List<clLocation>();
        switch on sObjectApiName {
            when 'Route__c' {
                clLocations = retrieveRouteAccounts(parentRecordId);
            }
            when 'Route_Schedule__c' {
                clLocations = retrieveRouteScheduleAccounts(parentRecordId);
            }
        }
        dto.isSuccess = !clLocations.isEmpty();
        dto.values.put(MAP_KEY_LOCATIONS,clLocations);
        return dto;
    }

    /**
     * @param allRecords All sObjects to update.
     * @return Response dto containing opp info
     */
    @AuraEnabled
    public static ResponseDto doUpdateStopNumbers(List<SObject> allRecords) {
        ResponseDto dto = new ResponseDto();
        Long mStart = SYSTEM.now().millisecond();
        update allRecords;
        Long mEnd = System.now().millisecond();
        dto.technicalMsg += '--> updated '+allRecords.size() + ' records for stop number. total upd time='+ (mEnd - mStart);
        dto.isSuccess = true;
        return dto;
    }

    /**
     * @param parentRecordId  The parent Record Id
     * @return                A list of clLocation which wraps Route_Account__c.
     */
    public static List<clLocation> retrieveRouteAccounts(Id parentRecordId) {
        List<clLocation> clLocations = new List<clLocation>();

        List<Route_Account__c> routeAccounts = [
                SELECT  Id,Route__c,Stop_Number__c,Route__r.Name,
                        Account__r.Access_Time__c,Collection_Type__c,Replenishment_Type__c,
                        Account__c,Account__r.Name,Account__r.ShippingCity,Account__r.ShippingState,Account__r.ShippingStreet,
                        Account__r.ShippingCountry,Account__r.ShippingPostalCode
                FROM    Route_Account__c
                WHERE   Route__c = :parentRecordId
                ORDER BY Stop_Number__c ASC NULLS LAST,
                         Account__r.Name
        ];

        for(Route_Account__c ra : routeAccounts) {
            clLocation clLoc = new clLocation();
            clLoc.recordId = ra.Id;
            clLoc.locName = ra.Account__r.Name;
            clLoc.locId = ra.Account__c;
            clLoc.locAccessTime = ra.Account__r.Access_Time__c;
            clLoc.stopNumber = ra.Stop_Number__c != null ? Integer.valueOf(ra.Stop_Number__c) : 0;
            clLoc.formattedAddress = formatAddress(new clAddy(ra));
            clLoc.formattedLocName = getFormattedLocName(clLoc.locName,clLoc.stopNumber);
            clLoc.parentName = ra.Route__r.Name;
            clLoc.collectionType = ra.Collection_Type__c;
            clLoc.replenishmentType = ra.Replenishment_Type__c;
            clLocations.add(clLoc);
        }
        return clLocations;
    }

    /**
     * @param parentRecordId  The parent Record Id
     * @return                A list of clLocation which wraps Route_Schedule_Account__c.
     */
    public static List<clLocation> retrieveRouteScheduleAccounts(Id parentRecordId) {
        List<clLocation> clLocations = new List<clLocation>();

        List<Route_Schedule_Account__c> routeScheduleAccounts = [
                SELECT  Id,Route_Schedule__c,Stop_Number__c,Route_Schedule__r.Name,
                        Account__r.Access_Time__c,Collection_Type__c,Replenishment_Type__c,
                        Account__c,Account__r.Name,Account__r.ShippingCity,Account__r.ShippingState,Account__r.ShippingStreet,
                        Account__r.ShippingCountry,Account__r.ShippingPostalCode
                FROM    Route_Schedule_Account__c
                WHERE   Route_Schedule__c = :parentRecordId
                ORDER BY Stop_Number__c ASC NULLS LAST,
                        Account__r.Name
        ];
        for(Route_Schedule_Account__c rsa : routeScheduleAccounts) {
            clLocation clLoc = new clLocation();
            clLoc.recordId = rsa.Id;
            clLoc.locName = rsa.Account__r.Name;
            clLoc.locId = rsa.Account__c;
            clLoc.locAccessTime = rsa.Account__r.Access_Time__c;
            clLoc.stopNumber = rsa.Stop_Number__c != null ? Integer.valueOf(rsa.Stop_Number__c) : 0;
            clLoc.formattedAddress = formatAddress(new clAddy(rsa));
            clLoc.formattedLocName = getFormattedLocName(clLoc.locName,clLoc.stopNumber);
            clLoc.parentName = rsa.Route_Schedule__r.Name;
            clLoc.collectionType = rsa.Collection_Type__c;
            clLoc.replenishmentType = rsa.Replenishment_Type__c;
            clLocations.add(clLoc);
        }
        return clLocations;
    }

    /**
     * @param clAddy a clAddy object.
     * @return formatted address string.
     */
    @TestVisible
    private Static String formatAddress(clAddy clAddy) {
        String addy = '';
        if (clAddy != null) {
            addy += clAddy.street;
            addy += ' - ' + clAddy.city;
            addy += ' ' + clAddy.state;
        }
        return addy;
    }

    /**
     * @param locName     The location name (account name).
     * @param stopNumber  The location stop number.
     *
     * @return            A string including the stop name next to the location name.
     */
    @TestVisible
    private static String getFormattedLocName(String locName, Integer stopNumber) {
        String stopText = '';
        if(stopNumber == null) {
            stopNumber = 0;
        }
        stopText = stopNumber != null ? '(' + stopNumber + ') ' : '';
        return stopText + locName;
    }
    /**
     * Wraps either a Route_Account__c or Route_Schedule_Account__c.
     */
    public class clLocation {
        @AuraEnabled public String parentName;
        @AuraEnabled public String locName;
        @AuraEnabled public String locAccessTime;
        @AuraEnabled public String formattedLocName;
        @AuraEnabled public Id locId;
        @AuraEnabled public Id recordId;
        @AuraEnabled public Integer stopNumber;
        @AuraEnabled public String formattedAddress;
        @AuraEnabled public String collectionType;
        @AuraEnabled public String replenishmentType;
    }

    public class clAddy {
        @AuraEnabled public String street;
        @AuraEnabled public String city;
        @AuraEnabled public String state;
        @AuraEnabled public String postalCode;
        @AuraEnabled public String country;

        public clAddy( Route_Account__c ra) {
            this.street = ra.Account__r.ShippingStreet;
            this.city = ra.Account__r.ShippingCity;
            this.state = ra.Account__r.ShippingState;
        }

        public clAddy( Route_Schedule_Account__c rsa) {
            this.street = rsa.Account__r.ShippingStreet;
            this.city = rsa.Account__r.ShippingCity;
            this.state = rsa.Account__r.ShippingState;
        }
    }
}