objects/Account.object
<CustomObject>
    <fields>
        <fullName>Date__c</fullName>
        <formula>TODAY()</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Most_Recent_Hold_Per_Day__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Most Recent Hold Per Day</label>
        <referenceTo>Hold_Per_Day__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Hold_Per_Day__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Holds Per Day</relationshipLabel>
        <relationshipName>Holds_Per_Day</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <label>Hold Per Day</label>
    <nameField>
        <displayFormat>HPD-{000000000}</displayFormat>
        <label>Hold Per Day Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Holds Per Day</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/BatchFixAccountMostRecentHpd.cls
global with sharing class BatchFixAccountMostRecentHpd implements Database.Batchable<Sobject>, Database.Stateful {
    public String rtName    {get;set;}
    public Date   hpdDate   {get;set;}

    global BatchFixAccountMostRecentHpd(String pRtName, Date pHpdDate) {
        this.rtName     = pRtName;
        this.hpdDate    = pHpdDate;
    }
    global database.querylocator start(Database.BatchableContext bc) {
        return Database.getQueryLocator([
                SELECT  Id,Account__c
                FROM    Hold_Per_Day__c
                WHERE   RecordType.name = :rtName
                AND     Date__c         = :hpdDate
        ]);
    }
    global void execute(Database.BatchableContext bc, List<Hold_Per_Day__c> scope) {
        if(!scope.isEmpty()) {
            List<Account> accountsToUpd = new List<Account>();
            Map<Id,Hold_Per_Day__c> mAccountId_Hpd = new Map<Id,Hold_Per_Day__c>();
            for(Hold_Per_Day__c hpd : scope) {
                mAccountId_Hpd.put(hpd.Account__c,hpd);
            }
            Map<Id,Account> mAccountsByIds = new Map<Id,Account> ([
                    SELECT  Id, Most_Recent_Hold_Per_Day__c
                    FROM    Account
                    WHERE   Id IN :mAccountId_Hpd.keySet()
            ]);
            for(Account account : mAccountsByIds.values()) {
                account.Most_Recent_Hold_Per_Day__c = ((Hold_Per_Day__c)mAccountId_Hpd.get(account.id)).id;
                accountsToUpd.add(account);
            }
            update accountsToUpd;
        }
    }
     global void finish(Database.BatchableContext bc) {}
}