objects/Account.object
<CustomObject>
    <fields>
        <fullName>Legal_Name__c</fullName>
        <label>Legal Name</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Route_Schedule__c.object
<CustomObject>
    <description>Assignment information of a physical route&apos;s locations, collectors, vehicles, and questions for a specific day</description>
    <fields>
        <fullName>Assigned_Driver__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Assigned Driver</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2 OR 3</booleanFilter>
            <filterItems>
                <field>User.Id</field>
                <operation>equals</operation>
                <valueField>$Source.Collector_1__c</valueField>
            </filterItems>
            <filterItems>
                <field>User.Id</field>
                <operation>equals</operation>
                <valueField>$Source.User__c</valueField>
            </filterItems>
            <filterItems>
                <field>User.Id</field>
                <operation>equals</operation>
                <valueField>$Source.Collector_3__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>Route_Schedules2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Starting_Vehicle_Milage__c</fullName>
        <label>Starting Vehicle Milage</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Vehicle_License__c</fullName>
        <label>Vehicle License</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Route Schedule</label>
    <nameField>
        <label>Route Schedule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Route Schedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/clFieldAuditControllerTest.cls
@IsTest
private class clFieldAuditControllerTest {
    @TestSetup
    static void setupData() {

        Test.startTest();
        Map<String,Object> mBaseData = clTESTUTILS.createAllNonClData();
        Test.stopTest();

        Map<String,Object> mClData =  clTESTUTILS.createEnd2EndRouteData(mBaseData);
    }

    @IsTest
    static void test_retrieveFieldHistoryByParams() {

        String historyObject = 'Route_Schedule__History';
        Datetime dtStart = System.now().addDays(-2);
        Datetime dtEnd = System.now();

        Map<Id,Route_Schedule__c> mRs = new Map<Id,Route_Schedule__c> ([
                Select Id
                FROM   Route_Schedule__c
                WHERE  CreatedDate >= :dtStart
                AND    CreatedDate <= :dtEnd
                LIMIT  2
        ]);
        Map<Id,Account> mAccounts = new Map<Id,Account> ([
                Select Id
                FROM   Account
                WHERE  CreatedDate >= :dtStart
                AND    CreatedDate <= :dtEnd
                LIMIT  2
        ]);

        Route_Schedule__History routeScheduleHistory = new Route_Schedule__History(
                Field = 'Starting_Vehicle_Milage__c', ParentId = mRs.values().get(0).Id
        );
        insert routeScheduleHistory;

        AccountHistory accountHistory = new AccountHistory(
                Field = 'Legal_Name__c', AccountId = mAccounts.values().get(0).Id
        );
        insert accountHistory;

        Test.startTest();

        System.runAs(new User(Id=UserInfo.getUserId())) {

            List<String> fields = new List<String>{'Assigned_Driver__c','Starting_Vehicle_Milage__c','Vehicle_License__c'};
            ResponseDto dto = clFieldAuditController.retrieveFieldHistoryByParams(dtStart,dtEnd,historyObject,fields);

            fields = new List<String>{'Legal_Name__c'};
            dto = clFieldAuditController.retrieveFieldHistoryByParams(dtStart,dtEnd,'AccountHistory',fields);
        }

        Test.stopTest();
    }

    @IsTest
    static void test_retrieveMdt() {

        Test.startTest();

        System.runAs(new User(Id=UserInfo.getUserId())) {
            ResponseDto dto = clFieldAuditController.retrieveFieldHistoryMetadata(clFieldAuditController.MDT_DEV_NAME_CL_FIELD_HISTORY);
        }

        Test.stopTest();
    }

}