objects/Account.object
<CustomObject>
    <fields>
        <fullName>X100_Fill_Level__c</fullName>
        <description>Note Count of 100&apos;s for Cash Logistics</description>
        <label>$100 Fill Level</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>X1_Fill_Level__c</fullName>
        <description>Note Count of 1&apos;s for Cash Logistics</description>
        <label>$1 Fill Level</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>X20_Fill_Level__c</fullName>
        <description>Note Count of 20&apos;s for Cash Logistics</description>
        <label>$20 Fill Level</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>X50_Fill_Level__c</fullName>
        <description>Note Count of 50&apos;s for Cash Logistics</description>
        <label>$50 Fill Level</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>X5_Fill_Level__c</fullName>
        <description>Note Count of 5&apos;s for Cash Logistics</description>
        <label>$5 Fill Level</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Route__c.object
<CustomObject>
    <description>Example object to house routes and routing of collections</description>
    <label>Route</label>
    <nameField>
        <label>Route Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Routes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Route_Account__c.object
<CustomObject>
    <description>POC Junction Route__c &lt;----&gt; Account</description>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Account.Accel_VGT_Live_Date__c</field>
                <operation>notEqual</operation>
                <value></value>
            </filterItems>
            <infoMessage>Account should have a VGT Live Date</infoMessage>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Route Accounts</relationshipLabel>
        <relationshipName>Route_Accounts</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Collection_Type__c</fullName>
        <label>Collection Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Collection_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Replenishment_Type__c</fullName>
        <label>Replenishment Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Full Audit</fullName>
                    <default>true</default>
                    <label>Full Audit</label>
                </value>
                <value>
                    <fullName>Cash Fill</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Route__c</fullName>
        <label>Route</label>
        <referenceTo>Route__c</referenceTo>
        <relationshipLabel>Route Accounts</relationshipLabel>
        <relationshipName>Route_Accounts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Stop_Number__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Stop Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>X100_Fill_Level__c</fullName>
        <description>Number of $100 notes to fill this location with</description>
        <label>$100 Fill Level</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>X1_Fill_Level__c</fullName>
        <description>Number of $1 notes to fill this location with</description>
        <label>$1 Fill Level</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>X20_Fill_Level__c</fullName>
        <description>Number of $20 notes to fill this location with</description>
        <label>$20 Fill Level</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>X50_Fill_Level__c</fullName>
        <description>Number of $50 notes to fill this location with</description>
        <label>$50 Fill Level</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>X5_Fill_Level__c</fullName>
        <description>Number of $5 notes to fill this location with</description>
        <label>$5 Fill Level</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Route Account</label>
    <nameField>
        <displayFormat>RA-{00000000}</displayFormat>
        <label>RA #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Route Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

globalValueSets/Collection_Type.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Regular - RT &amp; VGT</fullName>
        <default>true</default>
        <label>Regular - RT &amp; VGT</label>
    </customValue>
    <customValue>
        <fullName>Additional Fill – RT &amp; VGT</fullName>
    </customValue>
    <customValue>
        <fullName>Additional Fill – RT Only</fullName>
    </customValue>
    <customValue>
        <fullName>Additional Fill – VGT Only</fullName>
    </customValue>
    <customValue>
        <fullName>Regular - 2nd RT</fullName>
    </customValue>
    <customValue>
        <fullName>Regular - RT Only</fullName>
    </customValue>
    <customValue>
        <fullName>Regular - VGT Only</fullName>
    </customValue>
    <customValue>
        <fullName>Regular - RT Only (Go Lives/RT swaps)</fullName>
        <isActive>false</isActive>
        <label>Regular - RT Only (Go Lives/RT swaps)</label>
    </customValue>
    <description>* Regular – RT &amp; VGT (typical collection involves changing VGT cans and swapping RT Cassettes)﻿
* Additional Fill – RT Only (this collection involves just changing RT Cassettes)﻿
* Additional Fill – VGT Only (this collection involves just swapping VGT cans)﻿
* Additional Fill – RT &amp; VGT (this collection involves changing VGT cans and swapping RT cassettes)
* Regular - 2nd RT (OLD.. not sure?)
* Regular - RT Only (NEW... not sure?)
* Regular - VGT Only (NEW.. not sure?)</description>
    <masterLabel>Collection Type</masterLabel>
</GlobalValueSet>

classes/clRouteAccountCsv.cls
public class clRouteAccountCsv {

    public String generateRouteAccountCsv(List<Route_Account__c> routeAccounts) {
        String s = line(new String[] {
                format('Route Account Id'),
                format('Route Account Name'),
                format('Route Id'),
                format('Route Name'),
                format('Stop #'),
                format('Account Id'),
                format('Account Name'),
                format('Collection Type'),
                format('X1 Fill Level'),
                format('X5 Fill Level'),
                format('X20 Fill Level'),
                format('X50 Fill Level'),
                format('X100 Fill Level'),
                format('Replenishment Type'),
                format('Created Date'),
                format('Created By Id'),
                format('Created By User')
        });
        //String baseUrl =  URL.getSalesforceBaseUrl().toExternalForm();

        for (Route_Account__c  ra: routeAccounts) {
            //String raUrl = baseUrl+'/'+Route_Account__c.Id;
            s += line(new String[] {
                    format(ra.Id),
                    format(ra.Name),
                    format(ra.Route__c),
                    format(ra.Route__r.Name),
                    format(ra.Stop_Number__c),
                    format(ra.Account__c),
                    format(ra.Account__r.Name),
                    format(ra.Collection_Type__c),
                    format(ra.X1_Fill_Level__c),
                    format(ra.X5_Fill_Level__c),
                    format(ra.X20_Fill_Level__c),
                    format(ra.X50_Fill_Level__c),
                    format(ra.X100_Fill_Level__c),
                    format(ra.Replenishment_Type__c),
                    format(ra.CreatedDate),
                    format(ra.CreatedById),
                    format(ra.CreatedBy.UserName)
            });
        }
        return s;
    }
    private String line(String[] cells) {
        return String.join(cells, ',') + '\n';
    }
    private String format(Decimal d) {
        return d != null ? '"' + Integer.valueOf(d) + '"' : '""';
    }
    private String format(DateTime dt) {
        return dt != null ? '"' + dt + '"' : '""';
    }
    private String format(String s) {
        return s != null ? '"' + s.escapeCsv() + '"' : '""';
    }
}