objects/Account.object
<CustomObject>
    <fields>
        <fullName>Date__c</fullName>
        <formula>TODAY()</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Hold_Per_Day_Total__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Based on HPD Records of Record type = Monthly HPD</description>
        <inlineHelpText>Based on Monthly HPD Data</inlineHelpText>
        <label>Hold Per Day Total (Monthly)</label>
        <referenceTo>Hold_Per_Day_Total__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Most_Recent_Hold_Per_Day__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Most Recent Hold Per Day</label>
        <referenceTo>Hold_Per_Day__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Hold_Per_Day__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Holds Per Day</relationshipLabel>
        <relationshipName>Holds_Per_Day</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Amount_Played__c</fullName>
        <label>Amount Played</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Amount_Won__c</fullName>
        <label>Amount Won</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Funds_In__c</fullName>
        <label>Funds In</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Funds_Out__c</fullName>
        <label>Funds Out</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>HPD__c</fullName>
        <label>HPD</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>VGT_Count__c</fullName>
        <label>VGT Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Hold Per Day</label>
    <nameField>
        <displayFormat>HPD-{000000000}</displayFormat>
        <label>Hold Per Day Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Holds Per Day</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Hold_Per_Day_Total__c.object
<CustomObject>
    <description>Contains calculated information for HPD (currently only monthly)
Rolls up info for both Account(Location) and Municipality Levels (Separated by Record Type).
Fields such as TTM indicate 12 month roll-ups. all other fiels noted appropriated (4 weeks 8 weeks 12 weeks) etc.

Additional record type for future use of Machine exists as well.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Populated by script upon initial object creation. then populated upon creation of each account via trigger moving forward.</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Hold Per Day Totals</relationshipLabel>
        <relationshipName>Hold_Per_Day_Summaries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Municipality__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Municipality</label>
        <referenceTo>Municipality__c</referenceTo>
        <relationshipLabel>Hold Per Day Totals</relationshipLabel>
        <relationshipName>Hold_Per_Day_Totals</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Hold Per Day Total</label>
    <nameField>
        <displayFormat>HPDT-{000000000}</displayFormat>
        <label>HPD Total #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Hold Per Day Totals</pluralLabel>
    <recordTypes>
        <fullName>Municipality</fullName>
        <active>true</active>
        <label>Municipality</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Municipality__c.object
<CustomObject>
    <fields>
        <fullName>Amount_Played__c</fullName>
        <label>Amount Played</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Amount_Won__c</fullName>
        <label>Amount Won</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Funds_in__c</fullName>
        <label>Funds in</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Funds_out__c</fullName>
        <label>Funds out</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>HPD__c</fullName>
        <label>HPD</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Hold_Per_Day_Total__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Hold Per Day Totals</label>
        <referenceTo>Hold_Per_Day_Total__c</referenceTo>
        <relationshipLabel>Municipalities</relationshipLabel>
        <relationshipName>Municipalities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>VGT_Count__c</fullName>
        <description>Counts all Live locations existing in Salesforce for accounts of type Accel Account or Competitor Account. Uses the existence of a most recent HPD Record (within 75 days) on the account to ensure it&apos;s live. Uses the VGT Count from the Most Recent HPD Record.</description>
        <inlineHelpText>Counts all Live locations existing in Salesforce for accounts of type Accel Account or Competitor Account. Uses the existence of a most recent HPD Record (within 75 days) on the account to ensure it&apos;s live. Uses the VGT Count from the Most Recent HPD Rec.</inlineHelpText>
        <label>VGT Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Municipality</label>
    <nameField>
        <label>Municipality Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Municipalities</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/TEST_BatchFixAccountMostRecentHpd.cls
@isTest
private class TEST_BatchFixAccountMostRecentHpd {

    public static String UNAME = 'acceltest@accel.com';

    @testSetup static void setup() {
        User u = TestUtils.getUserForTest(UNAME);
        System.runAs(u) {
            List<Municipality__c> municipalities = TestUtils.createMunicipalities('testaccellmuni', 1);
            List<Account> accounts = new List<Account>();
            Integer i = 0;
            for (Municipality__c municipality : municipalities) {
                accounts.add(TestUtils.buildAccount('accel test acct:' + i + 'a', municipality.id, 'Accel Account'));
                accounts.add(TestUtils.buildAccount('accel test acct:' + i + 'b', municipality.id, 'Competitor Account'));
                i++;
            }
            insert accounts;

            //build more hold per days that the standard test util will but for just one of the accounts.
            String rtName = 'Monthly HPD';
            Id rtId = Schema.SObjectType.Hold_Per_Day__c.getRecordTypeInfosByName().get(rtName).getRecordTypeId();
            List<Hold_Per_Day__c> holdPerDays = new List<Hold_Per_Day__c>();
            Integer iNumPerAcct = 12;
            accounts = [select id from account];

            for (Account account : accounts) {
                Hold_Per_Day__c holdPerDay1 = new Hold_Per_Day__c();
                holdPerDay1.RecordTypeId = rtId;
                holdPerDay1.account__C = account.id;
                holdPerDay1.Date__c = System.today();
                holdPerDay1.VGT_Count__c = 5;
                holdPerDay1.Amount_Played__c = 1 * 1000;
                holdPerDay1.Amount_Won__c = holdPerDay1.Amount_Played__c * .8;
                holdPerDay1.Funds_In__c = holdPerDay1.Amount_Played__c;
                holdPerDay1.Funds_Out__c = holdPerDay1.Amount_Won__c;
                holdPerDay1.hpd__c = holdPerDay1.Funds_In__c - holdPerDay1.funds_out__c;
                holdPerDays.add(holdPerDay1);
                for (Integer x = 0; x < iNumPerAcct; x++) {
                    Hold_Per_Day__c holdPerDay = new Hold_Per_Day__c();
                    holdPerDay.RecordTypeId = rtId;
                    holdPerDay.account__C = account.id;
                    holdPerDay.Date__c = System.today().addMonths(-x);
                    holdPerDay.VGT_Count__c = 5;
                    holdPerDay.Amount_Played__c = x * 1000;
                    holdPerDay.Amount_Won__c = holdPerDay.Amount_Played__c * .8;
                    holdPerDay.Funds_In__c = holdPerDay.Amount_Played__c;
                    holdPerDay.Funds_Out__c = holdPerDay.Amount_Won__c;
                    holdPerDay.hpd__c = holdPerDay.Funds_In__c - holdPerDay.funds_out__c;
                    holdPerDays.add(holdPerDay);
                }
            }
            //============ VERY VERY BAD BUT WE SHOULD HAVE ENOUGH DML STATEMENTS IF WE DON'T DO THOSE THOSE BRITTLE PROCESS BUILDERS GO BOOM!
            //============ insert backwards so the most recent hpd doesn't get jazzed up.
            Integer iNumHpds = holdPerDays.size() - 1;
            for (Integer y = iNumHpds; y >= 0; y--) {
                insert holdPerDays[y];
            }

            List<Hold_Per_Day_Total__c> holdPerDayTotals2 = [SELECT Id from Hold_Per_Day_Total__c];
            delete holdPerDayTotals2;
            HpdStatsHelper.reInitHpdTotals();
        }
    }
    @isTest static void testUpdateAccount() {
        User u = TestUtils.getUserForTest(UNAME);
        System.runAs(u) {

            Test.startTest();

            Id rtIdMonthly = Schema.SObjectType.Hold_Per_Day__c.getRecordTypeInfosByName().get('Monthly HPD').getRecordTypeId();
            Map<Id, Hold_Per_Day__c> mHoldPerDaysByIds = new Map<Id, Hold_Per_Day__c>([select id,account__c,Date__c from Hold_Per_Day__c where recordtypeid = :rtIdMonthly]);
            BatchFixAccountMostRecentHpd b = new BatchFixAccountMostRecentHpd('Monthly HPD',System.today());
            Database.executeBatch(b,20);

            Test.stopTest();
            Set<Id> accountIds = new Set<Id>();
            for(Hold_Per_Day__c hpd : mHoldPerDaysByIds.values()) {
                accountIds.add(hpd.account__c);
            }
            List<Account> accounts = [SELECT Id, Most_Recent_Hold_Per_Day__c FROM Account where ID in :accountIds];
            for(Account account : accounts) {
                system.assert(account.Most_Recent_Hold_Per_Day__c ==   ((Hold_Per_Day__c)mHoldPerDaysByIds.get(account.Most_Recent_Hold_Per_Day__c)).id );
            }
        }
    }
}