objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Warehouse</fullName>
        <active>true</active>
        <description>Created for Inventory Request Project</description>
        <label>Warehouse</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Asset.object
<CustomObject>
    <fields>
        <fullName>Inventory_Request_Line_Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The inventory request line item that generated this asset.</description>
        <inlineHelpText>The inventory request line item that generated this asset.</inlineHelpText>
        <label>Inventory Request Line Item</label>
        <referenceTo>Inventory_Request_Line_Item__c</referenceTo>
        <relationshipLabel>Line Item Assets</relationshipLabel>
        <relationshipName>Assets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Inventory_Request__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Inventory Request that generated this item.</description>
        <label>Inventory Request</label>
        <referenceTo>Inventory_Request__c</referenceTo>
        <relationshipLabel>All Line Item Assets</relationshipLabel>
        <relationshipName>Assets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Manufacturer__c</fullName>
        <formula>Product2.Manufacturer__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Manufacturer</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PO_Number__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>PO Number</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Purchase_Order__c.Purchase_Order__c</field>
                <operation>equals</operation>
                <value></value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Purchase_Order__c</referenceTo>
        <relationshipLabel>Assets</relationshipLabel>
        <relationshipName>Assets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Software_Type__c</fullName>
        <description>Not sure if this yet.. per the IR project.</description>
        <inlineHelpText>Not sure if this yet.. per the IR project.</inlineHelpText>
        <label>Software Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Parent Asset</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Inventory_Request__c.object
<CustomObject>
    <description>Parent object to capture the request to order new inventory items.</description>
    <fields>
        <fullName>IR_Approved_Date__c</fullName>
        <description>Date Compliance has approved the IR. Only required before Assets can be generated.</description>
        <inlineHelpText>Date Compliance has approved the IR. Only required before Assets can be generated.</inlineHelpText>
        <label>IR Approved Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>PO_Number__c</fullName>
        <description>The Great Plains purchase order number.</description>
        <inlineHelpText>The Great Plains purchase order number.</inlineHelpText>
        <label>PO Number</label>
        <length>64</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PO_Submitted_Date__c</fullName>
        <description>Date the PO has been submitted to Finance. Only required before Assets can be generated.</description>
        <inlineHelpText>Date the PO has been submitted to Finance. Only required before Assets can be generated.</inlineHelpText>
        <label>PO Submitted Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>The status of the Inventory Request. This status will change based on various fields populated as well as state of approval.</description>
        <inlineHelpText>The status of the Inventory Request. This status will change based on various fields populated as well as state of approval.</inlineHelpText>
        <label>Request Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                    <default>true</default>
                    <label>Open</label>
                </value>
                <value>
                    <fullName>IR Request Pending Approval</fullName>
                    <label>Pending Approval</label>
                </value>
                <value>
                    <fullName>Approved for PO</fullName>
                </value>
                <value>
                    <fullName>PO Submitted</fullName>
                </value>
                <value>
                    <fullName>PO Partially Fulfilled</fullName>
                </value>
                <value>
                    <fullName>PO Fulfilled</fullName>
                </value>
                <value>
                    <fullName>IR Request Submitted</fullName>
                    <isActive>false</isActive>
                    <label>IR Request Submitted</label>
                </value>
                <value>
                    <fullName>PO Delivery Date Scheduled</fullName>
                    <isActive>false</isActive>
                    <label>PO Delivery Date Scheduled</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Submitted_Date__c</fullName>
        <description>Date the request was submitted for approval.</description>
        <inlineHelpText>Date the request was submitted for approval.</inlineHelpText>
        <label>IR Submitted Date</label>
        <type>Date</type>
    </fields>
    <label>Inventory Request</label>
    <nameField>
        <label>Request Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Inventory Requests</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Inventory_Request_Line_Item__c.object
<CustomObject>
    <description>Child Line Items for the Inventory Request object allowing the capture of products by model (1 record per model)</description>
    <fields>
        <fullName>Eligible_to_Create_Assets__c</fullName>
        <description>The item has passed all checks to create assets.. ie. it hasn&apos;t already created assets, it has a recieved date.. etc.etc.</description>
        <formula>/*
 * Used by Flows (and the UI to determine whether to show / allow Asset Creation for an IR Line Item.
 * Note Vendor is probably obsolete.
 */

AND( 
/* ======  ALL Assets have not already been created for the line  ====== */
!All_Line_Assets_Created__c, 

/* ======  The Parent IR has a PO Number Populated  ====== */
 !ISBLANK( Inventory_Request__r.PO_Number__c ),

/* ======  The Parent IR has a IR Approved Date  Populated  ====== */
 !ISBLANK( Inventory_Request__r.IR_Approved_Date__c ),

/* ======  The Parent IR has a PO Approved Date  Populated  ====== */
 !ISBLANK( Inventory_Request__r.PO_Submitted_Date__c ),

/* ======  The Item has been given a received date  ====== */
 !ISBLANK( Received_Date__c ),

/* ======  The Item has been given a Manufacturer  OBSOLETE 
 !ISBLANK( Manufacturer__c ),*/

/* ======  The Item has a qty received &gt; 0  ====== */
(  Received_Quantity__c &gt; 0 ),

/* ======  The Item has been assigned a vendor date ======= */
 !ISBLANK( Vendor__c )
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>The item has passed all checks to create assets.. ie. it hasn&apos;t already created assets, it has a recieved date.. etc.etc.</inlineHelpText>
        <label>Eligible to Create Assets</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Inventory_Request__c</fullName>
        <description>Link tto the Parent IR Record.</description>
        <inlineHelpText>Link to the Parent IR Record.</inlineHelpText>
        <label>Inventory Request</label>
        <referenceTo>Inventory_Request__c</referenceTo>
        <relationshipLabel>Request Line Items</relationshipLabel>
        <relationshipName>Inventory_Request_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Manufacturer__c</fullName>
        <description>Product__r.Manufacturer__r.Name</description>
        <formula>/*===============================================================================
 * This is a formula field that pulls the account name (accounts of record type 
 * manufacturer) associated with the manufacture tied to the selected product. 
 *===============================================================================
 */
Product__r.Manufacturer__r.Name
/* RJN DEFECT FOUND 2-5-2020 Product__r.Manufacturer__r.DBA_Account_Name__c*/</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>The Manufacturer associated with the product selected</inlineHelpText>
        <label>Manufacturer</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Parent_Asset__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent Asset</label>
        <referenceTo>Asset</referenceTo>
        <relationshipLabel>Inventory Request Line Items</relationshipLabel>
        <relationshipName>Inventory_Request_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Received_Date__c</fullName>
        <description>The date the Item was received in the warehouse.</description>
        <inlineHelpText>The date the Item was received in the warehouse.</inlineHelpText>
        <label>Received Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Vendor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>An Account filtered by Record Type of Vendors and Account.Vendor_Type__c = &apos;Software&apos;</description>
        <inlineHelpText>This field reflects Software Vendor Accounts . Any values that display immediately are recently viewed Vendors. To search, type at least the first 2 characters of the Vendor Name and hit enter or the search icon.</inlineHelpText>
        <label>Vendor</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Vendor must be an Account with a record type of &apos;Vendors&apos;. and have Account.Vendor_Type__c = &apos;Software&apos;</errorMessage>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Vendors</value>
            </filterItems>
            <filterItems>
                <field>Account.Vendor_Type__c</field>
                <operation>equals</operation>
                <value>Software</value>
            </filterItems>
            <infoMessage>Vendor much be an Account of Recordtype &apos;Vendors&apos;. and be a software vendor.</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Inventory Request Line Items</relationshipLabel>
        <relationshipName>Inventory_Request_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Inventory Request Line Item</label>
    <nameField>
        <displayFormat>IR-Line-{0000000}</displayFormat>
        <label>Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inventory Request Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Inventory_Request_Progress_Indicators__mdt.object
<CustomObject>
    <fields>
        <fullName>Current__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Current</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <description>Description of the progress stage (you can put raw html here)</description>
        <inlineHelpText>Description of the progress stage (you can put raw html here)</inlineHelpText>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>DisplayValue__c</fullName>
        <description>The actual value displayed.</description>
        <inlineHelpText>The actual value displayed.</inlineHelpText>
        <label>DisplayValue</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <precision>3</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Value__c</fullName>
        <description>The api value of the selected &apos;stage&apos;</description>
        <inlineHelpText>The api value of the selected &apos;stage&apos;</inlineHelpText>
        <label>Value</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Inventory Request Progress Indicator</label>
    <pluralLabel>Inventory Request Progress Indicators</pluralLabel>
</CustomObject>

objects/Software_Assets_Config__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Software Assets Config</label>
</CustomObject>

classes/InventoryRequestController.cls
/**
 * Main UI Controller backing Inventory_Request__c and Inventory_Request_Line_Item__c components.
 */
public without sharing class InventoryRequestController {

    public final static String MAP_KEY_SW_ASSET_CONFIG_SETTING  = 'SW_ASSET_CONFIG';
    public final static String MAP_KEY_IR_LINE                  = 'MAP_KEY_IR_LINE';
    public final static String MAP_KEY_IR_LINES                 = 'MAP_KEY_IR_LINES'; //@TODO deprecate
    public final static String MAP_KEY_CREATE_ASSET_PERMISSION  = 'MAP_KEY_CREATE_ASSET_PERMISSION';
    public final static String MAP_KEY_PROGRESS_INDICATORS      = 'MAP_KEY_PROGRESS_INDICATORS';
    public final static String MAP_KEY_PARENT_STATUS_IND        = 'MAP_KEY_PARENT_STATUS_IND';
    public final static String MAP_KEY_ACCOUNTS                 = 'MAP_KEY_ACCOUNTS';
    public final static String MAP_KEY_ASSETS                   = 'MAP_KEY_ASSETS';

   /**
    * Retrieve an Inventory_Request__c and child Inventory_Request_Line_Item__c record(s).
    *
    * @param irId  The SFDC Id of the Inventory_Request__c.
    * @return a dto containing the Inventory_Request__c and child array of Inventory_Request_Line_Item__c {dto.sObj}
    *         also a map keyed by SW_ASSET_CONFIG returning custom settings.
    *
    * @TODO deprecate in favor of line by line processing.
    */
    @AuraEnabled
    public static ResponseDto retrieveInventoryRequestAndLineItems( Id irId ) {
        ResponseDto dto = new ResponseDto();
        Inventory_Request__c ir = InventoryRequestSvc.retrieveInventoryRequestAndLineItems(irId);
        List<Inventory_Request_Line_Item__c> irLines = new List<Inventory_Request_Line_Item__c>();
        Software_Assets_Config__c configSettings = CustomSettingsSvc.getSoftwareAssetsConfigSettings(UserInfo.getUserId());
        if(ir != null) {
            dto.sObj = ir;
            //------------- deconstruct child related recs for easier client consumption.
            if(ir.Inventory_Request_Line_Items__r != null && !ir.Inventory_Request_Line_Items__r.isEmpty()) {
                for (Inventory_Request_Line_Item__c li: ir.Inventory_Request_Line_Items__r) {
                    irLines.add(li);
                }
            }
            dto.values.put(MAP_KEY_SW_ASSET_CONFIG_SETTING,configSettings);
            dto.values.put(MAP_KEY_IR_LINES,irLines);
            dto.isSuccess = true;
        }
        return dto;
    }
   /**
    * Retrieve an Inventory_Request_Line_Item__c record.
    *
    * @param irLineItemId The SFDC Id of the Inventory_Request_Line_Item__c.
    * @return a dto containing the Inventory_Request_Line_Item {dto.sObj}
    *         also a map keyed by SW_ASSET_CONFIG returning custom settings.
    */
    @AuraEnabled
    public static ResponseDto retrieveInventoryRequestLineItem( Id irLineItemId ) {
        ResponseDto dto = new ResponseDto();
        Inventory_Request_Line_Item__c irLineItem = InventoryRequestSvc.retrieveInventoryRequestLineItem( irLineItemId );
        Software_Assets_Config__c configSettings = CustomSettingsSvc.getSoftwareAssetsConfigSettings(UserInfo.getUserId());
        if(irLineItemId != null) {
            dto.sObj = irLineItem;
            dto.values.put(MAP_KEY_SW_ASSET_CONFIG_SETTING,configSettings);
            dto.isSuccess = true;
        }
        return dto;
    }

   /**
    * Checks Custom Permissions based on the custom permission api name.
    *
    * @param customPermissionApiName  the custom permission api name to check.
    * @return   TRUE if the user has permission, otherwise false.
    */
    @AuraEnabled
    public static Boolean doesUserHavePermission( String customPermissionApiName ) {
        Boolean hasPermission = FeatureManagement.checkPermission(customPermissionApiName);
        return hasPermission;
    }

    /**
     * Determines if the Line Item has assets associated with it.
     *
     * @param irLineItemId The SFDC Id of the Inventory_Request_Line_Item__c4
     * @return TRUE if the line item has assets, otherwise FALSE.
     */
    @AuraEnabled
    public static Boolean doesIrLineItemHaveAssets(  Id irLineItemId  ) {
        List<Asset> assets = [SELECT Id FROM Asset WHERE Inventory_Request_Line_Item__c = :irLineItemId];
        return !assets.isEmpty();
    }

    /**
     * Retrieves a Profile based on the running user Profile Id.
     * @return  a Profile sObject if found, otherwise null.
     */
    @AuraEnabled
    public static Profile retrieveUserProfile() {
        return UserSvc.retrieveUserProfileById( UserInfo.getProfileId() );
    }

    /**
     * Retrieves a RecordType sObject for a given recordTypeId.
     *
     * @param rtId  The recordTypeId to search for.
     * @return  a dto containing a RecordType sObject in the dto.sObj property
     * @TODO Move up to a Service.
     */
    @AuraEnabled
    public static ResponseDto retrieveRecordTypeViaId(String rtId) {
        ResponseDto dto = new ResponseDto();

        RecordType recordType;
        List<RecordType> recordTypes = [
                SELECT  Id, Name, DeveloperName
                FROM    RecordType
                WHERE   Id = :rtId
        ];
        if(!recordTypes.isEmpty()) {
            recordType = recordTypes[0];
            dto.sObj = recordType;
            dto.isSuccess = true;
        } else {
            dto.message = 'Could not find a valid record type for Inventory Request';
            dto.technicalMsg = 'No RT find for passed rtId ='+rtId;
        }
        return dto;
    }

    /**
     * Deletes assets associated with the Inventory_Request_Line_Item__c
     *
     * @param irLineItemId  An Inventory_Request_Line_Item__c Id.
     * @return              A ResponseDto object containing the status of the asset deletion
     *
     * @todo failsafe the delete!
     */
    @AuraEnabled
    public static ResponseDto deleteIrLineItemAssets(Id irLineItemId) {
        ResponseDto dto = new ResponseDto();

        List<Asset> assets = [SELECT Id FROM Asset WHERE Inventory_Request_Line_Item__c = :irLineItemId];
        Integer iNum = assets.size();
        if (!assets.isEmpty()) {
            delete assets;
            dto.message = iNum + ' assets deleted successfully!';
            dto.isSuccess = true;
        } else {
            dto.message = 'No Assets Found for Inventory Request Line Item to Delete';
            dto.technicalMsg = 'No Assets found for ir Line Item Id:'+irLineItemId;
        }
        return dto;
    }

    /**
     * If criteria of Line.Eligible_To_Create_Assets__c (Formula field) is not meant.. updates whatever is needed
     * to be updated (parent or child item item).
     *
     * @param irLineItemId  An Inventory_Request_Line_Item__c Id.
     * @return              A ResponseDto object containing the status of the update of the IR header and line.
     */
    @AuraEnabled
    public static ResponseDto makeIrLineEligibleToCreateAssets(Id irLineItemId) {

        ResponseDto dto = new ResponseDto();

        Inventory_Request_Line_Item__c irLine = InventoryRequestSvc.retrieveInventoryRequestLineItem(irLineItemId);
        Inventory_Request__c ir = InventoryRequestSvc.retrieveInventoryRequestAndLineItems(irLine.Inventory_Request__c);

        dto.message = 'Nothing done';
        if(irLine != null && ir != null) {
            if(ir.PO_Number__c == null) {
                ir.PO_Number__c = '666666';
            }
            if(ir.PO_Submitted_Date__c == null) {
                ir.PO_Submitted_Date__c = Date.today();
            }
            if(ir.Submitted_Date__c == null) {
                ir.Submitted_Date__c = Date.today();
            }
            if(ir.Status__c != 'Approved for PO') {
                ir.Status__c = 'Approved for PO';
            } else if(ir.IR_Approved_Date__c == null) {
                ir.IR_Approved_Date__c = Date.today();
            }
            update ir;
            if(irLine.Received_Date__c == null) {
                irLine.Received_Date__c = Date.today();
            }
            update irLine;
            dto.isSuccess = true;
            dto.message = 'IR / IR Lines successfully updated to allow asset creation.';
        } else {
            dto.message = 'idpassed='+irLineItemId+'..ir line='+ir +'.. irLineItem='+ir;
        }
        return dto;
    }

    /**
     * If criteria of Line.Eligible_To_Create_Assets__c (Formula field) is not meant.. updates whatever is needed
     * to be updated (parent or child item item).
     *
     * @param irLineItemId  An Inventory_Request_Line_Item__c Id.
     * @return              A ResponseDto object containing the status of the update of the IR Line.
     */
    @AuraEnabled
    public static ResponseDto makeIrLineInEligibleToCreateAssets(Id irLineItemId) {

        ResponseDto dto = new ResponseDto();

        Inventory_Request_Line_Item__c irLine = InventoryRequestSvc.retrieveInventoryRequestLineItem(irLineItemId);
        dto.message = 'Nothing done';
        if(irLine != null ) {
            irLine.Received_Date__c = null;
           // irLine.Manufacturer__c = null;
            update irLine;
            dto.isSuccess = true;
            dto.message = 'Received date Nullified on Line Item to make it ineligible to create assets..';
        } else {
            dto.message = 'idpassed='+irLineItemId+'..ir line='+irLine;
        }
        return dto;
    }

    /**
     * Retrieves a list of accounts for the given where criteria. .
     *
     * @param whereCriteria the where criteria for Account ie. RecordType.Developername = 'xyz
     * @return a dto containing a list of accounts in the values property.
     */
    @AuraEnabled
    public static ResponseDto retrieveAccountsForIrSelection(String whereCriteria) {
        List<Account> accounts;
        if(whereCriteria == null || whereCriteria == '') {
            //@todo dyna rt ret.
            whereCriteria = ' RecordType.Developername = \'Warehouse\'';
        }
        ResponseDto dto = new ResponseDto();

        String soql = '';
        soql += ' SELECT    Id, Name ';
        soql += ' FROM      Account ';
        soql += ' WHERE ' + whereCriteria;
        soql += ' ORDER BY Name ASC ';
        soql += ' LIMIT 500 ';

        try {
            accounts = Database.query(soql);
            if(!accounts.isEmpty()) {
                dto.isSuccess = true;
            } else {
                dto.message = 'No accounts found';
                dto.technicalMsg = 'empty list found for accounts with where criteria = '+whereCriteria;
            }
        } catch (Exception ex) {
            dto.technicalMsg = ex.getMessage();
            dto.message = 'Unable to locate accounts for selection. probably invalid whereCriteria=' + whereCriteria;
        }
        dto.values.put(MAP_KEY_ACCOUNTS,accounts);
        return dto;
    }

    /**
     * Retrieves a list of assets for the given where criteria. .
     *
     * @param whereCriteria the where criteria for Asset ie. RecordType.Developername = 'xyz currently not used.
     * @return a dto containing a list of assets in the values property.
     */
    @AuraEnabled
    public static ResponseDto retrieveParentAssetsForIrSelection(String whereCriteria) {
        List<Asset> assets;
        String parentAssetCriteria = ' Software_Type__c = \'Parent Asset\' ';

        if(whereCriteria == null || whereCriteria == '') {
            //@todo dyna rt ret.
            whereCriteria = parentAssetCriteria;
        }

        ResponseDto dto = new ResponseDto();

        String soql = '';
        soql += ' SELECT    Id, Name ';
        soql += ' FROM      Asset ';
        soql += ' WHERE ' + whereCriteria;
        soql += ' ORDER BY Name ASC ';
        soql += ' LIMIT 500 ';


        try {
            assets = Database.query(soql);
            if(!assets.isEmpty()) {
                dto.isSuccess = true;
            } else {
                dto.message = 'No assets found';
                dto.technicalMsg = 'empty list found for assets with where criteria = '+parentAssetCriteria;
            }
        } catch (Exception ex) {
            dto.technicalMsg = ex.getMessage();
            dto.message = 'Unable to locate assets for selection. probably invalid whereCriteria=' + parentAssetCriteria;
        }
        dto.values.put(MAP_KEY_ASSETS,assets);
        return dto;
    }

    /**
     * Retrieves the Inventory_Request_Progress_Indicators__mdt custom metadata which is basically a list of
     * Inventory_Request__c.Status__c with each Picklist option containing additional meta data.
     *
     * @param inventoryRequestId
     * @return a ResponseDto object containing a list of ProgressIndicator keys by MAP_KEY_PROGRESS_INDICATORS
     * @see ProgressIndicator
     */
    @AuraEnabled
    public static ResponseDto retrieveIrProgressIndicators(Id inventoryRequestId) {
        ResponseDto dto = new ResponseDto();

        List<ProgressIndicator> progressIndicators = new List<ProgressIndicator>();
        List <Inventory_Request_Progress_Indicators__mdt> settings =
                InventoryRequestSvc.retrieveInventoryRequestProgressSettingsMeta(null );
        if(settings != null) {
            for(Inventory_Request_Progress_Indicators__mdt setting : settings) {
                ProgressIndicator pi = new ProgressIndicator();
                pi.value = setting.Value__c;
                pi.displayValue = setting.DisplayValue__c;
                if(setting.Description__c != null) {
                    pi.description = setting.Description__c;
                }
                pi.order = Integer.valueOf(setting.Order__c);
                pi.current = setting.Current__c;
                progressIndicators.add(pi);
            }
            dto.values.put( MAP_KEY_PROGRESS_INDICATORS,progressIndicators );
            Boolean isLocked = InventoryRequestSvc.checkIfIrIsLocked(inventoryRequestId);
            ParentStatusIndicator psi = new ParentStatusIndicator();
            psi.isLocked = isLocked;
            dto.values.put( MAP_KEY_PARENT_STATUS_IND, psi);

            dto.isSuccess = true;
        }
        return dto;
    }

    /**
     * A nested class to wrap Inventory_Request_Progress_Indicators__mdt
     */
    public class ProgressIndicator {
        @AuraEnabled public String  value               { get;set; }
        @AuraEnabled public String  displayValue        { get;set; }
        @AuraEnabled public String  description         { get;set; }
        @AuraEnabled public Integer order               { get;set; }
        @AuraEnabled public Boolean current             { get;set; }
        @AuraEnabled public Boolean completed           { get;set; }
        @AuraEnabled public String  textClass           { get;set; } //  css class of the  display value and the desc.
        @AuraEnabled public String  valueContainerClass { get;set; } //  css class of value container ie. parent div.

        /**
         *  No arg constructor.. not setting empty string so the platform will return in the JSON.
         */
        public ProgressIndicator() {
            this.description = '';
            this.completed = false;
            this.current = false;
            this.textClass = '';
            this.valueContainerClass = '';
        }
    }

    /**
     *  An Inner class holding locked status of the parent IR for display in the progress indicator
     */
    public class ParentStatusIndicator {
        @AuraEnabled public Boolean isLocked          { get;set; }
        public ParentStatusIndicator() {
            this.isLocked = false;
        }
    }
}