objects/Account.object
<CustomObject>
    <fields>
        <fullName>Relationship_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Relationship Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Accounts3</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Municipality__c.object
<CustomObject>
    <label>Municipality</label>
    <nameField>
        <label>Municipality Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Municipalities</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/TEST_MailAction.cls
@isTest
private class TEST_MailAction{
    public static String UNAME = 'acceltest@accel.com';
    /**
     * Setup test data.
     */
    @testSetup static void setup() {
        User u = TestUtils.getUserForTest(UNAME);
        List<Municipality__c> munis = TestUtils.createMunicipalities('Test Accel Muni',2);
        List<Account> newAccounts = new List<Account>();
        for(Municipality__c muni : munis) {
            Account acct = TestUtils.buildAccount('test',muni.id);
            acct.relationship_manager__c = u.id;
            newAccounts.add(acct);
        }
        insert newAccounts;

    }
    /**
     *
     */
    @isTest static void testBlah() {
        User u = TestUtils.getUserForTest(UNAME);
        System.runAs(u) {

            Test.startTest();

            Map<Id,Municipality__c> munis =  new Map<Id,Municipality__c>([select id from municipality__c]);
            List<Id> muniIds = new List<Id>();
            muniIds.addAll(munis.keySet());
            MailAction.sendMuniEmails(muniIds);
            MailAction.EmailActionResult ear = new MailAction.EmailActionResult();
            Boolean success = ear.isSuccess;
            String em = ear.errorMessage;





            Test.stopTest();
        }
    }
}