objects/Account.object
<CustomObject>
    <fields>
        <fullName>Hold_Per_Day_Total__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Based on HPD Records of Record type = Monthly HPD</description>
        <inlineHelpText>Based on Monthly HPD Data</inlineHelpText>
        <label>Hold Per Day Total (Monthly)</label>
        <referenceTo>Hold_Per_Day_Total__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Vendor_Type__c</fullName>
        <description>The Type of Vendor. .ie. Software..etc.. used for IR to help filter vendors upon lookup</description>
        <inlineHelpText>The Type of Vendor</inlineHelpText>
        <label>Vendor Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Software</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Vendors</fullName>
        <active>true</active>
        <label>Vendors</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Asset.object
<CustomObject>
    <fields>
        <fullName>Asset__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Asset</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Assets</relationshipLabel>
        <relationshipName>Assets4</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Hold_Per_Day_Total__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Contains All Aggregated information for HPD Records for this Machine.</description>
        <inlineHelpText>Contains All Aggregated information for HPD Records for this Machine.</inlineHelpText>
        <label>Hold Per Day Total</label>
        <referenceTo>Hold_Per_Day_Total__c</referenceTo>
        <relationshipLabel>Assets</relationshipLabel>
        <relationshipName>Assets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Inventory_Request_Line_Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The inventory request line item that generated this asset.</description>
        <inlineHelpText>The inventory request line item that generated this asset.</inlineHelpText>
        <label>Inventory Request Line Item</label>
        <referenceTo>Inventory_Request_Line_Item__c</referenceTo>
        <relationshipLabel>Line Item Assets</relationshipLabel>
        <relationshipName>Assets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Inventory_Request__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Inventory Request that generated this item.</description>
        <label>Inventory Request</label>
        <referenceTo>Inventory_Request__c</referenceTo>
        <relationshipLabel>All Line Item Assets</relationshipLabel>
        <relationshipName>Assets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Vendor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>An Account filtered by Record Type of Vendors.</description>
        <inlineHelpText>This field reflects Vendor Accounts. Any values that display immediately are recently viewed Vendors. To search, type at least the first 2 characters of the Vendor Name and hit enter or the search icon.</inlineHelpText>
        <label>Vendor</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Vendor must be an Account with a record type of &apos;Vendors.</errorMessage>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Vendors</value>
            </filterItems>
            <infoMessage>Vendor much be an Account of Recordtype &apos;Vendors&apos; .</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Assets (Vendor)</relationshipLabel>
        <relationshipName>Assets</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Software</fullName>
        <active>true</active>
        <label>Software</label>
    </recordTypes>
    <recordTypes>
        <fullName>VGT</fullName>
        <active>true</active>
        <label>VGT</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Hold_Per_Day_Total__c.object
<CustomObject>
    <description>Contains calculated information for HPD (currently only monthly)
Rolls up info for both Account(Location) and Municipality Levels (Separated by Record Type).
Fields such as TTM indicate 12 month roll-ups. all other fiels noted appropriated (4 weeks 8 weeks 12 weeks) etc.

Additional record type for future use of Machine exists as well.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Populated by script upon initial object creation. then populated upon creation of each account via trigger moving forward.</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Hold Per Day Totals</relationshipLabel>
        <relationshipName>Hold_Per_Day_Summaries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Asset__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>For future use for Machines.</description>
        <inlineHelpText>For future use for Machines.</inlineHelpText>
        <label>Asset</label>
        <referenceTo>Asset</referenceTo>
        <relationshipLabel>Hold Per Day Totals</relationshipLabel>
        <relationshipName>Hold_Per_Day_Totals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Municipality__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Municipality</label>
        <referenceTo>Municipality__c</referenceTo>
        <relationshipLabel>Hold Per Day Totals</relationshipLabel>
        <relationshipName>Hold_Per_Day_Totals</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Hold Per Day Total</label>
    <nameField>
        <displayFormat>HPDT-{000000000}</displayFormat>
        <label>HPD Total #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Hold Per Day Totals</pluralLabel>
    <recordTypes>
        <fullName>Municipality</fullName>
        <active>true</active>
        <label>Municipality</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Inventory_Request__c.object
<CustomObject>
    <description>Parent object to capture the request to order new inventory items.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The location associated with the inventory request.</description>
        <inlineHelpText>The location associated with the inventory request</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Inventory Requests</relationshipLabel>
        <relationshipName>Inventory_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Inventory Request</label>
    <nameField>
        <label>Request Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Inventory Requests</pluralLabel>
    <recordTypes>
        <fullName>Software</fullName>
        <active>false</active>
        <description>OBSOLETE probably have to remove from profiles!</description>
        <label>Software</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Inventory_Request_Line_Item__c.object
<CustomObject>
    <description>Child Line Items for the Inventory Request object allowing the capture of products by model (1 record per model)</description>
    <fields>
        <fullName>Inventory_Request__c</fullName>
        <description>Link tto the Parent IR Record.</description>
        <inlineHelpText>Link to the Parent IR Record.</inlineHelpText>
        <label>Inventory Request</label>
        <referenceTo>Inventory_Request__c</referenceTo>
        <relationshipLabel>Request Line Items</relationshipLabel>
        <relationshipName>Inventory_Request_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The product to create assets from. This must be a product record type of Gaming Software. The addition of the 2nd filter is needed to solve what appears to be a spring 2020 bug</description>
        <inlineHelpText>The product to create assets from This must be a product record type of Gaming Software. Any default values when clicking the input are most recently viewed records. To Search enter at least 2 characters and then hit enter or click the search icon.</inlineHelpText>
        <label>Product</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <errorMessage>You must select a product of type Gaming Software.</errorMessage>
            <filterItems>
                <field>Product2.RecordType.Name</field>
                <operation>equals</operation>
                <value>Gaming Software</value>
            </filterItems>
            <filterItems>
                <field>Product2.Record_Type_Text__c</field>
                <operation>equals</operation>
                <value>Gaming Software</value>
            </filterItems>
            <infoMessage>Please select a product of type Gaming Software</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Inventory Request Line Items</relationshipLabel>
        <relationshipName>Inventory_Request_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <defaultValue>0</defaultValue>
        <description>The Original Quantity to be requested and approved.</description>
        <inlineHelpText>The Original Quantity to be requested and approved.</inlineHelpText>
        <label>Quantity Requested</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Received_Date__c</fullName>
        <description>The date the Item was received in the warehouse.</description>
        <inlineHelpText>The date the Item was received in the warehouse.</inlineHelpText>
        <label>Received Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Received_Quantity__c</fullName>
        <defaultValue>0</defaultValue>
        <description>The Number of products received in the warehouse that you want to create at this point in time. Will default to zero.</description>
        <inlineHelpText>The Number of products received in the warehouse that you want to create at this point in time. Will default to zero.</inlineHelpText>
        <label>Quantity to Create</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Vendor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>An Account filtered by Record Type of Vendors and Account.Vendor_Type__c = &apos;Software&apos;</description>
        <inlineHelpText>This field reflects Software Vendor Accounts . Any values that display immediately are recently viewed Vendors. To search, type at least the first 2 characters of the Vendor Name and hit enter or the search icon.</inlineHelpText>
        <label>Vendor</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Vendor must be an Account with a record type of &apos;Vendors&apos;. and have Account.Vendor_Type__c = &apos;Software&apos;</errorMessage>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Vendors</value>
            </filterItems>
            <filterItems>
                <field>Account.Vendor_Type__c</field>
                <operation>equals</operation>
                <value>Software</value>
            </filterItems>
            <infoMessage>Vendor much be an Account of Recordtype &apos;Vendors&apos;. and be a software vendor.</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Inventory Request Line Items</relationshipLabel>
        <relationshipName>Inventory_Request_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Inventory Request Line Item</label>
    <nameField>
        <displayFormat>IR-Line-{0000000}</displayFormat>
        <label>Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inventory Request Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Meter_Reading__c.object
<CustomObject>
    <description>Example object to capture electronic meters</description>
    <fields>
        <fullName>Asset__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Asset</label>
        <referenceTo>Asset</referenceTo>
        <relationshipLabel>Meter Readings</relationshipLabel>
        <relationshipName>Meter_Readings</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Meter Reading</label>
    <nameField>
        <displayFormat>MTR-{000000000}</displayFormat>
        <label>Meter Reading ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Meter Readings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Municipality__c.object
<CustomObject>
    <fields>
        <fullName>Hold_Per_Day_Total__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Hold Per Day Totals</label>
        <referenceTo>Hold_Per_Day_Total__c</referenceTo>
        <relationshipLabel>Municipalities</relationshipLabel>
        <relationshipName>Municipalities</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Municipality</label>
    <nameField>
        <label>Municipality Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Municipalities</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Products (Account)</relationshipLabel>
        <relationshipName>Products2</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Software_Assets_Config__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>Asset_Name_Prefix__c</fullName>
        <defaultValue>&quot;SW - &quot;</defaultValue>
        <label>Asset Name Prefix</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Latest_Serial_Number__c</fullName>
        <defaultValue>950000000</defaultValue>
        <label>Latest Serial Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Max_Single_Trans_Assets__c</fullName>
        <defaultValue>497</defaultValue>
        <description>The maximum number of assets to create in a single transaction (to avoid flow limit errors)</description>
        <inlineHelpText>The maximum number of assets to create in a single transaction (to avoid flow limit errors)</inlineHelpText>
        <label>Max Single Trans Assets</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Software Assets Config</label>
</CustomObject>

classes/TEST_AssetTrigger.cls
@IsTest
private class TEST_AssetTrigger {

    public static String UNAME = 'acceltest@accel.com';
    public static final Integer NUMBER_OF_PRODUCTS = 2;
    public static final Integer NUMBER_OF_IR_LINES = 5;
    public static final Integer NUMBER_OF_MUNIS = 2;
    public static final Integer NUMBER_OF_ACCTS_PER_MUNI = 2;

    @TestSetup
    static void setup() {

        List<Municipality__c> munis = TestUtils.createMunicipalities('UT MUNI', NUMBER_OF_MUNIS);
        List<Account> accounts = new List<Account>();
        List<Asset> assets = new List<Asset>();
        Integer z = 0;
        for (Municipality__c municipality : munis) {
            for (Integer i = 0; i < NUMBER_OF_ACCTS_PER_MUNI; i++) {
                Account account = TestUtils.buildAccount('accel test acct:' + z + 'a', municipality.Id,
                        'Accel Account');
                account.ShippingState = 'IL';
                accounts.add(account);
                z++;
            }
        }
        insert accounts;

        //create 'parent' account..
        Account parentInventoryAccount = TestUtils.buildAccount('Accel Entertainment - HQ', munis[0].Id,
                'Accel Account');
        insert parentInventoryAccount;

        String rtDevName = 'Software';
        for (Account account : accounts) {
            Asset asset = TestUtils.buildAsset('UT ' + account.Name + ' TEST ASSET', account.Id, rtDevName);
            assets.add(asset);
        }
        insert assets;

        List<Product2> products = new List<Product2>();
        Id softwareRtId = Schema.SObjectType.Product2.getRecordTypeInfosByName().get('Gaming Software').getRecordTypeId();
        for (Integer i = 0; i < NUMBER_OF_PRODUCTS; i++) {
            //@TODO RecordType? Family of Software?
            Product2 p = new Product2(Name = 'UT Test Product ' + i + 1, Family = 'ASSET', Description = 'Test Desc',
                    RecordTypeId = softwareRtId);
            products.add(p);
        }
        insert products;

        Id irSoftwareRtId = Schema.SObjectType.Inventory_Request__c.getRecordTypeInfosByName().get('Gaming Software')
                .getRecordTypeId();
        Inventory_Request__c inventoryRequest = new Inventory_Request__c();
        inventoryRequest.Name = 'TEST IR Name';
        inventoryRequest.RecordTypeId = irSoftwareRtId;
        inventoryRequest.Account__c = accounts[0].Id;
        insert inventoryRequest;

        //--- @TODO this should bne moved to TESTutils but given the additional overhead on then the necessity
        //--- to run all test when moving test utils.. why bother no one else cares about them.
        Account vendor = TestUtils.buildAccount('THIS IS A VENDOR', null);
        vendor.Vendor_Type__c = 'Software';
        Id vendorRtId = Schema.getGlobalDescribe().get('Account').getDescribe().getRecordTypeInfosByDeveloperName().get('Vendors').getRecordTypeId();
        vendor.RecordTypeId = vendorRtId;
        insert vendor;

        List<Inventory_Request_Line_Item__c> inventoryRequestLineItems = new List<Inventory_Request_Line_Item__c>();
        for (Integer i = 0; i < NUMBER_OF_IR_LINES; i++) {
            for (Integer x = 0; x < NUMBER_OF_PRODUCTS; x++) {
                Inventory_Request_Line_Item__c inventoryRequestLineItem = new Inventory_Request_Line_Item__c();
                inventoryRequestLineItem.Product__c = products[x].Id;
                inventoryRequestLineItem.Quantity__c = 10;
                inventoryRequestLineItem.Received_Quantity__c = 10;
                inventoryRequestLineItem.Received_Date__c = Date.today();
                inventoryRequestLineItem.Inventory_Request__c = inventoryRequest.Id;
                inventoryRequestLineItem.Vendor__c = vendor.Id;
                inventoryRequestLineItems.add(inventoryRequestLineItem);
            }
        }
        insert inventoryRequestLineItems;

        Software_Assets_Config__c configPrefixSetting = Software_Assets_Config__c.getOrgDefaults();
        configPrefixSetting.Asset_Name_Prefix__c = 'SW-';
        configPrefixSetting.Latest_Serial_Number__c = 1;
        configPrefixSetting.Max_Single_Trans_Assets__c = 20;
        insert configPrefixSetting;
        configPrefixSetting = CustomSettingsSvc.getSoftwareAssetsConfigSettings(UserInfo.getUserId());
        System.assert(configPrefixSetting.Latest_Serial_Number__c != null);

        Software_Assets_Config__c configPrefixSetting2 = new Software_Assets_Config__c();
        configPrefixSetting2.Asset_Name_Prefix__c = 'SW-';
        configPrefixSetting2.Latest_Serial_Number__c = 1;
        configPrefixSetting2.Max_Single_Trans_Assets__c = 20;
        configPrefixSetting2.SetupOwnerId = UserInfo.getUserId();
        insert configPrefixSetting2;

    }

    @IsTest
    static void testNewAssetCreationAndHpdTotalCreation() {
        User u = TestUtils.getUserForTest(UNAME);
        System.runAs(u) {
            Id assetRtId = Schema.getGlobalDescribe().get('Asset').getDescribe().getRecordTypeInfosByDeveloperName().get('VGT').getRecordTypeId();
            Asset a = new Asset(Name='asset trigger unit test asset',RecordTypeId=assetRtId);

            Test.startTest();
            insert a;
            Hold_Per_Day_Total__c holdPerDayTotal = [SELECT Id, Asset__c FROM Hold_Per_Day_Total__c WHERE Asset__c = :a.Id];
            System.assert(holdPerDayTotal != null);
            Asset asset = [SELECT Id, Hold_Per_Day_Total__c FROM Asset WHERE Hold_Per_Day_Total__c = :holdPerDayTotal.Id];
            System.assert(asset != null);
            Test.stopTest();
        }
    }

    @IsTest
    static void updateInventoryRequestLineOnDelete() {
        User u = TestUtils.getUserForTest(UNAME);
        //create assets...
        Id irId = [SELECT Id FROM Inventory_Request__c LIMIT 1].Id;
        List<Inventory_Request_Line_Item__c> irLineItemDbs   =  [
                SELECT  Id, Quantity__c,Inventory_Request__c,Product__c, Product__r.Name
                FROM    Inventory_Request_Line_Item__c
                WHERE   Inventory_Request__c = :irId
                AND     Item_Number__c = 1
        ];
        Inventory_Request_Line_Item__c irLineItemDb = irLineItemDbs[0];
        irLineItemDb.Quantity__c = 50;
        irLineItemDb.Received_Quantity__c = 50;
        irLineItemDb.Received_Date__c = Date.today();

        update irLineItemDb;
        List<String> irLineItemIds = new List<String>{irLineItemDb.Id};

        List<FlowAction_CreateAssetsFromIRLineItems.CreateAssetsResult> createAssetsResults =
                FlowAction_CreateAssetsFromIRLineItems.createAssetsFromInventoryRequestLineItem(irLineItemIds);
        FlowAction_CreateAssetsFromIRLineItems.CreateAssetsResult createAssetsResult = createAssetsResults[0];
        System.assertEquals(createAssetsResult.iNumAssetsCreated,irLineItemDb.Quantity__c);

        System.runAs(u) {

            Test.startTest();

            List<Asset> assets = [SELECT Id FROM Asset];
            delete assets;

            Test.stopTest();
        }
    }

    @IsTest
    static void testPopulateSerialNumber_Positive() {
        User u = TestUtils.getUserForTest(UNAME);
        Id softwareRecordTypeId = Schema.SObjectType.Asset.getRecordTypeInfosByName().get('Software').getRecordTypeId();

        System.runAs(u) {


            Test.startTest();

            Asset ass = new Asset(Name = 'TEST SW MAN Inserted Asset', RecordTypeId = softwareRecordTypeId);
            insert ass;
            ass = [ SELECT Id, SerialNumber FROM Asset WHERE Id = :ass.Id ];
            System.assert(ass.SerialNumber != null);

            Test.stopTest();
        }
    }

    @IsTest
    static void testPopulateSerialNumber_VGT_Negative() {
        User u = TestUtils.getUserForTest(UNAME);
        Id vgtRecordTypeId = Schema.SObjectType.Asset.getRecordTypeInfosByName().get('VGT').getRecordTypeId();

        System.runAs(u) {

            Test.startTest();

            Asset ass = new Asset(Name = 'TEST VGT MAN Inserted Asset', RecordTypeId = vgtRecordTypeId);
            insert ass;
            ass = [ SELECT Id, SerialNumber FROM Asset WHERE Id = :ass.Id ];
            System.assert(ass.SerialNumber == null);

            Test.stopTest();
        }
    }

    @IsTest
    static void testPopulateSerialNumber_InventoryRequest_Negative() {
        User u = TestUtils.getUserForTest(UNAME);
        Id softwareRecordTypeId = Schema.SObjectType.Asset.getRecordTypeInfosByName().get('Software').getRecordTypeId();

        System.runAs(u) {
            List<Inventory_Request_Line_Item__c> inventoryRequestLineItems = [SELECT Id FROM Inventory_Request_Line_Item__c];
            Id irLineItemId = inventoryRequestLineItems[0].Id;
            Test.startTest();

            Asset ass = new Asset(  Name = 'TEST VGT MAN IR Insert', Inventory_Request_Line_Item__c = irLineItemId,
                                    RecordTypeId = softwareRecordTypeId);
            insert ass;
            ass = [ SELECT Id, SerialNumber FROM Asset WHERE Id = :ass.Id ];
            System.assert(ass.SerialNumber == null); // generally will be done via create assets button.

            Test.stopTest();
        }
    }

    @IsTest
    static void testSwAssetParentAccountMod_Positive() {
        User u = TestUtils.getUserForTest(UNAME);
        Id softwareRecordTypeId = Schema.SObjectType.Asset.getRecordTypeInfosByName().get('Software').getRecordTypeId();
        ID vgtRecordTypeId = Schema.SObjectType.Asset.getRecordTypeInfosByName().get('VGT').getRecordTypeId();

        List<Account> accounts = [SELECT Id FROM Account];

        // Create some VGT Parent assets.
        List<Asset> vgts = new List<Asset>();
        Integer x = 0;
        for(Account account : accounts) {
            Asset asset = new Asset();
            asset.recordtypeId = vgtRecordTypeId;
            asset.Name = 'vgt-'+account.Id;
            asset.AccountId = account.Id;
            asset.SAS__c = '1';
            asset.model__c = 'model'+x;
            x++;
            vgts.add(asset);
        }
        insert vgts;

        // build some sw assets;
        List<ASset> swAssets = new List<Asset>();
        Integer i = 0;
        for(Asset parentVgt : vgts) {
            Asset swAsset = TestUtils.buildAsset('test ' +i, parentVgt.AccountId, 'Software');
            swAsset.recordtypeId = softwareRecordTypeId;
            swAsset.parentId = parentVgt.Id;
            swAssets.add(swAsset);
            i++;
        }
        insert swAssets;

        Municipality__c municipality = [SELECT Id FROM  Municipality__c LIMIT 1];

        Account newAccount = TestUtils.buildAccount('accel test acct:', municipality.Id,
                'Accel Account');
        newAccount.ShippingState = 'IL';
        insert newAccount;

        Test.startTest();
        System.runAs(u) {
            for(Asset parentAsset: vgts) {
                parentASset.AccountId = newAccount.Id;
            }
            update vgts;
        }
        Test.stopTest();
        List<Asset> childAssets = [ SELECT Id,AccountId,ParentId,Parent.AccountId FROM Asset where ID in :swAssets];
        System.debug('---> childAssets:'+childAssets);
        for(Asset childAsset : childAssets) {
           // System.assert(childAsset.AccountId == newAccount.Id);
        }

    }

    @IsTest
    static void test_Asset_AccountMove_Cl_sameday_Positive() {

        User u = TestUtils.getUserForTest(UNAME);

        //  Create CL Specific Stuff all tied to Route / Route Schedule
        Map<String,Object> mBaseData         = clTESTUTILS.createAllNonClData();
        Map<String,Object> mClData           =  clTESTUTILS.createEnd2EndRouteData(mBaseData);
        List<Meter_Reading__c> meterReadings = (List<Meter_Reading__c>)mClData.get(clTESTUTILS.SFDCMETERREADINGS);

        //  Create non CL Stuff so we have new accounts
        List<Municipality__c> munis = new List<Municipality__c>{clTESTUTILS.createMuni()};
        List<Account> newAccounts = clTESTUTILS.createAccounts(munis);
        Account newAccount = newAccounts[0];

        // Find all Assets associated with Meter_Reading__c sObjects.
        Set<Id> allMeterAssetIds = new Set<Id>();
        for(Meter_Reading__c mr : meterReadings) {
            allMeterAssetIds.add(mr.Asset__c);
        }
        Map<Id,Asset> mAssets =  new Map<Id,Asset>([
                SELECT Id,AccountId
                FROM   Asset
                WHERE  Id IN :allMeterAssetIds
        ]);


        System.runAs(u) {
            Test.startTest();

            // (1) Ensure That Meter_Reading__c.Asset_Moved_Date__c was set set via any other inserts / updated.
            Map<Id, Meter_Reading__c> mMeterReadings = new Map<Id, Meter_Reading__c>([
                    SELECT Id,Asset_Moved_Date__c
                    FROM Meter_Reading__c
                    WHERE Asset__c IN :mAssets.keySet()
            ]);
            for (Meter_Reading__c mr : mMeterReadings.values()) {
                System.assert(mr.Asset_Moved_Date__c == null);
            }

            // (2) Change the account id of assets associated with all meters and ensure Meter_Reading__c.Asset_Moved_Date__c was set.

            for (Asset asset : mAssets.values()) {
                asset.AccountId = newAccount.Id;
            }
            update mAssets.values();

            mMeterReadings = new Map<Id, Meter_Reading__c>([
                    SELECT Id,Asset_Moved_Date__c
                    FROM Meter_Reading__c
                    WHERE Asset__c IN :mAssets.keySet()
            ]);

            for (Meter_Reading__c mr : mMeterReadings.values()) {
                System.assert(mr.Asset_Moved_Date__c.date() == Date.today());
            }

            Test.stopTest();
        }
    }


    @IsTest
    static void test_Asset_AccountMove_Cl_prevdays_Positive() {

        User u = TestUtils.getUserForTest(UNAME);

        //  Create CL Specific Stuff all tied to Route / Route Schedule
        Map<String,Object> mBaseData         = clTESTUTILS.createAllNonClData();
        Map<String,Object> mClData           =  clTESTUTILS.createEnd2EndRouteData(mBaseData);
        List<Meter_Reading__c> meterReadings = (List<Meter_Reading__c>)mClData.get(clTESTUTILS.SFDCMETERREADINGS);

        //  Create non CL Stuff so we have new accounts
        List<Municipality__c> munis = new List<Municipality__c>{clTESTUTILS.createMuni()};
        List<Account> newAccounts = clTESTUTILS.createAccounts(munis);
        Account newAccount = newAccounts[0];

        // Find all Assets associated with Meter_Reading__c sObjects.
        Set<Id> allMeterAssetIds = new Set<Id>();
        for(Meter_Reading__c mr : meterReadings) {
            Test.setCreatedDate(mr.Id,System.now().addDays(-2));
            allMeterAssetIds.add(mr.Asset__c);
        }
        Map<Id,Asset> mAssets =  new Map<Id,Asset>([
                SELECT Id,AccountId
                FROM   Asset
                WHERE  Id IN :allMeterAssetIds
        ]);


        Map<Id, Meter_Reading__c> mMeterReadings = new Map<Id, Meter_Reading__c>([
                SELECT Id,Asset_Moved_Date__c
                FROM Meter_Reading__c
                WHERE Asset__c IN :mAssets.keySet()
        ]);

        System.runAs(u) {
            Test.startTest();


            // (1) Change the account id of assets associated with all meters and ensure Meter_Reading__c.Asset_Moved_Date__c was NOT SET
            for (Asset asset : mAssets.values()) {
                asset.AccountId = newAccount.Id;
            }
            update mAssets.values();

            mMeterReadings = new Map<Id, Meter_Reading__c>([
                    SELECT Id,Asset_Moved_Date__c
                    FROM Meter_Reading__c
                    WHERE Asset__c IN :mAssets.keySet()
            ]);

            for (Meter_Reading__c mr : mMeterReadings.values()) {
                System.assert(mr.Asset_Moved_Date__c == null);
            }

            Test.stopTest();
        }
    }
}