objects/Account.object
<CustomObject>
    <fields>
        <fullName>Shipping_Address_Accuracy__c</fullName>
        <defaultValue>&quot;Weak&quot;</defaultValue>
        <description>@see Geocode_Settings__mdt for mapping. @see https://help.salesforce.com/articleView?id=data_dot_com_clean_geocode_information_fields.htm&amp;type=5</description>
        <inlineHelpText>Deprecated field</inlineHelpText>
        <label>Physical Address Accuracy</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Municipality__c.object
<CustomObject>
    <label>Municipality</label>
    <nameField>
        <label>Municipality Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Municipalities</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/TEST_BatchGeoLegacyUpdater.cls
@isTest
private class TEST_BatchGeoLegacyUpdater{

    public static String UNAME = 'acceltest@accel.com';

    @testSetup static void setup() {
        User u = TestUtils.getUserForTest(UNAME);
        System.runAs(u) {
            List<Municipality__c> municipalities = TestUtils.createMunicipalities('testaccellmuni',1);
            List<Account> accounts = new List<Account>();
            Integer i = 0;
            for(Municipality__c municipality : municipalities) {
                accounts.add(TestUtils.buildAccount('accel test acct:'+i + 'a', municipality.id,'Accel Account'));
                accounts.add(TestUtils.buildAccount('accel test acct:'+i + 'b', municipality.id,'Competitor Account'));
                i++;
            }
            insert accounts;
            accounts = [ select id, shipping_address_accuracy__c from account where Id in :accounts];
            for(Account account : accounts) {
                account.Shipping_Address_Accuracy__c = null;
            }
            update accounts;
        }
    }

    @isTest static void test_Batch_Update_Accuracy_Value_Positive() {
        User u = TestUtils.getUserForTest(UNAME);
        System.runAs(u) {
            Test.startTest();
            BatchGeoAccuracyLegacyUpdater b = new BatchGeoAccuracyLegacyUpdater();
            Id batchId = Database.ExecuteBatch(b,2);
            Account account = [SELECT Id, Type FROM Account limit 1];
            account.type = 'Bad value';

            Map<Id,Account> mAccountsByIds = new Map<Id,Account>{account.Id => account};

            List<Database.SaveResult> results = Database.update(mAccountsByIds.values(), false);
            for (Integer i = 0; i < results.size(); i++) {
                Database.SaveResult sr = results.get(i);
                if (sr.isSuccess()) {
                    //
                } else {
                    Id accountId = mAccountsByIds.values().get(i).Id;
                    b.handleErrors(accountId, results.get(i).getErrors());
                }
            }
            Test.stopTest();
            //@todo assert
        }
    }

}