objects/Account.object
<CustomObject>
    <fields>
        <fullName>Active_IGB_Gaming_License__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Linked IGB Gaming License</label>
        <referenceTo>License__c</referenceTo>
        <relationshipLabel>Accounts (Active IGB Gaming License)</relationshipLabel>
        <relationshipName>Accounts2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Hold_Per_Day_Total__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Based on HPD Records of Record type = Monthly HPD</description>
        <inlineHelpText>Based on Monthly HPD Data</inlineHelpText>
        <label>Hold Per Day Total (Monthly)</label>
        <referenceTo>Hold_Per_Day_Total__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IGB_License__c</fullName>
        <externalId>true</externalId>
        <label>IGB License #</label>
        <length>18</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Hold_Per_Day__c.object
<CustomObject>
    <label>Hold Per Day</label>
    <nameField>
        <displayFormat>HPD-{000000000}</displayFormat>
        <label>Hold Per Day Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Holds Per Day</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Hold_Per_Day_Total__c.object
<CustomObject>
    <description>Contains calculated information for HPD (currently only monthly)
Rolls up info for both Account(Location) and Municipality Levels (Separated by Record Type).
Fields such as TTM indicate 12 month roll-ups. all other fiels noted appropriated (4 weeks 8 weeks 12 weeks) etc.

Additional record type for future use of Machine exists as well.</description>
    <fields>
        <fullName>Eight_Week_HPD__c</fullName>
        <description>Aggregates HPD data for the last 12 weeks.  
For Machines....(Revenue Total / 60)  
For Locations.....(Revenue Total /  # of Vgts) / 2</description>
        <formula>/**
 * If Machine (ie Asset)
 *   Make sure we have enough HPD Data to eval ie. at least 8 weeks or 60 days.. if so
 *   calc rev / # of days... if not return null.
 *
 * If Location (ie Account)
 *   We are using monthlys so only need to look for 2 in this case.
 *   Also adding Total Vgt Count into the calc. 
 */
CASE( 
RecordType.Name, 
&quot;Machine&quot;, 
IF( HPD_Nbr_of_Records_8_Weeks__c&gt;=60, HPD_Revenue_Total_8_Weeks__c/60,null), 
&quot;Location&quot;, 
IF( HPD_Nbr_of_Records_8_Weeks__c&gt;=2, Eight_Week_HPD_Avg__c ,null) 
,null 
) 
/*
CASE( 
   RecordType.Name,
   &quot;Machine&quot;,
      IF( HPD_Nbr_of_Records_8_Weeks__c &gt;= 60,
          HPD_Revenue_Total_8_Weeks__c / 60,   
              null),
   &quot;Location&quot;,
       IF( AND(  HPD_Nbr_of_Records_8_Weeks__c &gt;= 2,HPD_Total_VGT_Count__c &gt; 0) , ( 
          HPD_Revenue_Total_8_Weeks__c / HPD_Total_VGT_Count__c ) / Total_Nbr_of_Days_in_Months_8_Weeks__c, null)
   ,null
)
*/</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Based on Monthly HPD Records. Aggregates HPD data for 2 Months.. (Revenue Total /  # of Vgts) / 2. If Not enough data available, will display a blank value.</inlineHelpText>
        <label>8 Week HPD</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Four_Week_HPD__c</fullName>
        <description>Aggregates HPD data for the last 4 weeks.  
For Machines....(Revenue Total / 30)  
For Locations.....(Revenue Total /  # of Vgts) / 30</description>
        <formula>/**
 * If Machine (ie Asset)
 *   Make sure we have enough HPD Data to eval ie. at least 4 weeks or 30 days.. if so
 *   calc rev / # of days... if not return null.
 *
 * If Location (ie Account)
 *   We are using monthlys so only need to look for 1 in this case.
 *   Also adding Total Vgt Count into the calc. 
 */
CASE( 
RecordType.Name, 
&quot;Machine&quot;, 
IF( HPD_Nbr_of_Records_4_Weeks__c&gt;=30, HPD_Revenue_Total_4_Weeks__c / 30 ,null), 
&quot;Location&quot;, 
IF( HPD_Nbr_of_Records_4_Weeks__c&gt;=1, Four_Week_HPD_Avg__c ,null) 
,null 
) 


/*===========
CASE( 
   RecordType.Name,
   &quot;Machine&quot;,
      IF( HPD_Nbr_of_Records_4_Weeks__c &gt;= 30,
          HPD_Revenue_Total_4_Weeks__c / 30,   
              null),
   &quot;Location&quot;,
       IF( AND( HPD_Nbr_of_Records_4_Weeks__c &gt;= 1,HPD_Total_VGT_Count__c &gt; 0) , ( 
          HPD_Revenue_Total_4_Weeks__c / HPD_Total_VGT_Count__c ) / Total_Nbr_of_Days_in_Months_4_Weeks__c, null)
   ,null
)*/</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Based on Monthly HPD Records. Aggregates HPD data for 1 Month.. (Revenue Total /  # of Vgts) / 1. If Not enough data available, will display a blank value.</inlineHelpText>
        <label>4 Week HPD</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Twelve_Week_HPD__c</fullName>
        <description>Aggregates HPD data for the last 12 weeks.  
For Machines....(Revenue Total / 90)  
For Locations.....(Revenue Total /  # of Vgts) / 3
If not enough data to calculate.. the value will be empty.</description>
        <formula>/**
 * If Machine (ie Asset)
 *   Make sure we have enough HPD Data to eval ie. at least 12 weeks or 90 days.. if so
 *   calc rev / # of days... if not return null.
 *
 * If Location (ie Account)
 *   We are using monthlys so only need to look for 3 in this case.
 *   Also adding Total Vgt Count into the calc. 
 */
CASE( 
   RecordType.Name,
   &quot;Machine&quot;,
      IF( HPD_Nbr_of_Records_12_Weeks__c&gt;=90, HPD_Revenue_Total_12_Weeks__c / 90 ,null),
   &quot;Location&quot;,
       IF( HPD_Nbr_of_Records_12_Weeks__c&gt;=3, Twelve_Week_HPD_Avg__c ,null)
   ,null
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Based on Monthly HPD Records. Aggregates HPD data for 3 Months.. (Revenue Total /  # of Vgts) / 3. If Not enough data available, will display a blank value.</inlineHelpText>
        <label>12 Week HPD</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Hold Per Day Total</label>
    <nameField>
        <displayFormat>HPDT-{000000000}</displayFormat>
        <label>HPD Total #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Hold Per Day Totals</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/License__c.object
<CustomObject>
    <label>License</label>
    <nameField>
        <label>License Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Licenses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/TEST_CommunityLocationSummaryController.cls
@isTest
private class TEST_CommunityLocationSummaryController {

    public static String UNAMEADMIN = 'acceltestadmin@accelentertainment.com';
    public static String UNAMECP = 'accelcustomerportal@portal.com';
    public static String ACCOUNTNAME = 'mollys unit test';
    public static String PROFILENAMECP = 'Accel Customer Community';
    public static String NETWORKNAME = 'Accel Entertainment Customer Community';
    /**
     * Setup test data. 
     * @TODO Refactor into generic TEST Util!
     */
    @testSetup static void setup() {
        UserRole adminRole = new UserRole(DeveloperName = 'TestCustomerPortalRole', Name = 'TestCustomerPortalRole');
        insert adminRole;
        User adminUser = TestUtils.getUserForTest(UNAMEADMIN);
        adminUser = [select id, userroleid from user where id = :adminUser.id];
        adminUser.userroleid = adminRole.id;
        update adminUser;

        system.runAs(adminUser) {
            User user = TestUtils.getPortalUserForTest(PROFILENAMECP, ACCOUNTNAME, UNAMECP);
            Contact contact = [select id,accountId from contact where id = :user.contactId];
            Account account = [select id, IGB_License__c,type from account where id = :contact.AccountId];
            account.IGB_License__c = '6666666';
            account.type = 'Accel Account';
            update account;
            License__c license = TestUtils.buildGenericIgbLicense(account.Id);
            insert license;
            account.active_igb_gaming_license__C = license.id;
            update account;
            List<Hold_Per_Day__c> holdPerDays = TestUtils.buildAccountHoldPerDays(new List<Account>{
                    account
            }, 10, 'Monthly HPD');
            insert holdPerDays;
            //@TODO build hold per day total data
        }

    }
    /**
     * @TODO Real asserts! This is Weak ass testing..
     */
    @isTest static void retrieveHoldPerDayByAccountsAllMonths() {

        User communityUser = TESTUtils.getUserForTest(UNAMECP);
        communityUser = [SELECT Id, contactId, accountId,username from user where id = :communityUser.id];
        System.runAs(communityUser) {
            Test.startTest();

            Account a = [select id,name, IGB_License__c from account where id = :communityUser.accountId];

            ResponseDto dto = Accel_CommunityLocComparisonController.retrieveHoldPerDayByAccountsAllMonths(new List<Id>{
                    a.id
            });
            system.debug(dto);

            Test.stopTest();
        }
    }

    @isTest static void testRetrieveAllLocationMonthlyWrappers() {
        User communityUser = TESTUtils.getUserForTest(UNAMECP);
        communityUser = [SELECT Id, contactId, accountId,username from user where id = :communityUser.id];
        System.runAs(communityUser) {
            Test.startTest();

            Account a = [select id,name, IGB_License__c from account where id = :communityUser.accountId];

            ResponseDto dto = Accel_CommunityLocationSummaryController.retrieveAllLocationMonthlyWrappers();
            system.debug(dto);

            Test.stopTest();
        }
    }
    @isTest static void testRetrieveAllLocationMonthlyWrappersLast12() {
        User communityUser = TESTUtils.getUserForTest(UNAMECP);
        communityUser = [SELECT Id, contactId, accountId,username from user where id = :communityUser.id];
        System.runAs(communityUser) {
            Test.startTest();

            Account a = [select id,name, IGB_License__c from account where id = :communityUser.accountId];

            ResponseDto dto = Accel_CommunityLocationSummaryController.retrieveAllLocationMonthlyWrappersLast12();
            system.debug(dto);

            Test.stopTest();
        }
    }
    @isTest static void testretrieveLocationMonthlyHpds() {
        User communityUser = TESTUtils.getUserForTest(UNAMECP);
        communityUser = [SELECT Id, contactId, accountId,username from user where id = :communityUser.id];
        System.runAs(communityUser) {
            Test.startTest();

            ResponseDto dto = Accel_CommunityLocationSummaryController.retrieveLocationMonthlyHpds(null);
            system.debug(dto);
            ResponseDto dto2 = Accel_CommunityLocationSummaryController.retrieveLocationMonthlyHpds('1YR');

            Test.stopTest();
        }
    }
    @isTest static void testRetrieveLocationAllMonthlyWrappers() {
        User communityUser = TESTUtils.getUserForTest(UNAMECP);
        communityUser = [SELECT Id, contactId, accountId,username from user where id = :communityUser.id];
        System.runAs(communityUser) {
            Test.startTest();

            Account a = [select id,name, IGB_License__c from account where id = :communityUser.accountId];

            ResponseDto dto = Accel_CommunityLocationSummaryController.retrieveLocationAllMonthlyWrappers();
            system.debug(dto);

            Test.stopTest();
        }
    }
    /**
     * @TODO this is not really doing anything but we are running out of time so be it!
     */
    @isTest static void testRetrieveUserLocationsAndHpdDataWithHpdTotalsGenerated() {

        User communityUser = TESTUtils.getUserForTest(UNAMECP);
        communityUser = [SELECT Id, contactId, accountId,username from user where id = :communityUser.id];
        System.runAs(communityUser) {
            Test.startTest();

            BatchHpdAccountTotals b = new BatchHpdAccountTotals('Monthly', -12);
            Database.executeBatch(b);
        }
        Test.stopTest();
        ResponseDto dto = Accel_CommunityLocationSummaryController.retrieveUserLocations();
        system.debug(dto);
    }
    @isTest static void testGetMaxAccountResults() {

        User communityUser = TESTUtils.getUserForTest(UNAMECP);
        communityUser = [SELECT Id, contactId, accountId,username from user where id = :communityUser.id];
        System.runAs(communityUser) {
            Test.startTest();

            Integer iMaxResults = Accel_CommunityLocationSummaryController.getMaxAccountResults();
            system.debug(iMaxResults);

            Test.stopTest();
        }
    }
    @isTest static void testRetrieveAccountRevenue() {

        User communityUser = TESTUtils.getUserForTest(UNAMECP);
        communityUser = [SELECT Id, contactId, accountId,username from user where id = :communityUser.id];
        System.runAs(communityUser) {
            Test.startTest();
            Account a = [select id from account limit 1];
            ResponseDto dto = Accel_CommunityLocationSummaryController.retrieveAccountRevenue(a.id,system.today().addMonths(-12), System.today());
            Test.stopTest();
        }
    }
    /**
     * @TODO is this even used?
     */
    @isTest static void testLocDetailConstructor() {
        Test.startTest();

        Account a = [
                select id,Hold_Per_Day_Total__r.Four_Week_HPD__c,Hold_Per_Day_Total__r.Eight_Week_HPD__c,Hold_Per_Day_Total__r.Twelve_Week_HPD__c
                from account
                limit 1
        ];
        Accel_CommunityLocationSummaryController.LocationDetail locationDetail = new Accel_CommunityLocationSummaryController.LocationDetail(a);

        Test.stopTest();
    }
    /**
 * @TODO this is not really doing anything but we are running out of time so be it!
 */
    @isTest static void testRetrieveUserHpdAndExpDate() {

        User communityUser = TESTUtils.getUserForTest(UNAMECP);
        communityUser = [SELECT Id, contactId, accountId,username from user where id = :communityUser.id];
        System.runAs(communityUser) {
            Test.startTest();

            BatchHpdAccountTotals b = new BatchHpdAccountTotals('Monthly', -12);
            Database.executeBatch(b);
        }
        Test.stopTest();
        ResponseDto dto = Accel_CommunityLocationSummaryController.retrieveUserHpdAndExpDate();
        system.debug(dto);
    }
}