objects/Account.object
<CustomObject>
    <fields>
        <fullName>Hold_Per_Day_Total__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Based on HPD Records of Record type = Monthly HPD</description>
        <inlineHelpText>Based on Monthly HPD Data</inlineHelpText>
        <label>Hold Per Day Total (Monthly)</label>
        <referenceTo>Hold_Per_Day_Total__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Most_Recent_Hold_Per_Day__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Most Recent Hold Per Day</label>
        <referenceTo>Hold_Per_Day__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Asset.object
<CustomObject>
    <fields>
        <fullName>Hold_Per_Day_Total__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Contains All Aggregated information for HPD Records for this Machine.</description>
        <inlineHelpText>Contains All Aggregated information for HPD Records for this Machine.</inlineHelpText>
        <label>Hold Per Day Total</label>
        <referenceTo>Hold_Per_Day_Total__c</referenceTo>
        <relationshipLabel>Assets</relationshipLabel>
        <relationshipName>Assets</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>VGT</fullName>
        <active>true</active>
        <label>VGT</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Hold_Per_Day_Total__c.object
<CustomObject>
    <description>Contains calculated information for HPD (currently only monthly)
Rolls up info for both Account(Location) and Municipality Levels (Separated by Record Type).
Fields such as TTM indicate 12 month roll-ups. all other fiels noted appropriated (4 weeks 8 weeks 12 weeks) etc.

Additional record type for future use of Machine exists as well.</description>
    <label>Hold Per Day Total</label>
    <nameField>
        <displayFormat>HPDT-{000000000}</displayFormat>
        <label>HPD Total #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Hold Per Day Totals</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/HPD_Total_Setting__mdt.object
<CustomObject>
    <description>Contains configurable parameters for HPD Totals Aggregation. (Nightly batch jobs that use SOQL aggregation to rollup data to Hold Per Day Total from Hold Per Data.</description>
    <label>HPD Total Setting</label>
    <pluralLabel>HPD Total Settings</pluralLabel>
</CustomObject>

classes/BatchHpdInitAssetRecs.cls
/**
 *
 */
global class BatchHpdInitAssetRecs implements Database.Batchable<Sobject>, Database.Stateful {

    global HPD_Total_Setting__mdt hpdTotalSetting;
    public final static String ASSET_AGGREGATION_DEVNAME = 'HPD_Account_Aggregation'; //@TODO create asset setting
    global Integer iNumHpdtsInserted = 0;
    global Integer iNumAssetsProcessed = 0;
    global String formattedLocalStartTimeString;
    global String formattedLocalEndTimeString;

    global BatchHpdInitAssetRecs() {
        formattedLocalStartTimeString = DateTime.now().format();
    }

    /**
     *
     *
     * @param bc
     * @return
     */
    global database.querylocator start(Database.BatchableContext bc) {
        hpdTotalSetting = CustomMetadataSvc.retrieveHpdTotalSettingsMeta(ASSET_AGGREGATION_DEVNAME);
//        Set<String> excludedAcctTypes = new Set<String>{
//                'Discontinued Account'
//        };
        return Database.getQueryLocator([
                SELECT Id, accountId, account.most_recent_hold_per_day__c
                FROM Asset
                WHERE recordtype.name = 'VGT'
              //  and Account.Type NOT IN :excludedAcctTypes
        ]);
    }
    /**
     *
     *
     * @param bc
     * @param scope
     */
    global void execute(Database.BatchableContext bc, List<Asset> scope) {
        iNumAssetsProcessed += scope.size();
        Map<String,Object> mReturn = HpdStatsHelper.initHpdAssetTotalRecs(scope);
        List<Hold_Per_Day_Total__c> holdPerDayTotalsInserted = (List<Hold_Per_Day_Total__c>)mReturn.get('HPD_TOTALS');
        iNumHpdtsInserted += holdPerDayTotalsInserted.size();
    }
    global void finish(Database.BatchableContext bc) {
        formattedLocalEndTimeString = DateTime.now().format();
        Id batchId;
        //String freq = 'Daily';

        String subject = 'Accel SFDC Batch HPD Init for Asset Automation process complete! ';
        String msg = '<br/>If you are receiving this email,it is because your email address was added to the HPD_Total_Setting__mdt as a valid address to receive debug emails for this job.<br/>';
        msg += '<br/>Start Time:<b> ' + formattedLocalStartTimeString + '</b>';
        msg += '<br/>End Time:<b> ' + formattedLocalEndTimeString + '</b><br/>';
        msg += '<br/># of Assets processed:<b> ' + iNumAssetsProcessed + '</b></br>';
        msg += '<br/># of Hold Per Day Total Records inserted:<b> ' + iNumHpdtsInserted + '</b></br>';
       if (!Test.isRunningTest()) {
            BatchHpdLinkAssetRecsWithHpdTotals b = new BatchHpdLinkAssetRecsWithHpdTotals();
            batchId = Database.executeBatch(b, 100);
            msg += '<br/>Firing Batch Job '+ batchId + ' (BatchHpdLinkAssetRecsWithHpdsTotals) to  Asset recs with hpd  total recs';
        }
        List<String> emailAddys = EmailSvc.getHpdEmailNotificationAddys(ASSET_AGGREGATION_DEVNAME);
        String body = msg;
        EmailSvc.sendEmail(emailAddys, subject, body);
    }
}