objects/Account.object
<CustomObject>
    <fields>
        <fullName>Service_Region__c</fullName>
        <label>Service Zone</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Service_Region</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Asset.object
<CustomObject>
    <fields>
        <fullName>GP_Manufacturer__c</fullName>
        <description>Manufacturer Field from GP Integration</description>
        <label>GP_Manufacturer</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Model__c</fullName>
        <label>Model</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Case.object
<CustomObject>
    <fields>
        <fullName>Accel_Solution__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Replacement for Solution Picklist</description>
        <label>Solution</label>
        <referenceTo>Solution__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Assigned_Resource__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Assigned Resource</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Cases2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <formula>Account.ShippingCity</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>City</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IGB_Number__c</fullName>
        <formula>Account.IGB_License__c</formula>
        <label>IGB Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Model__c</fullName>
        <formula>Asset.Model__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Model</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Serial__c</fullName>
        <formula>Asset.SerialNumber</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Serial</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service_Region__c</fullName>
        <formula>TEXT(Account.Service_Region__c)</formula>
        <label>Service Zone</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Work_Type__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Work Type</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>WorkType filter exception</errorMessage>
            <filterItems>
                <field>WorkType.Inactive__c</field>
                <operation>equals</operation>
                <value>False</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>WorkType</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/City__c.object
<CustomObject>
    <label>City</label>
    <nameField>
        <label>City Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Solution__c.object
<CustomObject>
    <description>Used for Lookup field reference as replacement for Solution picklist on Case, WorkOrder, And Service Appointment. Generally Trigger Maintained and synced (one way) ie copies value to corresponding Solution__c picklist value on Case, WorkOrder, ServiceAppointment as it was said that would cause too much reporting rewrite overhead.</description>
    <label>Accel Solution</label>
    <nameField>
        <label>Solution Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Solutions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

globalValueSets/Service_Region.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Champaign 1</fullName>
    </customValue>
    <customValue>
        <fullName>Chicagoland - Advanced</fullName>
    </customValue>
    <customValue>
        <fullName>Chicagoland - AVG</fullName>
    </customValue>
    <customValue>
        <fullName>Chicagoland Central</fullName>
    </customValue>
    <customValue>
        <fullName>Chicagoland - Lakeshore</fullName>
    </customValue>
    <customValue>
        <fullName>Chicagoland North 1</fullName>
    </customValue>
    <customValue>
        <fullName>Chicagoland North 2</fullName>
    </customValue>
    <customValue>
        <fullName>Chicagoland North 3</fullName>
    </customValue>
    <customValue>
        <fullName>Chicagoland North 4</fullName>
    </customValue>
    <customValue>
        <fullName>Chicagoland - Shamrock</fullName>
    </customValue>
    <customValue>
        <fullName>Chicagoland South 1</fullName>
    </customValue>
    <customValue>
        <fullName>Chicagoland South 2</fullName>
    </customValue>
    <customValue>
        <fullName>Chicagoland South 3</fullName>
    </customValue>
    <customValue>
        <fullName>Chicagoland South 4</fullName>
    </customValue>
    <customValue>
        <fullName>Chicagoland South 5</fullName>
    </customValue>
    <customValue>
        <fullName>Collinsville 1</fullName>
    </customValue>
    <customValue>
        <fullName>Collinsville 2</fullName>
    </customValue>
    <customValue>
        <fullName>Collinsville 3</fullName>
    </customValue>
    <customValue>
        <fullName>Collinsville 4</fullName>
    </customValue>
    <customValue>
        <fullName>Collinsville 5</fullName>
    </customValue>
    <customValue>
        <fullName>Collinsville 6</fullName>
    </customValue>
    <customValue>
        <fullName>Collinsville 7</fullName>
    </customValue>
    <customValue>
        <fullName>Collinsville - D&amp;S Vending</fullName>
        <label>Collinsville - D &amp; S Vending</label>
    </customValue>
    <customValue>
        <fullName>Collinsville - Olney/Oblong</fullName>
    </customValue>
    <customValue>
        <fullName>Peoria 1</fullName>
    </customValue>
    <customValue>
        <fullName>Peoria 2</fullName>
    </customValue>
    <customValue>
        <fullName>Peoria 3</fullName>
    </customValue>
    <customValue>
        <fullName>Peoria 4</fullName>
    </customValue>
    <customValue>
        <fullName>Peoria 5</fullName>
    </customValue>
    <customValue>
        <fullName>Rockford 1</fullName>
    </customValue>
    <masterLabel>Service Region</masterLabel>
</GlobalValueSet>

classes/GenDataTables.cls
public class GenDataTables {
    public List<AggregateResult> regionBreakDownList;
    public List<AggregateResult> technicianBreakDownList;
    public List<AggregateResult> callCenterBreakDownList;
    public List<AggregateResult> manufacturerBreakDownList;
    public List<Case> dailyLogList; 
    public List<Case> pendingLogList;
    public genDatatables(){
        regionBreakDownList = [Select Account.Service_Region__c, COUNT(Id) from Case where CreatedDate = yesterday GROUP BY Account.Service_Region__c order by COUNT(Id) DESC NULLS LAST];
        technicianBreakDownList = [Select Assigned_Resource__r.Name, COUNT(Id) from Case where CreatedDate = yesterday and Assigned_Resource__c NOT IN (select id from user where user.profile.name = 'Accel Call Center') GROUP BY Assigned_Resource__r.Name order by COUNT(Id) DESC NULLS LAST];
        callCenterBreakDownList = [Select Assigned_Resource__r.Name, COUNT(Id) from Case where CreatedDate = yesterday and Assigned_Resource__c IN (select id from user where user.profile.name = 'Accel Call Center') GROUP BY Assigned_Resource__r.Name order by COUNT(Id) DESC NULLS LAST];
        manufacturerBreakDownList = [Select Asset.GP_Manufacturer__c, COUNT(Id) from Case where CreatedDate = yesterday GROUP BY Asset.GP_Manufacturer__c order by COUNT(Id) DESC NULLS LAST];
        dailyLogList = [select IGB_Number__c, Account.Name, City__c, Service_Region__c, Assigned_Resource__r.Name,
                                FORMAT(CreatedDate), FORMAT(ClosedDate), Model__c, Serial__c, Work_Type__r.Name, Description, Accel_Solution__c, Accel_Solution__r.Name,  CreatedBy.Name
                        from    Case
                        where CreatedDate = yesterday ORDER BY Service_Region__c ASC NULLS LAST, CreatedDate DESC];
        pendingLogList = [select  Account.Name, Service_Region__c, Assigned_Resource__r.Name, FORMAT(CreatedDate), Model__c, Work_Type__r.Name, Description from Case where CreatedDate = yesterday and (Status = 'Pending' or Status = 'In Progress') and ClosedDate = NULL ORDER BY Service_Region__c ASC NULLS LAST, CreatedDate DESC];
    }  
    public List<AggregateResult> regionBreakDownListAgg {
      get{  return regionBreakDownList;}
    }
     public List<AggregateResult> technicianBreakDownListAgg {
      get{  return technicianBreakDownList;}
    }
     public List<AggregateResult> callCenterBreakDownListAgg {
      get{  return callCenterBreakDownList;}
    }
     public List<AggregateResult> manufacturerBreakDownListAgg {
      get{  return manufacturerBreakDownList;}
    }
     public List<Case> dailyLogAgg {
      get{  return dailyLogList;}
    }
     public List<Case> pendingLogAgg {
      get{   return pendingLogList;}
    }
    public String getReportDate() {
        Date d = date.Today().addDays(-1);
        return d.format();
    }
    public integer getTotalCalls(){
        integer tc=database.countQuery('select count() from Case where CreatedDate = yesterday');
        return tc;
    }
    public integer getTechComplete(){
        List<User> cc = [select id from user where user.profile.name = 'Accel Call Center'];
        integer tc=database.countQuery('Select COUNT() from Case where ClosedDate != null and Assigned_Resource__c NOT IN :cc and CreatedDate = yesterday');
        return tc;
    }
    public integer getCallCenterComplete(){
        List<User> cc = [select id from user where user.profile.name = 'Accel Call Center'];
        integer tc=database.countQuery('Select COUNT() from Case where  ClosedDate != null and Assigned_Resource__c IN :cc and CreatedDate = yesterday');
        return tc; 
    }
    public integer getIncompleteCalls(){
        integer tc=database.countQuery('select count() from Case where ClosedDate = null and CreatedDate = yesterday');
        return tc;
    }
    public integer getInProgressCalls(){
        String prog = 'In Progress';
        integer tc=database.countQuery('select count() from Case where ClosedDate = null and Status = :prog and CreatedDate = yesterday');
        return tc;
    }
    public integer getUnresolvedCalls(){
        String pend = 'Pending';
        integer tc=database.countQuery('select count() from Case where ClosedDate = null and Status = :pend and CreatedDate = yesterday');
        return tc;
    }
}