objects/Account.object
<CustomObject>
    <fields>
        <fullName>Hold_Per_Day_Total_Daily__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Based on HPD Records of Record type = Daily HPD</description>
        <inlineHelpText>Based on Monthly HPD Data</inlineHelpText>
        <label>Hold Per Day Total (Daily)</label>
        <referenceTo>Hold_Per_Day_Total__c</referenceTo>
        <relationshipLabel>Accounts (Hold Per Day Total (Daily))</relationshipLabel>
        <relationshipName>AccountsForDaily</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Hold_Per_Day_Total__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Based on HPD Records of Record type = Monthly HPD</description>
        <inlineHelpText>Based on Monthly HPD Data</inlineHelpText>
        <label>Hold Per Day Total (Monthly)</label>
        <referenceTo>Hold_Per_Day_Total__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Hold_Per_Day_Total__c.object
<CustomObject>
    <description>Contains calculated information for HPD (currently only monthly)
Rolls up info for both Account(Location) and Municipality Levels (Separated by Record Type).
Fields such as TTM indicate 12 month roll-ups. all other fiels noted appropriated (4 weeks 8 weeks 12 weeks) etc.

Additional record type for future use of Machine exists as well.</description>
    <label>Hold Per Day Total</label>
    <nameField>
        <displayFormat>HPDT-{000000000}</displayFormat>
        <label>HPD Total #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Hold Per Day Totals</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/TEST_BatchHpdLinkAccountRecs.cls
@isTest
public with sharing class TEST_BatchHpdLinkAccountRecs {
    public static String UNAME = 'acceltest@accel.com';

    @testSetup static void setup() {
        User u = TestUtils.getUserForTest(UNAME);
        System.runAs(u) {
            TestUtils.createTestHoldPerDays();
            HpdStatsHelper.reInitHpdTotals();
        }
    }
    //@TODO for future use
//    @isTest static void testBatchLinkAccountReqsWithHpdTotals_Daily() {
//        User u = TestUtils.getUserForTest(UNAME);
//        List<Account> accounts = [select id, type, hold_per_day_total__c, hold_per_day_total_daily__c from account];
//        system.debug('--------accounts='+accounts);
//        System.runAs(u) {
//
//            Test.startTest();
//
//            BatchHpdLinkAccountRecsWithHpdTotals b = new BatchHpdLinkAccountRecsWithHpdTotals('Daily', false);
//            Database.executeBatch(b);
//            //@TODO this is not calling the execute method why? batchsize?
//            //@todo do real assert
//            Test.stopTest();
//        }
//    }
    @isTest static void testBatchLinkAccountReqsWithHpdTotals_Monthly() {
        User u = TestUtils.getUserForTest(UNAME);
        System.runAs(u) {
            Test.startTest();
            BatchHpdLinkAccountRecsWithHpdTotals b = new BatchHpdLinkAccountRecsWithHpdTotals('Monthly', false);
            Database.executeBatch(b);
            //@TODO this is not calling the execute method why? batchsize?
            //@todo do real assert
            Test.stopTest();
        }
    }
}