objects/Account.object
<CustomObject>
    <fields>
        <fullName>County_Auto_Updated__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates the the County__c was auto updated with FCC (Federal Communication Commission) API Data. https://geo.fcc.gov/api/census/#!/block/get_block_find</description>
        <inlineHelpText>Indicates that the County__c was auto updated with FCC (Federal Communication Commission) API Data.</inlineHelpText>
        <label>County Auto Updated</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>County_LU_Auto_Update__c</fullName>
        <defaultValue>false</defaultValue>
        <description>POC</description>
        <inlineHelpText>POC</inlineHelpText>
        <label>County LU Auto Updated (POC)</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>County_LU__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Updated by Google within 1-3 seconds after creating a new account with an address or updating an account to a new address.</description>
        <inlineHelpText>Updated by Google within 1-3 seconds after creating a new account with an address or updating an account to a new address.</inlineHelpText>
        <label>County</label>
        <referenceTo>County__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>County__c</fullName>
        <description>This will be updated about 1-2 minutes after a new account is created or account has changed if there is accurate enough physical location information to determine the county.</description>
        <inlineHelpText>This will be updated about 1-2 minutes after a new account is created or account has changed if there is accurate enough physical location information to determine the county.</inlineHelpText>
        <label>County (TEXT)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Covid_Region_LU__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Based on the County selected. Updated by Google within 1-3 seconds after creating a new account with an address or updating an account to a new address.</description>
        <inlineHelpText>Based on the County selected. Updated by Google within 1-3 seconds after creating a new account with an address or updating an account to a new address.</inlineHelpText>
        <label>Covid Region</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Region__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Covid</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Region__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MunicipalityLookup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Updated by Google within 1-3 seconds after creating a new account with an address or updating an account to a new address.</inlineHelpText>
        <label>Municipality</label>
        <referenceTo>Municipality__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/County__c.object
<CustomObject>
    <description>Holds all County related info for states that Accel does gaming business with.</description>
    <fields>
        <fullName>Covaid_Region__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The Covid Region that this county is associated with. If Not Illinois, Defaults to a bucket Covid Region</inlineHelpText>
        <label>Covid Region</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Region__c.RecordType.Name</field>
                <operation>equals</operation>
                <value>Covid</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Region__c</referenceTo>
        <relationshipLabel>Counties</relationshipLabel>
        <relationshipName>Counties</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FIPS__c</fullName>
        <inlineHelpText>The numeric version of FIPS (SFDC Will insert commas in number fields so you might want to go with the text version (labeled just FIPS) for display.</inlineHelpText>
        <label>FIPS (Numeric)</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>State</valueSetName>
        </valueSet>
    </fields>
    <label>County</label>
    <nameField>
        <label>County Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Counties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Municipality__c.object
<CustomObject>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>State</valueSetName>
        </valueSet>
    </fields>
    <label>Municipality</label>
    <nameField>
        <label>Municipality Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Municipalities</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Region__c.object
<CustomObject>
    <description>Holds Region Related Info. Current Record Types = [Covid]. Can be expanded for other types of regions.  Linked to County and Accounts.</description>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>State</valueSetName>
        </valueSet>
    </fields>
    <label>Region</label>
    <nameField>
        <label>Region Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Regions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

globalValueSets/State.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>IL</fullName>
    </customValue>
    <customValue>
        <fullName>MO</fullName>
    </customValue>
    <customValue>
        <fullName>GA</fullName>
    </customValue>
    <customValue>
        <fullName>WV</fullName>
    </customValue>
    <customValue>
        <fullName>AL</fullName>
    </customValue>
    <customValue>
        <fullName>AK</fullName>
    </customValue>
    <customValue>
        <fullName>AZ</fullName>
    </customValue>
    <customValue>
        <fullName>AR</fullName>
    </customValue>
    <customValue>
        <fullName>CA</fullName>
    </customValue>
    <customValue>
        <fullName>CO</fullName>
    </customValue>
    <customValue>
        <fullName>CT</fullName>
    </customValue>
    <customValue>
        <fullName>DE</fullName>
    </customValue>
    <customValue>
        <fullName>FL</fullName>
    </customValue>
    <customValue>
        <fullName>HI</fullName>
    </customValue>
    <customValue>
        <fullName>ID</fullName>
    </customValue>
    <customValue>
        <fullName>IN</fullName>
    </customValue>
    <customValue>
        <fullName>IA</fullName>
    </customValue>
    <customValue>
        <fullName>KS</fullName>
    </customValue>
    <customValue>
        <fullName>KY</fullName>
    </customValue>
    <customValue>
        <fullName>LA</fullName>
    </customValue>
    <customValue>
        <fullName>ME</fullName>
    </customValue>
    <customValue>
        <fullName>MD</fullName>
    </customValue>
    <customValue>
        <fullName>MA</fullName>
    </customValue>
    <customValue>
        <fullName>MI</fullName>
    </customValue>
    <customValue>
        <fullName>MN</fullName>
    </customValue>
    <customValue>
        <fullName>MS</fullName>
    </customValue>
    <customValue>
        <fullName>MT</fullName>
    </customValue>
    <customValue>
        <fullName>NE</fullName>
    </customValue>
    <customValue>
        <fullName>NV</fullName>
    </customValue>
    <customValue>
        <fullName>NH</fullName>
    </customValue>
    <masterLabel>State</masterLabel>
</GlobalValueSet>

classes/TEST_QueuableCountyUpdaterLive.cls
@IsTest
private class TEST_QueuableCountyUpdaterLive {
    public static String ADMINUNAME = 'acceltestadmin@accel.com';
    public static User uAdmin = TestUtils.getUserForTest(ADMINUNAME);

    @testSetup
    static void setup() {

        System.runAs(uAdmin) {
            Test.startTest();

            List<Municipality__c> munis = TestUtils.createMunicipalities('Carol Stream', 1);
            for(Municipality__c muni : munis) {
                muni.Name = muni.Name.replace('0','');
            }
            update munis;

            Account account = TestUtils.buildAccount('account name', munis[0].id);
            account.MunicipalityLookup__c = null;
            account.ShippingStreet = '4916 Main Street Unit 2';
            account.ShippingCity = 'Lisle';
            account.ShippingState = 'IL';  //  Be careful of we implement state / country picklists!
            account.ShippingPostalCode = '60532';
            account.ShippingCountry = 'US';
            account.ShippingLatitude = 41.795778000000000;
            account.ShippingLongitude = -88.075013000000000;
            account.County_Auto_Updated__c = true;
            insert account;

            Test.stopTest();
        }
    }

    @IsTest
    static void test_Queueable_County_Updater_Live_Insert_Positive() {

        Region__c region = new Region__c(Name= 'Region 8',State__c = 'IL');
        insert region;
        County__c county = new County__c(Name = 'DuPage',State__c = 'IL', Covaid_Region__c = region.Id);
        insert county;

        Municipality__c municipality = [SELECT Id FROM Municipality__c LIMIT 1][0];
        Account newAccount = TestUtils.buildAccount('Test New Account', municipality.Id,'Accel Account');
        newAccount.ShippingStreet = '4619 Main';
        newAccount.ShippingState = 'IL';  //  Be careful of we implement state / country picklists!
        newAccount.ShippingPostalCode = '60532';
        newAccount.ShippingCountry = 'US';
        insert newAccount;

        String censusResponse = QueueableCountyUpdaterLive.TEST_JSON_RESPONSE;
        String ep = QueueableCountyUpdaterLive.BASE_EP+newAccount.ShippingLatitude+'&longitude=' + newAccount.ShippingLongitude + '&format=json';


        MockHttpResponseHandler.SimpleMockResponse getResp =
                new MockHttpResponseHandler.SimpleMockResponse('GET', censusResponse);

        MockHttpResponseHandler mock = new MockHttpResponseHandler();
        System.debug('---> mock ep = ' + ep);
        mock.addResponse(ep, getResp);
        Test.setMock(HttpCalloutMock.class, mock);

        System.runAs(uAdmin) {

            Test.startTest();

            //simulate data.com but avoid the triggers since we can't chain queueables in unit test code.
            QueueableMuniUpdater.doChainJob = false;
            newAccount.ShippingLatitude = 42.795778000000000;
            newAccount.ShippingLongitude = -87.075013000000000;
            update newAccount;

            QueueableCountyUpdaterLive q = new QueueableCountyUpdaterLive(new Set<Id>{newAccount.Id},false);
            System.enqueueJob(q);

            Test.stopTest();

            newAccount = [SELECT Id, County_LU__c, Covid_Region_LU__c,County_LU_Auto_Update__c FROM Account WHERE Id = :newAccount.Id];
            System.assertEquals(county.Id, newAccount.County_LU__c);
            System.assertEquals(region.Id, newAccount.Covid_Region_LU__c);
        }
    }

    @IsTest
    static void test_Queueable_County_Updater_Live_Insert_Positive_Fips() {

        Region__c region = new Region__c(Name= 'Region 8',State__c = 'IL');
        insert region;
        County__c county = new County__c(Name = 'DuPage County wrong name',State__c = 'IL', Covaid_Region__c = region.Id, FIPS__c = 17043);
        insert county;

        Municipality__c municipality = [SELECT Id FROM Municipality__c LIMIT 1][0];
        Account newAccount = TestUtils.buildAccount('Test New Account', municipality.Id,'Accel Account');
        newAccount.ShippingStreet = '4619 Main';
        newAccount.ShippingState = 'IL';  //  Be careful of we implement state / country picklists!
        newAccount.ShippingPostalCode = '60532';
        newAccount.ShippingCountry = 'US';
        insert newAccount;

        String censusResponse = QueueableCountyUpdaterLive.TEST_JSON_RESPONSE;
        String ep = QueueableCountyUpdaterLive.BASE_EP+newAccount.ShippingLatitude+'&longitude=' + newAccount.ShippingLongitude + '&format=json';


        MockHttpResponseHandler.SimpleMockResponse getResp =
                new MockHttpResponseHandler.SimpleMockResponse('GET', censusResponse);

        MockHttpResponseHandler mock = new MockHttpResponseHandler();
        System.debug('---> mock ep = ' + ep);
        mock.addResponse(ep, getResp);
        Test.setMock(HttpCalloutMock.class, mock);

        System.runAs(uAdmin) {

            Test.startTest();

            //simulate data.com but avoid the triggers since we can't chain queueables in unit test code.
            QueueableMuniUpdater.doChainJob = false;
            newAccount.ShippingLatitude = 42.795778000000000;
            newAccount.ShippingLongitude = -87.075013000000000;
            update newAccount;

            QueueableCountyUpdaterLive q = new QueueableCountyUpdaterLive(new Set<Id>{newAccount.Id},false);
            System.enqueueJob(q);

            Test.stopTest();

            newAccount = [SELECT Id, County_LU__c, Covid_Region_LU__c,County_LU_Auto_Update__c FROM Account WHERE Id = :newAccount.Id];
            System.assertEquals(county.Id, newAccount.County_LU__c);
            System.assertEquals(region.Id, newAccount.Covid_Region_LU__c);
        }
    }
    @IsTest
    static void test_Queueable_County_Updater_Live_Insert_NoGeoInfo() {

        Region__c region = new Region__c(Name= 'Region 8',State__c = 'IL');
        insert region;
        County__c county = new County__c(Name = 'DuPage',State__c = 'IL', Covaid_Region__c = region.Id);
        insert county;

        Municipality__c municipality = [SELECT Id FROM Municipality__c LIMIT 1][0];
        Account newAccount = TestUtils.buildAccount('Test New Account', municipality.Id,'Accel Account');
        newAccount.ShippingStreet = '4619 Main';
        newAccount.ShippingState = 'IL';  //  Be careful of we implement state / country picklists!
        newAccount.ShippingPostalCode = '60532';
        newAccount.ShippingCountry = 'US';
      //  newAccount.County__c = null;
        newAccount.Covid_Region_LU__c = null;
        insert newAccount;


        System.runAs(uAdmin) {

            Test.startTest();

            QueueableCountyUpdaterLive q = new QueueableCountyUpdaterLive(new Set<Id>{newAccount.Id},false);
            System.enqueueJob(q);

            Test.stopTest();

            newAccount = [SELECT Id, County_LU__c, Covid_Region_LU__c,County_LU_Auto_Update__c FROM Account WHERE Id = :newAccount.Id];
            System.assertEquals(newAccount.County_LU__c, null);
            System.assertEquals(newAccount.Covid_Region_LU__c, null);
        }
    }
}