objects/Account.object
<CustomObject>
    <fields>
        <fullName>Hold_Per_Day_Total_Daily__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Based on HPD Records of Record type = Daily HPD</description>
        <inlineHelpText>Based on Monthly HPD Data</inlineHelpText>
        <label>Hold Per Day Total (Daily)</label>
        <referenceTo>Hold_Per_Day_Total__c</referenceTo>
        <relationshipLabel>Accounts (Hold Per Day Total (Daily))</relationshipLabel>
        <relationshipName>AccountsForDaily</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Hold_Per_Day_Total__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Based on HPD Records of Record type = Monthly HPD</description>
        <inlineHelpText>Based on Monthly HPD Data</inlineHelpText>
        <label>Hold Per Day Total (Monthly)</label>
        <referenceTo>Hold_Per_Day_Total__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Hold_Per_Day_Total__c.object
<CustomObject>
    <description>Contains calculated information for HPD (currently only monthly)
Rolls up info for both Account(Location) and Municipality Levels (Separated by Record Type).
Fields such as TTM indicate 12 month roll-ups. all other fiels noted appropriated (4 weeks 8 weeks 12 weeks) etc.

Additional record type for future use of Machine exists as well.</description>
    <fields>
        <fullName>Municipality__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Municipality</label>
        <referenceTo>Municipality__c</referenceTo>
        <relationshipLabel>Hold Per Day Totals</relationshipLabel>
        <relationshipName>Hold_Per_Day_Totals</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Hold Per Day Total</label>
    <nameField>
        <displayFormat>HPDT-{000000000}</displayFormat>
        <label>HPD Total #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Hold Per Day Totals</pluralLabel>
    <recordTypes>
        <fullName>Municipality</fullName>
        <active>true</active>
        <label>Municipality</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/HPD_Total_Setting__mdt.object
<CustomObject>
    <description>Contains configurable parameters for HPD Totals Aggregation. (Nightly batch jobs that use SOQL aggregation to rollup data to Hold Per Day Total from Hold Per Data.</description>
    <label>HPD Total Setting</label>
    <pluralLabel>HPD Total Settings</pluralLabel>
</CustomObject>

objects/Municipality__c.object
<CustomObject>
    <fields>
        <fullName>Hold_Per_Day_Total_Daily__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Hold Per Day Total (Daily)</label>
        <referenceTo>Hold_Per_Day_Total__c</referenceTo>
        <relationshipLabel>Municipalities (Hold Per Day Total (Daily))</relationshipLabel>
        <relationshipName>Municipalities1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Hold_Per_Day_Total__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Hold Per Day Totals</label>
        <referenceTo>Hold_Per_Day_Total__c</referenceTo>
        <relationshipLabel>Municipalities</relationshipLabel>
        <relationshipName>Municipalities</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Municipality</label>
    <nameField>
        <label>Municipality Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Municipalities</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/BatchHpdInitAndLinkMuniRecs.cls
/**
 * Inits zero valued hpd total monthly and daily records and then puts a link on the account record back
 * to this records. (does this so future processes can be mere updates rather then upsert / insert.
 */
global class BatchHpdInitAndLinkMuniRecs  implements Database.Batchable<Sobject>, Database.Stateful {

    global HPD_Total_Setting__mdt hpdTotalSetting;
    global Integer iNumMonthlyHpdtsInserted = 0;
    global Integer iNumDailyHpdtsInserted = 0;
    global Integer iTotalInserted = 0;
    global Integer iNumMonthlyHpdtsUpdated = 0;
    global Integer iNumDailyHpdtsUpdated = 0;
    global Integer iTotalUpdated = 0;
    global Integer iNumMunis = 0;

    global String formattedLocalStartTimeString;
    global String formattedLocalEndTimeString;

    global BatchHpdInitAndLinkMuniRecs() {
        formattedLocalStartTimeString = DateTime.now().format();
    }
    global database.querylocator start(Database.BatchableContext bc) {
        hpdTotalSetting = CustomMetadataSvc.retrieveHpdTotalSettingsMeta(HpdSvc.MUNICIPALITY_AGGREGATION_DEVNAME);

        return Database.getQueryLocator([
                SELECT  Id,Hold_Per_Day_Total__c, Hold_Per_Day_Total_Daily__c
                FROM    Municipality__c
        ]);
    }
    /**
     *
     *
     * @param bc
     * @param scope
     */
    global void execute(Database.BatchableContext bc, List<Municipality__c> scope) {
        iNumMunis += scope.size();
        Map<String,Object> mReturn = HpdStatsHelper.initHpdMunicipalityTotalRecs(scope);
      //  iNumDailyHpdtsInserted += (Integer)mReturn.get('NUM_DAILY_INSERTED');
        iNumMonthlyHpdtsInserted += (Integer)mReturn.get('NUM_MONTHLY_INSERTED');
      //  List<Municipality__c> dailyMuniUpdates = HpdStatsHelper.linkMunicipalityWithHpd(scope,'Daily');
        List<Municipality__c> monthlyMuniUpdates = HpdStatsHelper.linkMunicipalityWithHpd(scope,'Monthly');
       // iNumDailyHpdtsUpdated += dailyMuniUpdates.size();
        iNumMonthlyHpdtsUpdated += monthlyMuniUpdates.size();
    }
    global void finish(Database.BatchableContext bc) {
        formattedLocalEndTimeString = DateTime.now().format();
        iTotalInserted = iNumMonthlyHpdtsInserted + iNumDailyHpdtsInserted;
        iTotalUpdated = iNumMonthlyHpdtsUpdated + iNumDailyHpdtsUpdated;

        String subject = 'Accel SFDC Batch HPD Init and link for Municipality Automation process complete! ';
        String msg = '<br/>If you are receiving this email,it is because your email address was added to the HPD_Total_Setting__mdt as a valid address to receive debug emails for this job.<br/>';
        msg += '<br/>Start Time:<b> ' + formattedLocalStartTimeString + '</b>';
        msg += '<br/>End Time:<b> ' + formattedLocalEndTimeString + '</b><br/>';
        msg += '<br/># of Munis Processed:<b> ' + iNumMunis + '</b></br>';
       // msg += '<br/># of Daily Muni Hpds inserted:<b> ' + iNumDailyHpdtsInserted + '</b></br>';
        msg += '<br/># of Monthly Muni Hpds inserted:<b> ' + iNumMonthlyHpdtsInserted+ '</b></br>';
        msg += '<br/># of Hold Per Day Totals inserted for Munis:<b> ' + iTotalInserted + '</b></br>';
       // msg += '<br/># of Daily Muni Hpds linked:<b> ' + iNumDailyHpdtsUpdated + '</b></br>';
        msg += '<br/># of Monthly Muni Hpds linked:<b> ' + iNumMonthlyHpdtsUpdated+ '</b></br>';
        msg += '<br/># of Hold Per Day Totals linked to for Munis:<b> ' + iTotalUpdated+ '</b></br>';

        List<String> emailAddys = EmailSvc.getHpdEmailNotificationAddys(HpdSvc.MUNICIPALITY_AGGREGATION_DEVNAME);
        String body = msg;
        EmailSvc.sendEmail(emailAddys,subject,body);
    }
}