objects/Account.object
<CustomObject>
    <fields>
        <fullName>Priority__c</fullName>
        <label>Priority</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Account_Priority</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Site_Grade__c</fullName>
        <label>Site Grade</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Case.object
<CustomObject>
    <fields>
        <fullName>Accel_Solution__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Replacement for Solution Picklist</description>
        <label>Solution</label>
        <referenceTo>Solution__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Caller_Phone__c</fullName>
        <description>Replacement for Caller Information so we can have clickable phone number.</description>
        <label>Caller Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Service_Category__c</fullName>
        <label>Service Category</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>All Games Down</fullName>
                </value>
                <value>
                    <fullName>Amusement</fullName>
                </value>
                <value>
                    <fullName>COAM</fullName>
                </value>
                <value>
                    <fullName>Customer</fullName>
                    <label>Customer Complaint / Ticket Issue</label>
                </value>
                <value>
                    <fullName>Marketing</fullName>
                </value>
                <value>
                    <fullName>Multiple VGTs</fullName>
                </value>
                <value>
                    <fullName>RT (Backup RT Available)</fullName>
                </value>
                <value>
                    <fullName>RT (No Backup RT)</fullName>
                </value>
                <value>
                    <fullName>Standalone ATM</fullName>
                </value>
                <value>
                    <fullName>VGT</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Jukebox</fullName>
                </value>
                <value>
                    <fullName>Wellness</fullName>
                </value>
                <value>
                    <fullName>Maintenance</fullName>
                    <isActive>false</isActive>
                    <label>Maintenance</label>
                </value>
                <value>
                    <fullName>RT</fullName>
                    <isActive>false</isActive>
                    <label>RT</label>
                </value>
                <value>
                    <fullName>RT / Customer</fullName>
                    <isActive>false</isActive>
                    <label>RT / Customer</label>
                </value>
                <value>
                    <fullName>SGI</fullName>
                    <isActive>false</isActive>
                    <label>SGI</label>
                </value>
                <value>
                    <fullName>Service Category</fullName>
                    <isActive>false</isActive>
                    <label>Service Category</label>
                </value>
                <value>
                    <fullName>Tablet</fullName>
                    <isActive>false</isActive>
                    <label>Tablet</label>
                </value>
                <value>
                    <fullName>UpShow</fullName>
                    <isActive>false</isActive>
                    <label>UpShow</label>
                </value>
                <value>
                    <fullName>Upgrade Appointment</fullName>
                    <isActive>false</isActive>
                    <label>Upgrade Appointment</label>
                </value>
                <value>
                    <fullName>VGT / RT</fullName>
                    <isActive>false</isActive>
                    <label>VGT / RT</label>
                </value>
                <value>
                    <fullName>VGT / RT / Amusement</fullName>
                    <isActive>false</isActive>
                    <label>VGT / RT / Amusement</label>
                </value>
                <value>
                    <fullName>VGT / SGI</fullName>
                    <isActive>false</isActive>
                    <label>VGT / SGI</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Solution__c</fullName>
        <label>Solution</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Adjusted part</fullName>
                </value>
                <value>
                    <fullName>Adjusted volume</fullName>
                </value>
                <value>
                    <fullName>Assessed the damages and reported information to superiors</fullName>
                </value>
                <value>
                    <fullName>ATM feature not enabled</fullName>
                </value>
                <value>
                    <fullName>Cash drawer refill process</fullName>
                </value>
                <value>
                    <fullName>Changed cash can / reject bin</fullName>
                </value>
                <value>
                    <fullName>Changed comm port</fullName>
                </value>
                <value>
                    <fullName>Cleaned part</fullName>
                </value>
                <value>
                    <fullName>Cleared cmos</fullName>
                </value>
                <value>
                    <fullName>Cleared jam</fullName>
                </value>
                <value>
                    <fullName>Cleared pending transaction</fullName>
                </value>
                <value>
                    <fullName>Delivered amusement equipment</fullName>
                </value>
                <value>
                    <fullName>Delivered hand pay bag</fullName>
                </value>
                <value>
                    <fullName>Enabled payout parameter</fullName>
                </value>
                <value>
                    <fullName>Enabled validation code manually</fullName>
                </value>
                <value>
                    <fullName>Exited game</fullName>
                </value>
                <value>
                    <fullName>Flashed bill acceptor</fullName>
                </value>
                <value>
                    <fullName>Informed location rm of issue</fullName>
                </value>
                <value>
                    <fullName>Installed nrt patch</fullName>
                </value>
                <value>
                    <fullName>Issued facility pay form</fullName>
                </value>
                <value>
                    <fullName>Issue resolved itself</fullName>
                </value>
                <value>
                    <fullName>Liquor license not in effect</fullName>
                </value>
                <value>
                    <fullName>Machine pending agent appt</fullName>
                </value>
                <value>
                    <fullName>Mass outage</fullName>
                </value>
                <value>
                    <fullName>Move amusement equipment</fullName>
                </value>
                <value>
                    <fullName>No issue</fullName>
                </value>
                <value>
                    <fullName>Open &amp; closed all doors</fullName>
                </value>
                <value>
                    <fullName>Powered machine up</fullName>
                </value>
                <value>
                    <fullName>Provided login info to location</fullName>
                </value>
                <value>
                    <fullName>Provided rm info to location</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/ServiceAppointment.object
<CustomObject>
    <fields>
        <fullName>Accel_Solution__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Solution</label>
        <referenceTo>Solution__c</referenceTo>
        <relationshipLabel>Service Appointments</relationshipLabel>
        <relationshipName>Service_Appointments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Location_Priority__c</fullName>
        <description>Pulled from the work order</description>
        <label>Location Priority</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>HIGH PRIORITY</fullName>
                </value>
                <value>
                    <fullName>MEDIUM PRIORITY</fullName>
                </value>
                <value>
                    <fullName>LOW PRIORITY</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Priority__c</fullName>
        <formula>Text(Account.Priority__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Priority</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service_Category__c</fullName>
        <description>Currently not restricting picklist to avoid lack of communication errors and inability to create a SA.. (Case.Service_Category__c should probably be a global PL)</description>
        <label>Service Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Amusement</fullName>
                </value>
                <value>
                    <fullName>Customer</fullName>
                </value>
                <value>
                    <fullName>Maintenance</fullName>
                </value>
                <value>
                    <fullName>Marketing</fullName>
                </value>
                <value>
                    <fullName>RT</fullName>
                </value>
                <value>
                    <fullName>SGI</fullName>
                </value>
                <value>
                    <fullName>Standalone ATM</fullName>
                </value>
                <value>
                    <fullName>Sweepstakes</fullName>
                </value>
                <value>
                    <fullName>Upgrade Appointment</fullName>
                </value>
                <value>
                    <fullName>VGT</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Solution__c</fullName>
        <label>Solution</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Solution</valueSetName>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Service</fullName>
        <active>true</active>
        <label>Service</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Solution__c.object
<CustomObject>
    <description>Used for Lookup field reference as replacement for Solution picklist on Case, WorkOrder, And Service Appointment. Generally Trigger Maintained and synced (one way) ie copies value to corresponding Solution__c picklist value on Case, WorkOrder, ServiceAppointment as it was said that would cause too much reporting rewrite overhead.</description>
    <label>Accel Solution</label>
    <nameField>
        <label>Solution Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Solutions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/WorkOrder.object
<CustomObject>
    <fields>
        <fullName>Accel_Solution__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Replacement for Solution Picklist</description>
        <label>Solution</label>
        <referenceTo>Solution__c</referenceTo>
        <relationshipLabel>Work Orders</relationshipLabel>
        <relationshipName>Work_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Caller_Phone__c</fullName>
        <description>Added to replace legacy Caller Information field to allow for clickable phone numbers.</description>
        <label>Caller Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Location_Priority__c</fullName>
        <description>Meant for display on the mobile uses Location Priority value... app.. ie. A=&gt; High B =&gt; Medium C =&gt; Low</description>
        <label>Location Priority</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>HIGH PRIORITY</fullName>
                </value>
                <value>
                    <fullName>MEDIUM PRIORITY</fullName>
                </value>
                <value>
                    <fullName>LOW PRIORITY</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Site_Grade__c</fullName>
        <label>Site Grade</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>A</fullName>
                </value>
                <value>
                    <fullName>B</fullName>
                </value>
                <value>
                    <fullName>C</fullName>
                </value>
                <value>
                    <fullName>D</fullName>
                </value>
                <value>
                    <fullName>F</fullName>
                </value>
                <value>
                    <fullName>N/A( Location Closed)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Solution__c</fullName>
        <label>Solution</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Solution</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

globalValueSets/Account_Priority.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>AAA</fullName>
    </customValue>
    <customValue>
        <fullName>AA</fullName>
    </customValue>
    <customValue>
        <fullName>A</fullName>
    </customValue>
    <customValue>
        <fullName>B</fullName>
    </customValue>
    <customValue>
        <fullName>C</fullName>
    </customValue>
    <customValue>
        <fullName>D</fullName>
    </customValue>
    <masterLabel>Account Priority</masterLabel>
</GlobalValueSet>

globalValueSets/Solution.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Adjusted part</fullName>
    </customValue>
    <customValue>
        <fullName>Adjusted volume</fullName>
    </customValue>
    <customValue>
        <fullName>Assessed the damages and reported information to superiors</fullName>
    </customValue>
    <customValue>
        <fullName>ATM feature not enabled</fullName>
    </customValue>
    <customValue>
        <fullName>Cash drawer refill process</fullName>
    </customValue>
    <customValue>
        <fullName>Changed cash can / reject bin</fullName>
    </customValue>
    <customValue>
        <fullName>Changed comm port</fullName>
    </customValue>
    <customValue>
        <fullName>Cleaned part</fullName>
    </customValue>
    <customValue>
        <fullName>Cleared cmos</fullName>
    </customValue>
    <customValue>
        <fullName>Cleared jam</fullName>
    </customValue>
    <customValue>
        <fullName>Cleared pending transaction</fullName>
    </customValue>
    <customValue>
        <fullName>Delivered amusement equipment</fullName>
    </customValue>
    <customValue>
        <fullName>Delivered hand pay bag</fullName>
    </customValue>
    <customValue>
        <fullName>Enabled payout parameter</fullName>
    </customValue>
    <customValue>
        <fullName>Enabled validation code manually</fullName>
    </customValue>
    <customValue>
        <fullName>Exited game</fullName>
    </customValue>
    <customValue>
        <fullName>Flashed bill acceptor</fullName>
    </customValue>
    <customValue>
        <fullName>Informed location rm of issue</fullName>
    </customValue>
    <customValue>
        <fullName>Installed nrt patch</fullName>
    </customValue>
    <customValue>
        <fullName>Issued facility pay form</fullName>
    </customValue>
    <customValue>
        <fullName>Issue resolved itself</fullName>
    </customValue>
    <customValue>
        <fullName>Liquor license not in effect</fullName>
    </customValue>
    <customValue>
        <fullName>Machine pending agent appt</fullName>
    </customValue>
    <customValue>
        <fullName>Mass outage</fullName>
    </customValue>
    <customValue>
        <fullName>Move amusement equipment</fullName>
    </customValue>
    <customValue>
        <fullName>No issue</fullName>
    </customValue>
    <customValue>
        <fullName>Open &amp; closed all doors</fullName>
    </customValue>
    <customValue>
        <fullName>Powered machine up</fullName>
    </customValue>
    <customValue>
        <fullName>Provided login info to location</fullName>
    </customValue>
    <customValue>
        <fullName>Provided rm info to location</fullName>
    </customValue>
    <masterLabel>Solution</masterLabel>
</GlobalValueSet>

classes/TEST_WorkOrderTrigger.cls
@isTest
private class TEST_WorkOrderTrigger {

    public static String ADMINUNAME         = 'acceltestadmin@accel.com';
    public static String CALLCENTERUNAME    = 'callcenterdude@dude.com';

    public static  User uCallCenter = TestUtils.getUserForTest( CALLCENTERUNAME );
    public static  User uAdmin      = TestUtils.getUserForTest( ADMINUNAME );

    static {
        List<Profile> profiles = [SELECT Id from Profile where Name in :SvcWatchdogController.noAssignedResourceProfileNames];
        uCallCenter.profileId = profiles[0].id;
        update uCallCenter;
    }

    /**
     * Builds munis, accounts, work types, assets, operating hours, service territories, cases, work orders, and
     * ties them all together.
     */
    @testSetup static void setup() {
        System.runAs(uCallCenter) {
            Test.startTest();  //merely to reset gov limits to get around cpu time
            TestSvcAppointmentDataParams params = new TestSvcAppointmentDataParams();
            TestUtils.createAllDataToServiceAppointments( params );
            Test.stopTest();
        }
    }
    /**
     * Test an insert of a WorkOrder. Note Process Builder will be fired causing an update. Generally this test is to
     * ensure that there is a field visible to service on the mobile app.
     *
     * --(1)-- Tests that when an account is set to Priority A. .WorkOrder.Location_Priority__c is High.
     * --(2)-- Tests that when an account is set to a non supported value ie.  'D' WorkOrder.Location__Priority__c is null.
     */
    @IsTest static void test_WorkOrderInsert_LocationPriority_Positive() {

        TestSvcAppointmentDataParams params = new TestSvcAppointmentDataParams();
        System.runAs(uAdmin) {

            List<Account> accounts = [SELECT Id, Priority__c FROM Account];
            for(Account account : accounts) {
                account.Priority__c = 'A';
            }
            update accounts;

            Id workOrderRtId = Schema.getGlobalDescribe().get('WorkOrder').getDescribe().getRecordTypeInfosByDeveloperName()
                    .get(params.workOrderRecordTypeName).getRecordTypeId();

            List<ServiceTerritory> serviceTerritories = [SELECT Id from ServiceTerritory];
            //---------- CREATE WORK ORDERS
            List<WorkOrder> workOrders = new List<WorkOrder>();
            List<Case > cases = [SELECT Id, AccountId FROM Case ] ;

            for (Case cse : cases) {
                for (Integer i = 0; i < params.iNumWorkOrdersPerCase; i++) {
                    WorkOrder workOrder = new WorkOrder();
                    workOrder.AccountId = cse.AccountId;
                    workOrder.CaseId = cse.id;
                    workOrder.RecordTypeId = workOrderRtId;
                  //  workOrder.Priority = 'A'; --- process will overwrite this anyway so n/a
                    workOrder.Status = params.workOrderStatus;
                    workOrder.Site_Grade__c = params.workOrderSiteGrade;
                    workOrder.ServiceTerritoryId = serviceTerritories[0].Id;
                    workOrders.add(workOrder);
                }
            }
            Test.startTest();

            insert workOrders;
            workOrders = [SELECT Id, Location_Priority__c,Priority FROM WorkOrder WHERE Id In :workOrders];
            //  TEST (1)
            for(WorkOrder wo : workOrders) {
                System.assertEquals(wo.Location_Priority__c, WorkOrderTriggerHandler.mPriorityTranslation.get('A'));
                wo.Priority = 'D'; // set priority to a non  supported value now so we can test a negative case.
            }
            update workOrders;
            workOrders = [SELECT Id, Location_Priority__c,Priority FROM WorkOrder WHERE Id In :workOrders];

            // TEST (2)
            for(WorkOrder wo : workOrders) {
                System.assertEquals(wo.Location_Priority__c, null);
            }

            Test.stopTest();
        }
    }
    /**
     * --(1)-- Test an insert of a ServiceAppointment. Ensure it's Solution__c (PL) Matches Accel_Solution__c (Lookup)
     */
    @isTest static void test_WorkOrderInsert_Solution_Positive() {
        TestSvcAppointmentDataParams params = new TestSvcAppointmentDataParams();
        Map<Id,Solution__c> mAccelSolutionsByIds = new Map<Id,Solution__c>( [SELECT Id, Name FROM Solution__c] );
        Solution__c solution;
        //just grab one.
        for(Solution__c sol : mAccelSolutionsByIds.values()) {
            solution = sol;
            break;
        }
        System.runAs(uAdmin) {

            List<Account> accounts = [SELECT Id, Priority__c FROM Account];
            for(Account account : accounts) {
                account.Priority__c = 'A';
            }
            update accounts;

            Id workOrderRtId = Schema.getGlobalDescribe().get('WorkOrder').getDescribe().getRecordTypeInfosByDeveloperName()
                    .get(params.workOrderRecordTypeName).getRecordTypeId();

            List<ServiceTerritory> serviceTerritories = [SELECT Id from ServiceTerritory];
            //---------- CREATE WORK ORDERS
            List<WorkOrder> workOrders = new List<WorkOrder>();
            List<Case > cases = [SELECT Id, AccountId FROM Case ] ;

            for (Case cse : cases) {
                for (Integer i = 0; i < params.iNumWorkOrdersPerCase; i++) {
                    WorkOrder workOrder = new WorkOrder();
                    workOrder.AccountId = cse.AccountId;
                    workOrder.CaseId = cse.id;
                    workOrder.RecordTypeId = workOrderRtId;
                    //  workOrder.Priority = 'A'; --- process will overwrite this anyway so n/a
                    workOrder.Status = params.workOrderStatus;
                    workOrder.Site_Grade__c = params.workOrderSiteGrade;
                    workOrder.ServiceTerritoryId = serviceTerritories[0].Id;
                    workOrder.Accel_Solution__c =  solution.id;
                    workOrders.add(workOrder);
                }
            }
            Test.startTest();

            insert workOrders;
            workOrders = [SELECT Id, Solution__c, Accel_Solution__r.Name FROM WorkOrder limit 12];

            for(WorkOrder wo : workOrders) {
                System.assertEquals(wo.Solution__c, wo.Accel_Solution__r.Name);
            }

            Test.stopTest();
        }
    }
    /**
     * --(1)-- Test an update of a WorkOrder. Ensure it's Solution__c (PL) Matches Accel_Solution__c (Lookup)
     */
    @isTest static void test_WorkOrderUpdate_Solution_Positive() {

        System.runAs(uAdmin) {

            List<WorkOrder> workOrders = [SELECT Id, Accel_Solution__c, Solution__C FROM WorkOrder LIMIT 12];
            Map<Id, Solution__c> mSolutionsByIds = new Map<Id, Solution__c> ([
                    SELECT  Id,Name
                    FROM    Solution__c
            ]);
            Solution__c solution;
            //just grab one.
            for(Solution__c sol : mSolutionsByIds.values()) {
                solution = sol;
                break;
            }
            for(WorkOrder wo : workOrders) {
                wo.Accel_Solution__c = solution.Id;
            }
            Test.startTest();

            update workOrders;
            workOrders = [SELECT Id, Accel_Solution__r.Name, Solution__C FROM WorkOrder LIMIT 12];
            for( WorkOrder wo : workOrders) {
                System.assertEquals(wo.Accel_Solution__r.Name, wo.Solution__c);
            }

            Test.stopTest();
        }
    }
   /**
    * --(1)-- Test an insert of a WorkOrder. Ensure it's WorkOrder caller phone equals it's parent Case
    * caller phone if they left it null on creation of the WO and it's parent case has a value.
    */
    @isTest static void test_WorkOrderInsert_Positive() {
        String testPhone = '630-310-0898';
        TestSvcAppointmentDataParams params = new TestSvcAppointmentDataParams();
        System.runAs(uAdmin) {

            Set<Id> caseIds = new Set<Id>();
            List<Case> cases = [    SELECT  Id, AccountId, Service_Category__c
                                    FROM    Case];
            for(Case cse : cases) {
                cse.Caller_Phone__c = testPhone;
                caseIds.add(cse.Id);
            }
            update cases;

            Id workOrderRtId = Schema.getGlobalDescribe().get('WorkOrder').getDescribe().getRecordTypeInfosByDeveloperName()
                    .get(params.workOrderRecordTypeName).getRecordTypeId();

            List<ServiceTerritory> serviceTerritories = [SELECT Id from ServiceTerritory];
            //---------- CREATE WORK ORDERS
            List<WorkOrder> workOrders = new List<WorkOrder>();

            for (Case cse : cases) {
                for (Integer i = 0; i < params.iNumWorkOrdersPerCase; i++) {
                    WorkOrder workOrder = new WorkOrder();
                    workOrder.AccountId = cse.AccountId;
                    workOrder.CaseId = cse.id;
                    workOrder.RecordTypeId = workOrderRtId;
                    //@TODO play the asset game.
//                    workOrder.AssetId = accountAssets[0].Id;
                    workOrder.Status = params.workOrderStatus;
                    workOrder.Site_Grade__c = params.workOrderSiteGrade;
                    workOrder.ServiceTerritoryId = serviceTerritories[0].Id;
                    workOrders.add(workOrder);
                }
            }
            Test.startTest();

            insert workOrders;
            workOrders = [SELECT Id, Caller_Phone__c,Case.Caller_Phone__c FROM WorkOrder where CaseId = :caseIds limit 12];
            //--(1)-- all ServiceAppointment.Service_Category__c matches their parent case Service_Category__c.
            for(WorkOrder wo : workOrders) {
                System.assertEquals(wo.Caller_Phone__c, wo.Case.Caller_Phone__c);
            }
            Test.stopTest();
        }
    }
    /**
     * --(1)-- Test an Update of a WorkOrder. Ensure it's parent cases caller phone equals it's parent Case caller phone
     * if it changed update update.
     */
    @isTest static void test_WorkOrderUpdate_CasePhone_Positive() {

        String testPhone = '666-666-6666';
        TestSvcAppointmentDataParams params = new TestSvcAppointmentDataParams();

        System.runAs(uCallCenter) {
            //create new work orders just use existing cases.
            Set<Id> caseIds = new Set<Id>();
            List<Case> cases = [    SELECT  Id, AccountId, Caller_Phone__c
                                    FROM    Case
            ];
            for(Case cse : cases) {
                cse.Caller_Phone__c = testPhone;
                caseIds.add(cse.Id);
            }
            update cases;

            Id workOrderRtId = Schema.getGlobalDescribe().get('WorkOrder').getDescribe().getRecordTypeInfosByDeveloperName()
                    .get(params.workOrderRecordTypeName).getRecordTypeId();

            List<ServiceTerritory> serviceTerritories = [SELECT Id from ServiceTerritory];
            //---------- CREATE WORK ORDERS
            List<WorkOrder> workOrders = new List<WorkOrder>();

            for (Case cse : cases) {
                for (Integer i = 0; i < params.iNumWorkOrdersPerCase; i++) {
                    WorkOrder workOrder = new WorkOrder();
                    workOrder.AccountId = cse.AccountId;
                    workOrder.CaseId = cse.id;
                    workOrder.RecordTypeId = workOrderRtId;
                    //@TODO play the asset game.
//                    workOrder.AssetId = accountAssets[0].Id;
                    workOrder.Status = params.workOrderStatus;
                    workOrder.Site_Grade__c = params.workOrderSiteGrade;
                    workOrder.ServiceTerritoryId = serviceTerritories[0].Id;
                    workOrders.add(workOrder);
                }
            }
            insert workOrders;

            Test.startTest();

            workOrders = [
                    SELECT  Id, Caller_Phone__c,Case.Caller_Phone__c
                    FROM    WorkOrder
                    WHERE   Id IN :workOrders
            ];
            for(WorkOrder wo : workOrders) {
                wo.Caller_Phone__c = testPhone;
            }
            update workOrders;
            //--(1)-- all Case Caller phones eq this work order caller phone.
            for(WorkOrder wo : workOrders) {
                System.assertEquals(wo.Caller_Phone__c, wo.Case.Caller_Phone__c);
            }
            Test.stopTest();
        }
    }
    /**
     *
     */
    @isTest static void test_WorkOrderUpdate_CaseAccelSolution_Positive() {

        TestSvcAppointmentDataParams params = new TestSvcAppointmentDataParams();
        params.iNumWorkOrdersPerCase = 2;

        Map<Id, Solution__c> mSolutionsByIds = new Map<Id, Solution__c> ([
                SELECT  Id,Name
                FROM    Solution__c
        ]);
        Solution__c solution;
        //just grab one.
        for(Solution__c sol : mSolutionsByIds.values()) {
            solution = sol;
            break;
        }

        System.runAs(uCallCenter) {
            //create new work orders just use existing cases.
            Set<Id> caseIds = new Set<Id>();
            List<Case> cases = [    SELECT  Id, AccountId
                                    FROM    Case
                                    LIMIT   2
            ];
            for(Case cse : cases) {
                caseIds.add(cse.Id);
            }
            update cases;

            Id workOrderRtId = Schema.getGlobalDescribe().get('WorkOrder').getDescribe().getRecordTypeInfosByDeveloperName()
                    .get(params.workOrderRecordTypeName).getRecordTypeId();

            List<ServiceTerritory> serviceTerritories = [SELECT Id from ServiceTerritory];
            //---------- CREATE WORK ORDERS
            List<WorkOrder> workOrders = new List<WorkOrder>();

            for (Case cse : cases) {
                for (Integer i = 0; i < params.iNumWorkOrdersPerCase; i++) {
                    WorkOrder workOrder = new WorkOrder();
                    workOrder.AccountId = cse.AccountId;
                    workOrder.CaseId = cse.id;
                    workOrder.RecordTypeId = workOrderRtId;
                    //@TODO play the asset game.
//                    workOrder.AssetId = accountAssets[0].Id;
                    workOrder.Status = params.workOrderStatus;
                    workOrder.Site_Grade__c = params.workOrderSiteGrade;
                    workOrder.ServiceTerritoryId = serviceTerritories[0].Id;
                    workOrders.add(workOrder);
                }
            }
            insert workOrders;

            Test.startTest();

            workOrders = [
                    SELECT  Id, Status, Accel_Solution__c, CaseId
                    FROM    WorkOrder
                    WHERE   Id IN :workOrders
            ];
            Map<Id,Id> mCaseIdSolutionId = new Map<Id,Id>();
            for(WorkOrder wo : workOrders) {
                wo.Status = 'Completed';
                wo.Accel_Solution__c = solution.Id;
                mCaseIdSolutionId.put(wo.CaseId, wo.Accel_Solution__c);
            }
            update workOrders;
            cases = [SELECT Id, Accel_Solution__c FROM Case where id in :mCaseIdSolutionId.keySet()];
            for(Case cse : cases) {
                System.assertEquals(cse.Accel_Solution__c, mCaseIdSolutionId.get(cse.Id));
            }
            Test.stopTest();
        }
    }
}