objects/Account.object
<CustomObject>
    <fields>
        <fullName>Accel_VGT_Live_Date__c</fullName>
        <label>Accel VGT Live Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Location_Type__c</fullName>
        <label>Accel Establishment Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Accel_Establishment_Type</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

globalValueSets/Accel_Establishment_Type.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Adult Entertainment</fullName>
    </customValue>
    <customValue>
        <fullName>American Legion</fullName>
    </customValue>
    <customValue>
        <fullName>Bar</fullName>
    </customValue>
    <customValue>
        <fullName>Bar &amp; Grill</fullName>
    </customValue>
    <customValue>
        <fullName>Bowling Alley</fullName>
    </customValue>
    <customValue>
        <fullName>C-Store</fullName>
    </customValue>
    <customValue>
        <fullName>C-Store W/O Gas</fullName>
    </customValue>
    <customValue>
        <fullName>Fraternal</fullName>
    </customValue>
    <customValue>
        <fullName>Gaming Parlor</fullName>
    </customValue>
    <customValue>
        <fullName>Golf Course</fullName>
    </customValue>
    <customValue>
        <fullName>Hotel</fullName>
    </customValue>
    <customValue>
        <fullName>Liquor Store</fullName>
    </customValue>
    <customValue>
        <fullName>OTB</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <customValue>
        <fullName>Private Club</fullName>
    </customValue>
    <customValue>
        <fullName>Recreation (Comedy,Billiards)</fullName>
    </customValue>
    <customValue>
        <fullName>Restaurant</fullName>
    </customValue>
    <customValue>
        <fullName>Truck Stop</fullName>
    </customValue>
    <customValue>
        <fullName>VFW</fullName>
    </customValue>
    <customValue>
        <fullName>Grocery Store</fullName>
    </customValue>
    <customValue>
        <fullName>Barber Shop</fullName>
        <isActive>false</isActive>
        <label>Barber Shop</label>
    </customValue>
    <customValue>
        <fullName>Bait Shop</fullName>
        <isActive>false</isActive>
        <label>Bait Shop</label>
    </customValue>
    <customValue>
        <fullName>Lounge</fullName>
        <isActive>false</isActive>
        <label>Lounge</label>
    </customValue>
    <customValue>
        <fullName>Unavailable</fullName>
        <isActive>false</isActive>
        <label>Unavailable</label>
    </customValue>
    <customValue>
        <fullName>C-Store/Liquor Store</fullName>
        <isActive>false</isActive>
        <label>C-Store/Liquor Store</label>
    </customValue>
    <masterLabel>Accel Establishment Type</masterLabel>
</GlobalValueSet>

classes/AdminSvc.cls
/**
 * Created by Zach on 3/21/2019.
 */

public without sharing class AdminSvc {

    //trick here is to use "without sharing" in order to bypass user security for data calculation purposes

    public static List<Account> getClosestAccounts(Id id, String accType) {
        List<Account> accList = new List<Account>();
        List<Account> accAddr = new List<Account>();
        Double lat;
        Double llong;
        accAddr=[select ShippingLatitude, ShippingLongitude from Account where id = :id limit 1];
        lat=accAddr[0].ShippingLatitude;
        llong=accAddr[0].ShippingLongitude;
        Set<String> accountTypes = CustomMetaDataSvc.retrieveCommunityAccountTypes();

        accList = [ select  id, name, Location_Type__c, DISTANCE(ShippingAddress, GEOLOCATION(:lat, :llong), 'mi') dist
                    from    Account
                    where   ShippingLatitude != null
                    and     Type  in :accountTypes
                    and     Accel_VGT_Live_Date__c != null
                    and     id != :id
                    and     Location_Type__c = :accType
                    order by DISTANCE(ShippingAddress, GEOLOCATION(:lat, :llong), 'mi') ASC limit 10];

        return accList;
    }
}