objects/Account.object
<CustomObject>
    <fields>
        <fullName>Date__c</fullName>
        <formula>TODAY()</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Hold_Per_Day__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Holds Per Day</relationshipLabel>
        <relationshipName>Holds_Per_Day</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Funds_In__c</fullName>
        <label>Funds In</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Location_Share__c</fullName>
        <formula>IF(Date__c &gt;= DATE(2020,7,1), ( Funds_In__c -  Funds_Out__c ) *0.3257, (IF(Date__c &gt;= DATE(2019,7,1), ( Funds_In__c -  Funds_Out__c ) *0.3314, ( Funds_In__c -  Funds_Out__c ) *0.3464)))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Location Share</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>NTI__c</fullName>
        <label>NTI</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Position__c</fullName>
        <label>Position</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Hold Per Day</label>
    <nameField>
        <displayFormat>HPD-{000000000}</displayFormat>
        <label>Hold Per Day Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Holds Per Day</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/HPD_Total_Setting__mdt.object
<CustomObject>
    <description>Contains configurable parameters for HPD Totals Aggregation. (Nightly batch jobs that use SOQL aggregation to rollup data to Hold Per Day Total from Hold Per Data.</description>
    <fields>
        <fullName>HPD_Account_Types__c</fullName>
        <defaultValue>&quot;Accel Account,Competitor Account&quot;</defaultValue>
        <label>HPD Account Types</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>HPD Total Setting</label>
    <pluralLabel>HPD Total Settings</pluralLabel>
</CustomObject>

classes/Accel_CommunityHpdController.cls
public with sharing class Accel_CommunityHpdController {

    public static final String MAP_KEY_HPD_LIST         = 'HPD_LIST';
    public static final String MAP_KEY_ACCOUNT_LIST     = 'ACCOUNT_LIST';

    @AuraEnabled
    public static ResponseDto retrieveAccounts() {
        ResponseDto dto = new ResponseDto();
        HPD_Total_Setting__mdt hpdTotalSetting = CustomMetadataSvc.retrieveHpdTotalSettingsMeta(HpdSvc.ACCT_AGGREGATION_DEVNAME);
        List<String> accountTypes = hpdTotalSetting.HPD_Account_Types__c.split(',');
        List<Account> accounts =  [select   id,Name,ShippingCity
                                    from    account
                                    where  type in :accountTypes
                                    order  by name ASC
                                    limit 500];
        dto.isSuccess = true;
        dto.values.put(MAP_KEY_ACCOUNT_LIST,accounts);
        return dto;
    }

    /**
     *
     *
     * @param accountIds
     *
     * @return DTO  with the HPD List.
     */
    @AuraEnabled
    public static ResponseDto retrieveAccountHpds(Id accountId) {
        Integer iLimitRows = 2000;
        List<Hold_Per_Day__c> hpds = new List<Hold_Per_Day__c>();
        ResponseDto dto = new ResponseDto();
        try {
            hpds = [SELECT  id, account__c,Position__c,
                            Date__c,NTI__c,Funds_In__c,Location_Share__c
                    FROM    Hold_Per_Day__c
                    WHERE   account__c = :accountId
                    and     RecordType.Name = 'Daily HPD'
                    ORDER BY Date__c DESC
                    LIMIT   :iLimitRows ];
            dto.isSuccess = true;
        } catch (Exception e) {
            dto.severity = 'error';
            dto.message = e.getMessage();
            dto.technicalMsg = e.getStackTraceString();
        }
        dto.values.put(MAP_KEY_HPD_LIST, hpds);
        return dto;
    }
}