objects/Account.object
<CustomObject>
    <fields>
        <fullName>County_Auto_Updated__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates the the County__c was auto updated with FCC (Federal Communication Commission) API Data. https://geo.fcc.gov/api/census/#!/block/get_block_find</description>
        <inlineHelpText>Indicates that the County__c was auto updated with FCC (Federal Communication Commission) API Data.</inlineHelpText>
        <label>County Auto Updated</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>County__c</fullName>
        <description>This will be updated about 1-2 minutes after a new account is created or account has changed if there is accurate enough physical location information to determine the county.</description>
        <inlineHelpText>This will be updated about 1-2 minutes after a new account is created or account has changed if there is accurate enough physical location information to determine the county.</inlineHelpText>
        <label>County (TEXT)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/County__c.object
<CustomObject>
    <description>Holds all County related info for states that Accel does gaming business with.</description>
    <label>County</label>
    <nameField>
        <label>County Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Counties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Google_Setting__mdt.object
<CustomObject>
    <description>Settings that contain data about google endpoints</description>
    <fields>
        <fullName>Http_Method__c</fullName>
        <defaultValue>&quot;GET&quot;</defaultValue>
        <description>ie. POST,PUT,GET etc</description>
        <inlineHelpText>ie. POST,PUT,GET etc</inlineHelpText>
        <label>Http Method</label>
        <length>16</length>
        <type>Text</type>
    </fields>
    <label>Google Setting</label>
    <pluralLabel>Google Settings</pluralLabel>
</CustomObject>

objects/Municipality__c.object
<CustomObject>
    <label>Municipality</label>
    <nameField>
        <label>Municipality Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Municipalities</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/TEST_QueueableMuniSample.cls
@IsTest
private class TEST_QueueableMuniSample {

    public static String ADMINUNAME = 'acceltestadmin@accel.com';
    public static User uAdmin = TestUtils.getUserForTest(ADMINUNAME);

    @testSetup
    static void setup() {

        System.runAs(uAdmin) {
            Test.startTest();

            List<Municipality__c> munis = TestUtils.createMunicipalities('Carol Stream', 1);
            for(Municipality__c muni : munis) {
                muni.Name = muni.Name.replace('0','');
            }
            update munis;

            Account account = TestUtils.buildAccount('account name', munis[0].id);
            account.ShippingStreet = '4916 Main Street Unit 2';
            account.ShippingCity = 'Lisle';
            account.ShippingState = 'IL';  //  Be careful of we implement state / country picklists!
            account.ShippingPostalCode = '60532';
            account.ShippingCountry = 'US';
            account.ShippingLatitude = 41.795778000000000;
            account.ShippingLongitude = -88.075013000000000;
            account.County_Auto_Updated__c = true;
            insert account;

            Test.stopTest();
        }
    }

    @IsTest
    static void test_Queueable_County_Updater_Insert_Positive() {
        Account account = [SELECT Id,  County_Auto_Updated__c,ShippingLatitude,ShippingLongitude FROM Account WHERE ShippingStreet = '4916 Main Street Unit 2'];

       // Account account = [SELECT Id, County__c, County_Auto_Updated__c,ShippingLatitude,ShippingLongitude FROM Account WHERE ShippingStreet = '4916 Main Street Unit 2'];

        System.debug('--- acount=' + account);


        String getResponse = TEST_GoogleGeocodeJsonToApex.testJsonValidMuni;
        Google_Setting__mdt mdt = GoogleSvc.queryForMetadata(GoogleTransaction.GEOCODING.name());
        HttpRequest httpRequest = GoogleSvc.initHttpRequest(GoogleTransaction.GEOCODING);

        String ep = httpRequest.getEndpoint() + '&latlng='+account.ShippingLatitude + ',' + account.ShippingLongitude;


        MockHttpResponseHandler.SimpleMockResponse getResp =
                new MockHttpResponseHandler.SimpleMockResponse(mdt.Http_Method__c, getResponse);

        MockHttpResponseHandler mock = new MockHttpResponseHandler();
        System.debug('---> mock ep = ' + ep);
        mock.addResponse(ep, getResp);
        Test.setMock(HttpCalloutMock.class, mock);

        System.runAs(uAdmin) {

            Test.startTest();
            QueueableMuniSample q = new QueueableMuniSample();
            q.performExecute();
            Test.stopTest();
        }
    }

    @IsTest
    static void test_Queueable_Muni_Gmuni_Not_Found() {
        Account account = [SELECT Id,  County_Auto_Updated__c,ShippingLatitude,ShippingLongitude FROM Account WHERE ShippingStreet = '4916 Main Street Unit 2'];

       // Account account = [SELECT Id, County__c, County_Auto_Updated__c,ShippingLatitude,ShippingLongitude FROM Account WHERE ShippingStreet = '4916 Main Street Unit 2'];

        System.debug('--- acount=' + account);


        String getResponse = TEST_GoogleGeocodeJsonToApex.testJsonInValidMuni;
        Google_Setting__mdt mdt = GoogleSvc.queryForMetadata(GoogleTransaction.GEOCODING.name());
        HttpRequest httpRequest = GoogleSvc.initHttpRequest(GoogleTransaction.GEOCODING);

        String ep = httpRequest.getEndpoint() + '&latlng='+account.ShippingLatitude + ',' + account.ShippingLongitude;


        MockHttpResponseHandler.SimpleMockResponse getResp =
                new MockHttpResponseHandler.SimpleMockResponse(mdt.Http_Method__c, getResponse);

        MockHttpResponseHandler mock = new MockHttpResponseHandler();
        System.debug('---> mock ep = ' + ep);
        mock.addResponse(ep, getResp);
        Test.setMock(HttpCalloutMock.class, mock);

        System.runAs(uAdmin) {

            Test.startTest();
            QueueableMuniSample q = new QueueableMuniSample();
            q.performExecute();
            Test.stopTest();
        }
    }
}