objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Location</fullName>
        <active>true</active>
        <label>Location</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Asset.object
<CustomObject>
    <fields>
        <fullName>Model__c</fullName>
        <label>Model</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Cash_Logistics_Automation_Setting__mdt.object
<CustomObject>
    <description>All configurable settings for Cash Logistics - Automation</description>
    <fields>
        <fullName>Email_Template_Dev_Name__c</fullName>
        <description>The Development Name (found in EmailTemplate sObject) associated with the template if email is to be sent. This is required if you turn emails on.</description>
        <inlineHelpText>The Development Name (found in EmailTemplate sObject) associated with the template if email is to be sent. This is required if you turn emails on.</inlineHelpText>
        <label>Email Template Dev Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Public_Group_Dev_Names__c</fullName>
        <description>A Comma Delimited List of Public Group Developer Names to send the email to (used for whoIds)</description>
        <inlineHelpText>A Comma Delimited List of Public Group Developer Names to send the email to (used for whoIds)</inlineHelpText>
        <label>Public Group Dev Names</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Send_Email__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If checked and the applicable automation process sends email, emails will be sent. If not, emails will not be sent. ie. the automation still runs but no emails are sent.</description>
        <inlineHelpText>If checked and the applicable automation process sends email, emails will be sent. If not, emails will not be sent. ie the automation still runs but no emails are sent.</inlineHelpText>
        <label>Send Email</label>
        <type>Checkbox</type>
    </fields>
    <label>Cash Logistics Automation Setting</label>
    <pluralLabel>Cash Logistics Automation Setting</pluralLabel>
</CustomObject>

objects/Cash_Logistics_Region__mdt.object
<CustomObject>
    <description>Region specific settings (processing location) for Cash Logistics</description>
    <fields>
        <fullName>RPS_Email_Public_Group_Dev_Names__c</fullName>
        <label>RPS Email Public Group Dev Names</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Cash Logistics Region Setting</label>
    <pluralLabel>Cash Logistics Regions</pluralLabel>
</CustomObject>

objects/Cash_Logistics_Setting__mdt.object
<CustomObject>
    <description>All Configurable Settings for the Cash Logistics Experience Cloud</description>
    <fields>
        <fullName>Show_Send_Route_End_Email_Menu_Item__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Show Send Route End Email Menu Item</label>
        <type>Checkbox</type>
    </fields>
    <label>Cash Logistics Experience Cloud Setting</label>
    <pluralLabel>Cash Logistics Experience Cloud Settings</pluralLabel>
</CustomObject>

objects/Cash_Logistics_Survey_Setting__mdt.object
<CustomObject>
    <description>Used to config any cash logistics survey / questionnaire.</description>
    <fields>
        <fullName>Field_Api_Name__c</fullName>
        <description>Field field api name for the particular field on the sObject</description>
        <inlineHelpText>Field field api name for the particular field on the sObject</inlineHelpText>
        <label>Field Api Name</label>
        <length>64</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Cash Logistics Survey Setting</label>
    <pluralLabel>Cash Logistics Survey Settings</pluralLabel>
</CustomObject>

objects/Route__c.object
<CustomObject>
    <description>Example object to house routes and routing of collections</description>
    <fields>
        <fullName>Processing_Location__c</fullName>
        <label>Processing Location</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Processing_Location</valueSetName>
        </valueSet>
    </fields>
    <label>Route</label>
    <nameField>
        <label>Route Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Routes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Route_Processing_Sheet__c.object
<CustomObject>
    <description>Example digitization of the route processing sheet</description>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account DBA</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Route Processing Sheets</relationshipLabel>
        <relationshipName>Route_Processing_Sheets</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Cash_Return_Unused__c</fullName>
        <label>Cash Return Unused</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Collection_Type__c</fullName>
        <description>Copied down from the parent Route Schedule Account.</description>
        <inlineHelpText>Copied down from the parent Route Schedule Account.</inlineHelpText>
        <label>Collection Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Collection_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Processing_Location__c</fullName>
        <label>Processing Location</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Processing_Location</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Redemption_Asset__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Redemption Asset</label>
        <referenceTo>Asset</referenceTo>
        <relationshipLabel>Route Processing Sheets</relationshipLabel>
        <relationshipName>Route_Processing_Sheets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Redemption_Type__c</fullName>
        <formula>Account__r.Redemption__r.GP_Manufacturer__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Redemption Type(Obsolete)</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Route_End_Email_Sent_By__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Internal field indicating the user that last send the route end email for this RPS.</description>
        <inlineHelpText>Internal field indicating the user that last send the route end email for this RPS.</inlineHelpText>
        <label>Route End Email Sent By</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Route_Processing_Sheets5</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Route_End_Email_Sent_Date__c</fullName>
        <description>Internal field indicating when the user hit the route send email button.</description>
        <inlineHelpText>Internal field indicating when the user hit the route send email button.</inlineHelpText>
        <label>Route End Email Sent Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Route_Schedule__c</fullName>
        <label>Route Schedule</label>
        <referenceTo>Route_Schedule__c</referenceTo>
        <relationshipLabel>Route Processing Sheets</relationshipLabel>
        <relationshipName>Route_Processing_Sheets</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Collection Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Not Started</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
                <value>
                    <fullName>Skipped</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Stop_Number__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Stop Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_Meter_Readings__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Total Number of Meter Readings Associated with this Route Processing Sheet. (DLRS Maintained). Currently async.. ie runs once an hour on the hour.</description>
        <inlineHelpText>Total Number of Meter Readings Associated with this Route Processing Sheet. (DLRS Maintained) This is refreshed once an hour at the top of the hour</inlineHelpText>
        <label>Total Meter Readings</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Route Processing Sheet</label>
    <nameField>
        <displayFormat>Collection-Id-{000000000}</displayFormat>
        <label>Collection ID Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Route Processing Sheets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Route_Schedule__c.object
<CustomObject>
    <description>Assignment information of a physical route&apos;s locations, collectors, vehicles, and questions for a specific day</description>
    <fields>
        <fullName>Processing_Location__c</fullName>
        <label>Processing Location</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Processing_Location</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Route_End_Email_Sent_By__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Route End Email Sent By</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Route_Schedules7</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Route_End_Email_Sent_Date__c</fullName>
        <label>Route End Email Sent Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Route__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Route to collect</description>
        <label>Route</label>
        <referenceTo>Route__c</referenceTo>
        <relationshipLabel>Route Schedules</relationshipLabel>
        <relationshipName>Route_Schedules</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Total_Meter_Readings__c</fullName>
        <description>The total # of meter readings for all route processing sheets associated with this route schedule.</description>
        <inlineHelpText>The total # of meter readings for all route processing sheets associated with this route schedule.</inlineHelpText>
        <label>Total Meter Readings</label>
        <summarizedField>Route_Processing_Sheet__c.Total_Meter_Readings__c</summarizedField>
        <summaryForeignKey>Route_Processing_Sheet__c.Route_Schedule__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>Route Schedule</label>
    <nameField>
        <label>Route Schedule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Route Schedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>Processing_Location__c</fullName>
        <description>Used for Cash Logistics - When an Route schedule is created, it is assigned to a processing location. This is used to determine, when a user of profile CL - Route Processor logs in, what route schedules they see.</description>
        <inlineHelpText>Used for Cash Logistics - When an Route schedule is created, it is assigned to a processing location. This is used to determine, when a user of profile CL - Route Processor logs in, what route schedules they see.</inlineHelpText>
        <label>Processing Location</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Processing_Location</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

globalValueSets/Collection_Type.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Regular - RT &amp; VGT</fullName>
        <default>true</default>
        <label>Regular - RT &amp; VGT</label>
    </customValue>
    <customValue>
        <fullName>Additional Fill – RT &amp; VGT</fullName>
    </customValue>
    <customValue>
        <fullName>Additional Fill – RT Only</fullName>
    </customValue>
    <customValue>
        <fullName>Additional Fill – VGT Only</fullName>
    </customValue>
    <customValue>
        <fullName>Regular - 2nd RT</fullName>
    </customValue>
    <customValue>
        <fullName>Regular - RT Only</fullName>
    </customValue>
    <customValue>
        <fullName>Regular - VGT Only</fullName>
    </customValue>
    <customValue>
        <fullName>Regular - RT Only (Go Lives/RT swaps)</fullName>
        <isActive>false</isActive>
        <label>Regular - RT Only (Go Lives/RT swaps)</label>
    </customValue>
    <description>* Regular – RT &amp; VGT (typical collection involves changing VGT cans and swapping RT Cassettes)﻿
* Additional Fill – RT Only (this collection involves just changing RT Cassettes)﻿
* Additional Fill – VGT Only (this collection involves just swapping VGT cans)﻿
* Additional Fill – RT &amp; VGT (this collection involves changing VGT cans and swapping RT cassettes)
* Regular - 2nd RT (OLD.. not sure?)
* Regular - RT Only (NEW... not sure?)
* Regular - VGT Only (NEW.. not sure?)</description>
    <masterLabel>Collection Type</masterLabel>
</GlobalValueSet>

globalValueSets/Processing_Location.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Burr Ridge</fullName>
    </customValue>
    <customValue>
        <fullName>DEV TEST 1</fullName>
    </customValue>
    <customValue>
        <fullName>Tinley Park</fullName>
    </customValue>
    <customValue>
        <fullName>Peoria</fullName>
    </customValue>
    <customValue>
        <fullName>Springfield</fullName>
    </customValue>
    <customValue>
        <fullName>CW</fullName>
    </customValue>
    <customValue>
        <fullName>Rockford</fullName>
    </customValue>
    <customValue>
        <fullName>Collinsville</fullName>
    </customValue>
    <masterLabel>Processing Location</masterLabel>
</GlobalValueSet>

classes/clQueueableRpsEmailer.cls
public class clQueueableRpsEmailer implements Queueable{

    //  Various defaults.
    @TestVisible private static String DEFAULT_TEMPLATE_DEV_NAME = 'CL_Route_Schedule_Completed';
    @TestVisible private static String DEFAULT_OWA_EMAIL_ADDRESS = 'crm@accelentertainment.com';
    @TestVisible private static String DEFAULT_NO_REPLY_ADDRESS  = 'no-reply@accelentertainment.com';
    @TestVisible private static String SURVEY_MDT_DEV_NAME       = 'RPSQuestions';
    @TestVisible private static String NO_SURVEY_VALUE_DISPLAY   = '[Field left Blank]';
    public final static String MDT_DEV_NAME_RPS_EMAIL = 'clQueueableRpsEmailer';
    @TestVisible private final static String MDT_DEV_NAME_RPS       = 'Route_Processing_Sheet';

    @TestVisible private Id jobId;
    @TestVisible private Id rsId;
    @TestVisible private String publicGroupDevName = 'Cash_Logistics_Managers';
    @TestVisible private List<String> publicMdtDevNames = new List<String>();
    @TestVisible private String templateDevName = 'CL_Route_Schedule_Completed';
    @TestVisible private  Cash_Logistics_Automation_Setting__mdt automationMdt;
    @TestVisible private  Cash_Logistics_Setting__mdt expCloudMdt;
    @TestVisible private  Cash_Logistics_Region__mdt regionMdt;


    public clQueueableRpsEmailer() {

    }
    /**
     * @param rsId  The Route_Schedule__c.Id.
     */
    public clQueueableRpsEmailer(Id rsId) {
        this.rsId = rsId;
        this.automationMdt = CustomMetadataSvc.retrieveAutomationMetadata(MDT_DEV_NAME_RPS_EMAIL);
        this.expCloudMdt = (Cash_Logistics_Setting__mdt)CustomMetadataSvc.retrieveCustomMetadata(Cash_Logistics_Setting__mdt.getSObjectType(),MDT_DEV_NAME_RPS);
        System.debug('---> expCloudMdt='+expCloudMdt);
        if(automationMdt.Email_Template_Dev_Name__c != null)  {
            templateDevName = automationMdt.Email_Template_Dev_Name__c;
        }
//        if(automationMdt.Public_Group_Dev_Names__c != null) {
//            publicMdtDevNames = automationMdt.Public_Group_Dev_Names__c.split(',');
//        }
       // System.debug('---> public mdt dev names:'+publicMdtDevNames);
    }

    /**
     * @param rsId                  The Route_Schedule__c.Id.
     * @param publicGroupDevName    The developer name of Group.
     * @param templateDevName       The Email Template Developer Name to use.
     */
    public clQueueableRpsEmailer(Id rsId,String publicGroupDevName,String templateDevName) {
        this.rsId = rsId;
        this.publicGroupDevName = publicGroupDevName;
        this.expCloudMdt = (Cash_Logistics_Setting__mdt)CustomMetadataSvc.retrieveCustomMetadata(Cash_Logistics_Setting__mdt.getSObjectType(),MDT_DEV_NAME_RPS);
        this.templateDevName = templateDevName;
        this.automationMdt = CustomMetadataSvc.retrieveAutomationMetadata(MDT_DEV_NAME_RPS_EMAIL);
    }

   /**
    * Implements the queueable execute interface.
    * @param ctx The Queueable context.
    */
    public void execute(QueueableContext ctx) {
        this.jobId = ctx.getJobId();
        performExecute();
    }

    /**
     *  Find Route_Processing_Sheet__c records for the parent route schedule id.
     *  Build email data (whoIds,whatIds,template etc).
     *  Fire off the survey email.
     */
    @TestVisible
    private void performExecute() {
        List<Route_Processing_Sheet__c> rpss =  this.queryRpsChildren();
        if(automationMdt.Send_Email__c || expCloudMdt.Show_Send_Route_End_Email_Menu_Item__c) {
            // @see https://accel-entertainment.monday.com/boards/1300348967/pulses/2898284761  7/5/2022
            if(rsId != null) {
                List<Route_Schedule__c> routeSchedules = [
                        SELECT Id,Route_End_Email_Sent_Date__c,Route_End_Email_Sent_By__c
                        FROM   Route_Schedule__c
                        WHERE  Id = :rsId
                ];
                if(!routeSchedules.isEmpty()) {
                    Route_Schedule__c rs = routeSchedules[0];
                    rs.Route_End_Email_Sent_Date__c = System.now();
                    rs.route_End_Email_Sent_By__c = UserInfo.getUserId();
                    update rs;
                }
            }
            for(Route_Processing_Sheet__c rps :rpss) {
                rps.Route_End_Email_Sent_Date__c = System.now();
                rps.Route_End_Email_Sent_by__c = UserInfo.getUserId();
            }
            update rpss;
            List<clRouteScheduleSvc.EmailData> rsEmailDatas = buildEmails(rpss);
            fireEmail(rsEmailDatas);
        }
    }

    /**
     * @param rsEmailDatas  EmailData used to fire the email off.
     */
    @TestVisible
    private void fireEmail(List<clRouteScheduleSvc.EmailData> rsEmailDatas) {

        List<Messaging.SendEmailResult> sendResults = clRouteScheduleSvc.sendEmailTemplates(rsEmailDatas);
        System.debug('---> sendResults:'+sendResults);
        //return sendResults;
    }

    /**
     * @return a List of Route_Processing_Sheet__c sObjects.
     */
    @TestVisible
    private List<Route_Processing_Sheet__c> queryRpsChildren() {

        List<Route_Processing_Sheet__c> rpssToGenEmail = new List<Route_Processing_Sheet__c>();

        List<Route_Processing_Sheet__c> routeProcessingSheets =
                clRouteProcessingSheetSvc.retrieveRouteProcessingSheets(this.rsId);

        if(!routeProcessingSheets.isEmpty()) {
            for(Route_Processing_Sheet__c rps : routeProcessingSheets) {
               rpssToGenEmail.add(rps);
            }
        }
        return rpssToGenEmail;
    }

    /**
     * Build the email (used to propulate the template) and build the 1-N child location records by injecteding
     * dynamic Html.
     *
     * @param routeProcessingSheets a List of Route_Processing_Sheet__c sObjects.
     * @return                      a List of EmailData objects.
     */
    @TestVisible
    private List<clRouteScheduleSvc.EmailData> buildEmails(List<Route_Processing_Sheet__c> routeProcessingSheets) {
        EmailTemplate emailTemplate = EmailSvc.retrieveEmailTemplate(this.templateDevName);

        List<clRouteScheduleSvc.EmailData> emails =  new List<clRouteScheduleSvc.EmailData>();
        clRouteScheduleSvc.EmailData data = new clRouteScheduleSvc.EmailData();

        data.templateId = emailTemplate.Id;
        data.dynamicHtml = this.buildEmailDynamicChildData(routeProcessingSheets);
        data.recordId = this.rsId;
        data.whoIds = getWhoIds();
        data.saveAsActivity = false;
        emails.add(data);

        return emails;
    }
    /**
     * @param routeProcessingSheets  a List of Route_Processing_Sheet__c sObjects
     * @return                       they dynamic html to inject into the email template.
     */
    private String buildEmailDynamicChildData(List<Route_Processing_Sheet__c> routeProcessingSheets) {

        String html = '';
        if(!routeProcessingSheets.isEmpty()) {
            // dynamically find the RPS fields to use based on Cash_Logistics_Survey_Setting__mdt
            Set<String> surveyFields = retrieveSurveyFields();
            if(surveyFields.isEmpty()) {
                System.debug(LoggingLevel.WARN,' No Fields have been configured for the RPS Survey. Check Survey Metadata!');
                return html;
            }
            Map<String, Schema.SObjectField> mFields = Schema.SObjectType.Route_Processing_Sheet__c.fields.getMap();

            for(Route_Processing_Sheet__c rps : routeProcessingSheets) {
                String accountDisplay = getAccountDisplayValue(rps);
                html += '<br/>';
                html += '<table border="0" cellpadding="2" cellspacing="1" width="100%">';
                html += '<tbody>';
                html += '<tr>';
                html += '<td colspan=2 bgcolor="#F3F2F2">';
                html += '  <span style="font-size:12px;">';
                //  https://accel-entertainment.monday.com/boards/942883797/pulses/3015869903?notification=2101617472
                String rpsRtModel =  rps.Redemption_Asset__r?.Model__c; //  <-- a guess on what model type means?

                html += '   <b>&nbsp;'+accountDisplay+'</b> '
                        + '&nbsp;-&nbsp;' + rps.Collection_Type__c
                        + '&nbsp;-&nbsp;' + rpsRtModel
                        + '&nbsp;-&nbsp;Total VGTs:&nbsp;' + rps.Total_Meter_Readings__c
                        + '&nbsp;-&nbsp;' + rps.Redemption_Type__c;

                if(rps.Redemption_Type__c == 'Cash Fill') {
                    html += '<br/>'
                            + 'Unused Return: '+rps.Cash_Return_Unused__c;
                }

                html += '  </span>';
                html += '</td>';
                html += '</tr>';

                Boolean hasValidSurveyFields = false;
                for (String surveyFieldApiName : surveyFields) {
                    Schema.SObjectField sObjectField = mFields.get(surveyFieldApiName);
                    //  Spit out the field label and field value.
                    Schema.DescribeFieldResult field = sObjectField.getDescribe();
                    Object oFieldValue = getFieldValue(field, rps);
                    if (!isFieldBlank(oFieldValue)) { // @see https://accel-entertainment.monday.com/boards/1300348967/pulses/2757155735
                        html += '<tr>';
                        html += '<td style="width:2%">&nbsp;</td>';
                        html += '<td style="width:98%"><span style="font-size:12px;"><i><u>' + field.getLabel() + '</u></i></span></td>';
                        html += '</tr>';
                        html += '<tr>';
                        html += '<td style="width:2%">&nbsp;</td>';
                        html += '<td style="width:98%"><span style="font-size:12px;">&nbsp;&nbsp;' + oFieldValue + '</span></td>';
                        html += '</tr>';
                        hasValidSurveyFields = true;
                    } else {
                       // html += '<tr><td colspan="2">TEST TEST FIELD DEFINED AS BLANK='+field.getLabel() + ' ... apiname='+ field.getName() + ' ... value='+oFieldValue + '</td></tr>';

                        //html += '<tr><td>&nbsp;</td></tr>'; //@see https://accel-entertainment.monday.com/boards/1300348967/pulses/2757155735
                    }
                }
                if(rps.Status__c == 'Skipped') {
                    html += '<tr><td colspan="2">Location was Skipped</td></tr>';
                }
                if(!hasValidSurveyFields) {
                    html += '<tr><td colspan="2">&nbsp;</td></tr>';
                }
                html += '</tbody>';
                html += '</table>';
            }
        }
        return html;
    }
    /**
     * @param oFieldValue The value of the notes or survey field
     * @return true if blank or '[Field left Blank]' assigned, otherwise false;
     * @see https://accel-entertainment.monday.com/boards/1300348967/pulses/2757155735
     */
    public  Boolean isFieldBlank(Object oFieldValue) {
        Boolean isBlank = false;
        if(oFieldValue != null) {
            if(oFieldValue == NO_SURVEY_VALUE_DISPLAY){
                isBlank = true;
            }
        } else {
            isBlank = true;
        }
        return isBlank;
    }

    /**
     * Use the public group name as defined by the group dev name in Cash_Logistics_Automation_Setting__mdt and
     * find all the users in that public group to act as the whoIds for the email.
     *
     * @return a Set of User.Id values.
     *
     */
    @TestVisible
    private Set<Id> getWhoIds() {
        Id routeId = [SELECT Id,Route__c FROM Route_Schedule__c WHERE Id = :this.rsId]?.Route__c;
        Route__c route = [SELECT Id,Name,Processing_Location__c FROM Route__c WHERE  Id = :routeId];
        String region = route.Processing_Location__c.replaceAll(' ','_');
        this.regionMdt = (Cash_Logistics_Region__mdt)CustomMetadataSvc.retrieveCustomMetadata(Cash_Logistics_Region__mdt.getSObjectType(),region);
        this.publicMdtDevNames = regionMdt.Rps_Email_Public_Group_Dev_Names__c.split(',');
        System.debug('----> group dev names='+this.publicMdtDevNames);
        List<User> groupUsers = retrievePublicGroupsUsersRecords(publicMdtDevNames);
        System.debug('---> groupUsers='+groupUsers);
        Set<Id> whoIds = new Set<Id>();
        for(User user : groupUsers) {
            whoIds.add(user.Id);
        }
        return whoIds;
    }

    /**
     * @return a Set containing Field Api Names to use in inject the dynamic html with.
     */
    public Set<String> retrieveSurveyFields() {
        Set<String> surveyFieldApiNames = new Set<String>();

        List<Cash_Logistics_Survey_Setting__mdt> mdts = CustomMetadataSvc.retrieveSurveyMetadatas(SURVEY_MDT_DEV_NAME);
        for(Cash_Logistics_Survey_Setting__mdt mdt : mdts) {
            surveyFieldApiNames.add(mdt.Field_Api_Name__c);
        }
        return surveyFieldApiNames;

    }

    /**
     * @param rps   A Route Processing sheet sObject.
     * @return      The value to display for account name.
     */
    private static String getAccountDisplayValue(Route_Processing_Sheet__c rps) {
        String accountDisplay = '';
        if(rps.Stop_Number__c != null) {
            accountDisplay = '('+rps.Stop_Number__c+') '+rps.Account__r.Name;
        } else {
            accountDisplay = rps.Account__r.Name;
        }
        return accountDisplay;
    }

    /**
     * @param field   A Describe field result.
     * @param rps     A Route_Processing_Sheet__c sObject.
     *
     * @return        The value of the field on the RPS sObject to use to inject in the email.
     */
    private static String getFieldValue(Schema.DescribeFieldResult field, Route_Processing_Sheet__c rps) {
        String sFieldValue;
        Object oFieldValue = rps.get(field.getName());
        sFieldValue = oFieldValue == null ? NO_SURVEY_VALUE_DISPLAY : oFieldValue.toString();
        String soapType = field.getSoapType().name();

        if(oFieldValue != null) {
            //  @todo other types?
            switch on soapType {
                when 'DATE' {
                    sFieldValue = ((Date) oFieldValue).format();
                }
            }
        }
        return sFieldValue;
    }

    public static List<User> retrievePublicGroupsUsersRecords(List<String> groupNames) {
        List<User> users = [
                SELECT Id,Email,userName
                FROM    User
                WHERE Id IN (
                        SELECT UserOrGroupId
                        FROM GroupMember
                        WHERE Group.DeveloperName IN :groupNames
                )];
        return users;
    }
}