objects/Account.object
<CustomObject>
    <fields>
        <fullName>RM_Region__c</fullName>
        <label>Relationship Manager Region</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Chicagoland - Dan</fullName>
                </value>
                <value>
                    <fullName>Central - Jenny</fullName>
                </value>
                <value>
                    <fullName>Chicagoland - Ryan N.</fullName>
                </value>
                <value>
                    <fullName>Northwest - Kerry</fullName>
                </value>
                <value>
                    <fullName>South - Hillary</fullName>
                </value>
                <value>
                    <fullName>Springfield - Colin</fullName>
                </value>
                <value>
                    <fullName>West - Amy</fullName>
                </value>
                <value>
                    <fullName>CSM Region</fullName>
                </value>
                <value>
                    <fullName>Central - Bill</fullName>
                    <isActive>false</isActive>
                    <label>Central - Bill</label>
                </value>
                <value>
                    <fullName>G3 Gaming</fullName>
                    <isActive>false</isActive>
                    <label>G3 Gaming</label>
                </value>
                <value>
                    <fullName>Lincoln</fullName>
                    <isActive>false</isActive>
                    <label>Lincoln</label>
                </value>
                <value>
                    <fullName>South - Colin</fullName>
                    <isActive>false</isActive>
                    <label>South - Colin</label>
                </value>
                <value>
                    <fullName>South- Colin</fullName>
                    <isActive>false</isActive>
                    <label>South- Colin</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>ProjectID</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>Opportunity_Product</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Products (Account)</relationshipLabel>
        <relationshipName>Products2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Manufacturer__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Look up to the Account - Record Type: Manufacturer</description>
        <inlineHelpText>The Manufacturer Associated with the Product (An Account of record type Manufacturer)</inlineHelpText>
        <label>Manufacturer</label>
        <lookupFilter>
            <active>false</active>
            <errorMessage>Product selected must be an account with a record type of Manufacturer.</errorMessage>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Manufacturer</value>
            </filterItems>
            <infoMessage>Product selected must be an account with a record type of Manufacturer.</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <recordTypes>
        <fullName>Organic</fullName>
        <active>true</active>
        <label>Organic</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Project_Line__c.object
<CustomObject>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Project Lines</relationshipLabel>
        <relationshipName>Project_Lines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Project Line</label>
    <nameField>
        <label>Project Line Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/ProjectTriggerTest.cls
@isTest
private class ProjectTriggerTest {

    static final String OPPTY_NAME = 'TEST_CLASS_PROJECT';
    static final String PRODUCT_NAME = 'Test Product';
    static final STring TEST_RM_REGION = 'Lincoln';
    
    @isTest static void testCreateProjectLines() {
        User u = new User(
                             ProfileId = [SELECT Id FROM Profile WHERE Name = 'System Administrator'].Id,
                             LastName = 'last',
                             Email = 'puser000@amamama.com',
                             Username = 'puser000@amamama.com' + System.currentTimeMillis(),
                             CompanyName = 'TEST',
                             Title = 'title',
                             Alias = 'alias',
                             TimeZoneSidKey = 'America/Los_Angeles',
                             EmailEncodingKey = 'UTF-8',
                             LanguageLocaleKey = 'en_US',
                             LocaleSidKey = 'en_US'
                        );
        insert u;

        Account acc = new Account();
        acc.Name = 'Test Account';

        //--- RJN Added RM_Region__c 3/5/2020.. not sure of business reason but it appears to be needed to prevent the following
        //---18:29:58:880 FLOW_ELEMENT_ERROR The flow failed to access the value for myVariable_current.Account__r.RM_Region__c
        // because it hasn't been set or assigned.|FlowDecision|myDecision2. This test class is not currently failing
        // in UAT but is failing in prod (there are some version differences in things being kicked off)
        acc.RM_Region__c = TEST_RM_REGION;
        insert acc;

        Opportunity oppty = new Opportunity();
        oppty.Name = OPPTY_NAME;
        oppty.Pricebook2Id = Test.getStandardPricebookId();
        oppty.StageName = 'New';
        oppty.CloseDate = System.today();
        oppty.AccountId = acc.Id;
        insert oppty;

        Product2 product = new Product2();
        product.Name = PRODUCT_NAME;
        product.Manufacturer__c = acc.Id;
        insert product;

        PricebookEntry pricebookEntry = new PricebookEntry();
        pricebookEntry.Product2Id = product.Id;
        pricebookEntry.UnitPrice = 0;
        pricebookEntry.Pricebook2Id = Test.getStandardPricebookId();
        pricebookEntry.IsActive = true;
        insert pricebookEntry;

        OpportunityLineItem opptyLine = new OpportunityLineItem();
        opptyLine.Quantity = 2;
        opptyLine.Product2Id = product.Id;
        opptyLine.OpportunityId = oppty.Id;
        insert opptyLine;

        Id organicRtId = SObjectType.Project__c.getRecordTypeInfosByDeveloperName().get('Organic').getRecordTypeId();
        Project__c project = new Project__c();
        project.Name = oppty.Name;
        project.Opportunity__c = oppty.Id;
        project.Account__c = acc.id;
        //RJN Added record type to conform to stuff added onto project since this trigger was last maintained by Penrod
        project.RecordTypeId = organicRtId;


        Test.startTest();

        insert project;
        update project;
        Test.stopTest();

        List<Project_Line__c> projectLines = [SELECT Id, Name FROM Project_Line__c WHERE Project__c = :project.Id];
        System.assertEquals(1, projectLines.size());
        //System.assertEquals(OPPTY_NAME + ' ' + PRODUCT_NAME, projectLines[0].Name);
        System.assertEquals(PRODUCT_NAME, projectLines[0].Name);
    }

}