objects/Asset.object
<CustomObject>
    <fields>
        <fullName>Asset__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Asset</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Assets</relationshipLabel>
        <relationshipName>Assets4</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>BV_Type__c</fullName>
        <description>Bill Vaildator Type</description>
        <label>BV Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>JCM</fullName>
                </value>
                <value>
                    <fullName>MEI</fullName>
                    <default>true</default>
                    <label>MEI</label>
                </value>
                <value>
                    <fullName>Small MEI</fullName>
                </value>
                <value>
                    <fullName>NV-200</fullName>
                </value>
                <value>
                    <fullName>ICT PA7</fullName>
                </value>
                <value>
                    <fullName>ICT TAO-A</fullName>
                </value>
                <value>
                    <fullName>MEI2831U</fullName>
                </value>
                <value>
                    <fullName>MEI SC Advance</fullName>
                </value>
                <value>
                    <fullName>JCM UBA10</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>VGT</fullName>
        <active>true</active>
        <label>VGT</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Meter_Reading__c.object
<CustomObject>
    <description>Example object to capture electronic meters</description>
    <fields>
        <fullName>Asset__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Asset</label>
        <referenceTo>Asset</referenceTo>
        <relationshipLabel>Meter Readings</relationshipLabel>
        <relationshipName>Meter_Readings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>BV_Type__c</fullName>
        <description>Asset.BV_Type__c Since the picklist on Asset was not global this must be synchronized with those values for now. Written upon creation of meter_reading__c and used by DLRS to rollup to RPS</description>
        <inlineHelpText>Asset.BV_Type__c Since the picklist on Asset was not global this must be synchronized with those values for now. Written upon creation of meter_reading__c and used by DLRS to rollup to RPS</inlineHelpText>
        <label>BV Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>JCM</fullName>
                </value>
                <value>
                    <fullName>MEI</fullName>
                </value>
                <value>
                    <fullName>Small MEI</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Reading_Status__c</fullName>
        <defaultValue>&quot;New&quot;</defaultValue>
        <description>That status of the meter reading.. Generally this will start in In Progress unless we are inserting this meter records outside of the ui... Completion is currently when there is shapshot count &gt; 0 (image uploaded) and current lifetime case in value added. @see  MeterReadingTriggerHandler.cls</description>
        <inlineHelpText>That status of the meter reading.. Generally this will start in In Progress unless we are inserting this meter records outside of the ui... Completion is currently when there is shapshot count &gt; 0 (image uploaded) and current lifetime case in value added.</inlineHelpText>
        <label>Reading Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Cannot Collect</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Route_Processing_Sheet__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Route Processing Sheet</label>
        <referenceTo>Route_Processing_Sheet__c</referenceTo>
        <relationshipLabel>Meter Readings</relationshipLabel>
        <relationshipName>Meter_Readings</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Meter Reading</label>
    <nameField>
        <displayFormat>MTR-{000000000}</displayFormat>
        <label>Meter Reading ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Meter Readings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Route_Processing_Sheet__c.object
<CustomObject>
    <description>Example digitization of the route processing sheet</description>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account DBA</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Route Processing Sheets</relationshipLabel>
        <relationshipName>Route_Processing_Sheets</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Processing_Location__c</fullName>
        <label>Processing Location</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Processing_Location</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Route_Schedule__c</fullName>
        <label>Route Schedule</label>
        <referenceTo>Route_Schedule__c</referenceTo>
        <relationshipLabel>Route Processing Sheets</relationshipLabel>
        <relationshipName>Route_Processing_Sheets</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Route Processing Sheet</label>
    <nameField>
        <displayFormat>Collection-Id-{000000000}</displayFormat>
        <label>Collection ID Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Route Processing Sheets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Route_Schedule__c.object
<CustomObject>
    <description>Assignment information of a physical route&apos;s locations, collectors, vehicles, and questions for a specific day</description>
    <fields>
        <fullName>Processing_Location__c</fullName>
        <label>Processing Location</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Processing_Location</valueSetName>
        </valueSet>
    </fields>
    <label>Route Schedule</label>
    <nameField>
        <label>Route Schedule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Route Schedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

globalValueSets/Processing_Location.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Burr Ridge</fullName>
    </customValue>
    <customValue>
        <fullName>DEV TEST 1</fullName>
    </customValue>
    <customValue>
        <fullName>Tinley Park</fullName>
    </customValue>
    <customValue>
        <fullName>Peoria</fullName>
    </customValue>
    <customValue>
        <fullName>Springfield</fullName>
    </customValue>
    <customValue>
        <fullName>CW</fullName>
    </customValue>
    <customValue>
        <fullName>Rockford</fullName>
    </customValue>
    <customValue>
        <fullName>Collinsville</fullName>
    </customValue>
    <masterLabel>Processing Location</masterLabel>
</GlobalValueSet>

classes/clAdminOnlyGenMeterReadingsController.cls
public with sharing class clAdminOnlyGenMeterReadingsController {

    public static final String MAP_KEY_METERS   = 'MAP_KEY_METERS';
    public static final String MAP_KEY_RPS      = 'MAP_KEY_RPS';

    /**
     * Simulates clBatchMeterReadingsCreation
     *
     * @param rpsId The Route_Processing_Sheet.Id value.
     * @return      A ResponseDto object with a List of Meter_Reading__c sObjects in the values Map.
     */
    @AuraEnabled
    public static ResponseDto doCreateMeterReadings(Id rpsId) {
        ResponseDto dto = new ResponseDto();

        Route_Processing_Sheet__c rps =  [
                SELECT  Id,Account__c,Route_Schedule__c,Processing_Location__c
                FROM    Route_Processing_Sheet__c
                WHERE   Id = :rpsId
        ];
        Set<String> rtDevNames = new Set<String>{'VGT'};
        Map<Id,Asset> accountMachines = AssetSvc.retrieveAccountMachines(new Set<Id>{rps.Account__c}, rtDevNames);
        List<Meter_Reading__c> meterReadingsIns = new List<Meter_Reading__c>();

        Map<Id,List<Asset>> mAccountId_Assets = new Map<Id,List<Asset>>();
        for(Asset asset : accountMachines.values()) {
            if(!mAccountId_Assets.containsKey(asset.AccountID)) {
                mAccountId_Assets.put(asset.AccountId,new List<Asset>{asset});
            } else {
                List<Asset> currAccountAssets = mAccountId_Assets.get(asset.AccountId);
                currAccountAssets.add(asset);
            }
        }
        List<Asset> rpsAssets = mAccountId_Assets.get(rps.Account__c);

        if(rpsAssets != null && !rpsAssets.isEmpty()) {
            for (Asset rpsAsset : rpsAssets) {
                Meter_Reading__c reading = new Meter_Reading__c();
                reading.Asset__c = rpsAsset.Id;
                reading.BV_Type__c = rpsAsset.BV_Type__c;
                reading.Route_Processing_Sheet__c = rps.Id;
                reading.Reading_Status__c = 'New';
                meterReadingsIns.add(reading);
            }
        }
        insert  meterReadingsIns;

        Map<Id,Meter_Reading__c> mMeters = clMeterSvc.retrieveRpsMeterReadings(rpsId);
        dto.values.put(MAP_KEY_METERS,mMeters.values());
        dto.isSuccess = mMeters != null && !mMeters.isEmpty();

        return dto;
    }

    /**
     * @param rpsId The Route_Processing_Sheet.Id value.
     * @return      A ResponseDto object with a Route_Processing_Sheet__c sObjects in the values Map.
     */
    @AuraEnabled
    public static ResponseDto doRetrieveRps(Id rpsId) {

        Route_Processing_Sheet__c rps = clRouteProcessingSheetSvc.retrieveRouteProcessingSheet(rpsId);
        ResponseDto dto = new ResponseDto();

        dto.values.put(MAP_KEY_RPS,rps);
        dto.isSuccess = rps != null;

        return dto;
    }
}