objects/Asset.object
<CustomObject>
    <fields>
        <fullName>Asset__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Asset</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Assets</relationshipLabel>
        <relationshipName>Assets4</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>BV_Type__c</fullName>
        <description>Bill Vaildator Type</description>
        <label>BV Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>JCM</fullName>
                </value>
                <value>
                    <fullName>MEI</fullName>
                    <default>true</default>
                    <label>MEI</label>
                </value>
                <value>
                    <fullName>Small MEI</fullName>
                </value>
                <value>
                    <fullName>NV-200</fullName>
                </value>
                <value>
                    <fullName>ICT PA7</fullName>
                </value>
                <value>
                    <fullName>ICT TAO-A</fullName>
                </value>
                <value>
                    <fullName>MEI2831U</fullName>
                </value>
                <value>
                    <fullName>MEI SC Advance</fullName>
                </value>
                <value>
                    <fullName>JCM UBA10</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Model__c</fullName>
        <label>Model</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SAS__c</fullName>
        <label>SAS</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>VGT</fullName>
        <active>true</active>
        <label>VGT</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Case.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Choose the Location destination of the part, VGT, RT, etc.</description>
        <label>Location to Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Cases (Location to Name)</relationshipLabel>
        <relationshipName>Cases2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Model__c</fullName>
        <formula>Asset.Model__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Model</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Meter_Reading__c.object
<CustomObject>
    <description>Example object to capture electronic meters</description>
    <fields>
        <fullName>Actual_100_Note_Count__c</fullName>
        <label>Actual $100 Note Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Actual_1_Note_Count__c</fullName>
        <label>Actual $1 Note Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Actual_20_Note_Count__c</fullName>
        <label>Actual $20 Note Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Actual_5_Note_Count__c</fullName>
        <label>Actual $5 Note Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Actual_Drop__c</fullName>
        <description>Should be the total cash amount that was counted for this VGT</description>
        <label>Actual Drop</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Asset__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Asset</label>
        <referenceTo>Asset</referenceTo>
        <relationshipLabel>Meter Readings</relationshipLabel>
        <relationshipName>Meter_Readings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>BV_Type__c</fullName>
        <description>Asset.BV_Type__c Since the picklist on Asset was not global this must be synchronized with those values for now. Written upon creation of meter_reading__c and used by DLRS to rollup to RPS</description>
        <inlineHelpText>Asset.BV_Type__c Since the picklist on Asset was not global this must be synchronized with those values for now. Written upon creation of meter_reading__c and used by DLRS to rollup to RPS</inlineHelpText>
        <label>BV Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>JCM</fullName>
                </value>
                <value>
                    <fullName>MEI</fullName>
                </value>
                <value>
                    <fullName>Small MEI</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Cannot_Collect__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates that for, multiple reasons, the collector cannot complete the required fields for the particular meter reading.</description>
        <inlineHelpText>Indicates that for, multiple reasons, the collector cannot complete the required fields for the particular meter reading.</inlineHelpText>
        <label>Cannot Collect</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Current_Lifetime_Cash_In__c</fullName>
        <label>Current Lifetime Cash In</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Model__c</fullName>
        <formula>Asset__r.Model__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Model</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Reading_Status__c</fullName>
        <defaultValue>&quot;New&quot;</defaultValue>
        <description>That status of the meter reading.. Generally this will start in In Progress unless we are inserting this meter records outside of the ui... Completion is currently when there is shapshot count &gt; 0 (image uploaded) and current lifetime case in value added. @see  MeterReadingTriggerHandler.cls</description>
        <inlineHelpText>That status of the meter reading.. Generally this will start in In Progress unless we are inserting this meter records outside of the ui... Completion is currently when there is shapshot count &gt; 0 (image uploaded) and current lifetime case in value added.</inlineHelpText>
        <label>Reading Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Cannot Collect</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Required_Data_Entered__c</fullName>
        <description>Checks to see if the collector entered enough data for the meter record to be completed ( Current Lifetime Cash In and associated an image )</description>
        <formula>AND( !ISBLANK(Current_Lifetime_Cash_In__c),Current_Lifetime_Cash_In__c &gt; 0,!ISBLANK(Snapshot__c))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Determines if the collector entered enough data on the meter record.</inlineHelpText>
        <label>Required Data Entered</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Route_Processing_Sheet__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Route Processing Sheet</label>
        <referenceTo>Route_Processing_Sheet__c</referenceTo>
        <relationshipLabel>Meter Readings</relationshipLabel>
        <relationshipName>Meter_Readings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SAS__c</fullName>
        <formula>Asset__r.SAS__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>SAS</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Snapshot__c</fullName>
        <label>Snapshot</label>
        <type>Url</type>
    </fields>
    <label>Meter Reading</label>
    <nameField>
        <displayFormat>MTR-{000000000}</displayFormat>
        <label>Meter Reading ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Meter Readings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Route_Processing_Sheet__c.object
<CustomObject>
    <description>Example digitization of the route processing sheet</description>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account DBA</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Route Processing Sheets</relationshipLabel>
        <relationshipName>Route_Processing_Sheets</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Actual_Drop__c</fullName>
        <label>(Depreciated) Actual Drop</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Route Processing Sheet</label>
    <nameField>
        <displayFormat>Collection-Id-{000000000}</displayFormat>
        <label>Collection ID Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Route Processing Sheets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/clMeterSvc.cls
public class clMeterSvc {


//    /**
//     * @todo for future use.
//     * @param rps xx
//     *
//     * @return xx
//     */
//    public static List<Meter_Reading__c> initMeterReadings(Route_Processing_Sheet__c rps) {
//
//        List<Meter_Reading__c> meterReadingsIns = new List<Meter_Reading__c>();
//
//        Set<String> rtDevNames = new Set<String>{'VGT'};
//        List<Asset> accountMachines = AssetSvc.retrieveAccountMachines(rps.Account__c,rtDevNames);
//        for(Asset machine : accountMachines) {
//            Meter_Reading__c reading = new Meter_Reading__c();
//            reading.Asset__c = machine.Id;
//            reading.BV_Type__c = machine.BV_Type__c;
//            reading.Route_Processing_Sheet__c = rps.Id;
//            reading.Reading_Status__c = 'New';
//            meterReadingsIns.add(reading);
//        }
//        insert meterReadingsIns;
//        return meterReadingsIns;
//    }


    public static Map<Id,Meter_Reading__c> retrieveRpsMeterReadings(Id rpsId) {

        Map<Id,Meter_Reading__c> mMeterReadings = new Map<Id,Meter_Reading__c>([
                SELECT Id,Name,Current_Lifetime_Cash_In__c,Asset__c,Route_Processing_Sheet__c, Reading_Status__c,
                        LastModifiedDate,Actual_1_Note_Count__c,Actual_5_Note_Count__c,Actual_20_Note_Count__c,
                        CreatedDate,BV_Type__c,
                        Actual_100_Note_Count__c,Actual_Drop__c,
                        Route_Processing_Sheet__r.Account__r.Name,
                        Asset__r.SAS__c,Asset__r.RecordType.DeveloperName,Asset__r.Model__c,Asset__r.SerialNumber,
                        Asset__r.RecordType.Name,Required_Data_Entered__c,Cannot_Collect__c
                FROM   Meter_Reading__c
                WHERE  Route_Processing_Sheet__c = :rpsId
                ORDER  BY LastModifiedDate DESC
        ]);
        return mMeterReadings;
    }
    /**
     * @param rpsId
     *
     * @return
     */
    public static Map<Id,Meter_Reading__c> retrieveRpsMeterReadingsSummary(Id rpsId) {

        Map<Id,Meter_Reading__c> mMeterReadings = new Map<Id,Meter_Reading__c>([
                SELECT  Id,Name,Route_Processing_Sheet__c, Reading_Status__c,
                        LastModifiedDate,BV_Type__c,
                        Asset__r.SAS__c,Asset__r.RecordType.DeveloperName,Asset__r.Model__c,Asset__r.SerialNumber
                FROM    Meter_Reading__c
                WHERE   Route_Processing_Sheet__c = :rpsId
                ORDER  BY Asset__r.SAS__c ASC
        ]);
        return mMeterReadings;
    }

    public static Map<Id,Meter_Reading__c> retrieveRpsMeterReadings(Id rpsId, String rtDevName) {

        Map<Id,Meter_Reading__c> mMeterReadings = new Map<Id,Meter_Reading__c>([
                SELECT  Id,Name,Current_Lifetime_Cash_In__c,Asset__c,Route_Processing_Sheet__c, Reading_Status__c,
                        LastModifiedDate, Actual_1_Note_Count__c,Actual_5_Note_Count__c,Actual_20_Note_Count__c,
                        CreatedDate,
                        Actual_100_Note_Count__c,Actual_Drop__c,
                        Route_Processing_Sheet__r.Account__r.Name,
                        Asset__r.SAS__c,Asset__r.RecordType.DeveloperName,Asset__r.Model__c,Asset__r.SerialNumber,
                        Asset__r.RecordType.Name, Required_Data_Entered__c,Cannot_Collect__c,Snapshot__c
                FROM    Meter_Reading__c
                WHERE   Route_Processing_Sheet__c = :rpsId
                AND     Asset__r.RecordType.DeveloperName = :rtDevName
                ORDER  BY Asset__r.SAS__C ASC
        ]);
        return mMeterReadings;
    }

    public static Meter_Reading__c retrieveSingleMeterReading(Id meterId) {
        Meter_Reading__c meterReading;
        Map<Id,Meter_Reading__c> mMeterReadings = new Map<Id,Meter_Reading__c>([
                SELECT Id,Name,Current_Lifetime_Cash_In__c,Asset__c,Route_Processing_Sheet__c, Reading_Status__c,
                        LastModifiedDate, Actual_1_Note_Count__c,Actual_5_Note_Count__c,Actual_20_Note_Count__c,
                        Actual_100_Note_Count__c,Actual_Drop__c,
                        Route_Processing_Sheet__r.Account__r.Name,
                        CreatedDate,
                        Asset__r.SAS__c,Asset__r.RecordType.DeveloperName,Asset__r.Model__c,Asset__r.SerialNumber,
                        Asset__r.RecordType.Name, Snapshot__c,Required_Data_Entered__c,Cannot_Collect__c
                FROM   Meter_Reading__c
                WHERE  Id = :meterId
        ]);
        if(!mMeterReadings.isEmpty()) {
            meterReading = mMeterReadings.values()[0];
        }
        return meterReading;
    }


    public static Meter_Reading__c retrieveMeterReading(Id meterId) {
        Meter_Reading__c meterReading;

        List<Meter_Reading__c> meterReadings = [
                SELECT Id,Name,Current_Lifetime_Cash_In__c,Asset__c,Route_Processing_Sheet__c,Reading_Status__c,Required_Data_Entered__c,Cannot_Collect__c
                FROM   Meter_Reading__c
                WHERE  Id = :meterId
        ];
        meterReading = meterReadings.isEmpty() ? null : meterReadings[0];

        return meterReading;
    }

    public static Meter_Reading__c retrieveCollectorMeterDetail(Id meterId) {
        Meter_Reading__c meterReading;
        Map<Id,Meter_Reading__c> mMeterReadings = new Map<Id,Meter_Reading__c>([
                SELECT Id,Name,Current_Lifetime_Cash_In__c,Asset__c,Route_Processing_Sheet__c, Reading_Status__c,
                        LastModifiedDate, Actual_1_Note_Count__c,Actual_5_Note_Count__c,Actual_20_Note_Count__c,
                        Actual_100_Note_Count__c,Actual_Drop__c,
                        Route_Processing_Sheet__r.Account__r.Name,
                        CreatedDate,
                        Asset__r.SAS__c,Asset__r.RecordType.DeveloperName,Asset__r.Model__c,Asset__r.SerialNumber,
                        Asset__r.RecordType.Name, Snapshot__c,Required_Data_Entered__c,Cannot_Collect__c
                FROM   Meter_Reading__c
                WHERE  Id = :meterId
        ]);
        if(!mMeterReadings.isEmpty()) {
            meterReading = mMeterReadings.values()[0];
        }
        return meterReading;
    }
}