objects/Asset.object
<CustomObject>
    <fields>
        <fullName>Inventory_Request_Line_Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The inventory request line item that generated this asset.</description>
        <inlineHelpText>The inventory request line item that generated this asset.</inlineHelpText>
        <label>Inventory Request Line Item</label>
        <referenceTo>Inventory_Request_Line_Item__c</referenceTo>
        <relationshipLabel>Line Item Assets</relationshipLabel>
        <relationshipName>Assets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Inventory_Request__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Inventory Request that generated this item.</description>
        <label>Inventory Request</label>
        <referenceTo>Inventory_Request__c</referenceTo>
        <relationshipLabel>All Line Item Assets</relationshipLabel>
        <relationshipName>Assets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Item_Number__c</fullName>
        <label>Item Number</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PO_Number__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>PO Number</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Purchase_Order__c.Purchase_Order__c</field>
                <operation>equals</operation>
                <value></value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Purchase_Order__c</referenceTo>
        <relationshipLabel>Assets</relationshipLabel>
        <relationshipName>Assets</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Inventory_Request__c.object
<CustomObject>
    <description>Parent object to capture the request to order new inventory items.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The location associated with the inventory request.</description>
        <inlineHelpText>The location associated with the inventory request</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Inventory Requests</relationshipLabel>
        <relationshipName>Inventory_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Bypass_Validation_Rules__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Generally this shouldn&apos;t be used but if there is a mass import / upsert. It might come in handy.</description>
        <inlineHelpText>Generally this shouldn&apos;t be used but if there is a mass import / upsert. It might come in handy.</inlineHelpText>
        <label>Bypass Validation Rules</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Final_Approved_Indicator__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Final Approved Indicator</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IR_Approved_Date__c</fullName>
        <description>Date Compliance has approved the IR. Only required before Assets can be generated.</description>
        <inlineHelpText>Date Compliance has approved the IR. Only required before Assets can be generated.</inlineHelpText>
        <label>IR Approved Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Number_of_Items__c</fullName>
        <description>This is more of a helper field so we can generate line item numbers of the child records</description>
        <inlineHelpText>The total number of Child Line Items</inlineHelpText>
        <label>Total # of Line Items</label>
        <summaryForeignKey>Inventory_Request_Line_Item__c.Inventory_Request__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>PO_Number__c</fullName>
        <description>The Great Plains purchase order number.</description>
        <inlineHelpText>The Great Plains purchase order number.</inlineHelpText>
        <label>PO Number</label>
        <length>64</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PO_Submitted_Date__c</fullName>
        <description>Date the PO has been submitted to Finance. Only required before Assets can be generated.</description>
        <inlineHelpText>Date the PO has been submitted to Finance. Only required before Assets can be generated.</inlineHelpText>
        <label>PO Submitted Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Parent_Asset__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The asset the software will be assigned to.</description>
        <inlineHelpText>The asset the software will be assigned to.</inlineHelpText>
        <label>Parent Asset</label>
        <referenceTo>Asset</referenceTo>
        <relationshipLabel>Inventory Requests</relationshipLabel>
        <relationshipName>Inventory_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>The status of the Inventory Request. This status will change based on various fields populated as well as state of approval.</description>
        <inlineHelpText>The status of the Inventory Request. This status will change based on various fields populated as well as state of approval.</inlineHelpText>
        <label>Request Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                    <default>true</default>
                    <label>Open</label>
                </value>
                <value>
                    <fullName>IR Request Pending Approval</fullName>
                    <label>Pending Approval</label>
                </value>
                <value>
                    <fullName>Approved for PO</fullName>
                </value>
                <value>
                    <fullName>PO Submitted</fullName>
                </value>
                <value>
                    <fullName>PO Partially Fulfilled</fullName>
                </value>
                <value>
                    <fullName>PO Fulfilled</fullName>
                </value>
                <value>
                    <fullName>IR Request Submitted</fullName>
                    <isActive>false</isActive>
                    <label>IR Request Submitted</label>
                </value>
                <value>
                    <fullName>PO Delivery Date Scheduled</fullName>
                    <isActive>false</isActive>
                    <label>PO Delivery Date Scheduled</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Submitted_Date__c</fullName>
        <description>Date the request was submitted for approval.</description>
        <inlineHelpText>Date the request was submitted for approval.</inlineHelpText>
        <label>IR Submitted Date</label>
        <type>Date</type>
    </fields>
    <label>Inventory Request</label>
    <nameField>
        <label>Request Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Inventory Requests</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Inventory_Request_Line_Item__c.object
<CustomObject>
    <description>Child Line Items for the Inventory Request object allowing the capture of products by model (1 record per model)</description>
    <fields>
        <fullName>Inventory_Request__c</fullName>
        <description>Link tto the Parent IR Record.</description>
        <inlineHelpText>Link to the Parent IR Record.</inlineHelpText>
        <label>Inventory Request</label>
        <referenceTo>Inventory_Request__c</referenceTo>
        <relationshipLabel>Request Line Items</relationshipLabel>
        <relationshipName>Inventory_Request_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Item_Number__c</fullName>
        <description>Trigger maintained. Simply allows line 1,2,3 etc.</description>
        <inlineHelpText>The Inventory Request Line Item Number</inlineHelpText>
        <label>Item #</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Parent_Asset__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent Asset</label>
        <referenceTo>Asset</referenceTo>
        <relationshipLabel>Inventory Request Line Items</relationshipLabel>
        <relationshipName>Inventory_Request_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The product to create assets from. This must be a product record type of Gaming Software. The addition of the 2nd filter is needed to solve what appears to be a spring 2020 bug</description>
        <inlineHelpText>The product to create assets from This must be a product record type of Gaming Software. Any default values when clicking the input are most recently viewed records. To Search enter at least 2 characters and then hit enter or click the search icon.</inlineHelpText>
        <label>Product</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <errorMessage>You must select a product of type Gaming Software.</errorMessage>
            <filterItems>
                <field>Product2.RecordType.Name</field>
                <operation>equals</operation>
                <value>Gaming Software</value>
            </filterItems>
            <filterItems>
                <field>Product2.Record_Type_Text__c</field>
                <operation>equals</operation>
                <value>Gaming Software</value>
            </filterItems>
            <infoMessage>Please select a product of type Gaming Software</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Inventory Request Line Items</relationshipLabel>
        <relationshipName>Inventory_Request_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Qty_of_assets_to_create__c</fullName>
        <description>The Qty of Assets to create (Helper in case assets were created by some of them then delete)</description>
        <formula>/*Quantity__c -  Number_of_Assets_Created__c*/
 Received_Quantity__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>The Qty of Assets to Create</inlineHelpText>
        <label>Qty of assets to create</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <defaultValue>0</defaultValue>
        <description>The Original Quantity to be requested and approved.</description>
        <inlineHelpText>The Original Quantity to be requested and approved.</inlineHelpText>
        <label>Quantity Requested</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Received_Date__c</fullName>
        <description>The date the Item was received in the warehouse.</description>
        <inlineHelpText>The date the Item was received in the warehouse.</inlineHelpText>
        <label>Received Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Received_Quantity__c</fullName>
        <defaultValue>0</defaultValue>
        <description>The Number of products received in the warehouse that you want to create at this point in time. Will default to zero.</description>
        <inlineHelpText>The Number of products received in the warehouse that you want to create at this point in time. Will default to zero.</inlineHelpText>
        <label>Quantity to Create</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Inventory Request Line Item</label>
    <nameField>
        <displayFormat>IR-Line-{0000000}</displayFormat>
        <label>Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inventory Request Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Products (Account)</relationshipLabel>
        <relationshipName>Products2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <defaultValue>&quot;Active&quot;</defaultValue>
        <description>Active denotes that we are actively buying more of this product. Inactive denotes that are out there but we are not actively buying more of this product. Revoked denotes that this product is revoked and should not be on an Asset.</description>
        <inlineHelpText>Active denotes that we are actively buying more of this product. Inactive denotes that are out there but we are not actively buying more of this product. Revoked denotes that this product is revoked and should not be on an Asset.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Revoked</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Vendor_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Vendor ID</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Products (Vendor ID)</relationshipLabel>
        <relationshipName>Products3</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/InventoryRequestSvc.cls
/**
  * All General operations on Inventory_Request__c and associated Inventory_Request_Line_Item__c should go here.
 */
public with sharing class InventoryRequestSvc {

    /**
     * Retrieves and Inventory Request and it's associated line items.
     *
     * @param irId   The Inventory_Request__c Id.
     * @return       an Inventory_Request__c sObject and it's Inventory_Request_Line_Item__c sObjects if found,
     *               otherwise null.
     */
    public static Inventory_Request__c retrieveInventoryRequestAndLineItems( Id irId ) {
        Inventory_Request__c inventoryRequest;

        List<Inventory_Request__c> inventoryRequests = [
                SELECT  Id,Name,Number_of_Items__c,Status__c,Account__c,Parent_Asset__c,
                        PO_Number__c,IR_Approved_Date__c,PO_Submitted_Date__c,Submitted_Date__c,
                        ByPass_Validation_Rules__c,Final_Approved_Indicator__c,
                        (   SELECT  Id,Name,Item_Number__c,Product__c,Product__r.Name,Product__r.Vendor_ID__c,
                                    Quantity__c,Received_Date__c,Qty_of_assets_to_create__c, Received_Quantity__c,
                                    All_Line_Assets_Created__c,Number_of_Assets_Created__c,Vendor__c,
                                    Vendor__r.Name , Manufacturer__c, Product__r.Manufacturer__r.Name,
                                    Product__r.Description
                            FROM    Inventory_Request_Line_Items__r )
                FROM    Inventory_Request__c
                WHERE   Id = :irId
        ];
        if(!inventoryRequests.isEmpty()) {
            inventoryRequest = inventoryRequests[0];
        }
        return inventoryRequest;
    }
    /**
     * Retrieves a single Inventory_Request_Line_Item__c sObject
     *
     * @param irLineId The Inventory_Request_Line_Item.Id
     * @return a fully populated Inventory_Request_Line_Item__c sObject along with a number of parent fields.
     */
    public static Inventory_Request_Line_Item__c retrieveInventoryRequestLineItem(Id irLineId) {
        Inventory_Request_Line_Item__c inventoryRequestLineItem;

        List<Inventory_Request_Line_Item__c> inventoryRequestLineItems = [
                SELECT  Id,Name,Item_Number__c,Product__c,Product__r.Name,Product__r.Vendor_ID__c,Product__r.Description,
                        Quantity__c,Received_Date__c,Number_of_Assets_Created__c,Eligible_to_Create_Assets__c,
                        All_Line_Assets_Created__c,Qty_of_assets_to_create__c,Vendor__c,Vendor__r.Name,
                        Manufacturer__c, Product__r.Manufacturer__r.Name,Received_Quantity__c,
                        Inventory_Request__c,Inventory_Request__r.Parent_Asset__c,Inventory_Request__r.Account__c,
                        Inventory_Request__r.Account__r.Name,Inventory_Request__r.PO_Number__c,
                        Inventory_Request__r.IR_Approved_Date__c,Inventory_Request__r.PO_Submitted_Date__c,
                        Inventory_Request__r.Submitted_Date__c,Inventory_Request__r.Status__c,
                        Inventory_Request__r.ByPass_Validation_Rules__c,Inventory_Request__r.Final_Approved_Indicator__c
                FROM    Inventory_Request_Line_Item__c
                WHERE   Id = :irLineId
        ];
        if(!inventoryRequestLineItems.isEmpty()) {
            inventoryRequestLineItem = inventoryRequestLineItems[0];
        }
        return inventoryRequestLineItem;
    }

    /**
     * Inserts a list of assets based on Inventory_Request_Line_Item.Qty_of_assets_to_create__c.
     * Will also attempt to lock the Parent IR if all assets have been created for all line items.
     * Finally will attempt to update the unique serial number counter to the latest (stored in a custom setting).
     *
     * @param irLineItemId  The Inventory_Request_Line_Item__c Id.
     * @return A List of Created Asset sObjects
     */
    public static List<Asset> insertAssetsFromIrLineItem(   Inventory_Request_Line_Item__c irLineItem,
                                                            String recordTypeName) {
        List<Asset> assetsInserted = new List<Asset>();
        if(irLineItem != null) {
            Id assetSoftwareRtId = Schema.SObjectType.Asset.getRecordTypeInfosByName().get(recordTypeName).getRecordTypeId();
            //Software_Assets_Config__c configSettings = CustomSettingsSvc.getSoftwareAssetsConfigSettings(UserInfo.getUserId());
            Software_Assets_Config__c configSettings = Software_Assets_Config__c.getOrgDefaults();
            Decimal serialNumber = configSettings.Latest_Serial_Number__c;
            for(Integer i = 0; i < irLineItem.Qty_of_assets_to_create__c; i++) {
                serialNumber += 1;
                Asset asset = new Asset( RecordTypeId = assetSoftwareRtId);
                asset.Name = irLineItem.Product__r.Name;/* + ' '  configSettings.Asset_Name_Prefix__c + serialNumber ;*/
               //------> asset.Description = irLineItem.Product__r.Description;
                asset.Item_Content__c = irLineItem.Product__r.Description;
                asset.SerialNumber = configSettings.Asset_Name_Prefix__c + String.valueOf(serialNumber);
                asset.Product2Id = irLineItem.Product__c;
                asset.Product2Id = irLineItem.Product__c;
                asset.Vendor__c = irLineItem.Vendor__c;
                asset.Quantity = 1;
                asset.ParentId = irLineItem.Inventory_Request__r.Parent_Asset__c;
                asset.AccountId = irLineItem.Inventory_Request__r.Account__c;
                asset.DBA_Text__c = irLineItem.Inventory_Request__r.Account__r.Name;
                asset.InstallDate = irLineItem.Received_Date__c;
                asset.Date_Delivered__c = irLineItem.Received_Date__c;
                asset.Purchase_Order_Number__c = irLineItem.Inventory_Request__r.PO_Number__c;
                asset.Inventory_Request__c = irLineItem.Inventory_Request__c;
                asset.Inventory_Request_Line_Item__c = irLineItem.Id;
               //---- asset.Software_Upgraded_Date__c = Date.today();
                asset.Status = 'Available';
                assetsInserted.add(asset);
            }
            insert assetsInserted;
            if(shouldIrBeLocked(irLineItem)) {
                List<Database.Error> errors = lockInventoryRequest(irLineItem.Inventory_Request__c);
            }
            configSettings.Latest_Serial_Number__c = serialNumber;
            //@TODO double check this auto incrementer
            //configSettings = [SELECT Id,Name,Latest_Serial_Number__c  FROM Software_Assets_Config__c WHERE SetupOwnerId = :UserInfo.getUserId()];
            upsert configSettings;
        }
        return assetsInserted;
    }
    /**
     * Gets the IR Request Progress Settings meta-data for use with the 'path'.
     *
     * @param devName   The developername of the custom metadata type.
     * @return a List of Inventory_Request_Progress_Indicator__mdt meta sta types.
     *
     * @todo move to CustomMetadataSvc
     */
    public static List <Inventory_Request_Progress_Indicators__mdt> retrieveInventoryRequestProgressSettingsMeta
                                                                                                (String devName) {
        List<Inventory_Request_Progress_Indicators__mdt> settings;
        String soql = '';
        soql += ' SELECT  Id, DeveloperName, MasterLabel, Order__c, Value__c,DisplayValue__c,Description__c,';
        soql += '         Current__c ';
        soql += ' FROM    Inventory_Request_Progress_Indicators__mdt ';
        if (devName != null) {
            soql += ' WHERE DeveloperName = :devName ';
        }
        soql += ' ORDER BY Order__c ASC ';
        settings = (List<Inventory_Request_Progress_Indicators__mdt>) Database.query(soql);
        return settings;
    }
    /**
     * Determines if an inventory request should be locked (ie. is it a status of 'PO Fulfilled'.
     *
     * @param inventoryRequestLineItem  The inventory request line item sObject to eval.
     * @return                          True if it should be locked, otherwise false.
     */
    public static Boolean shouldIrBeLocked(Inventory_Request_Line_Item__c inventoryRequestLineItem) {
        Boolean lockIt = false;
        if(inventoryRequestLineItem.Inventory_Request__r.Status__c == 'PO Fulfilled') {
            lockIt = true;
        }
        return lockIt;
    }
    /**
     * Lock's the Inventory Request (via Approval.lock)
     *
     * @param inventoryRequestId The Id of the Inventory_Request__c.
     * @return A List of Database.Error objects if an Error, otherwise an empty list.
     */
    public static List<DataBase.Error> lockInventoryRequest(Id inventoryRequestId) {
        List<Database.Error> errors = new List<Database.Error>();
        try {
            Approval.LockResult alr = Approval.lock(inventoryRequestId);
            if (!alr.isSuccess()) {
                for (Database.Error err : alr.getErrors()) {
                    errors.add(err);
                    System.debug('The following error has occurred.');
                    System.debug(err.getStatusCode() + ': ' + err.getMessage());
                    System.debug('Account fields that affected this error: ' + err.getFields());
                }
            }
        } catch (System.NoAccessException nae) {
             System.debug(LoggingLevel.ERROR,nae);
        }
        return errors;
    }

    /**
     * Determine if the Inventory request is locked (via Approval.isLocked)
     *
     * @param inventoryRequestId    The Inventory_Request__c id.
     * @return                      True if it is locked, otherwise false. 
     */
    public static Boolean checkIfIrIsLocked(Id inventoryRequestId) {
        Boolean success = false;
        try {
            success = Approval.isLocked(inventoryRequestId);
        } catch (System.NoAccessException nae) {
            System.debug(LoggingLevel.ERROR, nae);
        }
        return success;
    }
}