objects/Asset.object
<CustomObject>
    <fields>
        <fullName>Software__c</fullName>
        <label>Gameset</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Software</valueSetName>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Software</fullName>
        <active>true</active>
        <label>Software</label>
    </recordTypes>
    <recordTypes>
        <fullName>VGT</fullName>
        <active>true</active>
        <label>VGT</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Municipality__c.object
<CustomObject>
    <label>Municipality</label>
    <nameField>
        <label>Municipality Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Municipalities</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

globalValueSets/Software.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>ARI-1.01-62959-GS2</fullName>
    </customValue>
    <customValue>
        <fullName>ATI_2.4.1.18_Win12_v1.2_GP4_88</fullName>
    </customValue>
    <customValue>
        <fullName>ATI_2.4.1.18_Win12_v1.2_GP4_90</fullName>
    </customValue>
    <customValue>
        <fullName>ATI_2.4.1.18_Win12_v1.2_GP4_92</fullName>
    </customValue>
    <customValue>
        <fullName>ATI_2.4.1.18_Win31_v1.2_GP4_88</fullName>
    </customValue>
    <customValue>
        <fullName>ATI_2.4.1.18_Win31_v1.2_GP4_90</fullName>
    </customValue>
    <customValue>
        <fullName>ATI_2.4.1.18_Win31_v1.2_GP4_92</fullName>
    </customValue>
    <customValue>
        <fullName>ATI_2.4.1.21_MARSXP_88</fullName>
    </customValue>
    <customValue>
        <fullName>ATI_2.4.1.21_MARSXP_90</fullName>
    </customValue>
    <customValue>
        <fullName>ATI_2.4.1.21_MARSXP_92</fullName>
    </customValue>
    <customValue>
        <fullName>ATI_IL_2.4.0.21_GP1_88</fullName>
    </customValue>
    <customValue>
        <fullName>ATI_IL_2.4.0.21_GP1_90</fullName>
    </customValue>
    <customValue>
        <fullName>ATI_IL_2.4.0.21_GP1_92</fullName>
    </customValue>
    <customValue>
        <fullName>ATI_IL_2.4.0.21_GP3_88</fullName>
    </customValue>
    <customValue>
        <fullName>ATI_IL_2.4.0.21_GP3_90</fullName>
    </customValue>
    <customValue>
        <fullName>ATI_IL_2.4.0.21_GP3_92</fullName>
    </customValue>
    <customValue>
        <fullName>ATI_IL_2.4.0.21_TP_GP1_90</fullName>
    </customValue>
    <customValue>
        <fullName>ATI_IL_2.4.0.21_TP_GP1_92</fullName>
    </customValue>
    <customValue>
        <fullName>ATI_IL_2.4.1.18_GP1_92</fullName>
    </customValue>
    <customValue>
        <fullName>ATI_IL_2.4.1.18_GP3_88</fullName>
    </customValue>
    <customValue>
        <fullName>ATI_IL_2.4.1.18_GP3_90</fullName>
    </customValue>
    <customValue>
        <fullName>ATI_IL_2.4.1.18_GP3_92</fullName>
    </customValue>
    <customValue>
        <fullName>ATI_IL_2.4.1.18_MARSXP_88</fullName>
    </customValue>
    <customValue>
        <fullName>ATI_IL_2.4.1.18_MARSXP_90</fullName>
    </customValue>
    <customValue>
        <fullName>ATI_IL_2.4.1.18_MARSXP_92</fullName>
    </customValue>
    <customValue>
        <fullName>ATI_IL_2.4.1.18_Win12_GP1_92</fullName>
    </customValue>
    <customValue>
        <fullName>ATI_IL_2.4.1.18_Win12_GP3_88</fullName>
    </customValue>
    <customValue>
        <fullName>ATI_IL_2.4.1.18_Win12_GP3_90</fullName>
    </customValue>
    <customValue>
        <fullName>ATI_IL_2.4.1.18_Win12_GP3_92</fullName>
    </customValue>
    <customValue>
        <fullName>ATI_IL_2.4.1.18_Win31_GP3_90</fullName>
    </customValue>
    <masterLabel>Software</masterLabel>
</GlobalValueSet>

classes/TEST_BatchVGTSoftwareToAsset.cls
@IsTest
private class TEST_BatchVGTSoftwareToAsset{

    public static String UNAMEADMIN             = 'acceltestadmin@accelentertainment.com';
    public static String ACCOUNTNAME            = 'Blah Random UT Account';
    public static Date CURRENT_DATE_OVERRIDE    = Date.today();

    public static final Integer NUMBER_OF_PRODUCTS = 2;
    public static final Integer NUMBER_OF_IR_LINES = 5;
    public static final Integer NUMBER_OF_MUNIS = 2;
    public static final Integer NUMBER_OF_ACCTS_PER_MUNI = 2;
    public static final Integer NUMBER_OF_ASSETS_PER_ACCT = 10;

    @TestSetup
    static void setup() {

        User adminUser = TestUtils.getUserForTest(UNAMEADMIN);
        Date TODAY = CURRENT_DATE_OVERRIDE;

        System.runAs(adminUser) {

            Schema.DescribeFieldResult assetSoftwareDr = Asset.Software__c.getDescribe();
            List<Schema.PicklistEntry> assetSoftwarePlEntries = assetSoftwareDr.getPicklistValues();


            List<Municipality__c> munis = TestUtils.createMunicipalities('UT MUNI', NUMBER_OF_MUNIS);
            List<Account> accounts = new List<Account>();
            List<Asset> assets = new List<Asset>();
            Integer z = 0;
            for (Municipality__c municipality : munis) {
                for (Integer i = 0; i < NUMBER_OF_ACCTS_PER_MUNI; i++) {
                    Account account = TestUtils.buildAccount('accel test acct:' + z + 'a', municipality.id,
                            'Accel Account');
                    account.ShippingState = 'IL';
                    accounts.add(account);
                    z++;
                }
            }
            insert accounts;
            String rtDevName = 'VGT';
            for (Account account : accounts) {
                for(Integer i=0; i < NUMBER_OF_ASSETS_PER_ACCT; i++) {
                    Asset asset = TestUtils.buildAsset('UT ' + account.Name + ' ' +i+ ' TEST VGT ASSET',
                                    account.Id, rtDevName);
                    //get a random entry
                    Schema.PicklistEntry ple = assetSoftwarePlEntries[i];
                    asset.Software__c = ple.value;
                    assets.add(asset);
                }
            }
           // insert assets;
        }
    }

    @IsTest
    static void test_fireBatch_VGT_SoftwareToAsset_Rollback() {

        User adminUser = TestUtils.getUserForTest(UNAMEADMIN);
        Boolean bCommit = false;

        List<ASset> swAssets = [SELECT Id FROM Asset WHERE RecordType.Name = 'Software'];
        if(!swAssets.isEmpty()) {
            delete swAssets;
        }

        System.runAs(adminUser) {
            Test.startTest();
                //TEST rollback
                BatchVGTSoftwareToAsset b = new BatchVGTSoftwareToAsset(null,bCommit);
                Database.executeBatch(b);
            Test.stopTest();

//            swAssets = [SELECT Id FROM Asset WHERE RecordType.Name = 'Software'];
            //System.assert(swAssets.isEmpty());
        }
    }
}