objects/Asset.object
<CustomObject>
    <fields>
        <fullName>GP_Manufacturer__c</fullName>
        <description>Manufacturer Field from GP Integration</description>
        <label>GP_Manufacturer</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Notes__c</fullName>
        <label>Notes</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>SAS__c</fullName>
        <label>SAS</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Route__c.object
<CustomObject>
    <description>Example object to house routes and routing of collections</description>
    <fields>
        <fullName>Processing_Location__c</fullName>
        <label>Processing Location</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Processing_Location</valueSetName>
        </valueSet>
    </fields>
    <label>Route</label>
    <nameField>
        <label>Route Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Routes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Route_Processing_Sheet__c.object
<CustomObject>
    <description>Example digitization of the route processing sheet</description>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account DBA</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Route Processing Sheets</relationshipLabel>
        <relationshipName>Route_Processing_Sheets</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Cassette_100_Note_Count_Outbound__c</fullName>
        <label>$100 Note Count Outbound</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Cassette_1_Note_Count_Outbound__c</fullName>
        <label>$1 Note Count Outbound</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Cassette_20_Note_Count_Outbound__c</fullName>
        <label>$20 Note Count Outbound</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Cassette_50_Note_Count_Outbound__c</fullName>
        <defaultValue>0</defaultValue>
        <label>$50 Note Count Outbound</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Cassette_5_Note_Count_Outbound__c</fullName>
        <label>$5 Note Count Outbound</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Collection_Type__c</fullName>
        <description>Copied down from the parent Route Schedule Account.</description>
        <inlineHelpText>Copied down from the parent Route Schedule Account.</inlineHelpText>
        <label>Collection Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Collection_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>End_RT_Replenishment_Date__c</fullName>
        <description>POC For Billy</description>
        <inlineHelpText>POC For Billy</inlineHelpText>
        <label>End RT Replenishment Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>End_RT_Replenishment_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>POC for Billy</description>
        <inlineHelpText>POC For Billy</inlineHelpText>
        <label>End RT Replenishment User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Route_Processing_SheetsFxsQ</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>End_VGT_Collection_Date__c</fullName>
        <description>POC For Billy</description>
        <inlineHelpText>POC For Billy</inlineHelpText>
        <label>End VGT Collection Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>End_VGT_Collection_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>POC For Billy</description>
        <inlineHelpText>POC For Billy</inlineHelpText>
        <label>End VGT Collection User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Route_Processing_Sheets8</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Notes__c</fullName>
        <label>Notes</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Processing_Location__c</fullName>
        <label>Processing Location</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Processing_Location</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Redemption_Asset__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Redemption Asset</label>
        <referenceTo>Asset</referenceTo>
        <relationshipLabel>Route Processing Sheets</relationshipLabel>
        <relationshipName>Route_Processing_Sheets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Route_Fill_Date__c</fullName>
        <description>not sure?</description>
        <inlineHelpText>not sure?</inlineHelpText>
        <label>Route Fill Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Route_Schedule_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Exists in case we want to roll up info to RSA</description>
        <inlineHelpText>Exists in case we want to roll up info to RSA</inlineHelpText>
        <label>Route Schedule Account</label>
        <referenceTo>Route_Schedule_Account__c</referenceTo>
        <relationshipLabel>Route Processing Sheets</relationshipLabel>
        <relationshipName>Route_Processing_Sheets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Route_Schedule__c</fullName>
        <label>Route Schedule</label>
        <referenceTo>Route_Schedule__c</referenceTo>
        <relationshipLabel>Route Processing Sheets</relationshipLabel>
        <relationshipName>Route_Processing_Sheets</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Start_RT_Replenishment_Date__c</fullName>
        <description>POC For Billy</description>
        <inlineHelpText>POC For Billy</inlineHelpText>
        <label>Start RT Replenishment Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Start_RT_Replenishment_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>POC For Billy</description>
        <inlineHelpText>POC For Billy</inlineHelpText>
        <label>Start RT Replenishment User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Route_Processing_Sheets9</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Start_VGT_Collection_Date__c</fullName>
        <description>POC For Billy</description>
        <inlineHelpText>POC For Billy</inlineHelpText>
        <label>Start VGT Collection Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Start_VGT_Collection_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>POC For Billy</description>
        <inlineHelpText>POC For Billy</inlineHelpText>
        <label>Start VGT Collection User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Route_Processing_Sheets7</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Route Processing Sheet</label>
    <nameField>
        <displayFormat>Collection-Id-{000000000}</displayFormat>
        <label>Collection ID Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Route Processing Sheets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Route_Schedule__c.object
<CustomObject>
    <description>Assignment information of a physical route&apos;s locations, collectors, vehicles, and questions for a specific day</description>
    <fields>
        <fullName>Processing_Location__c</fullName>
        <label>Processing Location</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Processing_Location</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Route_Fill_Date__c</fullName>
        <description>Not sure how this is used yet?</description>
        <inlineHelpText>Note sure how this is used yet?</inlineHelpText>
        <label>Route Fill Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Route__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Route to collect</description>
        <label>Route</label>
        <referenceTo>Route__c</referenceTo>
        <relationshipLabel>Route Schedules</relationshipLabel>
        <relationshipName>Route_Schedules</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Route Schedule</label>
    <nameField>
        <label>Route Schedule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Route Schedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Route_Schedule_Account__c.object
<CustomObject>
    <description>POC Junction Route_Schedule__c &lt;----&gt; Account</description>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Account.Accel_VGT_Live_Date__c</field>
                <operation>notEqual</operation>
                <value></value>
            </filterItems>
            <infoMessage>Account Must Have A VGT Live Date</infoMessage>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Route Schedule Accounts</relationshipLabel>
        <relationshipName>Route_Schedule_Accounts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Collection_Type__c</fullName>
        <description>Used for additional fills.</description>
        <inlineHelpText>Used for additional fills.</inlineHelpText>
        <label>Collection Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Collection_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Redemption_Asset_Manual_Override__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Bypasses any update logic of attempted automatic set of Redemption_Type_From_Asset__c and Redemption_Asset__c in preference of allow an admin to manually set it. (BEFORE UPDATE EVENT ONLY)</description>
        <inlineHelpText>Bypasses any update logic of attempted automatic set of Redemption_Type_From_Asset__c and Redemption_Asset__c in preference of allow an admin to manually set it. (BEFORE UPDATE EVENT ONLY)</inlineHelpText>
        <label>Redemption Asset Manual Override</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Redemption_Asset__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Flows to Rps.Redemption_Asset__c. Needed to see which redemption terminal we are using for the unified display. @see clRouteSvc.tagRedemptionTypes(List&lt;Route_Schedule_Account__c&gt; rsas)  (called from RSA Trigger)</description>
        <inlineHelpText>The application redemption terminal.</inlineHelpText>
        <label>Redemption Asset</label>
        <referenceTo>Asset</referenceTo>
        <relationshipLabel>Route Schedule Accounts</relationshipLabel>
        <relationshipName>Route_Schedule_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Redemption_Terminal__c</fullName>
        <description>Use this to select which Redemption Terminal is desired.</description>
        <inlineHelpText>Use this to select which Redemption Terminal is desired. Defaults to RT1</inlineHelpText>
        <label>Redemption Terminal</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>RT1</fullName>
                    <default>true</default>
                    <label>RT1</label>
                </value>
                <value>
                    <fullName>RT2</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Route_Schedule__c</fullName>
        <label>Route Schedule</label>
        <referenceTo>Route_Schedule__c</referenceTo>
        <relationshipLabel>Route Schedule Accounts</relationshipLabel>
        <relationshipName>Route_Schedule_Accounts</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Route Schedule Account</label>
    <nameField>
        <displayFormat>RSA-{00000000}</displayFormat>
        <label>RSA #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Route Schedule Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>Processing_Location__c</fullName>
        <description>Used for Cash Logistics - When an Route schedule is created, it is assigned to a processing location. This is used to determine, when a user of profile CL - Route Processor logs in, what route schedules they see.</description>
        <inlineHelpText>Used for Cash Logistics - When an Route schedule is created, it is assigned to a processing location. This is used to determine, when a user of profile CL - Route Processor logs in, what route schedules they see.</inlineHelpText>
        <label>Processing Location</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Processing_Location</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

globalValueSets/Collection_Type.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Regular - RT &amp; VGT</fullName>
        <default>true</default>
        <label>Regular - RT &amp; VGT</label>
    </customValue>
    <customValue>
        <fullName>Additional Fill – RT &amp; VGT</fullName>
    </customValue>
    <customValue>
        <fullName>Additional Fill – RT Only</fullName>
    </customValue>
    <customValue>
        <fullName>Additional Fill – VGT Only</fullName>
    </customValue>
    <customValue>
        <fullName>Regular - 2nd RT</fullName>
    </customValue>
    <customValue>
        <fullName>Regular - RT Only</fullName>
    </customValue>
    <customValue>
        <fullName>Regular - VGT Only</fullName>
    </customValue>
    <customValue>
        <fullName>Regular - RT Only (Go Lives/RT swaps)</fullName>
        <isActive>false</isActive>
        <label>Regular - RT Only (Go Lives/RT swaps)</label>
    </customValue>
    <description>* Regular – RT &amp; VGT (typical collection involves changing VGT cans and swapping RT Cassettes)﻿
* Additional Fill – RT Only (this collection involves just changing RT Cassettes)﻿
* Additional Fill – VGT Only (this collection involves just swapping VGT cans)﻿
* Additional Fill – RT &amp; VGT (this collection involves changing VGT cans and swapping RT cassettes)
* Regular - 2nd RT (OLD.. not sure?)
* Regular - RT Only (NEW... not sure?)
* Regular - VGT Only (NEW.. not sure?)</description>
    <masterLabel>Collection Type</masterLabel>
</GlobalValueSet>

globalValueSets/Processing_Location.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Burr Ridge</fullName>
    </customValue>
    <customValue>
        <fullName>DEV TEST 1</fullName>
    </customValue>
    <customValue>
        <fullName>Tinley Park</fullName>
    </customValue>
    <customValue>
        <fullName>Peoria</fullName>
    </customValue>
    <customValue>
        <fullName>Springfield</fullName>
    </customValue>
    <customValue>
        <fullName>CW</fullName>
    </customValue>
    <customValue>
        <fullName>Rockford</fullName>
    </customValue>
    <customValue>
        <fullName>Collinsville</fullName>
    </customValue>
    <masterLabel>Processing Location</masterLabel>
</GlobalValueSet>

classes/clRouteSvcTest.cls
@IsTest
private class clRouteSvcTest {
    /**
 * NOTE start / stop test merely there to reset gov limits as creating non cl data takes forever given
 * all the processors / flows and eventually will bust cpu time outs on it's own.
 */
    @TestSetup
    static void setupData() {

        Test.startTest();
        Map<String,Object> mBaseData = clTESTUTILS.createAllNonClData();
        Test.stopTest();

        Map<String,Object> mClData =  clTESTUTILS.createEnd2EndRouteData(mBaseData);
    }

    @IsTest
    static void test_retrieveRouteProcessingSheet() {

        Map<String,Object> mUser = clTESTUTILS.getClUsers();
        User collector = (User)mUser.get(clTESTUTILS.COLLECTOR);
        Date tomorrow = Date.today().addDays(1);
        Route__c route = [SELECT ID From Route__c LIMIT 1];
        Route_Schedule__c routeSchedule = [SELECT Id FROM Route_Schedule__c WHERE Route__c = :route.Id LIMIT 1];
        Route_Processing_Sheet__c rps = [SELECT Id FROM Route_Processing_Sheet__c WHERE Route_Schedule__c = :routeSchedule.Id LIMIT 1];

        Test.startTest();

        System.runAs(collector) {
            Route_Processing_Sheet__c routeProcessingSheet = clRouteSvc.retrieveRouteProcessingSheet(rps.Id);
            System.assertEquals(rps.Id,routeProcessingSheet.Id);
        }

        Test.stopTest();
    }


    @IsTest
    static void test_retrieveRoute() {

        Map<String,Object> mUser = clTESTUTILS.getClUsers();
        User collector = (User)mUser.get(clTESTUTILS.COLLECTOR);
        Route__c rte = [SELECT ID From Route__c LIMIT 1];

        Test.startTest();

        System.runAs(collector) {
            Route__c route = clRouteSvc.retrieveRoute(rte.Id);
            System.assertEquals(route.Id,rte.Id);
        }

        Test.stopTest();
    }

    @IsTest
    static void test_retrieveRoutes() {

        Map<String,Object> mUser = clTESTUTILS.getClUsers();
        User collector = (User)mUser.get(clTESTUTILS.COLLECTOR);

        Test.startTest();

        System.runAs(collector) {
            List<Route__c> routes = clRouteSvc.retrieveRoutes(collector.Id);
            System.assertNotEquals(routes.isEmpty(),true);
        }

        Test.stopTest();
    }

    @IsTest
    static void test_retrieveAllRoutes() {

        Map<String,Object> mUser = clTESTUTILS.getClUsers();
        User collector = (User)mUser.get(clTESTUTILS.COLLECTOR);

        Test.startTest();

        System.runAs(collector) {
            List<Route__c> routes = clRouteSvc.retrieveAllRoutes();
            System.assertNotEquals(routes.isEmpty(),true);
        }

        Test.stopTest();
    }

    @IsTest
    static void test_retrieveAllRoutesWithCollectionDates() {

        Map<String,Object> mUser = clTESTUTILS.getClUsers();
        User collector = (User)mUser.get(clTESTUTILS.COLLECTOR);

        Test.startTest();

        System.runAs(collector) {
            List<Route__c> routes = clRouteSvc.retrieveAllRoutesWithRpsRecordsWithCollectionDates();
            System.assertNotEquals(routes.isEmpty(),true);
        }

        Test.stopTest();
    }

    @IsTest
    static void test_retrieveAllRouteRpsCollectionDates() {

        Map<String,Object> mUser = clTESTUTILS.getClUsers();
        //User collector = (User)mUser.get(clTESTUTILS.COLLECTOR);
        Route__c route = [SELECT Id FROM Route__c LIMIT 1];

        Test.startTest();

            Set<Date> collectionDates = clRouteSvc.retrieveAllRouteRpsCollectionDates(route.Id);
            System.assertNotEquals(collectionDates.isEmpty(),true);


        Test.stopTest();
    }

    @IsTest
    static void test_retrieveRpsFillDataResults() {

        Map<String,Object> mUser = clTESTUTILS.getClUsers();
        Route__c route = [SELECT ID From Route__c LIMIT 1];
        Route_Schedule__c routeSchedule = [SELECT Id FROM Route_Schedule__c WHERE Route__c = :route.Id LIMIT 1];

        List<Route_Processing_Sheet__c> rpss = [
                SELECT Id,Notes__c,Processing_Location__c,Route_Fill_Date__c
                FROM Route_Processing_Sheet__c
                WHERE Route_Schedule__c = :routeSchedule.Id
        ];
        for(Route_Processing_Sheet__c rps : rpss) {
            rps.Route_Fill_Date__c = Date.today();
            rps.Cassette_1_Note_Count_Outbound__c = 1;
            rps.Cassette_5_Note_Count_Outbound__c = 5;
            rps.Cassette_20_Note_Count_Outbound__c = 20;
            rps.Cassette_50_Note_Count_Outbound__c = 50;
            rps.Cassette_100_Note_Count_Outbound__c = 100;
        }
        update rpss;
        for(Route_Processing_Sheet__c rps : rpss) {
            System.debug('---> TEST RPS: '+rps);
        }

        Test.startTest();
        clRouteSvc.ProcessingFillSummary pfs = clRouteSvc.retrieveRpsFillDataResults(clTESTUTILS.DEFAULT_PROCESSING_LOC);
        Test.stopTest();
    }

    @IsTest
    static void test_tagRpsUtilizationDates() {

        Map<String,Object> mUser = clTESTUTILS.getClUsers();
        //User collector = (User)mUser.get(clTESTUTILS.COLLECTOR);
        Map<Id,Route_Processing_Sheet__c> mAllRps = new Map<Id,Route_Processing_Sheet__c>([
                SELECT Id FROM Route_Processing_Sheet__c
        ]);
        Route_Processing_Sheet__c rps = mAllRps.values()[0];
        rps = clRouteSvc.retrieveRouteProcessingSheet(rps.Id);

        Test.startTest();

        //System.runAs(collector) {  @todo cross reference on entity error is this a real issue?

        rps = clRouteSvc.tagRpsUtilizationDates(rps,clRpsDateEnum.START_RT_REPLENISHMENT_DATE);
        System.assert(rps.Start_RT_Replenishment_Date__c.date() == Date.today());
        System.assert(rps.Start_RT_Replenishment_User__c == UserInfo.getUserId());

        rps = clRouteSvc.tagRpsUtilizationDates(rps,clRpsDateEnum.END_RT_REPLENISHMENT_DATE);
        System.assert(rps.End_RT_Replenishment_Date__c.date() == Date.today());
        System.assert(rps.End_RT_Replenishment_User__c == UserInfo.getUserId());

        rps = clRouteSvc.tagRpsUtilizationDates(rps,clRpsDateEnum.START_VGT_COLLECTION_DATE);
        System.assert(rps.Start_VGT_Collection_Date__c.date() == Date.today());
        System.assert(rps.Start_VGT_Collection_User__c == UserInfo.getUserId());

        rps = clRouteSvc.tagRpsUtilizationDates(rps,clRpsDateEnum.END_VGT_COLLECTION_DATE);
        System.assert(rps.End_VGT_Collection_Date__c.date() == Date.today());
        System.assert(rps.End_VGT_Collection_User__c == UserInfo.getUserId());

        Test.stopTest();
    }

    @IsTest
    private static void test_emailStuff() {

        Contact c = new Contact(LastName = 'dummy', Email='no-reply@accelentertainment.com');
        insert c;

        String testRegion = clTESTUTILS.DEFAULT_PROCESSING_LOC;

        Test.startTest();

        clRouteSvc.ProcessingFillSummary processingFillSummary = clRouteSvc.retrieveRpsFillDataResults(testRegion);
        List<clRouteSvc.EmailData> emailDatas = new clQueueableProcessFillSummaryEmail(testRegion).buildEmails(processingFillSummary,c.Id);
        List<Messaging.SendEmailResult> emailResults = clRouteSvc.sendEmailTemplates(emailDatas);

        Test.stopTest();
    }


    @IsTest
    private static void test_tagRedemptionAssets() {

        Route_Schedule__c routeSchedule = [SELECT Id FROM Route_Schedule__c LIMIT 1];
        routeSchedule = clRouteScheduleSvc.retrieveRouteSchedule(routeSchedule.Id);

        Account account = new Account( Name='Test UT ACCOUNT', ShippingState = 'IL');
        insert account;

        Asset rtAsset =   TestUtils.buildAsset('Sample RT Asset1', account.Id, AssetSvc.ASSET_RT_REDEMPTION);
        rtAsset.GP_Manufacturer__c = 'NRT';
        rtAsset.SAS__c = 'RT1';
        insert rtAsset;

        Test.startTest();

        //  (1)  Test insert. 1 RT ASset.  Regular 2nd Collection Type
        Route_Schedule_Account__c rsa = new Route_Schedule_Account__c(
                Route_Schedule__c = routeSchedule.Id,
                Account__c = account.Id,
                Collection_Type__c = clFillSvc.REGULAR_2ND_RT_COLLECTION_TYPE
        );
        insert rsa;
        rsa = clRouteScheduleAccountSvc.retrieveRouteScheduleAccountsByIds( new Set<Id> {rsa.Id})[0];
        System.assert(rsa.Redemption_Asset__c == rtAsset.Id);

        //  (2)  Test insert. 1 RT Asset.  Any of the Additional Fill Collection Types
        String additionalFillCollectionType;
        List<String> types = new List<String>();
        types.addAll(clFillSvc.ADDITIONAL_FILL_COLLECTION_TYPES);
        additionalFillCollectionType = types[0];
        rsa = new Route_Schedule_Account__c(
                Route_Schedule__c = routeSchedule.Id,
                Account__c = account.Id,
                Collection_Type__c = additionalFillCollectionType
        );
        insert rsa;
        rsa = clRouteScheduleAccountSvc.retrieveRouteScheduleAccountsByIds( new Set<Id> {rsa.Id})[0];
        System.assert(rsa.Redemption_Asset__c == rtAsset.Id);


        //  (3) 2 RT assets Regular Second.
        Asset rtAsset2 =   TestUtils.buildAsset('Sample RT Asset2', account.Id, AssetSvc.ASSET_RT_REDEMPTION);
        rtAsset2.GP_Manufacturer__c = 'M3T';
        rtAsset2.SAS__c = 'RT2';
        insert rtAsset2;
        rsa = new Route_Schedule_Account__c(
                Route_Schedule__c = routeSchedule.Id,
                Account__c = account.Id,
                Collection_Type__c = clFillSvc.REGULAR_2ND_RT_COLLECTION_TYPE,
                Redemption_Terminal__c = clRouteSvc.ASSET_SAS_RT_POSITION_2
        );
        insert rsa;
        rsa = clRouteScheduleAccountSvc.retrieveRouteScheduleAccountsByIds( new Set<Id> {rsa.Id})[0];
        System.assert(rsa.Redemption_Asset__c == rtAsset2.Id);


        //  (4) 2 RT assets Additional Fill RT2
        delete rtAsset2;
       // delete rsa;
        Asset rtAsset3 =   TestUtils.buildAsset('Sample RT Asset2', account.Id, AssetSvc.ASSET_RT_REDEMPTION);
        rtAsset3.GP_Manufacturer__c = 'M3T';
        rtAsset3.SAS__c = 'RT2';
        insert rtAsset3;
        rsa = new Route_Schedule_Account__c(
                Route_Schedule__c = routeSchedule.Id,
                Account__c = account.Id,
                Collection_Type__c = additionalFillCollectionType,
                Redemption_Terminal__c = clRouteSvc.ASSET_SAS_RT_POSITION_2
        );
        insert rsa;
        rsa = clRouteScheduleAccountSvc.retrieveRouteScheduleAccountsByIds( new Set<Id> {rsa.Id})[0];
        System.assert(rsa.Redemption_Asset__c == rtAsset3.Id);


        //  (5a) 2 RT assets Additional Fill RT1 update
        rsa.Redemption_Terminal__c = clRouteSvc.ASSET_SAS_RT_POSITION_1;
        update rsa;
        rsa = clRouteScheduleAccountSvc.retrieveRouteScheduleAccountsByIds( new Set<Id> {rsa.Id})[0];
        System.assert(rsa.Redemption_Asset__c == rtAsset.Id);


        //  (6a) 2 RT assets Additional Fill RT1 update manual override
        rsa.Redemption_Terminal__c = clRouteSvc.ASSET_SAS_RT_POSITION_1;
        rsa.Redemption_Asset_Manual_Override__c = true;
        rsa.Redemption_Asset__c = rtAsset3.Id;
        update rsa;
        rsa = clRouteScheduleAccountSvc.retrieveRouteScheduleAccountsByIds( new Set<Id> {rsa.Id})[0];
        System.assert(rsa.Redemption_Asset__c == rtAsset3.Id);

        Test.stopTest();
    }
}