objects/Case.object
<CustomObject>
    <fields>
        <fullName>Age_of_Case_Hours__c</fullName>
        <formula>if(ispickval(Status, &quot;Closed&quot;), 
(((ClosedDate - CreatedDate)*24)*60), 
(((Now() - CreatedDate)*24)*60))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Age of Case (Minutes)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Assigned_Resource__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Assigned Resource</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Cases2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Service_Appointment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Service Appointment</label>
        <referenceTo>ServiceAppointment</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Work_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Work Order</label>
        <referenceTo>WorkOrder</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Custom_Notifications_Sent__c.object
<CustomObject>
    <description>An Object to hold references to desktop and mobile custom notifications sent (so as to prevent sending dup notifications)</description>
    <fields>
        <fullName>Notification_Type__c</fullName>
        <description>The type of notification, either Manual (user clicked the send icon) or Automated.</description>
        <inlineHelpText>The type of notification, either Manual (user clicked the send icon) or Automated.The type of notification, either Manual (user clicked the send icon) or Automated.</inlineHelpText>
        <label>Notification Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Manual</fullName>
                    <default>true</default>
                    <label>Manual</label>
                </value>
                <value>
                    <fullName>Automated</fullName>
                </value>
                <value>
                    <fullName>Event</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Service_Appointment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>If the parent record  (ie target id) is a Service Appointment, this will be populated.</description>
        <inlineHelpText>If the parent record  (ie target id) is a Service Appointment, this will be populated.</inlineHelpText>
        <label>Service Appointment</label>
        <referenceTo>ServiceAppointment</referenceTo>
        <relationshipLabel>Custom Notifications Sent</relationshipLabel>
        <relationshipName>Custom_Notifications_Sent</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Custom Notifications Sent</label>
    <nameField>
        <displayFormat>N-{0000000}</displayFormat>
        <label>Notification #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Custom Notifications Sent</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/ServiceAppointment.object
<CustomObject>
    <fields>
        <fullName>Pending_Acceptance_Time__c</fullName>
        <formula>if(isblank(Time_Accepted__c),
((( Now() - CreatedDate)*24)*60),0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Pending Acceptance Time</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Work_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Work Order</label>
        <referenceTo>WorkOrder</referenceTo>
        <relationshipLabel>Service Appointments</relationshipLabel>
        <relationshipName>Service_Appointments</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Service</fullName>
        <active>true</active>
        <label>Service</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Svc_Utility_Bar_Settings__mdt.object
<CustomObject>
    <description>Custom metadata settings to configure utility items for the Service Cloud Console.</description>
    <fields>
        <fullName>Case_Created_Override__c</fullName>
        <inlineHelpText>In addition to profile this will look for a name in the createdby of the case  ie OR CreatedBy.Name like &apos;%Nendza%</inlineHelpText>
        <label>Case Created Override</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Notification_Msg_Body__c</fullName>
        <defaultValue>&quot;Please be sure to acknowledge all service appointments on your FSL schedule, thank you.&quot;</defaultValue>
        <description>The Body in the notification sent to a mobile device or SFDC Desktop bell notification.</description>
        <inlineHelpText>The Body in the notification sent to a mobile device or SFDC Desktop bell notification.</inlineHelpText>
        <label>Notification Msg Body</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Notification_Msg_Send_Age_Mins__c</fullName>
        <defaultValue>3</defaultValue>
        <description>The criteria of the Amt of minutes a notification should be sent in.</description>
        <inlineHelpText>The criteria of the Amt of minutes a notification should be sent in.</inlineHelpText>
        <label>Notification Msg Send Age (Mins)</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Notification_Msg_Title__c</fullName>
        <defaultValue>&quot;Service Appointment Acknowledgement Required!&quot;</defaultValue>
        <description>The Title in the notification sent to a mobile device or SFDC Desktop bell notification.</description>
        <inlineHelpText>The Title in the notification sent to a mobile device or SFDC Desktop bell notification.</inlineHelpText>
        <label>Notification Msg Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Profile_Names_to_Watch__c</fullName>
        <label>Profile Names to Watch</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Svc Utility Bar Setting</label>
    <pluralLabel>Svc Utility Bar Settings</pluralLabel>
</CustomObject>

classes/QueueableSvcAutomatedNotifications.cls
/**
 * The class will run on an interval as determined by it's scheduling class (probably every minute).
 * It will looking for not dispatched SAs that have been available for 3-4 for minutes and send an automated
 * notification.
 *
 * @see Svc_Utility_Bar_Settings__mdt
 * @see Sch_QueueableSvcAutomationNotifications
 * @see CustomNotificationsSvc
 */
global class QueueableSvcAutomatedNotifications implements Queueable {

    static final String                         META_SETTING_NOT_DISPATCHED = 'Accepted_But_Not_En_route';
    static final String                         NOTIFICATION_API_NAME       = 'TEST_SERVICE_WATCHDOG_NOTIFICATION';
    static Svc_Utility_Bar_Settings__mdt        notDispatchedMdt;

    //  Mostly query defaults.
    static List<String>                         profileNamesToWatch   = new List<String>{'Accel Call Center'};
    static List<String>                         caseStatusesToExclude = new List<String>{'Closed'};
    static List<String>                         svcApptStatusesToFind = new List<String>{'Scheduled', 'None'};
    static String                               caseCreatedByOverride = null;
    static Integer                              iMaxMinutesBeforeSend = 2;
    static Date                                 svcApptCreatedDate    = Date.today().addDays(-1);
    static String                               notificationType      = 'Automated';
    static String                               alertType             = 'NOT_DISPATCHED';

    //  Retrieve MDT for dynamic query params
    static {
        notDispatchedMdt = (Svc_Utility_Bar_Settings__mdt) CustomMetadataSvc.retrieveCustomSearchMeta(
                Svc_Utility_Bar_Settings__mdt.getSObjectType(), META_SETTING_NOT_DISPATCHED);

        profileNamesToWatch     = notDispatchedMdt?.Profile_Names_to_Watch__c != null ? notDispatchedMdt.Profile_Names_to_Watch__c.split(',') : profileNamesToWatch;
        caseCreatedByOverride   = notDispatchedMdt?.Case_Created_Override__c != null ? notDispatchedMdt.Case_Created_Override__c : caseCreatedByOverride;
        iMaxMinutesBeforeSend   = notDispatchedMdt?.Notification_Msg_Send_Age_Mins__c != null ? Integer.valueOf(notDispatchedMdt.Notification_Msg_Send_Age_Mins__c) : iMaxMinutesBeforeSend;
    }

    /**
     * Implments the queueable execute interface.
     *
     * @param ctx The Queueable context.
     */
    global void execute(QueueableContext ctx){
        System.debug(LoggingLevel.INFO, '---> in queuableSvcAutomations with ctx: '+ctx + ' settings='+notDispatchedMdt);
        processNotDispatched();
    }

    /**
     * Retrieves not dispatched service appointments that have not already had automated sends and fit within the criteria.
     *
     * ie. Case status ['Closed'], Created date today or yesterday, Service Appointment Status ['Scheduled','None'],
     * Pending acceptance time >= dyna setting in MDT ie. 2 or 3 minutes (Because the scheduled job runs every 1 minute
     * so there is some lag time.
     *
     * Use these service appointments to send custom notifications and ultimately record the send
     * in Custom_Notifications_Sent__c
     *
     * @see ServiceAppointmentSvc
     * @see CustomNotificationsSvc
     */
    public void processNotDispatched() {

        List<ServiceAppointment> serviceAppointments = [
                SELECT Id,Work_Order__r.Case.Assigned_Resource__c
                FROM ServiceAppointment
                WHERE Status                        IN  :svcApptStatusesToFind
                AND CreatedDate                     >=  :svcApptCreatedDate
                AND Work_Order__r.Case.Status   NOT IN  :caseStatusesToExclude
                AND Pending_Acceptance_Time__c      >=  :iMaxMinutesBeforeSend
                AND (CreatedBy.Profile.Name IN :profileNamesToWatch OR CreatedBy.Name LIKE :caseCreatedByOverride )
                AND Id NOT IN (
                        SELECT Service_Appointment__c
                        FROM Custom_Notifications_Sent__c
                        WHERE Notification_Type__c = :notificationType
                )
                ORDER BY Work_Order__r.Case.Age_of_Case_Hours__c DESC
        ];
        System.debug(LoggingLevel.INFO, '----> queueable: found ' + serviceAppointments.size() +
                ' Service Appointments meeting initial not dispatched criteria : ' + serviceAppointments);

        if (!serviceAppointments.isEmpty()) {
            ServiceAppointmentSvc.sendServiceAppointmentAlerts( serviceAppointments,alertType, notificationType,
                                                                NOTIFICATION_API_NAME, notDispatchedMdt.Notification_Msg_Title__c,
                                                                notDispatchedMdt.Notification_Msg_Body__c);
        }
    }
}