objects/Case.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Choose the Location destination of the part, VGT, RT, etc.</description>
        <label>Location to Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Cases (Location to Name)</relationshipLabel>
        <relationshipName>Cases2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/AccelEditorAccountLookupFieldPickerTest.cls
@isTest
private with sharing class AccelEditorAccountLookupFieldPickerTest {

    @isTest
    static void test_getDefaultValue() {

        VisualEditor.DesignTimePageContext context = new VisualEditor.DesignTimePageContext();
        context.entityName = 'Account';
        AccelEditorAccountLookupFieldPicker picker = new AccelEditorAccountLookupFieldPicker(context);

        Test.startTest();
        VisualEditor.DataRow defaultValue = picker.getDefaultValue();
        Test.stopTest();

        System.assertNotEquals(null,defaultValue);
    }

    @isTest
    static void test_getValues_for_Case() {

        VisualEditor.DesignTimePageContext context = new VisualEditor.DesignTimePageContext();
        context.entityName = 'Case';
        AccelEditorAccountLookupFieldPicker picker = new AccelEditorAccountLookupFieldPicker(context);

        Test.startTest();
        VisualEditor.DynamicPickListRows plValues = picker.getValues();
        Test.stopTest();

        System.assert(plValues.size() > 0, 'No parent picklist values found for Account');

        Boolean foundAccountId = false;
        for(VisualEditor.DataRow dataRow : plValues.getDataRows()) {
            if(dataRow.getValue() == 'AccountId') {
                foundAccountId = true;
            }
        }
        System.assert(foundAccountId,' Could not find accountId on case');
    }

    @isTest
    static void test_getValues_for_Project() {

        VisualEditor.DesignTimePageContext context = new VisualEditor.DesignTimePageContext();
        context.entityName = 'Project__c';
        AccelEditorAccountLookupFieldPicker picker = new AccelEditorAccountLookupFieldPicker(context);

        Test.startTest();
        VisualEditor.DynamicPickListRows plValues = picker.getValues();
        Test.stopTest();

        System.assert(plValues.size() > 0, 'No parent picklist values found for Account');

        Boolean foundAccountId = false;
        for(VisualEditor.DataRow dataRow : plValues.getDataRows()) {
            if(dataRow.getValue() == 'Account__c') {
                foundAccountId = true;
            }
        }
       System.assert(foundAccountId,' Could not find account__c on project');
    }

    @isTest
    static void test_getValues_for_EmailStatus() {

        VisualEditor.DesignTimePageContext context = new VisualEditor.DesignTimePageContext();
        context.entityName = 'EmailStatus';

        AccelEditorAccountLookupFieldPicker picker = new AccelEditorAccountLookupFieldPicker(context);

        Test.startTest();
        VisualEditor.DynamicPickListRows plValues = picker.getValues();
        Test.stopTest();

        System.assert(plValues.size() == 0, 'We should have no account lookups on EmailStatus');
        
    }
}