objects/Cash_Logistics_Setting__mdt.object
<CustomObject>
    <description>All Configurable Settings for the Cash Logistics Experience Cloud</description>
    <label>Cash Logistics Experience Cloud Setting</label>
    <pluralLabel>Cash Logistics Experience Cloud Settings</pluralLabel>
</CustomObject>

objects/Route__c.object
<CustomObject>
    <description>Example object to house routes and routing of collections</description>
    <fields>
        <fullName>Processing_Location__c</fullName>
        <label>Processing Location</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Processing_Location</valueSetName>
        </valueSet>
    </fields>
    <label>Route</label>
    <nameField>
        <label>Route Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Routes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Route_Schedule__c.object
<CustomObject>
    <description>Assignment information of a physical route&apos;s locations, collectors, vehicles, and questions for a specific day</description>
    <fields>
        <fullName>Collector_1__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Collector #1</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Route_Schedules</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Processing_Location__c</fullName>
        <label>Processing Location</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Processing_Location</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Route__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Route to collect</description>
        <label>Route</label>
        <referenceTo>Route__c</referenceTo>
        <relationshipLabel>Route Schedules</relationshipLabel>
        <relationshipName>Route_Schedules</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Collector #2</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Route_Schedules1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Route Schedule</label>
    <nameField>
        <label>Route Schedule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Route Schedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Route_Schedule_Account__c.object
<CustomObject>
    <description>POC Junction Route_Schedule__c &lt;----&gt; Account</description>
    <fields>
        <fullName>Route_Schedule__c</fullName>
        <label>Route Schedule</label>
        <referenceTo>Route_Schedule__c</referenceTo>
        <relationshipLabel>Route Schedule Accounts</relationshipLabel>
        <relationshipName>Route_Schedule_Accounts</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Route Schedule Account</label>
    <nameField>
        <displayFormat>RSA-{00000000}</displayFormat>
        <label>RSA #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Route Schedule Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>Default_Collector_Location__c</fullName>
        <description>The default location / region for the collector.</description>
        <inlineHelpText>The default location / region for the collector.</inlineHelpText>
        <label>Default Collector Location</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Processing_Location</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Processing_Location__c</fullName>
        <description>Used for Cash Logistics - When an Route schedule is created, it is assigned to a processing location. This is used to determine, when a user of profile CL - Route Processor logs in, what route schedules they see.</description>
        <inlineHelpText>Used for Cash Logistics - When an Route schedule is created, it is assigned to a processing location. This is used to determine, when a user of profile CL - Route Processor logs in, what route schedules they see.</inlineHelpText>
        <label>Processing Location</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Processing_Location</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

globalValueSets/Processing_Location.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Burr Ridge</fullName>
    </customValue>
    <customValue>
        <fullName>DEV TEST 1</fullName>
    </customValue>
    <customValue>
        <fullName>Tinley Park</fullName>
    </customValue>
    <customValue>
        <fullName>Peoria</fullName>
    </customValue>
    <customValue>
        <fullName>Springfield</fullName>
    </customValue>
    <customValue>
        <fullName>CW</fullName>
    </customValue>
    <customValue>
        <fullName>Rockford</fullName>
    </customValue>
    <customValue>
        <fullName>Collinsville</fullName>
    </customValue>
    <masterLabel>Processing Location</masterLabel>
</GlobalValueSet>

classes/clRouteScheduleSelectionTest.cls
@IsTest
private class clRouteScheduleSelectionTest {

   /**
    * NOTE start / stop test merely there to reset gov limits as creating non cl data takes forever given
    * all the processors / flows and eventually will bust cpu time outs on it's own.
    */
    @TestSetup
    static void setupData() {

        Test.startTest();
        Map<String,Object> mBaseData = clTESTUTILS.createAllNonClData();
        Test.stopTest();
        Map<String,Object> mClData =  clTESTUTILS.createEnd2EndRouteData(mBaseData);
    }

    @IsTest
    static void test_retrieveTodaysRouteSchedules() {
        Test.startTest();
        ResponseDto dto = clRouteScheduleSelection.retrieveRouteSchedules(Date.today().addDays(1));
        System.assertEquals(dto.isSuccess,true);
        Test.stopTest();
    }

    @IsTest
    static void test_retrieveTodaysRouteSchedulesByRegion() {

        List<Route_Schedule__c> routeSchedules = [
                SELECT Id, Processing_Location__c
                FROM Route_Schedule__c
        ];
        for(Route_Schedule__c rs : routeSchedules) {
            rs.Processing_Location__c = 'Burr Ridge';
        }
        update routeSchedules;

        Test.startTest();
        User u = [SELECT Id, Default_Collector_Location__c FROM User WHERE Id = :UserInfo.getUserId()];
        u.Default_Collector_Location__c = 'Burr Ridge';
        update u;
        ResponseDto dto = clRouteScheduleSelection.retrieveRegionRouteSchedules(Date.today().addDays(1),'Burr Ridge',null);
        System.assertEquals(dto.isSuccess,true);


        delete [SELECT Id FROM Route_Schedule_Account__c];
        clRouteScheduleSelection.TEST_HIDE_INVALID_ROUTES = true;
        dto = clRouteScheduleSelection.retrieveRegionRouteSchedules(Date.today().addDays(1),'Burr Ridge',null);
        System.assertEquals(dto.isSuccess,false);

        Test.stopTest();
    }

    @IsTest
    static void test_retrieveRegions() {

        Test.startTest();
        List<String> suppressValues = null;

        ResponseDto dto = clRouteScheduleSelection.retrieveCollectorLocationInfo(UserInfo.getUserId(),suppressValues);
        System.assertEquals(dto.isSuccess,true);
        List<clRouteScheduleSelection.RegionPlWrapper> plWrappers
                = (List<clRouteScheduleSelection.RegionPlWrapper>)dto.values.get(clRouteScheduleSelection.MAP_KEY_COLLECTOR_LOC_WRAPPERS);

        Boolean hasBurrRidge = false;
        for(clRouteScheduleSelection.RegionPlWrapper plWrapper : plWrappers) {
            if(plWrapper.value == 'Burr Ridge') {
                hasBurrRidge = true;
                break;
            }
        }
        System.assert( hasBurrRidge );

        suppressValues = new List<String> {'Burr Ridge'};
        dto = clRouteScheduleSelection.retrieveCollectorLocationInfo(UserInfo.getUserId(),suppressValues);
        System.assertEquals(dto.isSuccess,true);
        plWrappers = (List<clRouteScheduleSelection.RegionPlWrapper>)dto.values.get(clRouteScheduleSelection.MAP_KEY_COLLECTOR_LOC_WRAPPERS);

        hasBurrRidge = false;
        for(clRouteScheduleSelection.RegionPlWrapper plWrapper : plWrappers) {
            if(plWrapper.value == 'Burr Ridge') {
                hasBurrRidge = true;
                break;
            }
        }
        System.assert( !hasBurrRidge );


        Test.stopTest();
    }

    @IsTest
    static void test_invalidRoutes() {
        DELETE [SELECT Id From Route__c];
        DELETE [SELECT Id FROM Route_Schedule__c];
        Route__c route = new Route__c(Name = ' Route with no accounts');
        insert route;

        Test.startTest();
        clRouteScheduleSelection.TEST_HIDE_INVALID_ROUTES = TRUE;
        ResponseDto dto = clRouteScheduleSelection.retrieveRouteSchedules(Date.today().addDays(1));
        System.assertEquals(dto.isSuccess,false);
        Test.stopTest();
    }


    @IsTest
    static void test_retrieveRouteProcessingSheets() {
        Route_Schedule__c routeSchedule = [SELECT Id FROM Route_Schedule__c LIMIT  1];

        Test.startTest();
        ResponseDto dto = clRouteScheduleSelection.retrieveRouteProcessingSheets(routeSchedule.Id);
        System.assertEquals(dto.isSuccess,true);
        Test.stopTest();
    }

    @IsTest
    static void test_doRouteScheduleSelection_positive_collector1() {
        Route_Schedule__c routeSchedule = [SELECT Id,Collector_1__c FROM Route_Schedule__c LIMIT  1];
        routeSchedule.Collector_1__c = null;
        update routeSchedule;

        Test.startTest();
        ResponseDto dto = clRouteScheduleSelection.doRouteScheduleSelection(UserInfo.getUserId(),routeSchedule.Id);
        System.assertEquals(dto.isSuccess,true);

        Test.stopTest();
    }

    @IsTest
    static void test_doRouteScheduleSelection_positive_collector2() {
        Route_Schedule__c routeSchedule = [SELECT Id,User__c FROM Route_Schedule__c LIMIT  1];
        routeSchedule.User__c = null;
        update routeSchedule;

        Test.startTest();
        ResponseDto dto = clRouteScheduleSelection.doRouteScheduleSelection(UserInfo.getUserId(),routeSchedule.Id);
        System.assertEquals(dto.isSuccess,true);

        Test.stopTest();
    }

    @IsTest
    static void test_doRouteScheduleSelection_allreadyscheduled() {
        Route_Schedule__c routeSchedule = [SELECT Id FROM Route_Schedule__c LIMIT  1];

        Test.startTest();
        ResponseDto dto = clRouteScheduleSelection.doRouteScheduleSelection(UserInfo.getUserId(),routeSchedule.Id);
        System.assertEquals(dto.isSuccess,false);

        Test.stopTest();
    }


    @IsTest
    static void test_retrieveMdt() {

        Map<String,Object> mUser = clTESTUTILS.getClUsers();
        User collector = (User)mUser.get(clTESTUTILS.COLLECTOR);

        Test.startTest();

        System.runAs(collector) {
            ResponseDto dto = clRouteScheduleSelection.retrieveMdt('Route_Selection');
            System.assert(dto.values.get(clRouteScheduleSelection.MAP_KEY_MDT_RECORD) != null);
            Cash_Logistics_Setting__mdt mdt = clRouteScheduleSelection.retrieveMdt();
        }

        Test.stopTest();
    }
}