objects/Cash_Logistics_Automation_Setting__mdt.object
<CustomObject>
    <description>All configurable settings for Cash Logistics - Automation</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>If unchecked, the automation will be bypassed.</description>
        <inlineHelpText>If unchecked, the automation will be bypassed.</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <label>Cash Logistics Automation Setting</label>
    <pluralLabel>Cash Logistics Automation Setting</pluralLabel>
</CustomObject>

objects/Cash_Logistics_Survey_Setting__mdt.object
<CustomObject>
    <description>Used to config any cash logistics survey / questionnaire.</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>If checked. the field will not be displayed on the form.</description>
        <inlineHelpText>If checked. the field will not be displayed on the form.</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <defaultValue>0</defaultValue>
        <description>The order the field displays on the form.</description>
        <inlineHelpText>The order the field displays on the form.</inlineHelpText>
        <label>Order</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Survey_Dev_Name__c</fullName>
        <description>The custom developer name for the form. this should be the same for fall fields within the form. This is used to key on in the query in the client form logic.</description>
        <inlineHelpText>The custom developer name for the form. this should be the same for fall fields within the form.</inlineHelpText>
        <label>Survey Dev Name</label>
        <length>64</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Cash Logistics Survey Setting</label>
    <pluralLabel>Cash Logistics Survey Settings</pluralLabel>
</CustomObject>

objects/Community_Setting__mdt.object
<CustomObject>
    <description>Used for any config parms for communities that cannot be stored natively in the community itself.</description>
    <fields>
        <fullName>Account_Types__c</fullName>
        <defaultValue>&quot;Accel Account,Other&quot;</defaultValue>
        <description>Comma Delim</description>
        <inlineHelpText>Comma Delim</inlineHelpText>
        <label>Account Types</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Max_Account_Results__c</fullName>
        <defaultValue>15</defaultValue>
        <description>Max number of accounts to return. (used primarily for us logging in as system admins!)</description>
        <inlineHelpText>Max number of accounts to return. (used primarily for us logging in as system admins!)</inlineHelpText>
        <label>Max Account Results</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Community Setting</label>
    <pluralLabel>Community Settings</pluralLabel>
</CustomObject>

objects/Geocode_Setting__mdt.object
<CustomObject>
    <fields>
        <fullName>Display_Value__c</fullName>
        <label>Display Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Geocode Setting</label>
    <pluralLabel>Geocode Settings</pluralLabel>
</CustomObject>

objects/HPD_Total_Setting__mdt.object
<CustomObject>
    <description>Contains configurable parameters for HPD Totals Aggregation. (Nightly batch jobs that use SOQL aggregation to rollup data to Hold Per Day Total from Hold Per Data.</description>
    <fields>
        <fullName>Account_Batch_Size__c</fullName>
        <defaultValue>200</defaultValue>
        <label>Account Batch Size</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>HPD_Account_Types__c</fullName>
        <defaultValue>&quot;Accel Account,Competitor Account&quot;</defaultValue>
        <label>HPD Account Types</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Daily_HPD_Upload_Date__c</fullName>
        <defaultValue>TODAY()</defaultValue>
        <label>Last Daily HPD Upload Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Notification_Email_Addresses__c</fullName>
        <defaultValue>&apos;rick@chicagosalesforceconsulting.com&apos;</defaultValue>
        <description>Email addresses for Scheduled Batch Jobs to notify of the results.</description>
        <inlineHelpText>Email addresses for Scheduled Batch Jobs to notify of the results.</inlineHelpText>
        <label>Notification Email Addresses</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Record_Type_Dev_Name_To_Process__c</fullName>
        <label>Record Type Dev Name To Process</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>HPD Total Setting</label>
    <pluralLabel>HPD Total Settings</pluralLabel>
</CustomObject>

classes/CustomMetadataSvc.cls
/**
 * CustomMetadataSvc provides for retrieval operations on custom metadata objects.
 */
public class CustomMetadataSvc {

    /**
     * User the passed parameter to search for:
     *
     * 1. Check the Developer name of the custom meta data
     * OR
     * 2. Check the Label of the custom meta data.
     *
     * @param geoAccuracyValue  The value provided in say Account.ShippingGeocodeAccuracy (or any of the accuracy fields)
     * @return A display value of weak / strong according to mapping in the mdt, otherwise an empty string.
     *
     * @implNote
     * This is done as OR statements are not allowed against custom metadata. Also values in the Geo Accuracy fields
     * are not all conducive to developername fields ie 'Zip/Postal Code'
     *
     * @see Geocode_Setting__mdt
     */
    public static String retrieveGeoAccuracyDisplayValue(String geoAccuracyValue) {
        String displayValue = '';

        List<Geocode_Setting__mdt> settings = [
                SELECT Display_Value__c
                FROM   Geocode_Setting__mdt
                WHERE  DeveloperName = :geoAccuracyValue
        ];
        if(!settings.isEmpty()) {
            Geocode_Setting__mdt setting = settings[0];
            displayValue = setting.Display_Value__c;
        } else {
            settings = [ SELECT Display_Value__c FROM   Geocode_Setting__mdt WHERE  Label = :geoAccuracyValue];
            if(!settings.isEmpty()) {
                Geocode_Setting__mdt setting = settings[0];
                displayValue = setting.Display_Value__c;
            }
        }
        return displayValue;
    }

    public static List<Cash_Logistics_Survey_Setting__mdt> retrieveSurveyMetadatas(String customDevName) {

        List<Cash_Logistics_Survey_Setting__mdt> mdts = new List<Cash_Logistics_Survey_Setting__mdt>();

        try {
            DescribeSObjectResult describeResult = Cash_Logistics_Survey_Setting__mdt.getSObjectType().getDescribe();
            List<String> fieldNames = new List<String>(describeResult.fields.getMap().keySet());

            String q =  ' SELECT ' + String.join(fieldNames, ',')
                    + '   FROM  ' + describeResult.getName() +
                        ' WHERE Survey_Dev_Name__c = :customDevName ' +
                        ' AND   Active__c = TRUE ' +
                        ' ORDER By Order__c ASC ';
            mdts = Database.query(q);
        } catch (Exception e) {
            system.debug(logginglevel.error, e);
        }
        return mdts;
    }

    public static Cash_Logistics_Automation_Setting__mdt retrieveAutomationMetadata(String devName) {

        Cash_Logistics_Automation_Setting__mdt mdt;

        try {
            DescribeSObjectResult describeResult = Cash_Logistics_Automation_Setting__mdt.getSObjectType().getDescribe();
            List<String> fieldNames = new List<String>(describeResult.fields.getMap().keySet());

            String q =  ' SELECT ' + String.join(fieldNames, ',')
                    + '   FROM  ' + describeResult.getName() +
                    '     WHERE DeveloperName = :devName ';

            List<Cash_Logistics_Automation_Setting__mdt> mdts = Database.query(q);
            mdt = !mdts.isEmpty() ? mdts[0] : mdt;
        } catch (Exception e) {
            system.debug(logginglevel.error, e);
        }
        return mdt;
    }

    /**
     * @param sObjectType   The Type of sObject.
     * @param devName       The Developer name of the custom metadata record.
     *
     * @return              A Raw sObject if found (Client responsibility to cast), otherwise null.
     */
    public static SObject retrieveCustomMetadata(SObjectType sObjectType,String devName) {
        SObject customMdt;

        try {
            DescribeSObjectResult describeResult = sObjectType.getDescribe();
            List<String> fieldNames = new List<String>(describeResult.fields.getMap().keySet());
            String q =  'SELECT ' + String.join(fieldNames, ',') + ' FROM  ' + describeResult.getName() + ' WHERE developername = :devName';
            customMdt = Database.query(q);
        } catch (Exception e) {
            system.debug(logginglevel.error, e);
        }
        return customMdt;
    }
    //----------- @TODO merge the below with above
    public static SObject retrieveCustomSearchMeta(SObjectType sObjectType,String devName) {
        SObject sObj;
        DescribeSObjectResult describeResult = sObjectType.getDescribe();
        List<String> fieldNames = new List<String>(describeResult.fields.getMap().keySet());
        String q = 'SELECT ' + String.join(fieldNames, ',') + ' FROM  ' + describeResult.getName() + ' WHERE developername = :devName';
        sObj = DataBase.query(q);
        return sObj;
    }

    /**
     * Retrieves a custom meta data type value for the community. (for now single community).
     *
     * @param settingName - the developer name for query. But think of it more as a record type. ie. Application_Search_Limits
     * @param fieldName   - the actual field name of the value you wish to find. ie. Max_Account_Results__c
     *
     * @return and object containing your value. (clients should case to correct type)
     */
    public static Object retrieveCommunityMetaFieldValue( String settingName, String fieldName ) {
        Community_Setting__mdt communityAppLimitsMdt;
        Object oReturn;
        try {
            communityAppLimitsMdt =
                    (Community_Setting__mdt) CustomMetadataSvc.retrieveCustomSearchMeta(Community_Setting__mdt.getSObjectType(), settingName);
        } catch (Exception e) {
            system.debug(logginglevel.error, e);
        }
        if (communityAppLimitsMdt != null) {
            oReturn = communityAppLimitsMdt.get(fieldName);
        }
        return oReturn;
    }

    /**
     * Retrieves account types that we want displayed in the external community.
     * If custom meta data not found. defaults to Accel Account.
     *
     * @return a set containing the account types ie {'Accel Account','Other'}
     */
    public static Set<String> retrieveCommunityAccountTypes() {
        Set<String> accountTypes = new Set<String>();
        Community_Setting__mdt communityAppLimitsMdt;
        String settingName = 'Account_Processing';
        String fieldName = 'Account_Types__c';

        try {
            communityAppLimitsMdt =
                    (Community_Setting__mdt) CustomMetadataSvc.retrieveCustomSearchMeta(Community_Setting__mdt.getSObjectType(), settingName);
        } catch (Exception e) {
            system.debug(logginglevel.error, e);
        }
        if (communityAppLimitsMdt != null) {
            Object obj = communityAppLimitsMdt.get(fieldName);
            if(obj!= null) {
                String sAccountTypes = (String)obj;
                if(sAccountTypes!= null) {
                    accountTypes.addAll(sAccountTypes.split(','));
                }
            }
        }
        if(accountTypes.isEmpty()) {
            //default barring we don't have a custom setting.
            accountTypes.add('Accel Account');
        }
        return accountTypes;
    }

    /**
     * @param sObjectType   The Type of sObject.
     * @param devName       The Developer name of the custom metadata record.
     *
     * @return              An instance of Community_Setting__mdt if found, otherwise null
     */
    public static Community_Setting__mdt retrieveCommunityMeta( String settingName ) {
        Community_Setting__mdt  communitySettingMdt;

        DescribeSObjectResult   describeResult          = Community_Setting__mdt.getSObjectType().getDescribe();
        List<String>            fieldNames              = new List<String>(describeResult.fields.getMap().keySet());

        String q = '    SELECT ' + String.join(fieldNames, ',') +
                    '   FROM    Community_Setting__mdt ' +
                    '   WHERE   developername = :settingName ';

        List<Community_Setting__mdt> mdts =  DataBase.query(q);
        if(!mdts.isEmpty()) {
            communitySettingMdt = Database.query(q);
        }
        return communitySettingMdt;
    }

    /**
     * Returns all 'rows' in the HPD_Total_Setting__mdt Custom Metadata type.
     * @return a list of HPD_Total_Setting__mdt Metadata types.
     */
    public static List<HPD_Total_Setting__mdt> retrieveHpdTotalSettingsMetas() {
        return retrieveHpdTotalSettingsMetas(null);
    }

    /**
     * @param devName the developer name of the HPD_Total_Setting__mdt Metadata type.
     * @return a HPD_Total_Setting__mdt.
     */
    public static HPD_Total_Setting__mdt retrieveHpdTotalSettingsMeta(String devName) {
        HPD_Total_Setting__mdt hpdTotalSetting;
        List<HPD_Total_Setting__mdt> hpdTotalSettings = retrieveHpdTotalSettingsMetas(devName);
        if (!hpdTotalSettings.isEmpty()) {
            hpdTotalSetting = hpdTotalSettings[0];
        }
        return hpdTotalSetting;
    }

    /**
     * @param devName - the developer name of the HPD_Total_Setting__mdt Metadata type.
     * @return a list of HPD_Total_Settings__Mdt objects (1 if devname passed, otherwise multiple for each dev name)
     */
    private static List <HPD_Total_Setting__mdt> retrieveHpdTotalSettingsMetas(String devName) {
        List<HPD_Total_Setting__mdt> hpdTotalSettings;
        if (devName != null) {
            hpdTotalSettings = [
                    SELECT Id, developername,MasterLabel, QualifiedApiName,Notification_Email_Addresses__c,
                            Record_type_Dev_Name_To_Process__c,HPD_Account_Types__c,Last_Daily_HPD_Upload_Date__c,
                            Account_Batch_Size__c 
                    FROM HPD_Total_Setting__mdt
                    WHERE DeveloperName = :devName
            ];
        } else {
            hpdTotalSettings = [
                    SELECT Id, developername,MasterLabel, QualifiedApiName,Notification_Email_Addresses__c,
                            Record_type_Dev_Name_To_Process__c,HPD_Account_Types__c,Last_Daily_HPD_Upload_Date__c,
                            Account_Batch_Size__c
                    FROM HPD_Total_Setting__mdt
            ];
        }
        return hpdTotalSettings;
    }
}