objects/CL_User_Setting__c.object
<CustomObject>
    <description>Case logics settings specific to a user. (record is initially inserted via user trigger.. or for system admins there will be a script / cmp to do manually_</description>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to the Standard User Record. (Must be CL Profile or Accel Super User Profile or Accel Regional Route Management Profile... or you must be an Admin To Override)</description>
        <inlineHelpText>Lookup to the Standard User Record. (Must be CL Profile or Accel Super User Profile or Accel Regional Route Management Profile... or you must be an Admin To Override)</inlineHelpText>
        <label>User</label>
        <lookupFilter>
            <active>false</active>
            <booleanFilter>1 OR 2 OR 3 OR 4</booleanFilter>
            <errorMessage>User Must be a System Admin or CL Profile or Accel Super User Profile or Accel Regional Route Management Profile.</errorMessage>
            <filterItems>
                <field>$Profile.Name</field>
                <operation>equals</operation>
                <value>System Administrator</value>
            </filterItems>
            <filterItems>
                <field>User.Profile.Name</field>
                <operation>startsWith</operation>
                <value>CL</value>
            </filterItems>
            <filterItems>
                <field>User.Profile.Name</field>
                <operation>equals</operation>
                <value>Accel Super User</value>
            </filterItems>
            <filterItems>
                <field>User.Profile.Name</field>
                <operation>equals</operation>
                <value>Accel Regional Route Management</value>
            </filterItems>
            <infoMessage>Please add a system administrator or Cash Logistics User  or Accel Super User Profile or Accel Regional Route Management Profile.</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>CL_User_Settings</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>CL User Setting</label>
    <nameField>
        <label>CL User Setting Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CL User Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/clUserSettingsSvc.cls
public with sharing class clUserSettingsSvc {

    public static CL_User_Setting__c retrieveSetting(Id userId) {
        CL_User_Setting__c setting;
        List<CL_User_Setting__c> settings = retrieveSettings( new Set<Id> {userId});
        if(!settings.isEmpty()) {
            setting = settings[0];
        }
        return setting;
    }

    public static List<CL_User_Setting__c> retrieveSettings(Set<Id> userIds) {

        String q = '';
        q += 'SELECT {0} ';
        q += 'FROM   CL_User_Setting__c ';
        q += 'WHERE  User__c IN :userIds ';
        String formattedQuery = String.format(q,getAllUserSettingsFields());

        List<CL_User_Setting__c> settings = Database.query(formattedQuery);
        return settings;
    }

    /**
     * @return Get all fields (doesn't span relationships)
     */
    @TestVisible
    private static List<String>  getAllUserSettingsFields() {
        Map<String, Schema.SObjectField> fieldsMap = CL_User_Setting__c.sObjectType.getDescribe().fields.getMap();
        String sFields = String.join(new List<String>(fieldsMap.keySet()), ',');
        List<String> fields = new List<String>{sfields};
        return fields;
    }
}