objects/CL_User_Setting__c.object
<CustomObject>
    <description>Case logics settings specific to a user. (record is initially inserted via user trigger.. or for system admins there will be a script / cmp to do manually_</description>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to the Standard User Record. (Must be CL Profile or Accel Super User Profile or Accel Regional Route Management Profile... or you must be an Admin To Override)</description>
        <inlineHelpText>Lookup to the Standard User Record. (Must be CL Profile or Accel Super User Profile or Accel Regional Route Management Profile... or you must be an Admin To Override)</inlineHelpText>
        <label>User</label>
        <lookupFilter>
            <active>false</active>
            <booleanFilter>1 OR 2 OR 3 OR 4</booleanFilter>
            <errorMessage>User Must be a System Admin or CL Profile or Accel Super User Profile or Accel Regional Route Management Profile.</errorMessage>
            <filterItems>
                <field>$Profile.Name</field>
                <operation>equals</operation>
                <value>System Administrator</value>
            </filterItems>
            <filterItems>
                <field>User.Profile.Name</field>
                <operation>startsWith</operation>
                <value>CL</value>
            </filterItems>
            <filterItems>
                <field>User.Profile.Name</field>
                <operation>equals</operation>
                <value>Accel Super User</value>
            </filterItems>
            <filterItems>
                <field>User.Profile.Name</field>
                <operation>equals</operation>
                <value>Accel Regional Route Management</value>
            </filterItems>
            <infoMessage>Please add a system administrator or Cash Logistics User  or Accel Super User Profile or Accel Regional Route Management Profile.</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>CL_User_Settings</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>CL User Setting</label>
    <nameField>
        <label>CL User Setting Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CL User Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/clUserSettingsSvcTest.cls
@IsTest
private class clUserSettingsSvcTest {

    @TestSetup
    static void setupData() {

        Test.startTest();

        Map<String,Object> mUsers = clTESTUTILS.createClUsers();
        User collector = (User)mUsers.get(clTESTUTILS.COLLECTOR);
        User processor = (User)mUsers.get(clTESTUTILS.PROCESSOR);
        clTESTUTILS.createUserSetting(collector);
        clTESTUTILS.createUserSetting(processor);

        Test.stopTest();
    }

    @IsTest
    static void test_retrieveSetting() {

        Map<String,Object> mUser = clTESTUTILS.getClUsers();
        User collector = (User)mUser.get(clTESTUTILS.COLLECTOR);
        User processor = (User)mUser.get(clTESTUTILS.PROCESSOR);

        Test.startTest();

        System.runAs(collector) {
            CL_User_Setting__c collectorSetting = clUserSettingsSvc.retrieveSetting(collector.Id);
            System.assertEquals(collectorSetting.User__c,collector.Id);
        }
        System.runAs(processor) {
            CL_User_Setting__c processorSetting = clUserSettingsSvc.retrieveSetting(processor.Id);
            System.assertEquals(processorSetting.User__c,processor.Id);
        }

        Test.stopTest();
    }
}