objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Portal_Contact_Request__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is updated via a FLOW when the contact record is created as the result of an approved PCR
Not editable by users who have visibility rights to it.</description>
        <inlineHelpText>If this field is populated, it was created as a the result of the Portal Contact Request record that populates it.</inlineHelpText>
        <label>Portal Contact Request</label>
        <referenceTo>Portal_Contact_Request__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Portal_Contact_Request__c.object
<CustomObject>
    <description>Users submit requests for the creation of a Portal Contact and a Portal User record.</description>
    <fields>
        <fullName>First_Name__c</fullName>
        <description>used to populate the first name of the contact that will be created from the PCR record</description>
        <label>First Name</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <description>will be used to populate the last name of the contact that will be created from the PCR record upon approval</description>
        <label>Last Name</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Portal Contact Request</label>
    <nameField>
        <displayFormat>PCR-{0}</displayFormat>
        <label>Portal Contact Request</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Portal Contact Requests</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/Test_DuplicateContact.cls
/**
 * Created by CedricN on 2/8/2022.
 */
@isTest
public with sharing class Test_DuplicateContact {

    public static String USERNAME_ADMIN             = 'acceltestadmin@accelentertainment.com';
    public static String USERNAME_PORTAL            = 'accelcustomerportal@portal.com';
    public static Integer NUMBER_OF_ACCOUNTS        = 5;
    public static String HQ_ACCOUNT_NAME            = 'HQ  Portal UT Account';
    public static String PROFILE_NAME_PORTAL        = 'Grouped User Community Standard';
    public static Set<String> ACCOUNT_TYPES         = CustomMetaDataSvc.retrieveCommunityAccountTypes();





    @testSetup
    static void setup(){
    /*UserRole adminRole = new UserRole(DeveloperName = 'TestCustomerPortalRole', Name = 'TestCustomerPortalRole');
    insert adminRole;

    User adminUser = TestUtils.getUserForTest(USERNAME_ADMIN);
    adminUser = [ SELECT Id, UserRoleId FROM User WHERE Id = :adminUser.Id ];
    adminUser.UserRoleId = adminRole.Id;
    update adminUser;
    User setupUser = adminUser;*/
        Contact portalContact = new Contact(FirstName='Portal', LastName='User');

        insert portalContact;

        Portal_Contact_Request__c PCR = new Portal_Contact_Request__c(First_Name__c ='Portal', Last_Name__c='User');

        insert PCR;

    }



  @isTest  static void  Test_DuplicateContactMethod(){

      Portal_Contact_Request__c usercontact = [Select Id From Portal_Contact_Request__c Where First_Name__C ='Portal' Limit 1];




        String ContactId = Id.valueOf(usercontact.id);

    List<Contact> contacts = DuplicateContact.DuplicateContactMethod(ContactId);
    }

}