objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Portal_Contact_Request__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is updated via a FLOW when the contact record is created as the result of an approved PCR
Not editable by users who have visibility rights to it.</description>
        <inlineHelpText>If this field is populated, it was created as a the result of the Portal Contact Request record that populates it.</inlineHelpText>
        <label>Portal Contact Request</label>
        <referenceTo>Portal_Contact_Request__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Portal_Contact_Request__c.object
<CustomObject>
    <description>Users submit requests for the creation of a Portal Contact and a Portal User record.</description>
    <fields>
        <fullName>Email__c</fullName>
        <caseSensitive>true</caseSensitive>
        <label>Email</label>
        <type>Email</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <description>used to populate the first name of the contact that will be created from the PCR record</description>
        <label>First Name</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <description>will be used to populate the last name of the contact that will be created from the PCR record upon approval</description>
        <label>Last Name</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Portal Contact Request</label>
    <nameField>
        <displayFormat>PCR-{0}</displayFormat>
        <label>Portal Contact Request</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Portal Contact Requests</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/DuplicateContact.cls
/**
 * Created by CedricN on 2/2/2022.
 */

public with sharing class DuplicateContact {

    @AuraEnabled(cacheable=true)



    public static List<Contact> DuplicateContactMethod (String records){

        // List<Portal_Contact_Request__c> PCRequests = [Select ]

        Portal_Contact_Request__c PCRRequest = [Select Id, First_Name__c, Last_Name__c, Email__c From Portal_Contact_Request__c Where Id =:records ];

        Return [Select Id, Name, Email, FirstName, LastName From Contact where ((FirstName Like: '%'+PCRRequest.First_Name__c+'%') AND (LastName like
: '%'+PCRRequest.Last_Name__c+'%')) OR ((LastName Like: '%'+PCRRequest.First_Name__c+'%') And (FirstName like: '%'+PCRrequest.Last_Name__c+'%')) OR (Email Like: '%'+PCRRequest.Email__c) ];



     //   Return [Select Id, Name, Email, FirstName, LastName From Contact where FirstName Like '%John'];




		//Debug Code
		
    }


}