objects/Custom_Notifications_Sent__c.object
<CustomObject>
    <description>An Object to hold references to desktop and mobile custom notifications sent (so as to prevent sending dup notifications)</description>
    <fields>
        <fullName>Alert_Type__c</fullName>
        <description>The type of alert.. this allows us to branch off. .say in a flow and send multiple types of alerts to the same entity.</description>
        <inlineHelpText>The type of alert.. this allows us to branch off. .say in a flow and send multiple types of alerts to the same entity.</inlineHelpText>
        <label>Alert Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>NO_ASSIGNED_RESOURCE</fullName>
                </value>
                <value>
                    <fullName>NOT_DISPATCHED</fullName>
                </value>
                <value>
                    <fullName>No Visit in 30 Days</fullName>
                </value>
                <value>
                    <fullName>No Visit in 45 Days</fullName>
                </value>
                <value>
                    <fullName>DISPATCHED</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Msg_Body__c</fullName>
        <description>The Body of the custom notification (Currently generated inside of flows)</description>
        <inlineHelpText>The Body of the custom notification.</inlineHelpText>
        <label>Msg Body`</label>
        <length>2084</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Msg_Title__c</fullName>
        <description>The Title of the custom notification (Currently Generated inside of flows)</description>
        <inlineHelpText>The Title of the custom notification</inlineHelpText>
        <label>Msg Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Notification_Type__c</fullName>
        <description>The type of notification, either Manual (user clicked the send icon) or Automated.</description>
        <inlineHelpText>The type of notification, either Manual (user clicked the send icon) or Automated.The type of notification, either Manual (user clicked the send icon) or Automated.</inlineHelpText>
        <label>Notification Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Manual</fullName>
                    <default>true</default>
                    <label>Manual</label>
                </value>
                <value>
                    <fullName>Automated</fullName>
                </value>
                <value>
                    <fullName>Event</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Service_Appointment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>If the parent record  (ie target id) is a Service Appointment, this will be populated.</description>
        <inlineHelpText>If the parent record  (ie target id) is a Service Appointment, this will be populated.</inlineHelpText>
        <label>Service Appointment</label>
        <referenceTo>ServiceAppointment</referenceTo>
        <relationshipLabel>Custom Notifications Sent</relationshipLabel>
        <relationshipName>Custom_Notifications_Sent</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>If the recipient Id is a User.. This will be populated.</description>
        <inlineHelpText>If the recipient Id is a User.. This will be populated.</inlineHelpText>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Custom_Notifications_Sent</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Custom Notifications Sent</label>
    <nameField>
        <displayFormat>N-{0000000}</displayFormat>
        <label>Notification #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Custom Notifications Sent</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/FslPocQuickActionController.cls
public class FslPocQuickActionController {

    public static final String MAP_KEY_NOTIFICATION_WRAPS = 'NOTIFICATION_WRAPS';

    /**
     * @param saId  The Service_Appointment__c.Id.
     * @return      A ResponseDto containing A List of Notification Wrapper objs in the values map.
     */
    @AuraEnabled(Cacheable=true)
    public static ResponseDto retrieveSaCustomNotifications(Id saId) {
        ResponseDto dto = new ResponseDto();

        List<Custom_Notifications_Sent__c> recs = [
                SELECT  Id,User__c,User__r.Name,Msg_Title__c,Msg_Body__c,Alert_Type__c,Notification_Type__c,
                        CreatedDate,Name
                FROM    Custom_Notifications_Sent__c
                WHERE   Service_Appointment__c = :saId
                ORDER BY CreatedDate DESC
        ];
        List<Notification> notificationWraps = buildNotificationWrappers(recs);

        dto.isSuccess = !notificationWraps.isEmpty();
        dto.values.put(MAP_KEY_NOTIFICATION_WRAPS,notificationWraps);

        return dto;
    }

    /**
     * @param recs  A list of Custom_Notification_Sent__c sObjects.
     * @return      A list of Notification wrapper objects.
     */
    private static List<Notification> buildNotificationWrappers(List<Custom_Notifications_Sent__c> recs) {
        List<Notification> wraps = new List<Notification>();

        for(Custom_Notifications_Sent__c rec : recs){
            wraps.add(new Notification(rec));
        }
        return wraps;
    }

    /**
     * A Wrapper class on top of Custom_Notification_Sent__c sObjects.
     */
    public class Notification {
        @AuraEnabled public Id recordId;
        @AuraEnabled public String recordName;
        @AuraEnabled public String recordUrl;
        @AuraEnabled public Id recipientId;
        @AuraEnabled public String recipientName;
        @AuraEnabled public Datetime sentDate;
        @AuraEnabled public String alertType;
        @AuraEnabled public String msgTitle;

        public Notification(Custom_Notifications_Sent__c sentNotification) {
            this.recordId = sentNotification.Id;
            this.recordName = sentNotification.Name;
            this.recordUrl =  '/'+recordId;
            this.recipientId = sentNotification.User__c;
            this.recipientName = sentNotification.User__r.Name;
            this.sentDate = sentNotification.CreatedDate;
            this.alertType = sentNotification.Alert_Type__c;
            this.msgTitle = sentNotification.Msg_Title__c;
        }
    }
}