objects/Field_Assessment__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Field Assessments</relationshipLabel>
        <relationshipName>Field_Assessments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Field_Assessment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Field Assessments</relationshipLabel>
        <relationshipName>Field_Assessments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Field Assessments</relationshipLabel>
        <relationshipName>Field_Assessments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Field Assessment</label>
    <nameField>
        <displayFormat>FA-{0000}</displayFormat>
        <label>Field Assessment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Field Assessments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Municipality__c.object
<CustomObject>
    <label>Municipality</label>
    <nameField>
        <label>Municipality Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Municipalities</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Count_of_Field_Assessements__c</fullName>
        <label>Count of Field Assessments</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Field_Assessment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Field Assessment</label>
        <referenceTo>Field_Assessment__c</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project_Status__c</fullName>
        <label>Project Status</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Project_Type__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Application Process</fullName>
                </value>
                <value>
                    <fullName>Pending Licensing</fullName>
                </value>
                <value>
                    <fullName>Licensed</fullName>
                </value>
                <value>
                    <fullName>Live</fullName>
                </value>
                <value>
                    <fullName>Planning</fullName>
                </value>
                <value>
                    <fullName>Evaluation</fullName>
                </value>
                <value>
                    <fullName>Execution</fullName>
                </value>
                <value>
                    <fullName>Approvals</fullName>
                </value>
                <value>
                    <fullName>Field Assessment</fullName>
                </value>
                <value>
                    <fullName>IGB Approval</fullName>
                </value>
                <value>
                    <fullName>Install Scheduled</fullName>
                </value>
                <value>
                    <fullName>SGI Project Scheduled</fullName>
                </value>
                <value>
                    <fullName>Closure</fullName>
                </value>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>In progress</fullName>
                </value>
                <value>
                    <fullName>Stalled</fullName>
                </value>
                <value>
                    <fullName>On Hold</fullName>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
                <value>
                    <fullName>Regional Approval</fullName>
                </value>
                <value>
                    <fullName>Parts Fulfillment</fullName>
                </value>
                <value>
                    <fullName>Pending Location Delivery</fullName>
                </value>
                <value>
                    <fullName>Delivered</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                    <isActive>false</isActive>
                    <label>Closed</label>
                </value>
                <value>
                    <fullName>Closed Lost</fullName>
                    <isActive>false</isActive>
                    <label>Closed Lost</label>
                </value>
                <value>
                    <fullName>Initiation</fullName>
                    <isActive>false</isActive>
                    <label>Initiation</label>
                </value>
                <value>
                    <fullName>Lost</fullName>
                    <isActive>false</isActive>
                    <label>Lost</label>
                </value>
                <value>
                    <fullName>Pre-Initiation</fullName>
                    <isActive>false</isActive>
                    <label>Pre-Initiation</label>
                </value>
                <value>
                    <fullName>Prerequisites</fullName>
                    <isActive>false</isActive>
                    <label>Prerequisites</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/Test_FieldAssessmentCount.cls
/**
 * Created by CedricN on 8/13/2020.
 */

@IsTest
private class Test_FieldAssessmentCount {
   /* public static final String USERNAME_ADMIN             = 'acceltestadmin@accelentertainment.com';
    public static final String ACCOUNT_NAME               = 'Blah Random UT Account';
    public static final string count;
    public static final String KNOWN_SOBJECT_API_NAME     = 'Account';
    public static final String KNOWN_FIELDSET_API_NAME    = 'test_lookup';
    public static final String KNOWN_FIELDSET_FIELD_NAME  = 'Type';*/

    @testSetup static void setup(){
     /*  Profile pr = new Profile(name ='Regional Manager');
     User test = TestUtils.getUserForTest('TestUser@accelentertainment.com');
        test.ProfileId=pr.Id;
        test.Email = 'acceltestadmin@accelentertainment.com';

        User adminUser = TestUtils.getUserForTest(USERNAME_ADMIN);

        User user = new User();
        // populate the record
        user.emailencodingkey='UTF-8';
        user.languagelocalekey='en_US';
        user.localesidkey='en_US';
        user.timezonesidkey='America/Chicago';

        user.Alias = 'test1';
        user.email = 'test1@accelentertainment.com';
        user.lastname = 'theRegion';
        user.username = 'test1@accelentertainment.com';
        user.ProfileId = pr.Id;

        insert user;*/

      /* Account Account1 = new Account();
        List<Municipality__c> muni = TestUtils.createMunicipalities('Test Muni', 2);
        For(Municipality__c m : muni){
            Account1 = TestUtils.buildAccount('TestAccount', m.id);
        }
        insert Account1;
        Project__c Proj1 = new Project__c(Name = 'Project 1', Account__r=Account1, Count_of_Field_Assessements__c=0, Project_Status__c='Pre-Initiation');
      //  count=Proj1.Count_of_Field_Assessements__c;
        insert Proj1;

        Field_Assessment__c Field1 = new Field_Assessment__c( Project__c=Proj1.ID);
        insert Field1;*/


    }
    @IsTest
    static void testBehavior() {
      // User adminUser = TestUtils.getUserForTest(USERNAME_ADMIN);

     //   System.runAs( adminUser){

            FieldAssessmentCount f1 = new FieldAssessmentCount();
        Test.startTest();
        Database.executeBatch(f1);

    Test.stopTest();

         //   system.assert(false, [Select Id, Name From Field_Assessment__c Where Count_of_Field_Assessements__c!=0] = Null);

          // system.assertEquals(1, f1.Account)

        }



    }