objects/Hold_Per_Day_Total__c.object
<CustomObject>
    <description>Contains calculated information for HPD (currently only monthly)
Rolls up info for both Account(Location) and Municipality Levels (Separated by Record Type).
Fields such as TTM indicate 12 month roll-ups. all other fiels noted appropriated (4 weeks 8 weeks 12 weeks) etc.

Additional record type for future use of Machine exists as well.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Populated by script upon initial object creation. then populated upon creation of each account via trigger moving forward.</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Hold Per Day Totals</relationshipLabel>
        <relationshipName>Hold_Per_Day_Summaries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Municipality__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Municipality</label>
        <referenceTo>Municipality__c</referenceTo>
        <relationshipLabel>Hold Per Day Totals</relationshipLabel>
        <relationshipName>Hold_Per_Day_Totals</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Hold Per Day Total</label>
    <nameField>
        <displayFormat>HPDT-{000000000}</displayFormat>
        <label>HPD Total #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Hold Per Day Totals</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Municipality__c.object
<CustomObject>
    <fields>
        <fullName>Hold_Per_Day_Total__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Hold Per Day Totals</label>
        <referenceTo>Hold_Per_Day_Total__c</referenceTo>
        <relationshipLabel>Municipalities</relationshipLabel>
        <relationshipName>Municipalities</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Municipality</label>
    <nameField>
        <label>Municipality Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Municipalities</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/TEST_MunicipalityTrigger.cls
@IsTest
private class TEST_MunicipalityTrigger{
    public static String UNAME = 'acceltest@accel.com';
    
    @IsTest
    static void testNewMuniCreation() {
        User u = TestUtils.getUserForTest(UNAME);
        System.runAs(u) {
            Test.startTest();

            List<Municipality__c> munis = TestUtils.createMunicipalities('Test Accel Muni',2);

            List<Hold_Per_Day_Total__c> holdPerDayTotals = [
                    SELECT Id, Account__c
                    FROM   Hold_Per_Day_Total__c
                    WHERE  Municipality__c IN :munis
            ];
            System.assert(holdPerDayTotals.size() == munis.size());

            Test.stopTest();
        }
    }
}