objects/Inventory_Request__c.object
<CustomObject>
    <description>Parent object to capture the request to order new inventory items.</description>
    <fields>
        <fullName>Number_of_Items__c</fullName>
        <description>This is more of a helper field so we can generate line item numbers of the child records</description>
        <inlineHelpText>The total number of Child Line Items</inlineHelpText>
        <label>Total # of Line Items</label>
        <summaryForeignKey>Inventory_Request_Line_Item__c.Inventory_Request__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>Inventory Request</label>
    <nameField>
        <label>Request Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Inventory Requests</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Inventory_Request_Line_Item__c.object
<CustomObject>
    <description>Child Line Items for the Inventory Request object allowing the capture of products by model (1 record per model)</description>
    <fields>
        <fullName>Inventory_Request__c</fullName>
        <description>Link tto the Parent IR Record.</description>
        <inlineHelpText>Link to the Parent IR Record.</inlineHelpText>
        <label>Inventory Request</label>
        <referenceTo>Inventory_Request__c</referenceTo>
        <relationshipLabel>Request Line Items</relationshipLabel>
        <relationshipName>Inventory_Request_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Item_Number__c</fullName>
        <description>Trigger maintained. Simply allows line 1,2,3 etc.</description>
        <inlineHelpText>The Inventory Request Line Item Number</inlineHelpText>
        <label>Item #</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Inventory Request Line Item</label>
    <nameField>
        <displayFormat>IR-Line-{0000000}</displayFormat>
        <label>Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inventory Request Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/InventoryRequestLineItemTriggerHandler.cls
public with sharing class InventoryRequestLineItemTriggerHandler {

    /**
     * @param lineItems   The line items being inserted.
     * @return            a List of the implicity updated  Inventory_Line_Item__c
     */
    public static List<Inventory_Request_Line_Item__c> updateLineItemNumber(List<Inventory_Request_Line_Item__c> lineItems) {
        List<Inventory_Request_Line_Item__c> updatedItems = new List<Inventory_Request_Line_Item__c>();

        //   Simply query parent rollup summary field to get total number of lines.
        Set<Id> irIds = new Set<Id>();
        for(Inventory_Request_Line_Item__c irLi :lineItems) {
            irIds.add(irLi.Inventory_Request__c);
        }
        Map<Id,Inventory_Request__c>  inventoryRequestMap = new Map<Id,Inventory_Request__c> (
            [   SELECT  Number_of_Items__c
                FROM    Inventory_Request__c
                WHERE   Id IN:irIds ]
        );
        Map<Id,Integer> latestChild = new Map<Id,Integer>();
        //    Implicity update Inventory_Request_Line_Item.Item_Number__c
        for(Inventory_Request_Line_Item__c lineItem : lineItems) {
            if(latestChild.containsKey(lineItem.Inventory_Request__c)) {
                lineItem.Item_Number__c = latestChild.get(lineItem.Inventory_Request__c);
            }
            else {
                Inventory_Request__c inventoryRequest = inventoryRequestMap.get(lineItem.Inventory_Request__c);
                Decimal itemNumber = 0;
                if(inventoryRequest != null && inventoryRequest.Number_of_Items__c != null) {
                    itemNumber = inventoryRequest.Number_of_Items__c;
                }
                lineItem.Item_Number__c = itemNumber + 1;
                latestChild.put(lineItem.Inventory_Request__c, (Integer)lineItem.Item_Number__c);
            }
            updatedItems.add(lineItem);
        }
        return updatedItems;
    }
}