objects/Inventory_Request__c.object
<CustomObject>
    <description>Parent object to capture the request to order new inventory items.</description>
    <fields>
        <fullName>Final_Approved_Indicator__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Final Approved Indicator</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IR_Approved_Date__c</fullName>
        <description>Date Compliance has approved the IR. Only required before Assets can be generated.</description>
        <inlineHelpText>Date Compliance has approved the IR. Only required before Assets can be generated.</inlineHelpText>
        <label>IR Approved Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Number_of_Items__c</fullName>
        <description>This is more of a helper field so we can generate line item numbers of the child records</description>
        <inlineHelpText>The total number of Child Line Items</inlineHelpText>
        <label>Total # of Line Items</label>
        <summaryForeignKey>Inventory_Request_Line_Item__c.Inventory_Request__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>PO_Number__c</fullName>
        <description>The Great Plains purchase order number.</description>
        <inlineHelpText>The Great Plains purchase order number.</inlineHelpText>
        <label>PO Number</label>
        <length>64</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PO_Submitted_Date__c</fullName>
        <description>Date the PO has been submitted to Finance. Only required before Assets can be generated.</description>
        <inlineHelpText>Date the PO has been submitted to Finance. Only required before Assets can be generated.</inlineHelpText>
        <label>PO Submitted Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>The status of the Inventory Request. This status will change based on various fields populated as well as state of approval.</description>
        <inlineHelpText>The status of the Inventory Request. This status will change based on various fields populated as well as state of approval.</inlineHelpText>
        <label>Request Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                    <default>true</default>
                    <label>Open</label>
                </value>
                <value>
                    <fullName>IR Request Pending Approval</fullName>
                    <label>Pending Approval</label>
                </value>
                <value>
                    <fullName>Approved for PO</fullName>
                </value>
                <value>
                    <fullName>PO Submitted</fullName>
                </value>
                <value>
                    <fullName>PO Partially Fulfilled</fullName>
                </value>
                <value>
                    <fullName>PO Fulfilled</fullName>
                </value>
                <value>
                    <fullName>IR Request Submitted</fullName>
                    <isActive>false</isActive>
                    <label>IR Request Submitted</label>
                </value>
                <value>
                    <fullName>PO Delivery Date Scheduled</fullName>
                    <isActive>false</isActive>
                    <label>PO Delivery Date Scheduled</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Submitted_Date__c</fullName>
        <description>Date the request was submitted for approval.</description>
        <inlineHelpText>Date the request was submitted for approval.</inlineHelpText>
        <label>IR Submitted Date</label>
        <type>Date</type>
    </fields>
    <label>Inventory Request</label>
    <nameField>
        <label>Request Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Inventory Requests</pluralLabel>
    <recordTypes>
        <fullName>Gaming_Software</fullName>
        <active>true</active>
        <description>Please select this record type for Inventory Requests related to Gaming Software.</description>
        <label>Gaming Software</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Inventory_Request_Line_Item__c.object
<CustomObject>
    <description>Child Line Items for the Inventory Request object allowing the capture of products by model (1 record per model)</description>
    <fields>
        <fullName>Inventory_Request__c</fullName>
        <description>Link tto the Parent IR Record.</description>
        <inlineHelpText>Link to the Parent IR Record.</inlineHelpText>
        <label>Inventory Request</label>
        <referenceTo>Inventory_Request__c</referenceTo>
        <relationshipLabel>Request Line Items</relationshipLabel>
        <relationshipName>Inventory_Request_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Number_of_Assets_Created__c</fullName>
        <defaultValue>0</defaultValue>
        <description>The total # of Assets Created for this line item.</description>
        <inlineHelpText>The total # of Assets Created for this line item.</inlineHelpText>
        <label>Total # of Assets Created</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <defaultValue>0</defaultValue>
        <description>The Original Quantity to be requested and approved.</description>
        <inlineHelpText>The Original Quantity to be requested and approved.</inlineHelpText>
        <label>Quantity Requested</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Received_Date__c</fullName>
        <description>The date the Item was received in the warehouse.</description>
        <inlineHelpText>The date the Item was received in the warehouse.</inlineHelpText>
        <label>Received Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Received_Quantity__c</fullName>
        <defaultValue>0</defaultValue>
        <description>The Number of products received in the warehouse that you want to create at this point in time. Will default to zero.</description>
        <inlineHelpText>The Number of products received in the warehouse that you want to create at this point in time. Will default to zero.</inlineHelpText>
        <label>Quantity to Create</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Inventory Request Line Item</label>
    <nameField>
        <displayFormat>IR-Line-{0000000}</displayFormat>
        <label>Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inventory Request Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/TEST_InventoryRequestTrigger.cls
@IsTest
private class TEST_InventoryRequestTrigger {
    public static final String USERNAME_ADMIN             = 'acceltestadmin@accelentertainment.com';
    public static final Integer NUM_LINE_ITEMS            = 3;
    /**
     * Obviously.. initiate UT data.
     */
    @TestSetup
    static void setup() {
        List<Schema.RecordTypeInfo> recordTypeInfos =  Inventory_Request__c.SObjectType.getDescribe().getRecordTypeInfos();
        List<Inventory_Request__c> inventoryRequests = new List<Inventory_Request__c>();

        for(Schema.RecordTypeInfo recordTypeInfo : recordTypeInfos) {
            if(recordTypeInfo.getDeveloperName() != 'Master' && recordTypeInfo.active && recordTypeInfo.developerName == 'Gaming_Software') {
                System.debug('---------- RT Info ='+recordTypeInfo.getDeveloperName());
                Inventory_Request__c inventoryRequest = new Inventory_Request__c();
                inventoryRequest.RecordTypeId = recordTypeInfo.getRecordTypeId();
                inventoryRequest.Name = 'UT IR Name for RT ' + recordTypeInfo.developerName;
                Inventory_Request__c irClone = inventoryRequest.clone(false,true);
                inventoryRequests.add(inventoryRequest);
                inventoryRequests.add(irClone);
            }
        }
        insert inventoryRequests;
        System.debug(LoggingLevel.DEBUG,'----> Number of IR created:'+inventoryRequests.size());
    }

    @IsTest
    static void test_insertInventoryRequestUpdateIrStatus_Positive() {
        User adminUser = TestUtils.getUserForTest(USERNAME_ADMIN);

        System.runAs(adminUser) {
            Map<Id,Inventory_Request__c> inventoryRequestMap = new Map<Id,Inventory_Request__c>( [
                    SELECT  Id, Number_of_Items__c
                    FROM    Inventory_Request__c
            ]);
            List<Inventory_Request_Line_Item__c> lineItems = new List<Inventory_Request_Line_Item__c>();
            for(Id irId : inventoryRequestMap.keySet()) {
                Inventory_Request__c inventoryRequest = inventoryRequestMap.get(irId);
                for(Integer i = 0; i< NUM_LINE_ITEMS; i++) {
                    Inventory_Request_Line_Item__c lineItem = new Inventory_Request_Line_Item__c();
                    lineItem.Inventory_Request__c = inventoryRequest.Id;
                    lineItem.Quantity__c = i + 1;
                    lineItem.Received_Quantity__c = lineItem.Quantity__c;
                    lineItem.Received_Date__c = Date.today();
                    lineItems.add(lineItem);
                }
            }
            insert lineItems;

            List<Inventory_Request__c> inventoryRequests = [SELECT Id,PO_Submitted_Date__c,PO_Number__c,Status__c FROM Inventory_Request__c];
            for(Inventory_Request__c inventoryRequest : inventoryRequests ) {
                inventoryRequest.Final_Approved_Indicator__c = true;
                inventoryRequest.IR_Approved_Date__c = Date.today();
                inventoryRequest.Submitted_Date__c = Date.today();
                inventoryRequest.Status__c = 'Approved for PO';
            }
            update inventoryRequests;

            for(Inventory_Request__c inventoryRequest : inventoryRequests) {
                inventoryRequest.PO_Number__c = '23434';
                inventoryRequest.PO_Submitted_Date__c = Date.today();
            }
            update inventoryRequests;

            List<String> irLineItemIds = new List<String>();
            List<Inventory_Request_Line_Item__c> inventoryRequestLineItems = [SELECT Id, Quantity__c, Received_Quantity__c, Number_of_Assets_Created__c FROM Inventory_Request_Line_Item__c];
            //@TODO Make proccess “Inventory Request Processor bulk safe!
            for(Inventory_Request_Line_Item__c inventoryRequestLineItem : inventoryRequestLineItems) {
                irLineItemIds.add(inventoryRequestLineItem.Id);
            }
            irLineItemIds.add(inventoryRequestLineItems[0].Id);

            Test.startTest();

            //create assets.
            List<FlowAction_CreateAssetsFromIRLineItems.CreateAssetsResult> createAssetsResults =
                    FlowAction_CreateAssetsFromIRLineItems.createAssetsFromInventoryRequestLineItem(irLineItemIds);

            for(Inventory_Request_Line_Item__c irLineItem : inventoryRequestLineItems) {
                irLineItem.Number_of_Assets_Created__c = 0;
                irLineItem.Quantity__c = 10;
                irLineItem.Received_Quantity__c = 1;
            }
            update inventoryRequestLineItems; //

            for(Inventory_Request_Line_Item__c irLineItem : inventoryRequestLineItems) {
                irLineItem.Number_of_Assets_Created__c = 1;
                irLineItem.Received_Quantity__c = 9;
            }
            update inventoryRequestLineItems; // force Rollup summary. fire.

            Test.stopTest();
        }
    }
}