objects/Inventory_Request__c.object
<CustomObject>
    <description>Parent object to capture the request to order new inventory items.</description>
    <fields>
        <fullName>PO_Submitted_Date__c</fullName>
        <description>Date the PO has been submitted to Finance. Only required before Assets can be generated.</description>
        <inlineHelpText>Date the PO has been submitted to Finance. Only required before Assets can be generated.</inlineHelpText>
        <label>PO Submitted Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>The status of the Inventory Request. This status will change based on various fields populated as well as state of approval.</description>
        <inlineHelpText>The status of the Inventory Request. This status will change based on various fields populated as well as state of approval.</inlineHelpText>
        <label>Request Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                    <default>true</default>
                    <label>Open</label>
                </value>
                <value>
                    <fullName>IR Request Pending Approval</fullName>
                    <label>Pending Approval</label>
                </value>
                <value>
                    <fullName>Approved for PO</fullName>
                </value>
                <value>
                    <fullName>PO Submitted</fullName>
                </value>
                <value>
                    <fullName>PO Partially Fulfilled</fullName>
                </value>
                <value>
                    <fullName>PO Fulfilled</fullName>
                </value>
                <value>
                    <fullName>IR Request Submitted</fullName>
                    <isActive>false</isActive>
                    <label>IR Request Submitted</label>
                </value>
                <value>
                    <fullName>PO Delivery Date Scheduled</fullName>
                    <isActive>false</isActive>
                    <label>PO Delivery Date Scheduled</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Total_Nbr_of_Assets_Created__c</fullName>
        <description>The Total # of Assets Created for ALL Line Items.</description>
        <inlineHelpText>The Total # of Assets Created for ALL Line Items.</inlineHelpText>
        <label>Total # of Assets Created</label>
        <summarizedField>Inventory_Request_Line_Item__c.Number_of_Assets_Created__c</summarizedField>
        <summaryForeignKey>Inventory_Request_Line_Item__c.Inventory_Request__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Total_Qty_Requested__c</fullName>
        <description>Sum of quantity requested on all line items.</description>
        <inlineHelpText>The summation of quantity requested from all the line items.</inlineHelpText>
        <label>Total Qty Requested</label>
        <summarizedField>Inventory_Request_Line_Item__c.Quantity__c</summarizedField>
        <summaryForeignKey>Inventory_Request_Line_Item__c.Inventory_Request__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>Inventory Request</label>
    <nameField>
        <label>Request Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Inventory Requests</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/InventoryRequestTriggerHandler.cls
public with sharing class InventoryRequestTriggerHandler {

    public static final String      PO_FULFILLED_STATUS = 'PO Fulfilled';
    public static final String      PO_PARTIALLY_FULFILLED_STATUS = 'PO Partially Fulfilled';
    public static final String      PO_SUBMITTED_STATUS = 'PO Submitted';
    public static final Set<String> NOT_APPROVED_STATUSES = new Set<String>{ 'Open', PO_SUBMITTED_STATUS } ;

    /**
     * IMPLICIT!
     *
     * @param mOldIrs
     * @param mNewIrs
     *
     * @return
     */
    public static List<Inventory_Request__c> updateIrStatus ( Map<Id,Inventory_Request__c> mOldIrs,
                                                             Map<Id,Inventory_Request__c> mNewIrs ) {

        List<Inventory_Request__c> irsUpdated = new List<Inventory_Request__c>();

        for ( Inventory_Request__c newIr : mNewIrs.values() ) {
            Inventory_Request__c oldIr  = mOldIrs.get(newIr.Id);

            if( newIr.Total_Nbr_of_Assets_Created__c != oldIr.Total_Nbr_of_Assets_Created__c ) {
                if( newIr.Total_Nbr_of_Assets_Created__c == newIr.Total_Qty_Requested__c ) {
                    newIr.Status__c = PO_FULFILLED_STATUS;
                } else if ( newIr.Total_Nbr_of_Assets_Created__c > 0 ) {
                    newIr.Status__c = PO_PARTIALLY_FULFILLED_STATUS;
                } else  {
                    if(newIr.PO_Submitted_Date__c != null && newIr.Status__c != PO_SUBMITTED_STATUS) {
                        newIr.Status__c = PO_SUBMITTED_STATUS;
                    }
                }
                irsUpdated.add(newIr);
            }
        }
        return irsUpdated;
    }

    public static List<Inventory_Request__c> updateFinalApprovedIndicator ( Map<Id,Inventory_Request__c> mOldIrs,
            Map<Id,Inventory_Request__c> mNewIrs ) {

        List<Inventory_Request__c> irsUpdated = new List<Inventory_Request__c>();

        for ( Inventory_Request__c newIr : mNewIrs.values() ) {
            Inventory_Request__c oldIr  = mOldIrs.get(newIr.Id);
            if( newIr.Status__c != oldIr.Status__c ) {
                irsUpdated.add(newIr);
            }
        }
        return irsUpdated;
    }
}