objects/Meter_Reading__c.object
<CustomObject>
    <description>Example object to capture electronic meters</description>
    <fields>
        <fullName>Route_Processing_Sheet__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Route Processing Sheet</label>
        <referenceTo>Route_Processing_Sheet__c</referenceTo>
        <relationshipLabel>Meter Readings</relationshipLabel>
        <relationshipName>Meter_Readings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Snapshot__c</fullName>
        <label>Snapshot</label>
        <type>Url</type>
    </fields>
    <label>Meter Reading</label>
    <nameField>
        <displayFormat>MTR-{000000000}</displayFormat>
        <label>Meter Reading ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Meter Readings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Route_Processing_Sheet__c.object
<CustomObject>
    <description>Example digitization of the route processing sheet</description>
    <fields>
        <fullName>Snapshot_Cassette__c</fullName>
        <label>Snapshot Cassette</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Snapshot_New_Cassette__c</fullName>
        <label>Snapshot New Cassette</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Total_Meter_Readings__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Total Number of Meter Readings Associated with this Route Processing Sheet. (DLRS Maintained). Currently async.. ie runs once an hour on the hour.</description>
        <inlineHelpText>Total Number of Meter Readings Associated with this Route Processing Sheet. (DLRS Maintained) This is refreshed once an hour at the top of the hour</inlineHelpText>
        <label>Total Meter Readings</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Route Processing Sheet</label>
    <nameField>
        <displayFormat>Collection-Id-{000000000}</displayFormat>
        <label>Collection ID Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Route Processing Sheets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/FileUploadSvcTest.cls
@IsTest
private class FileUploadSvcTest {

    @TestSetup
    static void setupData() {
        Test.startTest();
        Map<String,Object> mBaseData = clTESTUTILS.createAllNonClData();
        Test.stopTest();

        clTESTUTILS.createEnd2EndRouteData(mBaseData);
    }

    @IsTest
    static void test_saveTheChunkFile() {

        Route_Processing_Sheet__c rps = [SELECT Id FROM Route_Processing_Sheet__c WHERE Total_Meter_Readings__c > 0 LIMIT 1];
        List<Meter_Reading__c> meterReadings = [SELECT Id, Name FROM Meter_Reading__c WHERE Route_Processing_Sheet__c = :rps.Id];
        String contentType = 'png';
        Blob blobImg = Blob.valueOf('A pretty picture');
        String base64Data = EncodingUtil.base64Encode(blobImg);

        Test.startTest();
        Id fileId = null;
        for(Meter_Reading__c meterReading : meterReadings) {
            fileId = FileUploadSvc.saveTheChunkFile(meterReading.Id,meterReading.Name,base64Data,contentType,fileId,null);
        }
        List<Meter_Reading__c> processedMeterReadings = [
                SELECT Id, Snapshot__c
                FROM   Meter_Reading__c
                WHERE   Id in :meterReadings
        ];
        for(Meter_Reading__c tmpMr : processedMeterReadings) {
            System.debug('---> processed mr= '+tmpMr);
        }


        Test.stopTest();
    }

    @IsTest
    static void test_saveRpsImage() {

        Route_Processing_Sheet__c rps = [SELECT Id,Name FROM Route_Processing_Sheet__c WHERE Total_Meter_Readings__c > 0 LIMIT 1];
        List<Meter_Reading__c> meterReadings = [SELECT Id, Name FROM Meter_Reading__c WHERE Route_Processing_Sheet__c = :rps.Id];
        String contentType = 'png';
        Blob blobImgCassette = Blob.valueOf('A pretty picture cassette');
        String base64DataCassette = EncodingUtil.base64Encode(blobImgCassette);
        Blob blobImgNewCassette = Blob.valueOf('A pretty picture new cassette');
        String base64DataNewCassette = EncodingUtil.base64Encode(blobImgNewCassette);

        Test.startTest();
        Id fileIdCassette = null;
        Id fileIdNewCassette = null;
        fileIdCassette = FileUploadSvc.saveTheChunkFile(rps.Id,rps.Name,base64DataCassette,contentType,fileIdCassette,'Current Cassette');
        fileIdNewCassette = FileUploadSvc.saveTheChunkFile(rps.Id,rps.Name,base64DataNewCassette,contentType,fileIdNewCassette,'New Cassette');

        rps = clRouteProcessingSheetSvc.retrieveRouteProcessingSheet(rps.Id);
        System.assert(rps.Snapshot_New_Cassette__c != null);
        System.assert(rps.Snapshot_Cassette__c != null);

        Test.stopTest();
    }

    @IsTest
    static void test_deleteDoc() {

        Route_Processing_Sheet__c rps = [SELECT Id FROM Route_Processing_Sheet__c WHERE Total_Meter_Readings__c > 0 LIMIT 1];
        List<Meter_Reading__c> meterReadings = [SELECT Id, Name FROM Meter_Reading__c WHERE Route_Processing_Sheet__c = :rps.Id];
        String contentType = 'png';
        Blob blobImg = Blob.valueOf('A pretty picture');
        String base64Data = EncodingUtil.base64Encode(blobImg);

        Set<Id> cvIds = new Set<Id>();
        for(Meter_Reading__c meterReading : meterReadings) {
            cvIds.add(FileUploadSvc.saveTheChunkFile(meterReading.Id,meterReading.Name,base64Data,contentType,null,null));
        }

        ContentDocumentLink cdl = [
                SELECT Id,LinkedEntityId,ContentDocumentId
                FROM ContentDocumentLink
                WHERE LinkedEntityId = :meterReadings[0].Id
                LIMIT 1
        ];

        Test.startTest();
        ResponseDto dto = FileUploadSvc.deleteDoc(cdl.ContentDocumentId, cdl.LinkedEntityId);
        System.assert(dto.isSuccess);
        dto = FileUploadSvc.deleteDoc(null, cdl.LinkedEntityId);
        System.assert(!dto.isSuccess);
        Test.stopTest();
    }

}