objects/Meter_Reading__c.object
<CustomObject>
    <description>Example object to capture electronic meters</description>
    <fields>
        <fullName>Current_Lifetime_Cash_In__c</fullName>
        <label>Current Lifetime Cash In</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Processing_Status__c</fullName>
        <label>Processing Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>In Progress</fullName>
                    <default>true</default>
                    <label>In Progress</label>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Reading_Status__c</fullName>
        <defaultValue>&quot;New&quot;</defaultValue>
        <description>That status of the meter reading.. Generally this will start in In Progress unless we are inserting this meter records outside of the ui... Completion is currently when there is shapshot count &gt; 0 (image uploaded) and current lifetime case in value added. @see  MeterReadingTriggerHandler.cls</description>
        <inlineHelpText>That status of the meter reading.. Generally this will start in In Progress unless we are inserting this meter records outside of the ui... Completion is currently when there is shapshot count &gt; 0 (image uploaded) and current lifetime case in value added.</inlineHelpText>
        <label>Reading Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Cannot Collect</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Route_Processing_Sheet__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Route Processing Sheet</label>
        <referenceTo>Route_Processing_Sheet__c</referenceTo>
        <relationshipLabel>Meter Readings</relationshipLabel>
        <relationshipName>Meter_Readings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Snapshot__c</fullName>
        <label>Snapshot</label>
        <type>Url</type>
    </fields>
    <label>Meter Reading</label>
    <nameField>
        <displayFormat>MTR-{000000000}</displayFormat>
        <label>Meter Reading ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Meter Readings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Route__c.object
<CustomObject>
    <description>Example object to house routes and routing of collections</description>
    <label>Route</label>
    <nameField>
        <label>Route Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Routes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Route_Processing_Sheet__c.object
<CustomObject>
    <description>Example digitization of the route processing sheet</description>
    <fields>
        <fullName>Processing_Status__c</fullName>
        <description>More processor based since reqs differed between the status for a collector and the status for a processor.</description>
        <inlineHelpText>More processor based since reqs differed between the status for a collector and the status for a processor.</inlineHelpText>
        <label>Fill Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>COMPLETED FILL</fullName>
                </value>
                <value>
                    <fullName>Not Yet Filled</fullName>
                    <default>true</default>
                    <label>Not Yet Filled</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Processor_RT_Status__c</fullName>
        <label>Processor RT Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Redemption_Terminal_Status__c</fullName>
        <description>@TODO automation sets this based on ?</description>
        <inlineHelpText>@TODO automation sets this based on ?</inlineHelpText>
        <label>Collector RT Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Not Started</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Route_Schedule__c</fullName>
        <label>Route Schedule</label>
        <referenceTo>Route_Schedule__c</referenceTo>
        <relationshipLabel>Route Processing Sheets</relationshipLabel>
        <relationshipName>Route_Processing_Sheets</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Collection Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Not Started</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
                <value>
                    <fullName>Skipped</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Route Processing Sheet</label>
    <nameField>
        <displayFormat>Collection-Id-{000000000}</displayFormat>
        <label>Collection ID Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Route Processing Sheets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Route_Schedule__c.object
<CustomObject>
    <description>Assignment information of a physical route&apos;s locations, collectors, vehicles, and questions for a specific day</description>
    <fields>
        <fullName>Processing_Status__c</fullName>
        <label>Processing Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Processing Incomplete</fullName>
                    <color>#FF6666</color>
                    <default>true</default>
                    <label>Processing Incomplete</label>
                </value>
                <value>
                    <fullName>COMPLETED PROCESSING</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Route_End_Timestamp__c</fullName>
        <description>The Date/Time the collector clicked the end route button</description>
        <inlineHelpText>The Date/Time the collector clicked the end route button, When this is set an email will be sent.</inlineHelpText>
        <label>Route End Timestamp</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Route__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Route to collect</description>
        <label>Route</label>
        <referenceTo>Route__c</referenceTo>
        <relationshipLabel>Route Schedules</relationshipLabel>
        <relationshipName>Route_Schedules</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Route Schedule</label>
    <nameField>
        <label>Route Schedule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Route Schedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/Accel_RouteScheduleTriggerTest.cls
@IsTest
private class Accel_RouteScheduleTriggerTest {
    /**
     * NOTE start / stop test merely there to reset gov limits as creating non cl data takes forever given
     * all the processors / flows and eventually will bust cpu time outs on it's own.
     */
    @TestSetup
    static void setupData() {

        Test.startTest();
        Map<String,Object> mBaseData = clTESTUTILS.createAllNonClData();
        Test.stopTest();

        Map<String,Object> mClData =  clTESTUTILS.createEnd2EndRouteData(mBaseData);
    }

    @IsTest
    static void test_updateCollectionStatus() {

        Map<String,Object> mUser = clTESTUTILS.getClUsers();
        User processor = (User)mUser.get(clTESTUTILS.PROCESSOR);
        Route__c route = [SELECT ID From Route__c LIMIT 1];
        Route_Schedule__c routeSchedule = [SELECT Id FROM Route_Schedule__c WHERE Route__c = :route.Id LIMIT 1];
        List<Route_Processing_Sheet__c> rpss = [SELECT  Id,Status__c FROM Route_Processing_Sheet__c WHERE Route_Schedule__c = :routeSchedule.Id];
        List<Meter_Reading__c> meterReadings = [SELECT Id, Current_Lifetime_Cash_In__c,Reading_Status__c FROM Meter_Reading__c WHERE Route_Processing_Sheet__c IN :rpss];

        Test.startTest();
        for(Meter_Reading__c meterReading : meterReadings) {
            meterReading.Current_Lifetime_Cash_In__c = 1;
        }
        update meterReadings;

        for(Route_Processing_Sheet__c rps : rpss) {
            rps.Status__c = 'Complete';
        }
        //  fires rollup summary to parent route schedule
        update rpss;

        for(Meter_Reading__c meterReading : meterReadings) {
            meterReading.Current_Lifetime_Cash_In__c = 0;
        }
        update meterReadings;

        Test.stopTest();
    }

    @IsTest
    static void test_updateProcessorProcessStatus() {

        Map<String,Object> mUser = clTESTUTILS.getClUsers();
        User processor = (User)mUser.get(clTESTUTILS.PROCESSOR);
        Route__c route = [SELECT ID From Route__c LIMIT 1];
        Route_Schedule__c routeSchedule = [SELECT Id FROM Route_Schedule__c WHERE Route__c = :route.Id LIMIT 1];
        Route_Processing_Sheet__c rps = [SELECT  Id,Processor_RT_Status__c  FROM Route_Processing_Sheet__c WHERE Route_Schedule__c = :routeSchedule.Id LIMIT 1];
        List<Meter_Reading__c> meterReadings = [SELECT Id, Current_Lifetime_Cash_In__c,Reading_Status__c FROM Meter_Reading__c WHERE Route_Processing_Sheet__c = :rps.Id];

        Test.startTest();

        for(Meter_Reading__c meterReading : meterReadings) {
            meterReading.Current_Lifetime_Cash_In__c = 1;
            meterReading.Processing_Status__c = 'Completed';
            meterReading.Reading_Status__c = 'Completed';
        }
        update meterReadings;

        rps.Processor_RT_Status__c = 'Complete';
        update rps;

        Test.stopTest();
    }

    @IsTest
    static void test_updateRouteEndTime() {

        Map<String,Object> mUser = clTESTUTILS.getClUsers();
        User processor = (User)mUser.get(clTESTUTILS.PROCESSOR);
        Route__c route = [SELECT ID From Route__c LIMIT 1];
        Route_Schedule__c routeSchedule = [SELECT Id,Route_End_Timestamp__c FROM Route_Schedule__c WHERE Route__c = :route.Id LIMIT 1];
        List<Route_Processing_Sheet__c> rpss = [SELECT  Id,Status__c FROM Route_Processing_Sheet__c WHERE Route_Schedule__c = :routeSchedule.Id];
        List<Meter_Reading__c> meterReadings = [SELECT Id, Current_Lifetime_Cash_In__c,Reading_Status__c FROM Meter_Reading__c WHERE Route_Processing_Sheet__c IN :rpss];
        for(Meter_Reading__c meterReading : meterReadings) {
            meterReading.Current_Lifetime_Cash_In__c = 1;
            meterReading.Snapshot__c = 'http://www.bogus.com';
        }
        update meterReadings;

        for(Route_Processing_Sheet__c rps : rpss) {
            rps.Status__c = 'Complete';
            rps.Redemption_Terminal_Status__c = 'Complete';
        }
        //  fires rollup summary to parent route schedule
        update rpss;

        Test.startTest();
        routeSchedule.Route_End_Timestamp__c = System.now();
        update routeSchedule;
        Test.stopTest();
    }

    @IsTest
    static void test_fire_platform_event() {

        Map<String,Object> mUser = clTESTUTILS.getClUsers();
        User processor = (User)mUser.get(clTESTUTILS.PROCESSOR);
        Route__c route = [SELECT ID From Route__c LIMIT 1];
        Route_Schedule__c routeSchedule = [SELECT Id,Route_End_Timestamp__c FROM Route_Schedule__c WHERE Route__c = :route.Id LIMIT 1];
        List<Route_Processing_Sheet__c> rpss = [SELECT  Id,Status__c FROM Route_Processing_Sheet__c WHERE Route_Schedule__c = :routeSchedule.Id];
        List<Meter_Reading__c> meterReadings = [SELECT Id, Current_Lifetime_Cash_In__c,Reading_Status__c FROM Meter_Reading__c WHERE Route_Processing_Sheet__c IN :rpss];

        Test.startTest();
            clRouteScheduleTriggerHandler.firePlatformEvent(new Map<Id,Route_Schedule__c> {routeSchedule.Id => routeSchedule} );
        Test.stopTest();
    }
}