objects/Meter_Reading__c.object
<CustomObject>
    <description>Example object to capture electronic meters</description>
    <fields>
        <fullName>Route_Processing_Sheet__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Route Processing Sheet</label>
        <referenceTo>Route_Processing_Sheet__c</referenceTo>
        <relationshipLabel>Meter Readings</relationshipLabel>
        <relationshipName>Meter_Readings</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Meter Reading</label>
    <nameField>
        <displayFormat>MTR-{000000000}</displayFormat>
        <label>Meter Reading ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Meter Readings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Route_Processing_Sheet__c.object
<CustomObject>
    <description>Example digitization of the route processing sheet</description>
    <label>Route Processing Sheet</label>
    <nameField>
        <displayFormat>Collection-Id-{000000000}</displayFormat>
        <label>Collection ID Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Route Processing Sheets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/clAdminOnlyGenMeterReadingsCtrlTest.cls
@IsTest
private class clAdminOnlyGenMeterReadingsCtrlTest {

    @TestSetup
    static void setupData() {

        Test.startTest();
        Map<String,Object> mBaseData = clTESTUTILS.createAllNonClData();
        Test.stopTest();

        Map<String,Object> mClData =  clTESTUTILS.createEnd2EndRouteData(mBaseData);
    }

    @IsTest
    static void test_doCreateMeterReadings() {

        Route_Processing_Sheet__c rps = [SELECT Id FROM Route_Processing_Sheet__c LIMIT 1];
        List<Meter_Reading__c> meterReadings = [
                SELECT Id
                FROM   Meter_Reading__c
                WHERE  Route_Processing_Sheet__c = :rps.Id
        ];
        delete meterReadings;

        Test.startTest();

        ResponseDto dto = clAdminOnlyGenMeterReadingsController.doCreateMeterReadings(rps.Id);
        System.assert(dto.isSuccess);
        List<Meter_Reading__c> meterReadingsInserted = (List<Meter_Reading__c>)dto.values.get(clAdminOnlyGenMeterReadingsController.MAP_KEY_METERS);
        System.assert(meterReadingsInserted.size() > 0);

        Test.stopTest();
    }

    @IsTest
    static void test_doRetrieveRps() {

        Route_Processing_Sheet__c rps = [SELECT Id FROM Route_Processing_Sheet__c LIMIT 1];

        Test.startTest();

        ResponseDto dto = clAdminOnlyGenMeterReadingsController.doRetrieveRps(rps.Id);
        System.assert(dto.isSuccess);

        Test.stopTest();
    }
}