objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Asset_Model_Name__c</fullName>
        <description>Name as it appears on assets integrated from GP</description>
        <label>Asset Model Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Thirty_Day_Location_Share_Avg__c</fullName>
        <defaultValue>0</defaultValue>
        <label>30 Day Location Share Avg</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Thirty_Day_Location_Share_Total__c</fullName>
        <defaultValue>0</defaultValue>
        <label>30 Day Location Share Total</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Thirty_Day_Revenue_Avg__c</fullName>
        <defaultValue>0</defaultValue>
        <label>30 Day Revenue Avg</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Thirty_Day_Revenue_Total__c</fullName>
        <defaultValue>0</defaultValue>
        <label>30 Day Revenue Total</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/ProductSvc.cls
public with sharing class ProductSvc {
    /**
     * @return List<Product2> that have asset model names.
     */
    public static List<Product2> retrieveAllMachineAverages() {
        List<Product2> products;
        String productFamily = 'ASSET';
        products = [
                SELECT  id, name, asset_model_name__c,
                        Thirty_Day_Location_Share_Avg__c,Thirty_Day_Revenue_Avg__c,
                        Thirty_Day_Location_Share_Total__c,Thirty_Day_Revenue_Total__c
                FROM    Product2
                WHERE   Family  =   :productFamily
                and     asset_model_name__c != null
                order by name asc
        ];
        return products;
    }
}