objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Products (Account)</relationshipLabel>
        <relationshipName>Products2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Manufacturer__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Look up to the Account - Record Type: Manufacturer</description>
        <inlineHelpText>The Manufacturer Associated with the Product (An Account of record type Manufacturer)</inlineHelpText>
        <label>Manufacturer</label>
        <lookupFilter>
            <active>false</active>
            <errorMessage>Product selected must be an account with a record type of Manufacturer.</errorMessage>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Manufacturer</value>
            </filterItems>
            <infoMessage>Product selected must be an account with a record type of Manufacturer.</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Assigned_RM__c</fullName>
        <formula>Account__r.Relationship_Manager__r.FirstName &amp;&apos; &apos;&amp;Account__r.Relationship_Manager__r.LastName</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Relationship Manager</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Project_Line__c.object
<CustomObject>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Project Lines</relationshipLabel>
        <relationshipName>Project_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Project Lines</relationshipLabel>
        <relationshipName>Project_Lines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Project Line</label>
    <nameField>
        <label>Project Line Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/ProductSearchControllerTest.cls
@isTest
private class ProductSearchControllerTest {
    private static final String PROJ_NAME = 'Test Project';
    private static final String PROJ_LINE_NAME = 'Test Project Line';
    private static final String PROJ_LINE_NAME_2 = 'Test Project Line 2';
    private static final String PROJ_LINE_NAME_3 = 'Test Project Line 3';
    private static final String ACC_NAME = 'Test Account';
    private static final String PRODUCT_NAME = 'Test Product';
    private static final String OPP_NAME = 'Test Opportunity';
    private static final String PRICEBOOK_NAME = 'Test Pricebook';
    private static final String PRICEBOOK_ENTRY_NAME = 'Test Pricebook Entry Name';

    @testSetup static void setup() {

        User u = new User(
                             ProfileId = [SELECT Id FROM Profile WHERE Name = 'System Administrator'].Id,
                             LastName = 'last',
                             Email = 'puser000@amamama.com',
                             Username = 'puser000@amamama.com' + System.currentTimeMillis(),
                             CompanyName = 'TEST',
                             Title = 'title',
                             Alias = 'alias',
                             TimeZoneSidKey = 'America/Los_Angeles',
                             EmailEncodingKey = 'UTF-8',
                             LanguageLocaleKey = 'en_US',
                             LocaleSidKey = 'en_US'
                        );
        insert u;

        Account acc = new Account();
        acc.Name = ACC_NAME;
        //acc.Assigned_RM__c = u.Id;
        insert acc;

        Opportunity opp = new Opportunity();
        opp.Name = OPP_NAME;
        opp.AccountId = acc.Id;
        opp.StageName = 'New';
        opp.CloseDate = system.today().addDays(7);
        insert opp;

        Project__c proj = new Project__c();
        proj.Name = PROJ_NAME;
        proj.Account__c = acc.Id;
        proj.Opportunity__c = opp.Id;
        insert proj;

        Product2 product = new Product2();
        product.Name = PRODUCT_NAME;
        product.Family = 'GAMEPART';
        product.Manufacturer__c = acc.Id;
        insert product;

        //PriceBook2 pricebook = new PriceBook2();
        //pricebook.Name = PRICEBOOK_NAME;
        //insert pricebook;

        PricebookEntry pricebookEntry = new PricebookEntry();
        pricebookEntry.Product2Id = product.Id;
        pricebookEntry.UnitPrice = 0;
        pricebookEntry.Pricebook2Id = Test.getStandardPricebookId();
        //pricebookEntry.UseStandardPrice = true;
        insert pricebookEntry;

        Project_Line__c projLine = new Project_Line__c();
        ProjLine.Name = PROJ_LINE_NAME;
        ProjLine.Project__c = proj.Id;
        ProjLine.Product__c = product.Id;
        insert ProjLine;
    }
    
    @isTest static void test_getProjectLineItems_Insert() {
        Project__c proj = [SELECT Id FROM Project__c LIMIT 1];
        //system.debug(proj.Id);

        Test.startTest();
        List<Project_Line__c> projectLineItems = ProductSearchController.getProjectLineItems(proj.Id);
        Test.stopTest();

        system.assertEquals(1, projectLineItems.size());
    }
    
    @isTest static void test_saveProjectLines_Insert() {
        Project__c project = [SELECT Id, Name FROM Project__c LIMIT 1];
        Product2 product = [SELECT Id, Name FROM Product2 LIMIT 1];

        List<Project_Line__c> projectLines = new List<Project_Line__c>();
        projectLines.add(new Project_Line__c(
                Name = PROJ_LINE_NAME_2,
                Product__c = product.Id
            ));
        projectLines.add(new Project_Line__c(
                Name = PROJ_LINE_NAME_3,
                Product__c = product.Id
            ));

        Test.startTest();
        String result = ProductSearchController.saveProjectLines(projectLines, project.Id);
        Test.stopTest();

        system.assertEquals('SUCCESS',result);

        // rjn removed String expectedProjectLineName = project.Name + ' ' + product.Name;
        String expectedProjectLineName = product.Name;
        List<Project_Line__c> projectLinesResults = [SELECT Project__c, Id, Name
                                                    FROM Project_Line__c
                                                    WHERE Name = :expectedProjectLineName];

        system.assertEquals(2, projectLinesResults.size());                                                 
    }

    @isTest static void test_getProducts_Insert() {
        Product2 product = [SELECT Id, Name FROM Product2 LIMIT 1];
        String searchString = PRODUCT_NAME;
        Integer queryOffset = 0;

        //CREATE PRICEBOOK ENTRY


        system.debug(product);
        system.debug(product.Name);

        Test.startTest();
        ProductSearchController.ProductTableResponse result = ProductSearchController.getProducts(searchString, queryOffset);
        system.debug(result);
        system.debug(result.productData);
        //system.debug(result.productData);

        Test.stopTest();

        system.assertEquals(product.Name, result.productData[0].Name);

    }
    
}