objects/Purchase_Order__c.object
<CustomObject>
    <fields>
        <fullName>Purchase_Order__c</fullName>
        <label>Purchase Order #</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Purchase Order</label>
    <nameField>
        <label>Purchase Order Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Purchase Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Purchase_Order_Item__c.object
<CustomObject>
    <fields>
        <fullName>Purchase_Order__c</fullName>
        <inlineHelpText>M</inlineHelpText>
        <label>Purchase Order</label>
        <referenceTo>Purchase_Order__c</referenceTo>
        <relationshipLabel>Purchase Order Items</relationshipLabel>
        <relationshipName>Purchase_Order_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Purchase Order Item</label>
    <nameField>
        <displayFormat>PO-Item-{0000000}</displayFormat>
        <label>Purchase Order Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Purchase Order Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Software_Assets_Config__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Software Assets Config</label>
</CustomObject>

classes/AssetController.cls
public with sharing class AssetController {

    public final static String MAP_KEY_SW_ASSET_CONFIG_SETTING = 'SW_ASSET_CONFIG';
    public final static String MAP_KEY_PO_ITEMS = 'MAP_KEY_PO_ITEMS';
    /**
     * @param poId
     * @return a dto containing the Purchase_Order__c {dto.sObj}
     */
    @AuraEnabled
    public static ResponseDto retrievePo( Id poId ) {
        ResponseDto dto = new ResponseDto();
        Purchase_Order__c purchaseOrder = PoSvc.retrievePo(poId);
        Software_Assets_Config__c configSettings = CustomSettingsSvc.getSoftwareAssetsConfigSettings(UserInfo.getUserId());
        if(purchaseOrder != null) {
            dto.sObj = purchaseOrder;
            dto.values.put(MAP_KEY_SW_ASSET_CONFIG_SETTING,configSettings);
            dto.isSuccess = true;
        }
        return dto;
    }
    /**
     *
     * Retrieves all the po items for a parent purchase order id.
     * @param poId The parent Purchase Order SFDC Id.
     * @return a dto containing the custom setting info and po items
     */
    @AuraEnabled
    public static ResponseDto retrievePoItems( Id poId ) {
        ResponseDto dto = new ResponseDto();
        List<Purchase_Order_Item__c> purchaseOrderItems = PoSvc.retrievePoItems(poId);
        Software_Assets_Config__c configSettings = CustomSettingsSvc.getSoftwareAssetsConfigSettings(UserInfo.getUserId());
        if(!purchaseOrderItems.isEmpty()) {
            dto.values.put(MAP_KEY_PO_ITEMS,purchaseOrderItems);
            dto.values.put(MAP_KEY_SW_ASSET_CONFIG_SETTING,configSettings);
            dto.isSuccess = true;
        }
        return dto;
    }
}