objects/Record_Updated_Event__e.object
<CustomObject>
    <description>A generic platform event that can be fired when a record is updated outside of the standard platform life-cycle ie. Queueable / Batchable</description>
    <fields>
        <fullName>Record_Ids__c</fullName>
        <description>A comma delimited list of record ids</description>
        <label>Record Ids</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>SObject_API_Name__c</fullName>
        <label>SObject API Name</label>
        <length>64</length>
        <type>Text</type>
    </fields>
    <label>Record Updated Event</label>
    <pluralLabel>Record Updated Events</pluralLabel>
</CustomObject>

classes/PlatformEventSvcTest.cls
@IsTest
private class PlatformEventSvcTest {

    @IsTest
    static void test_publishPlatformEvents_success() {

        List<SObject> sObjects = new List<SObject>();
        Record_Updated_Event__e recordUpdatedEvent = new Record_Updated_Event__e();
        recordUpdatedEvent.Record_Ids__c = 'blahid';
        recordUpdatedEvent.SObject_API_Name__c = 'Account';
        sObjects.add(recordUpdatedEvent);

        Test.startTest();
        PlatformEventSvc.publishPlatformEvents(sObjects);
        Test.stopTest();
    }

    @IsTest
    static void test_publishPlatformEvents_error() {

        List<SObject> sObjects = new List<SObject>();
        sObjects.add(new Account());

        Test.startTest();
        PlatformEventSvc.publishPlatformEvents(sObjects);
        Test.stopTest();
    }
}