objects/Region__c.object
<CustomObject>
    <description>Holds Region Related Info. Current Record Types = [Covid]. Can be expanded for other types of regions.  Linked to County and Accounts.</description>
    <label>Region</label>
    <nameField>
        <label>Region Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Regions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Route_Import__c.object
<CustomObject>
    <description>Custom Object so that we can use an OOTB File Upload Component (we need to attach the files to some sort of parent). Create one record for each region aka processing location</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <description>Matches to region aka processing location.</description>
        <inlineHelpText>Matches to region aka processing location.</inlineHelpText>
        <label>Region</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Processing_Location</valueSetName>
        </valueSet>
    </fields>
    <label>Route Import</label>
    <nameField>
        <label>Region Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Route Imports</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

globalValueSets/Processing_Location.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Burr Ridge</fullName>
    </customValue>
    <customValue>
        <fullName>DEV TEST 1</fullName>
    </customValue>
    <customValue>
        <fullName>Tinley Park</fullName>
    </customValue>
    <customValue>
        <fullName>Peoria</fullName>
    </customValue>
    <customValue>
        <fullName>Springfield</fullName>
    </customValue>
    <customValue>
        <fullName>CW</fullName>
    </customValue>
    <customValue>
        <fullName>Rockford</fullName>
    </customValue>
    <customValue>
        <fullName>Collinsville</fullName>
    </customValue>
    <masterLabel>Processing Location</masterLabel>
</GlobalValueSet>

classes/Accel_ContentVersionTriggerTest.cls
@IsTest
private class Accel_ContentVersionTriggerTest {

    /**
     * NOTE start / stop test merely there to reset gov limits as creating non cl data takes forever given
     * all the processors / flows and eventually will bust cpu time outs on it's own.
     */
    @TestSetup
    static void setupData() {

        Test.startTest();
        Map<String,Object> mBaseData = clTESTUTILS.createAllNonClData();
        Test.stopTest();
        Map<String,Object> mClData =  clTESTUTILS.createEnd2EndRouteData(mBaseData);
        List<Route_Import__c> routeImports = clTESTUTILS.createClRouteImportRecords();
    }

    @IsTest
    static void test_uploadRouteImport() {

        List<Route_Import__c> routeImports = [
                SELECT Id, Name, Region__C, Active__c
                FROM Route_Import__c
        ];

        Test.startTest();
            List<ContentVersion> contentVersions = clTESTUTILS.createRouteImportFiles(routeImports);
            System.assertEquals(contentVersions.size(),routeImports.size());
            //@todo subscribe and assert to platform event fired?
        Test.stopTest();
    }
    
}