objects/Route__c.object
<CustomObject>
    <description>Example object to house routes and routing of collections</description>
    <fields>
        <fullName>Processing_Location__c</fullName>
        <label>Processing Location</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Processing_Location</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Total_Accounts__c</fullName>
        <description>R/S</description>
        <label>Total Accounts</label>
        <summaryForeignKey>Route_Account__c.Route__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>Route</label>
    <nameField>
        <label>Route Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Routes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Route_Processing_Sheet__c.object
<CustomObject>
    <description>Example digitization of the route processing sheet</description>
    <fields>
        <fullName>Processing_Location__c</fullName>
        <label>Processing Location</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Processing_Location</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Processing_Process_Status__c</fullName>
        <label>Processing Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Processing Incomplete</fullName>
                    <default>true</default>
                    <label>Processing Incomplete</label>
                </value>
                <value>
                    <fullName>COMPLETED PROCESSING</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Processing_Status__c</fullName>
        <description>More processor based since reqs differed between the status for a collector and the status for a processor.</description>
        <inlineHelpText>More processor based since reqs differed between the status for a collector and the status for a processor.</inlineHelpText>
        <label>Fill Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>COMPLETED FILL</fullName>
                </value>
                <value>
                    <fullName>Not Yet Filled</fullName>
                    <default>true</default>
                    <label>Not Yet Filled</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Route_Fill_Date__c</fullName>
        <description>not sure?</description>
        <inlineHelpText>not sure?</inlineHelpText>
        <label>Route Fill Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Route_Schedule__c</fullName>
        <label>Route Schedule</label>
        <referenceTo>Route_Schedule__c</referenceTo>
        <relationshipLabel>Route Processing Sheets</relationshipLabel>
        <relationshipName>Route_Processing_Sheets</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Route Processing Sheet</label>
    <nameField>
        <displayFormat>Collection-Id-{000000000}</displayFormat>
        <label>Collection ID Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Route Processing Sheets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Route_Schedule__c.object
<CustomObject>
    <description>Assignment information of a physical route&apos;s locations, collectors, vehicles, and questions for a specific day</description>
    <fields>
        <fullName>Processing_Location__c</fullName>
        <label>Processing Location</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Processing_Location</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Processing_Status__c</fullName>
        <label>Processing Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Processing Incomplete</fullName>
                    <color>#FF6666</color>
                    <default>true</default>
                    <label>Processing Incomplete</label>
                </value>
                <value>
                    <fullName>COMPLETED PROCESSING</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Route_Collection_Date__c</fullName>
        <description>Day Collection will take place</description>
        <label>Route Collection Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Route_Fill_Date__c</fullName>
        <description>Not sure how this is used yet?</description>
        <inlineHelpText>Note sure how this is used yet?</inlineHelpText>
        <label>Route Fill Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Route__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Route to collect</description>
        <label>Route</label>
        <referenceTo>Route__c</referenceTo>
        <relationshipLabel>Route Schedules</relationshipLabel>
        <relationshipName>Route_Schedules</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Total_Accounts__c</fullName>
        <description>Total Accounts Associated with this Route_Schedule_c record. (Rollup Summary or Route_Schedule_Account__c_)</description>
        <inlineHelpText>Total Accounts Associated with this Route_Schedule_c record. (RS)</inlineHelpText>
        <label>Total Accounts</label>
        <summaryForeignKey>Route_Schedule_Account__c.Route_Schedule__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Total_Processing_Sheets__c</fullName>
        <description>Total Processing Sheets generated by this schedule record. Rollup Summary of Route_Processing_Sheet__c</description>
        <inlineHelpText>Total Processing Sheets generated by this schedule record. (RS)</inlineHelpText>
        <label>Total Processing Sheets</label>
        <summaryForeignKey>Route_Processing_Sheet__c.Route_Schedule__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>Route Schedule</label>
    <nameField>
        <label>Route Schedule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Route Schedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>Processing_Location__c</fullName>
        <description>Used for Cash Logistics - When an Route schedule is created, it is assigned to a processing location. This is used to determine, when a user of profile CL - Route Processor logs in, what route schedules they see.</description>
        <inlineHelpText>Used for Cash Logistics - When an Route schedule is created, it is assigned to a processing location. This is used to determine, when a user of profile CL - Route Processor logs in, what route schedules they see.</inlineHelpText>
        <label>Processing Location</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Processing_Location</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

globalValueSets/Processing_Location.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Burr Ridge</fullName>
    </customValue>
    <customValue>
        <fullName>DEV TEST 1</fullName>
    </customValue>
    <customValue>
        <fullName>Tinley Park</fullName>
    </customValue>
    <customValue>
        <fullName>Peoria</fullName>
    </customValue>
    <customValue>
        <fullName>Springfield</fullName>
    </customValue>
    <customValue>
        <fullName>CW</fullName>
    </customValue>
    <customValue>
        <fullName>Rockford</fullName>
    </customValue>
    <customValue>
        <fullName>Collinsville</fullName>
    </customValue>
    <masterLabel>Processing Location</masterLabel>
</GlobalValueSet>

classes/clRouteScheduleControllerTest.cls
@IsTest
public with sharing class clRouteScheduleControllerTest {
    /**
        * NOTE start / stop test merely there to reset gov limits as creating non cl data takes forever given
        * all the processors / flows and eventually will bust cpu time outs on it's own.
        */
    @TestSetup
    static void setupData() {

        Test.startTest();
        Map<String,Object> mBaseData = clTESTUTILS.createAllNonClData();
        Test.stopTest();

        Map<String,Object> mClData =  clTESTUTILS.createEnd2EndRouteData(mBaseData);
    }

    @IsTest
    static void test_retrieveRouteProcessingSheetsForProcessor_positive() {

        Map<String,Object> mUser = clTESTUTILS.getClUsers();
        User processor = (User)mUser.get(clTESTUTILS.PROCESSOR);
        Date tomorrow = Date.today().addDays(1);
        Route__c route = [SELECT ID From Route__c LIMIT 1];
        Route_Schedule__c routeSchedule = [SELECT Id FROM Route_Schedule__c WHERE Route__c = :route.Id LIMIT 1];
        Route_Processing_Sheet__c rps = [SELECT Id FROM Route_Processing_Sheet__c WHERE Route_Schedule__c = :routeSchedule.Id LIMIT 1];

        Test.startTest();

        System.runAs(processor) {
            ResponseDto dto = clRouteScheduleController.retrieveRouteProcessingSheetsForProcessor(processor.id, tomorrow,'processor');
            sYSTEM.DEBUG('---> DTO:'+DTO);
        }

        Test.stopTest();
    }

    @IsTest
    static void test_retrieveRouteProcessingSheetsForProcessor_negative() {

        Map<String,Object> mUser = clTESTUTILS.getClUsers();
        User processor = (User)mUser.get(clTESTUTILS.PROCESSOR);
        Date today = Date.today();
        Route__c route = [SELECT ID From Route__c LIMIT 1];
        Route_Schedule__c routeSchedule = [SELECT Id,Processing_Location__c FROM Route_Schedule__c WHERE Route__c = :route.Id LIMIT 1];
        Test.startTest();

        System.runAs(processor) {
            ResponseDto dto = clRouteScheduleController.retrieveRouteProcessingSheetsForProcessor(processor.id, today,'processor');
            sYSTEM.DEBUG('---> DTO:'+DTO);
        }

        Test.stopTest();
    }

    @IsTest
    static void test_retrieveRouteProcessingSheetsForProcessorGrouping_positive() {

        Map<String,Object> mUser = clTESTUTILS.getClUsers();
        User processor = (User)mUser.get(clTESTUTILS.PROCESSOR);
        System.debug('running with processor '+processor);

        Test.startTest();

        System.runAs(processor) {
            List<Route_Schedule__c> routeSchedules = [
                    SELECT  Id, Route_Collection_Date__c,Processing_Location__c,Total_Accounts__c,Total_Processing_Sheets__c,
                            Processing_Status__c
                    FROM    Route_Schedule__c
                    ORDER By Route_Collection_Date__c ASC
            ];
            //List<Route_Processing_Sheet__c> rps = [SELECT Id,Processing_Process_Status__c FROM Route_Processing_Sheet__c WHERE Route_Schedule__c = :routeSchedule.Id];
            for(Route_Schedule__c rs : routeSchedules) {
                System.debug('running with rs=' + rs);
            }
            //System.debug('running with rps='+rps);
            Double cacheBust = Math.random();
            ResponseDto dto = clRouteScheduleController.retrieveRouteProcessingSheetsGroupedForProcessor(processor.id, cacheBust);
            sYSTEM.DEBUG('---> DTO:'+DTO);
        }

        Test.stopTest();
    }

    @IsTest
    static void test_retrieveRouteSchedulesForFillersGrouping_positive() {

        Map<String,Object> mUser = clTESTUTILS.getClUsers();
        User processor = (User)mUser.get(clTESTUTILS.PROCESSOR);
        System.debug('running with processor '+processor);

        Test.startTest();

        System.runAs(processor) {
            List<Route_Schedule__c> routeSchedules = [
                    SELECT  Id, Route_Fill_Date__c,Processing_Location__c,Total_Accounts__c,Total_Processing_Sheets__c,
                            Processing_Status__c
                    FROM    Route_Schedule__c
                    ORDER By Route_Collection_Date__c ASC
            ];
            for(Route_Schedule__c rs : routeSchedules) {
                System.debug('running with rs=' + rs);
            }
            Double cacheBust = Math.random();
            ResponseDto dto = clRouteScheduleController.retrieveRouteSchedulesGroupedForFiller(processor.id, 14,cacheBust);
            System.debug('---> DTO:'+DTO);
        }

        Test.stopTest();
    }

    @IsTest
    static void test_retrieveRouteSchedulesForFillersGrouping_negative() {

        Map<String,Object> mUser = clTESTUTILS.getClUsers();
        User processor = (User)mUser.get(clTESTUTILS.PROCESSOR);
        System.debug('running with processor '+processor);

        Test.startTest();

        System.runAs(processor) {
            Map<Id,Route_Schedule__c> mRouteSchedules = new Map<Id,Route_Schedule__c>([
                    SELECT  Id
                    FROM    Route_Schedule__c
                    ORDER By Route_Collection_Date__c ASC
            ]);
            List<Route_Processing_Sheet__c> rpss = [
                    SELECT Id,Processing_Status__c
                    FROM   Route_Processing_Sheet__c
                    WHERE  Route_Schedule__c IN :mRouteSchedules.keySet()
            ];
            for(Route_Processing_Sheet__c rps : rpss) {
                rps.Processing_Status__c = 'COMPLETED FILL';
            }
            update rpss;
            Double cacheBust = Math.random();
            ResponseDto dto = clRouteScheduleController.retrieveRouteSchedulesGroupedForFiller(processor.id, 14,cacheBust);
            System.debug('---> DTO:'+DTO);
        }

        Test.stopTest();
    }
}