objects/Route__c.object
<CustomObject>
    <description>Example object to house routes and routing of collections</description>
    <fields>
        <fullName>Cycle_Number__c</fullName>
        <description>The position of this route to be created in the 28 day cycle (4 weeks, 7 day per week)</description>
        <label>Fill Cycle Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Processing_Location__c</fullName>
        <label>Processing Location</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Processing_Location</valueSetName>
        </valueSet>
    </fields>
    <label>Route</label>
    <nameField>
        <label>Route Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Routes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Route_Account__c.object
<CustomObject>
    <description>POC Junction Route__c &lt;----&gt; Account</description>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Account.Accel_VGT_Live_Date__c</field>
                <operation>notEqual</operation>
                <value></value>
            </filterItems>
            <infoMessage>Account should have a VGT Live Date</infoMessage>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Route Accounts</relationshipLabel>
        <relationshipName>Route_Accounts</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Route__c</fullName>
        <label>Route</label>
        <referenceTo>Route__c</referenceTo>
        <relationshipLabel>Route Accounts</relationshipLabel>
        <relationshipName>Route_Accounts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Route Account</label>
    <nameField>
        <displayFormat>RA-{00000000}</displayFormat>
        <label>RA #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Route Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Route_Schedule__c.object
<CustomObject>
    <description>Assignment information of a physical route&apos;s locations, collectors, vehicles, and questions for a specific day</description>
    <fields>
        <fullName>Processing_Location__c</fullName>
        <label>Processing Location</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Processing_Location</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Route__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Route to collect</description>
        <label>Route</label>
        <referenceTo>Route__c</referenceTo>
        <relationshipLabel>Route Schedules</relationshipLabel>
        <relationshipName>Route_Schedules</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Route Schedule</label>
    <nameField>
        <label>Route Schedule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Route Schedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

globalValueSets/Processing_Location.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Burr Ridge</fullName>
    </customValue>
    <customValue>
        <fullName>DEV TEST 1</fullName>
    </customValue>
    <customValue>
        <fullName>Tinley Park</fullName>
    </customValue>
    <customValue>
        <fullName>Peoria</fullName>
    </customValue>
    <customValue>
        <fullName>Springfield</fullName>
    </customValue>
    <customValue>
        <fullName>CW</fullName>
    </customValue>
    <customValue>
        <fullName>Rockford</fullName>
    </customValue>
    <customValue>
        <fullName>Collinsville</fullName>
    </customValue>
    <masterLabel>Processing Location</masterLabel>
</GlobalValueSet>

classes/clBatchRouteScheduleCreationTest.cls
@IsTest
private class clBatchRouteScheduleCreationTest {


    /**
     * NOTE start / stop test merely there to reset gov limits as creating non cl data takes forever given
     * all the processors / flows and eventually will bust cpu time outs on it's own.
     */
    @TestSetup
    static void setupData() {
  
        Test.startTest();
        Map<String,Object> mBaseData = clTESTUTILS.createAllNonClData();
        Test.stopTest();

        Map<String,Object> mClData =  clTESTUTILS.createEnd2EndRouteData(mBaseData);
    }


    @IsTest
    static void test_exeBatch_cycleonly() {

        Test.startTest();

            Integer iNextCycle = 1;
            System.debug('---> running with cycle='+iNextCycle);
            clBatchRouteScheduleCreation b = new clBatchRouteScheduleCreation(iNextCycle);
            Database.executeBatch(b,50);

        Test.stopTest();
    }

    @IsTest
    static void test_exeBatch_cycle_and_region() {

        Test.startTest();

        String region = 'Tinley Park';

        DELETE [SELECT Id FROM Route__c];
        DELETE [SELECT Id FROM Route_Schedule__c];

        Route__c tinleyRoute = new Route__c();
        tinleyRoute.Processing_Location__c = region;
        tinleyRoute.Name = 'Blah Tinley 1';
        tinleyRoute.Cycle_Number__c = 1;
        insert tinleyRoute;

        Account account = [SELECT Id FROM Account lIMIT 1];
        Route_Account__c ra = new Route_Account__c();
        ra.Route__c = tinleyRoute.Id;
        ra.Account__c = account.Id;
        insert ra;

        Integer iNextCycle = 1;
        System.debug('---> running with cycle='+iNextCycle);
        clBatchRouteScheduleCreation b = new clBatchRouteScheduleCreation(iNextCycle,region);
        Database.executeBatch(b,50);

        Test.stopTest();

        List<Route_Schedule__c> routeSchedules = [
                SELECT Id,Processing_Location__c
                FROM   Route_Schedule__c
        ];
        System.assert(!routeSchedules.isEmpty());
        for(Route_Schedule__c rs : routeSchedules) {
            System.assert(rs.Processing_Location__c == region);
        }


    }

    @IsTest
    static void test_exeBatch_chain() {

        Test.startTest();
        Integer iNextCycle = 1;
        clBatchRouteScheduleCreation b = new clBatchRouteScheduleCreation(iNextCycle,true);
        Database.executeBatch(b,50);

        Test.stopTest();
    }

    @IsTest
    static void test_exeBatch_chain_with_batchsize() {

        Test.startTest();
        Integer iNextCycle = 1;
        clBatchRouteScheduleCreation b = new clBatchRouteScheduleCreation(iNextCycle,true,50);
        Database.executeBatch(b,50);

        Test.stopTest();
    }

    @IsTest
    static void test_exeBatch_chain_with_batchsize_and_collectiondate_and_filldate() {

        Test.startTest();
        Integer iNextCycle = 1;
        Date  routeCollectionDate = Date.today().addDays(1);
        Date  routeFillDate = Date.today();
        clBatchRouteScheduleCreation b = new clBatchRouteScheduleCreation(iNextCycle,true,50,routeCollectionDate,routeFillDate);
        Database.executeBatch(b,50);

        Test.stopTest();
    }


    @IsTest
    static void test_fire_failed_PE() {

        Test.startTest();
        clBatchRouteScheduleCreation b = new clBatchRouteScheduleCreation(1);
        b.fireFailurePlatformEvent();
        Test.stopTest();
    }
}