objects/Route__c.object
<CustomObject>
    <description>Example object to house routes and routing of collections</description>
    <fields>
        <fullName>Collection_Cycle_Number__c</fullName>
        <description>The position of this route to be collected in the 28 day cycle (4 weeks, 7 day per week)</description>
        <label>Collection Cycle Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Cycle_Number__c</fullName>
        <description>The position of this route to be created in the 28 day cycle (4 weeks, 7 day per week)</description>
        <label>Fill Cycle Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Next_Collection_Date__c</fullName>
        <formula>IF(Mod(TODAY() +1  - Origination_Date__c,28) &lt; Collection_Cycle_Number__c, TODAY() + Collection_Cycle_Number__c - Mod(TODAY()+1 - Origination_Date__c,28),
If(Mod(TODAY() +1  - Origination_Date__c,28) &gt; Collection_Cycle_Number__c, TODAY() + 28 - Mod(TODAY()+1 - Origination_Date__c,28) + Collection_Cycle_Number__c, TODAY()))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Next Collection Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Next_Fill_Date__c</fullName>
        <formula>IF(Mod(TODAY() - Origination_Date__c,28) +1 = Cycle_Number__c, TODAY(), IF(Mod(TODAY() - Origination_Date__c,28) +1 &lt; Cycle_Number__c, TODAY() + Cycle_Number__c - (Mod(TODAY() - Origination_Date__c,28) +1), TODAY() + 27 - Mod(TODAY() - Origination_Date__c,28) + Cycle_Number__c ))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Next Fill Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Processing_Location__c</fullName>
        <label>Processing Location</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Processing_Location</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Total_Accounts__c</fullName>
        <description>R/S</description>
        <label>Total Accounts</label>
        <summaryForeignKey>Route_Account__c.Route__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>Route</label>
    <nameField>
        <label>Route Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Routes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Route_Schedule__c.object
<CustomObject>
    <description>Assignment information of a physical route&apos;s locations, collectors, vehicles, and questions for a specific day</description>
    <fields>
        <fullName>Processing_Location__c</fullName>
        <label>Processing Location</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Processing_Location</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Route_Collection_Date__c</fullName>
        <description>Day Collection will take place</description>
        <label>Route Collection Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Route_Fill_Date__c</fullName>
        <description>Not sure how this is used yet?</description>
        <inlineHelpText>Note sure how this is used yet?</inlineHelpText>
        <label>Route Fill Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Route__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Route to collect</description>
        <label>Route</label>
        <referenceTo>Route__c</referenceTo>
        <relationshipLabel>Route Schedules</relationshipLabel>
        <relationshipName>Route_Schedules</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Total_Accounts__c</fullName>
        <description>Total Accounts Associated with this Route_Schedule_c record. (Rollup Summary or Route_Schedule_Account__c_)</description>
        <inlineHelpText>Total Accounts Associated with this Route_Schedule_c record. (RS)</inlineHelpText>
        <label>Total Accounts</label>
        <summaryForeignKey>Route_Schedule_Account__c.Route_Schedule__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Total_Meter_Readings__c</fullName>
        <description>The total # of meter readings for all route processing sheets associated with this route schedule.</description>
        <inlineHelpText>The total # of meter readings for all route processing sheets associated with this route schedule.</inlineHelpText>
        <label>Total Meter Readings</label>
        <summarizedField>Route_Processing_Sheet__c.Total_Meter_Readings__c</summarizedField>
        <summaryForeignKey>Route_Processing_Sheet__c.Route_Schedule__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Total_Processing_Sheets__c</fullName>
        <description>Total Processing Sheets generated by this schedule record. Rollup Summary of Route_Processing_Sheet__c</description>
        <inlineHelpText>Total Processing Sheets generated by this schedule record. (RS)</inlineHelpText>
        <label>Total Processing Sheets</label>
        <summaryForeignKey>Route_Processing_Sheet__c.Route_Schedule__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>Route Schedule</label>
    <nameField>
        <label>Route Schedule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Route Schedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

globalValueSets/Processing_Location.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Burr Ridge</fullName>
    </customValue>
    <customValue>
        <fullName>DEV TEST 1</fullName>
    </customValue>
    <customValue>
        <fullName>Tinley Park</fullName>
    </customValue>
    <customValue>
        <fullName>Peoria</fullName>
    </customValue>
    <customValue>
        <fullName>Springfield</fullName>
    </customValue>
    <customValue>
        <fullName>CW</fullName>
    </customValue>
    <customValue>
        <fullName>Rockford</fullName>
    </customValue>
    <customValue>
        <fullName>Collinsville</fullName>
    </customValue>
    <masterLabel>Processing Location</masterLabel>
</GlobalValueSet>

classes/clAdminUtilsController.cls
public without sharing class clAdminUtilsController {

    @AuraEnabled(cacheable=true)
    public static List<Route__c> retrieveRoutes( String searchKey, String sortBy, String sortDirection, Integer iLimit, Integer cycleNumber ) {

        String q = '';
        q += ' SELECT Id, Name, Cycle_Number__c, LastModifiedDate, Total_Accounts__c, Processing_Location__c, Collection_Cycle_Number__c ';
        q += ',Next_Fill_Date__c, Next_Collection_Date__c ';
        q += ' FROM Route__c ';

        Boolean searchKeySent = false;
        if ( searchKey != null && searchKey != '' ) {
            String key = '%' + searchKey + '%';
            searchKeySent = true;
            q += ' WHERE Name LIKE :key ';
        }
        if (cycleNumber != null && cycleNumber != 0) {
            if(searchKeySent) {
                q += ' AND Cycle_Number__c = :cycleNumber ';
            } else {
                q += ' WHERE Cycle_Number__c = :cycleNumber ';
            }
        }

        if ( sortBy != null && sortDirection != null ) {
            q += ' ORDER BY ' + sortBy + ' ' + sortDirection;
        }
        q += ' LIMIT :iLimit ';
        return Database.query(q);
    }

    @AuraEnabled(cacheable=true)
    public static List<RouteScheduleWrapper> retrieveRouteSchedules( String searchKey, Date collectionDate, Integer iLimit) {

        List<RouteScheduleWrapper> rsWraps = new List<RouteScheduleWrapper>();
        String q = '';
        q += ' SELECT Id, Name, Route_Collection_Date__c, Total_Accounts__c, Route_Fill_Date__c, ';
        q += '        Total_Processing_Sheets__c, Total_Meter_Readings__c, LastModifiedDate ';
        q += ' FROM   Route_Schedule__c ';

        if ( searchKey != null && searchKey != '' ) {
            String key = '%' + searchKey + '%';
            q += ' WHERE Name LIKE :key ';
            if ( collectionDate != null) {
                q += ' and Route_Collection_Date__c = :collectionDate ';
            }
        } else if(collectionDate != null) {
               q += 'WHERE Route_Collection_Date__C = :collectionDate ';
        }
        q += ' ORDER By LastModifiedDate DESC';
        q += ' LIMIT :iLimit ';
        List<Route_Schedule__c> routeSchedules = Database.query(q);
        if(!routeSchedules.isEmpty()) {
            for(Route_Schedule__c rs : routeSchedules) {
                rsWraps.add(new RouteScheduleWrapper(rs));
            }
        }
        return rsWraps;
    }

    public class RouteScheduleWrapper {

        @AuraEnabled  public Id rsId;
        @AuraEnabled  public String rsName;
        @AuraEnabled  public Date  rsCollectionDate;
        @AuraEnabled  public Date  rsFillDate;
        @AuraEnabled  public Integer totalAccounts;
        @AuraEnabled  public Integer totalRps;
        @AuraEnabled  public Integer totalMeterReadings;
        @AuraEnabled  public Datetime rsLastModifiedDate;

        public RouteScheduleWrapper(Route_Schedule__c rs) {
            this.rsId = rs.Id;
            this.rsName = rs.Name;
            this.rsCollectionDate = rs.Route_Collection_Date__c;
            this.rsFillDate = rs.Route_Fill_Date__c;
            this.totalAccounts = rs.Total_Accounts__c != null ? Integer.valueOf(rs.Total_Accounts__c) : null;
            this.totalRps = rs.Total_Processing_Sheets__c != null ?  Integer.valueOf(rs.Total_Processing_Sheets__c) : null;
            this.totalMeterReadings = rs.Total_Meter_Readings__c != null ?  Integer.valueOf(rs.Total_Meter_Readings__c) : null;
            this.rsLastModifiedDate = rs.LastModifiedDate;
        }

    }
}