objects/Route_Schedule__c.object
<CustomObject>
    <description>Assignment information of a physical route&apos;s locations, collectors, vehicles, and questions for a specific day</description>
    <fields>
        <fullName>Route_Collection_Date__c</fullName>
        <description>Day Collection will take place</description>
        <label>Route Collection Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Total_Processing_Sheets__c</fullName>
        <description>Total Processing Sheets generated by this schedule record. Rollup Summary of Route_Processing_Sheet__c</description>
        <inlineHelpText>Total Processing Sheets generated by this schedule record. (RS)</inlineHelpText>
        <label>Total Processing Sheets</label>
        <summaryForeignKey>Route_Processing_Sheet__c.Route_Schedule__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>Route Schedule</label>
    <nameField>
        <label>Route Schedule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Route Schedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/clRouteScheduleInfo.cls
public class clRouteScheduleInfo {

    public Id     rsId;
    public String rsName;
    public Date rsCollectionDate;
    public Integer totalLocations = 0;

    public clRouteScheduleInfo(Route_Schedule__c rs) {
        this.rsId = rs.Id;
        this.rsName = rs.Name;
        this.rsCollectionDate = rs.Route_Collection_Date__c;
        this.totalLocations = rs.Total_Processing_Sheets__c != null ? Integer.valueOf(rs.Total_Processing_Sheets__c) : 0;
    }
}