objects/Route_Schedule__c.object
<CustomObject>
    <description>Assignment information of a physical route&apos;s locations, collectors, vehicles, and questions for a specific day</description>
    <fields>
        <fullName>Processing_Location__c</fullName>
        <label>Processing Location</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Processing_Location</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Route_Collection_Date__c</fullName>
        <description>Day Collection will take place</description>
        <label>Route Collection Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Route_Fill_Date__c</fullName>
        <description>Not sure how this is used yet?</description>
        <inlineHelpText>Note sure how this is used yet?</inlineHelpText>
        <label>Route Fill Date</label>
        <type>Date</type>
    </fields>
    <label>Route Schedule</label>
    <nameField>
        <label>Route Schedule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Route Schedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Route_Schedule_Account__c.object
<CustomObject>
    <description>POC Junction Route_Schedule__c &lt;----&gt; Account</description>
    <fields>
        <fullName>Route_Schedule__c</fullName>
        <label>Route Schedule</label>
        <referenceTo>Route_Schedule__c</referenceTo>
        <relationshipLabel>Route Schedule Accounts</relationshipLabel>
        <relationshipName>Route_Schedule_Accounts</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Stop_Number__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Stop Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Route Schedule Account</label>
    <nameField>
        <displayFormat>RSA-{00000000}</displayFormat>
        <label>RSA #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Route Schedule Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

globalValueSets/Processing_Location.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Burr Ridge</fullName>
    </customValue>
    <customValue>
        <fullName>DEV TEST 1</fullName>
    </customValue>
    <customValue>
        <fullName>Tinley Park</fullName>
    </customValue>
    <customValue>
        <fullName>Peoria</fullName>
    </customValue>
    <customValue>
        <fullName>Springfield</fullName>
    </customValue>
    <customValue>
        <fullName>CW</fullName>
    </customValue>
    <customValue>
        <fullName>Rockford</fullName>
    </customValue>
    <customValue>
        <fullName>Collinsville</fullName>
    </customValue>
    <masterLabel>Processing Location</masterLabel>
</GlobalValueSet>

classes/clRouteScheduleAccountSvc.cls
public without sharing class clRouteScheduleAccountSvc {
    
    public static List<Route_Schedule_Account__c> retrieveRouteScheduleAccountsByIds(Set<Id> rsaIds) {
        System.debug('--- rsa ids='+rsaIds);
        String q = '';
        q += ' SELECT   {0},  ';
        q += '          Route_Schedule__r.Route_Fill_Date__c, Route_Schedule__r.Route_Collection_Date__c, ';
        //              Added 2/16/2022 for additional fill stuff.
        q += '          Route_Schedule__r.Processing_Location__c ';
        q += ' FROM     Route_Schedule_Account__c ';
        q += ' WHERE    Id IN :rsaIds ';
        q += ' ORDER BY Stop_Number__c ASC ';
        String formattedQuery = String.format(q,getAllRouteScheduleAccountFields());

        List<Route_Schedule_Account__c> routeScheduleAccounts = Database.query(formattedQuery);
        return routeScheduleAccounts;
    }

    @TestVisible
    private static List<String>  getAllRouteScheduleAccountFields() {
        Map<String, Schema.SObjectField> fieldsMap = Route_Schedule_Account__c.sObjectType.getDescribe().fields.getMap();
        String sFields = String.join(new List<String>(fieldsMap.keySet()), ',');
        List<String> fields = new List<String>{sfields};
        return fields;
    }
}