objects/Route_Processing_Sheet__c.object
<CustomObject>
    <description>Example digitization of the route processing sheet</description>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account DBA</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Route Processing Sheets</relationshipLabel>
        <relationshipName>Route_Processing_Sheets</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Collection_Date__c</fullName>
        <label>Collection Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Collection_Type__c</fullName>
        <description>Copied down from the parent Route Schedule Account.</description>
        <inlineHelpText>Copied down from the parent Route Schedule Account.</inlineHelpText>
        <label>Collection Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Collection_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>RT_Variance__c</fullName>
        <description>Formula: Drop Totals - Receipt Totals, both NRT specific fields and M3T specific fields are included in the formula so they should never both be filled out for a location or this formula would subtract twice</description>
        <formula>((Cassette_1_Note_Count_Drop__c)*1 + (Cassette_5_Note_Count_Drop__c)*5 + (Cassette_20_Note_Count_Drop__c)*20 + (Cassette_50_Note_Count_Drop__c)*50 +(Cassette_100_Note_Count_Drop__c)*100) + Reject_Drop_Total__c + Cash_Return_Unused_Drop__c - (( BLANKVALUE(VALUE(TEXT(Cassette_1_Denomination__c)),0) *  (Cassette_1_Note_Count__c + Cassette_1_Reject_Note_Count__c)) + ( BLANKVALUE(VALUE(TEXT(Cassette_2_Denomination__c)),0) *  (Cassette_2_Note_Count__c + Cassette_2_Reject_Note_Count__c) ) + ( BLANKVALUE(VALUE(TEXT(Cassette_3_Denomination__c)),0) *  (Cassette_3_Note_Count__c + Cassette_3_Reject_Note_Count__c)) + ( BLANKVALUE(VALUE(TEXT(Cassette_4_Denomination__c)),0)*(Cassette_4_Note_Count__c + Cassette_4_Reject_Note_Count__c) )) -  ((Cassette_1_Value__c + Cassette_2_Value__c + Cassette_3_Value__c + Cassette_4_Value__c + Cassette_5_Value__c + Reject_Total__c + Cash_Return_Unused__c))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>RT Variance</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Variance__c</fullName>
        <formula>VGT_Actual_Drop__c  - (Expected_Drop__c + BV_Value__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>VGT Variance</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Route Processing Sheet</label>
    <nameField>
        <displayFormat>Collection-Id-{000000000}</displayFormat>
        <label>Collection ID Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Route Processing Sheets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

globalValueSets/Collection_Type.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Regular - RT &amp; VGT</fullName>
        <default>true</default>
        <label>Regular - RT &amp; VGT</label>
    </customValue>
    <customValue>
        <fullName>Additional Fill – RT &amp; VGT</fullName>
    </customValue>
    <customValue>
        <fullName>Additional Fill – RT Only</fullName>
    </customValue>
    <customValue>
        <fullName>Additional Fill – VGT Only</fullName>
    </customValue>
    <customValue>
        <fullName>Regular - 2nd RT</fullName>
    </customValue>
    <customValue>
        <fullName>Regular - RT Only</fullName>
    </customValue>
    <customValue>
        <fullName>Regular - VGT Only</fullName>
    </customValue>
    <customValue>
        <fullName>Regular - RT Only (Go Lives/RT swaps)</fullName>
        <isActive>false</isActive>
        <label>Regular - RT Only (Go Lives/RT swaps)</label>
    </customValue>
    <description>* Regular – RT &amp; VGT (typical collection involves changing VGT cans and swapping RT Cassettes)﻿
* Additional Fill – RT Only (this collection involves just changing RT Cassettes)﻿
* Additional Fill – VGT Only (this collection involves just swapping VGT cans)﻿
* Additional Fill – RT &amp; VGT (this collection involves changing VGT cans and swapping RT cassettes)
* Regular - 2nd RT (OLD.. not sure?)
* Regular - RT Only (NEW... not sure?)
* Regular - VGT Only (NEW.. not sure?)</description>
    <masterLabel>Collection Type</masterLabel>
</GlobalValueSet>

classes/clLinkedRpsController.cls
/**
 * UI Backing controller for the clLinkedRps lwc component.
 * Retrieves all / filtered (searchparams) linked RPS records and total counts of records for display on the client.
 */
public class clLinkedRpsController {

    @TestVisible
    private static final Integer    DEFAULT_ROWS_LIMIT      = 200;
    public static final String      MAP_KEY_RPS_WRAPPERS    = 'RPS_WRAPPERS';
    public static final String      MAP_KEY_RPS_TOTAL_CNT   = 'RPS_TOTAL_CNT';
    public static final String      MAP_KEY_PARENT_ACCT_ID  = 'PARENT_ACCT_ID';

    /**
     * Retrieve all RPS records for the parent account other then the current RPS being viewed.
     *
     * @param currentRpsId  The Route_Processing_Sheet__c.Id.
     * @param searchParams  The search param object (filters).
     *
     * @return              A ResponseDto containing a List of RpsWrapper objects.
     * @see RpsSearchParams
     */
    @AuraEnabled(Cacheable=true)
    public static ResponseDto retrieveLinkedRps(Id currentRpsId,RpsSearchParams searchParams) {
        ResponseDto dto = new ResponseDto();

        Route_Processing_Sheet__c currentRps = retrieveRps(currentRpsId);
        Id parentAccountId = currentRps.Account__c;

        List<Route_Processing_Sheet__c> rpss = retrieveRpss(parentAccountId,currentRpsId,searchParams);
        dto.isSuccess = !rpss.isEmpty();
        dto.values.put(MAP_KEY_RPS_WRAPPERS,buildRpsWrappers(rpss));
        dto.values.put(MAP_KEY_PARENT_ACCT_ID,parentAccountId);
        return dto;
    }

    /**
     * Retrieve the count of all RPS records for the parent account other then the current RPS being viewed.
     *
     * @param currentRpsId  The Route_Processing_Sheet__c.Id.
     * @param searchParams  The search param object (filters).
     *
     * @return              A ResponseDto containing an Integer value of the count.
     * @see RpsSearchParams
     */
    @AuraEnabled(Cacheable=true)
    public static ResponseDto retrieveLinkedRpsTotalRecords(Id currentRpsId,RpsSearchParams searchParams) {
        ResponseDto dto = new ResponseDto();
        Integer iTotal = 0;

        Route_Processing_Sheet__c currentRps = retrieveRps(currentRpsId);
        Id parentAccountId = currentRps.Account__c;

        iTotal = retrieveRpssTotalRecords(parentAccountId,currentRpsId,searchParams);
        dto.isSuccess = true;
        dto.values.put(MAP_KEY_RPS_TOTAL_CNT,iTotal);
        return dto;
    }

    /**
     * Wrap the Route_Processing_Sheet__c up in a wrapper class.
     *
     * @param rpss  A List of Route_Processing_Sheet__c sObjects.
     * @return      A List of RpsWrapper objects.
     */
    public static List<RpsWrapper> buildRpsWrappers(List<Route_Processing_Sheet__c> rpss) {
        List<RpsWrapper> rpsWrappers = new List<RpsWrapper>();

        for(Route_Processing_Sheet__c rps : rpss) {
            rpsWrappers.add( new RpsWrapper(rps) );
        }
        return rpsWrappers;
    }

    /**
     * Calls the svc to retrieve the List of Route_Processing_Sheet__c sObjects.
     *
     * @param parentAccountId   The Route_Processing_Sheet.Account__c value.
     * @param currentRpsId      The Route_Processing_Sheet__c.Id value being viewed.
     * @param searchParams      The RpsSearchParams (query filters).
     *
     * @return                  A List of Route_Processing_Sheet__c sObjects.
     */
    public static List<Route_Processing_Sheet__c> retrieveRpss(Id parentAccountId, Id currentRpsId,RpsSearchParams searchParams) {

        clLinkedRpsSvc.DEBUG_QUERY = false;

        List<Route_Processing_Sheet__c> rpss = clLinkedRpsSvc.retrieveRpsAdvancedSearch(
                searchParams.iLimit,
                currentRpsId,
                parentAccountId,
                searchParams.hasVgtVariance,
                searchParams.hasRtVariance,
                searchParams.daysBackCollectionDate
        );
        return rpss;
    }

    /**
     * Calls the svc to retrieve the Count List of Route_Processing_Sheet__c sObjects for the parent account (minus 1).
     *
     * @param parentAccountId   The Route_Processing_Sheet.Account__c value.
     * @param currentRpsId      The Route_Processing_Sheet__c.Id value being viewed.
     * @param searchParams      The RpsSearchParams (query filters).
     *
     * @return                  A integer that sums the count of all rps for the account besides the current one being viewed.
     */
    public static Integer retrieveRpssTotalRecords(Id parentAccountId, Id currentRpsId,RpsSearchParams searchParams) {

        clLinkedRpsSvc.DEBUG_QUERY = false;

        Integer iTotal = clLinkedRpsSvc.retrieveRpsAdvancedSearchTotalRecords(  currentRpsId, parentAccountId,
                                                                                searchParams.hasVgtVariance,
                                                                                searchParams.hasRtVariance,
                                                                                searchParams.daysBackCollectionDate);
        return iTotal;
    }

    /**
     * Retrieves minimal fields for a single Route_Processing_Sheet__c.
     *
     * @param rpsId     The Route_Processing_Sheet__c.Id.
     * @return          The Route_Processing_Sheet__c sObject with minimal fields.
     */
    public static Route_Processing_Sheet__c retrieveRps(Id rpsId) {

        Route_Processing_Sheet__c rps =  [
                SELECT Id,Account__c
                FROM   Route_Processing_Sheet__c
                WHERE  Id = :rpsId
        ];
        return rps;
    }

    /**
     * A wrapper on Route_Processing_Sheet__c for future flexibility.
     */
    public class RpsWrapper {

        @AuraEnabled public Id rpsId;
        @AuraEnabled public String rpsName;
        @AuraEnabled public Date rpsCollectionDate;
        @AuraEnabled public String rpsCollectionType;
        @AuraEnabled public Double rpsVgtVariance;
        @AuraEnabled public Double rpsRtVariance;

        @AuraEnabled public Boolean hasVgtVariance {
            get {
                return rpsVgtVariance != null && rpsVgtVariance != 0;
            }
        }
        @AuraEnabled public Boolean hasRtVariance {
            get {
                return rpsRtVariance != null && rpsRtVariance != 0;
            }
        }

        public RpsWrapper(Route_Processing_Sheet__c rps) {
            this.rpsId = rps.Id;
            this.rpsName = rps.Name;
            this.rpsCollectionType = rps.Collection_Type__c;
            this.rpsCollectionDate = rps.Collection_Date__c;
            this.rpsVgtVariance = rps.Variance__c;
            this.rpsRtVariance = rps.RT_Variance__c;
        }
    }

    /**
     * Search filters for the query.
     */
    public class RpsSearchParams {
        @AuraEnabled public Boolean hasRtVariance  {get;set;}           //  Has a RPS.Variance__c value != 0
        @AuraEnabled public Boolean hasVgtVariance {get;set;}           //  Has a RPS.RT_Variance__c value != 0
        @AuraEnabled public Integer daysBackCollectionDate {get;set;}
        @AuraEnabled public Integer iLimit {get;set;}                   //  The limit of number of SOQL rows to return.

        public RpsSearchParams() {
            this.iLimit = DEFAULT_ROWS_LIMIT;
        }
    }
}