objects/Route__c.object
<CustomObject>
    <description>Example object to house routes and routing of collections</description>
    <label>Route</label>
    <nameField>
        <label>Route Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Routes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Route_Processing_Sheet__c.object
<CustomObject>
    <description>Example digitization of the route processing sheet</description>
    <fields>
        <fullName>Processing_Status__c</fullName>
        <description>More processor based since reqs differed between the status for a collector and the status for a processor.</description>
        <inlineHelpText>More processor based since reqs differed between the status for a collector and the status for a processor.</inlineHelpText>
        <label>Fill Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>COMPLETED FILL</fullName>
                </value>
                <value>
                    <fullName>Not Yet Filled</fullName>
                    <default>true</default>
                    <label>Not Yet Filled</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Route_Fill_Date__c</fullName>
        <description>not sure?</description>
        <inlineHelpText>not sure?</inlineHelpText>
        <label>Route Fill Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Route_Schedule__c</fullName>
        <label>Route Schedule</label>
        <referenceTo>Route_Schedule__c</referenceTo>
        <relationshipLabel>Route Processing Sheets</relationshipLabel>
        <relationshipName>Route_Processing_Sheets</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Route Processing Sheet</label>
    <nameField>
        <displayFormat>Collection-Id-{000000000}</displayFormat>
        <label>Collection ID Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Route Processing Sheets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Route_Schedule__c.object
<CustomObject>
    <description>Assignment information of a physical route&apos;s locations, collectors, vehicles, and questions for a specific day</description>
    <fields>
        <fullName>Processing_Status__c</fullName>
        <label>Processing Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Processing Incomplete</fullName>
                    <color>#FF6666</color>
                    <default>true</default>
                    <label>Processing Incomplete</label>
                </value>
                <value>
                    <fullName>COMPLETED PROCESSING</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Route_Fill_Date__c</fullName>
        <description>Not sure how this is used yet?</description>
        <inlineHelpText>Note sure how this is used yet?</inlineHelpText>
        <label>Route Fill Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Route__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Route to collect</description>
        <label>Route</label>
        <referenceTo>Route__c</referenceTo>
        <relationshipLabel>Route Schedules</relationshipLabel>
        <relationshipName>Route_Schedules</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Route Schedule</label>
    <nameField>
        <label>Route Schedule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Route Schedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/clRouteProcessingFillOutboundTest.cls
@IsTest
private class clRouteProcessingFillOutboundTest {
    /**
     * NOTE start / stop test merely there to reset gov limits as creating non cl data takes forever given
     * all the processors / flows and eventually will bust cpu time outs on it's own.
     */
    @TestSetup
    static void setupData() {

        Test.startTest();
        Map<String,Object> mBaseData = clTESTUTILS.createAllNonClData();
        Test.stopTest();

        Map<String,Object> mClData =  clTESTUTILS.createEnd2EndRouteData(mBaseData);
    }

    @IsTest
    static void test_retrieveRpsWrapper() {

        Map<String,Object> mUser = clTESTUTILS.getClUsers();
        User collector = (User)mUser.get(clTESTUTILS.COLLECTOR);
        Route__c route = [SELECT ID From Route__c LIMIT 1];
        Route_Schedule__c routeSchedule = [SELECT Id FROM Route_Schedule__c WHERE Route__c = :route.Id LIMIT 1];
        Route_Processing_Sheet__c rps = [SELECT  Id,Route_Fill_Date__c FROM Route_Processing_Sheet__c WHERE Route_Schedule__c = :routeSchedule.Id LIMIT 1];
        rps.Route_Fill_Date__c = date.today();
        update rps;

        Test.startTest();

        System.runAs(collector) {
            ResponseDto dto = clRouteProcessingFillOutbound.retrieveRpsWrapper(rps.Id);
            System.assertEquals(dto.isSuccess,true);

            dto = clRouteProcessingFillOutbound.retrieveRpsWrapperNoCache(rps.Id,Math.random());
            System.assertEquals(dto.isSuccess,true);
        }

        Test.stopTest();
    }

    @IsTest
    static void test_updateRpsStatus() {

        Map<String,Object> mUser = clTESTUTILS.getClUsers();
        User collector = (User)mUser.get(clTESTUTILS.COLLECTOR);
        Route__c route = [SELECT ID From Route__c LIMIT 1];
        Route_Schedule__c routeSchedule = [SELECT Id FROM Route_Schedule__c WHERE Route__c = :route.Id LIMIT 1];
        Route_Processing_Sheet__c rps = [SELECT Route_Fill_Date__c,Processing_Status__c,Id FROM Route_Processing_Sheet__c WHERE Route_Schedule__c = :routeSchedule.Id LIMIT 1];
        rps.Route_Fill_Date__c = date.today();
        update rps;

        Test.startTest();

        System.runAs(collector) {
            rps.Processing_Status__c = 'COMPLETED FILL';
            ResponseDto dto = clRouteProcessingFillOutbound.updateRpsStatus(rps);
            System.assertEquals(dto.isSuccess,true);

            rps.Processing_Status__c = 'BOGUS STATUS';
            dto = clRouteProcessingFillOutbound.updateRpsStatus(rps);
            System.assertEquals(dto.isSuccess,false);
        }

        Test.stopTest();
    }

}