objects/Route_Processing_Sheet__c.object
<CustomObject>
    <description>Example digitization of the route processing sheet</description>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account DBA</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Route Processing Sheets</relationshipLabel>
        <relationshipName>Route_Processing_Sheets</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Collection_Type__c</fullName>
        <description>Copied down from the parent Route Schedule Account.</description>
        <inlineHelpText>Copied down from the parent Route Schedule Account.</inlineHelpText>
        <label>Collection Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Collection_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Redemption_Type_From_Asset__c</fullName>
        <description>FF to RSA.Redemption_Type_From_Asset__c. The redemption type pulled via analyzing the assets associated with the account (as opposed to the FF that goes from Account and looks at GP Mfgr )</description>
        <formula>Route_Schedule_Account__r.Redemption_Type_From_Asset__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>FF to RSA.Redemption_Type_From_Asset__c. The redemption type pulled via analyzing the assets associated with the account (as opposed to the FF that goes from Account and looks at GP Mfgr )</inlineHelpText>
        <label>Redemption Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Route_Schedule_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Exists in case we want to roll up info to RSA</description>
        <inlineHelpText>Exists in case we want to roll up info to RSA</inlineHelpText>
        <label>Route Schedule Account</label>
        <referenceTo>Route_Schedule_Account__c</referenceTo>
        <relationshipLabel>Route Processing Sheets</relationshipLabel>
        <relationshipName>Route_Processing_Sheets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Route_Schedule__c</fullName>
        <label>Route Schedule</label>
        <referenceTo>Route_Schedule__c</referenceTo>
        <relationshipLabel>Route Processing Sheets</relationshipLabel>
        <relationshipName>Route_Processing_Sheets</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Route Processing Sheet</label>
    <nameField>
        <displayFormat>Collection-Id-{000000000}</displayFormat>
        <label>Collection ID Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Route Processing Sheets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Route_Schedule__c.object
<CustomObject>
    <description>Assignment information of a physical route&apos;s locations, collectors, vehicles, and questions for a specific day</description>
    <label>Route Schedule</label>
    <nameField>
        <label>Route Schedule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Route Schedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Route_Schedule_Account__c.object
<CustomObject>
    <description>POC Junction Route_Schedule__c &lt;----&gt; Account</description>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Account.Accel_VGT_Live_Date__c</field>
                <operation>notEqual</operation>
                <value></value>
            </filterItems>
            <infoMessage>Account Must Have A VGT Live Date</infoMessage>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Route Schedule Accounts</relationshipLabel>
        <relationshipName>Route_Schedule_Accounts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Collection_Type__c</fullName>
        <description>Used for additional fills.</description>
        <inlineHelpText>Used for additional fills.</inlineHelpText>
        <label>Collection Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Collection_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Redemption_Type_From_Asset__c</fullName>
        <description>The redemption type pulled via analyzing the assets associated with the account (as opposed to the FF that goes from Account and looks at GP Mfgr )</description>
        <inlineHelpText>The redemption type pulled via analyzing the assets associated with the account (as opposed to the FF that goes from Account and looks at GP Mfgr )</inlineHelpText>
        <label>Redemption Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Route_Schedule__c</fullName>
        <label>Route Schedule</label>
        <referenceTo>Route_Schedule__c</referenceTo>
        <relationshipLabel>Route Schedule Accounts</relationshipLabel>
        <relationshipName>Route_Schedule_Accounts</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Route Schedule Account</label>
    <nameField>
        <displayFormat>RSA-{00000000}</displayFormat>
        <label>RSA #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Route Schedule Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

globalValueSets/Collection_Type.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Regular - RT &amp; VGT</fullName>
        <default>true</default>
        <label>Regular - RT &amp; VGT</label>
    </customValue>
    <customValue>
        <fullName>Additional Fill – RT &amp; VGT</fullName>
    </customValue>
    <customValue>
        <fullName>Additional Fill – RT Only</fullName>
    </customValue>
    <customValue>
        <fullName>Additional Fill – VGT Only</fullName>
    </customValue>
    <customValue>
        <fullName>Regular - 2nd RT</fullName>
    </customValue>
    <customValue>
        <fullName>Regular - RT Only</fullName>
    </customValue>
    <customValue>
        <fullName>Regular - VGT Only</fullName>
    </customValue>
    <customValue>
        <fullName>Regular - RT Only (Go Lives/RT swaps)</fullName>
        <isActive>false</isActive>
        <label>Regular - RT Only (Go Lives/RT swaps)</label>
    </customValue>
    <description>* Regular – RT &amp; VGT (typical collection involves changing VGT cans and swapping RT Cassettes)﻿
* Additional Fill – RT Only (this collection involves just changing RT Cassettes)﻿
* Additional Fill – VGT Only (this collection involves just swapping VGT cans)﻿
* Additional Fill – RT &amp; VGT (this collection involves changing VGT cans and swapping RT cassettes)
* Regular - 2nd RT (OLD.. not sure?)
* Regular - RT Only (NEW... not sure?)
* Regular - VGT Only (NEW.. not sure?)</description>
    <masterLabel>Collection Type</masterLabel>
</GlobalValueSet>

classes/clBatchRouteProcessingSheetCreationTest.cls
@IsTest
private class clBatchRouteProcessingSheetCreationTest {

    /**
     * NOTE start / stop test merely there to reset gov limits as creating non cl data takes forever given
     * all the processors / flows and eventually will bust cpu time outs on it's own.
     */
    @TestSetup
    static void setupData() {

        Test.startTest();
        Map<String,Object> mBaseData = clTESTUTILS.createAllNonClData();
        Test.stopTest();

        Map<String,Object> mClData =  clTESTUTILS.createEnd2EndRouteData(mBaseData);
    }


    @IsTest
    static void test_exeBatch_fill_date() {

        Test.startTest();
        Date fillDate = Date.today().addDays(1);
        clBatchRouteProcessingSheetCreation  b = new clBatchRouteProcessingSheetCreation(fillDate);
        Database.executeBatch(b,2000);

        Test.stopTest();
    }

    @IsTest
    static void test_exeBatch_route_schedule_id() {

        Route_Schedule__c routeSchedule = [SELECT Id FROM Route_Schedule__c LIMIT 1];

        Test.startTest();

        Date collectionDate = Date.today().addDays(1);
        clBatchRouteProcessingSheetCreation  b = new clBatchRouteProcessingSheetCreation(routeSchedule.Id,clTESTUTILS.DEFAULT_PROCESSING_LOC);
        Database.executeBatch(b,2000);

        Test.stopTest();
    }
    //public clBatchRouteProcessingSheetCreation(Date pRouteFillDate, String region) {
    @IsTest
    static void test_exeBatch_fill_date_region() {
        Test.startTest();
        Date fillDate = Date.today().addDays(1);
        clBatchRouteProcessingSheetCreation  b = new clBatchRouteProcessingSheetCreation(fillDate,'Burr Ridge');
        Database.executeBatch(b,2000);

        Test.stopTest();
    }

    @IsTest
    static void test_remove_second_meter_from_creation() {

        Route_Schedule__c routeSchedule = [SELECT Id FROM Route_Schedule__c LIMIT 1];
        Route_Schedule_Account__c rsa = new Route_Schedule_Account__c();
        rsa.Route_Schedule__c= routeSchedule.Id;
        rsa.Account__c= [SELECT ID From Account LIMIT 1].ID;
        rsa.Collection_Type__c = 'Regular - 2nd RT';
        rsa.Redemption_Type_From_Asset__c = 'M3T';
        insert rsa;

        Route_Processing_Sheet__c rps = new Route_Processing_Sheet__c();
        rps.Route_Schedule__c = routeSchedule.Id;
        rps.Route_Schedule_Account__c = rsa.Id;
        rps.Collection_Type__c = rsa.Collection_Type__c;
        rps.Account__c = rsa.Account__c;
        insert rps;


        Test.startTest();

        clBatchRouteProcessingSheetCreation  b = new clBatchRouteProcessingSheetCreation(routeSchedule.Id,clTESTUTILS.DEFAULT_PROCESSING_LOC);
        Set<Id> filteredIds = b.remove2ndRtFromMeterCreation(new Set<Id> {rps.Id});
        System.assert(!filteredIds.contains(rps.Id));

        Test.stopTest();
    }

    @IsTest
    static void test_remove_second_meter_from_creation_regular_rt_only() {

        Route_Schedule__c routeSchedule = [SELECT Id FROM Route_Schedule__c LIMIT 1];
        Route_Schedule_Account__c rsa = new Route_Schedule_Account__c();
        rsa.Route_Schedule__c= routeSchedule.Id;
        rsa.Account__c= [SELECT ID From Account LIMIT 1].ID;
        rsa.Collection_Type__c = 'Regular - RT Only';
        rsa.Redemption_Type_From_Asset__c = 'M3T';
        insert rsa;

        Route_Processing_Sheet__c rps = new Route_Processing_Sheet__c();
        rps.Route_Schedule__c = routeSchedule.Id;
        rps.Route_Schedule_Account__c = rsa.Id;
        rps.Collection_Type__c = rsa.Collection_Type__c;
        rps.Account__c = rsa.Account__c;
        insert rps;


        Test.startTest();

        clBatchRouteProcessingSheetCreation  b = new clBatchRouteProcessingSheetCreation(routeSchedule.Id,clTESTUTILS.DEFAULT_PROCESSING_LOC);
        Set<Id> filteredIds = b.remove2ndRtFromMeterCreation(new Set<Id> {rps.Id});
        System.assert(!filteredIds.contains(rps.Id));

        Test.stopTest();
    }
}