objects/Route_Processing_Sheet__c.object
<CustomObject>
    <description>Example digitization of the route processing sheet</description>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account DBA</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Route Processing Sheets</relationshipLabel>
        <relationshipName>Route_Processing_Sheets</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Collection_Date__c</fullName>
        <label>Collection Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Processing_Status__c</fullName>
        <description>More processor based since reqs differed between the status for a collector and the status for a processor.</description>
        <inlineHelpText>More processor based since reqs differed between the status for a collector and the status for a processor.</inlineHelpText>
        <label>Fill Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>COMPLETED FILL</fullName>
                </value>
                <value>
                    <fullName>Not Yet Filled</fullName>
                    <default>true</default>
                    <label>Not Yet Filled</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Redemption_Type__c</fullName>
        <formula>Account__r.Redemption__r.GP_Manufacturer__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Redemption Type(Obsolete)</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Replenishment_Type__c</fullName>
        <label>Replenishment Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Full Audit</fullName>
                    <default>true</default>
                    <label>Full Audit</label>
                </value>
                <value>
                    <fullName>Cash Fill</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Route_Fill_Date__c</fullName>
        <description>not sure?</description>
        <inlineHelpText>not sure?</inlineHelpText>
        <label>Route Fill Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Route_Schedule__c</fullName>
        <label>Route Schedule</label>
        <referenceTo>Route_Schedule__c</referenceTo>
        <relationshipLabel>Route Processing Sheets</relationshipLabel>
        <relationshipName>Route_Processing_Sheets</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Route Processing Sheet</label>
    <nameField>
        <displayFormat>Collection-Id-{000000000}</displayFormat>
        <label>Collection ID Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Route Processing Sheets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Route_Schedule__c.object
<CustomObject>
    <description>Assignment information of a physical route&apos;s locations, collectors, vehicles, and questions for a specific day</description>
    <fields>
        <fullName>Processing_Status__c</fullName>
        <label>Processing Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Processing Incomplete</fullName>
                    <color>#FF6666</color>
                    <default>true</default>
                    <label>Processing Incomplete</label>
                </value>
                <value>
                    <fullName>COMPLETED PROCESSING</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Route_Fill_Date__c</fullName>
        <description>Not sure how this is used yet?</description>
        <inlineHelpText>Note sure how this is used yet?</inlineHelpText>
        <label>Route Fill Date</label>
        <type>Date</type>
    </fields>
    <label>Route Schedule</label>
    <nameField>
        <label>Route Schedule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Route Schedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/clRouteProcessingFillOutbound.cls
public without sharing class clRouteProcessingFillOutbound {

    @TestVisible private static final String MAP_KEY_RPS_DATA = 'RPS_WRAPPER_DATA';

    @AuraEnabled(cacheable=true)
    public static ResponseDto retrieveRpsWrapper(Id rpsId) {

        ResponseDto dto = new ResponseDto();
        dto.technicalMsg += ' rpsId param='+rpsId;
        Route_Processing_Sheet__c rpsRecord = clRouteProcessingSheetSvc.retrieveRouteProcessingSheet(rpsId);
        RpsWrapper rpsWrapper;

        if(rpsRecord != null) {
            dto.technicalMsg += ' have rps record..';
            rpsWrapper = buildRpsResponse(rpsRecord);
            dto.isSuccess = true;
        }
        dto.values.put(MAP_KEY_RPS_DATA,rpsWrapper);
        return dto;
    }

    @AuraEnabled(cacheable=true) 
    public static ResponseDto retrieveRpsWrapperNoCache(Id rpsId, Double cacheBust) {

        ResponseDto dto = new ResponseDto();
        dto.technicalMsg += ' rpsId param='+rpsId;
        Route_Processing_Sheet__c rpsRecord = clRouteProcessingSheetSvc.retrieveRouteProcessingSheet(rpsId);
        RpsWrapper rpsWrapper;

        if(rpsRecord != null) {
            dto.technicalMsg += ' have rps record..';
            rpsWrapper = buildRpsResponse(rpsRecord);
            dto.isSuccess = true;
        }
        dto.values.put(MAP_KEY_RPS_DATA,rpsWrapper);
        return dto;
    }

    @AuraEnabled
    public static ResponseDto updateRpsStatus(Route_Processing_Sheet__c rps) {

        ResponseDto dto = new ResponseDto();
        String techMsg = 'calling update with rps='+rps;
        try {
            update rps;
            dto = retrieveRpsWrapper(rps.Id);
            RpsWrapper rpsWrapper = (RpsWrapper)dto.values.get(MAP_KEY_RPS_DATA);
            techMsg += '.. update complete';
            dto.technicalMsg = techMsg;
            dto.isSuccess = true;
            dto.message = 'Successfully changed to '+rpsWrapper.rps.Processing_Status__c + '.';
        } catch (Exception e) {
            System.debug(LoggingLevel.ERROR,e);
            dto.message = e.getMessage();
            dto.technicalMsg = techMsg + 'error on update ' + e.getCause() + ' ' + e.getMessage() + ' ' + e.getStackTraceString();
        }
        return dto;
    }

    /**
     * @param rpsRecord
     * @return
     */
    private static RpsWrapper buildRpsResponse(Route_Processing_Sheet__c rpsRecord) {
        RpsWrapper rpsWrapper = new RpsWrapper(rpsRecord);
        return rpsWrapper;
    }


    public class RpsWrapper {
        @AuraEnabled public Route_Processing_Sheet__c rps;
        @AuraEnabled public Id rpsId;
        @AuraEnabled public String rpsName;
        @AuraEnabled public Id routeScheduleId;
        @AuraEnabled public String accountName;
        @AuraEnabled public Date collectionDate;
        @AuraEnabled public Date fillDate;
        @AuraEnabled public String collectionDateFormatted;
        @AuraEnabled public String fillDateFormatted;
        @AuraEnabled public String redemptionType;
        @AuraEnabled public String replenishmentType;
        @AuraEnabled public String processingFillStatus;

        public RpsWrapper(Route_Processing_Sheet__c rpsRecord) {
            this.rps = rpsRecord;
            this.rpsId = rpsRecord.Id;
            this.rpsName = rpsRecord.Name;
            this.routeScheduleId = rpsRecord.Route_Schedule__c;
            this.accountName = rpsRecord.Account__r.Name;
            this.collectionDate = rpsRecord.Collection_Date__c;
            if(this.collectionDate != null) {
                this.collectionDateFormatted = this.collectionDate.format();
            }
            this.fillDate = rpsRecord.Route_Fill_Date__c;
            if(this.fillDate != null) {
                this.fillDateFormatted = this.fillDate.format();
            }
            this.redemptionType = rpsRecord.Redemption_Type__c;
            this.replenishmentType = rpsRecord.Replenishment_Type__c;
            this.processingFillStatus = rpsRecord.Processing_Status__c;
        }
    }

}