objects/Route_Processing_Sheet__c.object
<CustomObject>
    <description>Example digitization of the route processing sheet</description>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account DBA</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Route Processing Sheets</relationshipLabel>
        <relationshipName>Route_Processing_Sheets</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Collection_Date__c</fullName>
        <label>Collection Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Collection_Type__c</fullName>
        <description>Copied down from the parent Route Schedule Account.</description>
        <inlineHelpText>Copied down from the parent Route Schedule Account.</inlineHelpText>
        <label>Collection Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Collection_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>RT_Variance__c</fullName>
        <description>Formula: Drop Totals - Receipt Totals, both NRT specific fields and M3T specific fields are included in the formula so they should never both be filled out for a location or this formula would subtract twice</description>
        <formula>((Cassette_1_Note_Count_Drop__c)*1 + (Cassette_5_Note_Count_Drop__c)*5 + (Cassette_20_Note_Count_Drop__c)*20 + (Cassette_50_Note_Count_Drop__c)*50 +(Cassette_100_Note_Count_Drop__c)*100) + Reject_Drop_Total__c + Cash_Return_Unused_Drop__c - (( BLANKVALUE(VALUE(TEXT(Cassette_1_Denomination__c)),0) *  (Cassette_1_Note_Count__c + Cassette_1_Reject_Note_Count__c)) + ( BLANKVALUE(VALUE(TEXT(Cassette_2_Denomination__c)),0) *  (Cassette_2_Note_Count__c + Cassette_2_Reject_Note_Count__c) ) + ( BLANKVALUE(VALUE(TEXT(Cassette_3_Denomination__c)),0) *  (Cassette_3_Note_Count__c + Cassette_3_Reject_Note_Count__c)) + ( BLANKVALUE(VALUE(TEXT(Cassette_4_Denomination__c)),0)*(Cassette_4_Note_Count__c + Cassette_4_Reject_Note_Count__c) )) -  ((Cassette_1_Value__c + Cassette_2_Value__c + Cassette_3_Value__c + Cassette_4_Value__c + Cassette_5_Value__c + Reject_Total__c + Cash_Return_Unused__c))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>RT Variance</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Variance__c</fullName>
        <formula>VGT_Actual_Drop__c  - (Expected_Drop__c + BV_Value__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>VGT Variance</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Route Processing Sheet</label>
    <nameField>
        <displayFormat>Collection-Id-{000000000}</displayFormat>
        <label>Collection ID Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Route Processing Sheets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

globalValueSets/Collection_Type.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Regular - RT &amp; VGT</fullName>
        <default>true</default>
        <label>Regular - RT &amp; VGT</label>
    </customValue>
    <customValue>
        <fullName>Additional Fill – RT &amp; VGT</fullName>
    </customValue>
    <customValue>
        <fullName>Additional Fill – RT Only</fullName>
    </customValue>
    <customValue>
        <fullName>Additional Fill – VGT Only</fullName>
    </customValue>
    <customValue>
        <fullName>Regular - 2nd RT</fullName>
    </customValue>
    <customValue>
        <fullName>Regular - RT Only</fullName>
    </customValue>
    <customValue>
        <fullName>Regular - VGT Only</fullName>
    </customValue>
    <customValue>
        <fullName>Regular - RT Only (Go Lives/RT swaps)</fullName>
        <isActive>false</isActive>
        <label>Regular - RT Only (Go Lives/RT swaps)</label>
    </customValue>
    <description>* Regular – RT &amp; VGT (typical collection involves changing VGT cans and swapping RT Cassettes)﻿
* Additional Fill – RT Only (this collection involves just changing RT Cassettes)﻿
* Additional Fill – VGT Only (this collection involves just swapping VGT cans)﻿
* Additional Fill – RT &amp; VGT (this collection involves changing VGT cans and swapping RT cassettes)
* Regular - 2nd RT (OLD.. not sure?)
* Regular - RT Only (NEW... not sure?)
* Regular - VGT Only (NEW.. not sure?)</description>
    <masterLabel>Collection Type</masterLabel>
</GlobalValueSet>

classes/clLinkedRpsSvc.cls
public with sharing class clLinkedRpsSvc {

    public static Boolean DEBUG_QUERY = true;

    /**
     * @param iLimit                    The query limit (number of rows) - required.
     * @param currentRpsId `            The Route_Processing_Sheet__c.Id to ignore - required.
     * @param parentAccountId           The Route_Processing_Sheet__c.Account__c - required.
     * @param hasVgtVariance            Filter for Variance__c = boolean.
     * @param hasRtVariance             Filter for RT_Variance__c = boolean.
     * @param daysBackCollectionDate    The Collection_Date__c = LAST_N_DAYS:[param].
     *
     * @return                  A list of Route_Processing_Sheet__c sObjects.
     */
    public static List<Route_Processing_Sheet__c> retrieveRpsAdvancedSearch(    Integer iLimit,
                                                                                Id currentRpsId,
                                                                                Id parentAccountId,
                                                                                Boolean hasVgtVariance,
                                                                                Boolean hasRtVariance,
                                                                                Integer daysBackCollectionDate) {
        String q = '';
        String filters = '';

        if(hasVgtVariance != null) {
            if( hasVgtVariance ) {
                filters += ' AND Variance__c != 0 ';
            } else {
                filters += ' AND Variance__c = 0 ';
            }
        }
        if(hasRtVariance != null) {
            if( hasRtVariance ) {
                filters += ' AND RT_Variance__c != 0 ';
            } else {
                filters += ' AND RT_Variance__c = 0 ';
            }
        }

        if(daysBackCollectionDate != null) {
            filters += ' AND Collection_Date__c = LAST_N_DAYS:'+daysBackCollectionDate + ' ';
        }

        q+= ' SELECT Id,Name,Collection_Date__c,Collection_Type__c,RT_Variance__c,Variance__c ';
        q+= ' FROM   Route_Processing_Sheet__c ';
        q+= ' WHERE  Id         != :currentRpsId';
        q+= ' AND    Account__c  = :parentAccountId ';
        if(filters != '') {
            q+= filters;
        }
        q+= ' ORDER  By CreatedDate DESC ';
        q+= ' LIMIT  :iLimit ';

        if(DEBUG_QUERY) {
            System.debug('---> query: ' + q);
        }
        List<Route_Processing_Sheet__c> rpss = Database.query(q);
        return rpss;
    }

    /**
     * Sum the count of RPS sObjects.
     *
     * @param currentRpsId `            The Route_Processing_Sheet__c.Id to ignore - required. `
     * @param parentAccountId           The Route_Processing_Sheet__c.Account__c - required.
     * @param hasVgtVariance            Filter for Variance__c = boolean..
     * @param hasRtVariance             Filter for RT_Variance__c = boolean.
     * @param daysBackCollectionDate    The Collection_Date__c = LAST_N_DAYS:[param].
     *
     * @return                  A Count of RPS sObjects.
     */
    public static Integer retrieveRpsAdvancedSearchTotalRecords(    Id currentRpsId, Id parentAccountId,
                                                                    Boolean hasVgtVariance, Boolean hasRtVariance,
                                                                    Integer daysBackCollectionDate ) {
        String q = '';
        String filters = '';

        if(hasVgtVariance != null) {
            if( hasVgtVariance ) {
                filters += ' AND Variance__c != 0 ';
            } else {
                filters += ' AND Variance__c = 0 ';
            }
        }
        if(hasRtVariance != null) {
            if( hasRtVariance ) {
                filters += ' AND RT_Variance__c != 0 ';
            } else {
                filters += ' AND RT_Variance__c = 0 ';
            }
        }

        if(daysBackCollectionDate != null) {
            filters += ' AND Collection_Date__c = LAST_N_DAYS:'+daysBackCollectionDate + ' ';
        }

        q+= ' SELECT Count() ';
        q+= ' FROM   Route_Processing_Sheet__c ';
        q+= ' WHERE  Id         != :currentRpsId';
        q+= ' AND    Account__c  = :parentAccountId ';
        if(filters != '') {
            q+= filters;
        }

        if(DEBUG_QUERY) {
            System.debug('---> query: ' + q);
        }
        Integer iCount = Database.countQuery(q);
        return iCount;
    }
}