objects/Route_Account__c.object
<CustomObject>
    <description>POC Junction Route__c &lt;----&gt; Account</description>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Account.Accel_VGT_Live_Date__c</field>
                <operation>notEqual</operation>
                <value></value>
            </filterItems>
            <infoMessage>Account should have a VGT Live Date</infoMessage>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Route Accounts</relationshipLabel>
        <relationshipName>Route_Accounts</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Route Account</label>
    <nameField>
        <displayFormat>RA-{00000000}</displayFormat>
        <label>RA #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Route Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/AssetSvcTest.cls
@IsTest
private class AssetSvcTest {

    /**
     * NOTE start / stop test merely there to reset gov limits as creating non cl data takes forever given
     * all the processors / flows and eventually will bust cpu time outs on it's own.
     */
    @TestSetup
    static void setupData() {

        Test.startTest();
        Map<String,Object> mBaseData = clTESTUTILS.createAllNonClData();
        Test.stopTest();

        Map<String,Object> mClData =  clTESTUTILS.createEnd2EndRouteData(mBaseData);
    }

    @IsTest
    static void test_retrieveAccountVgts() {

        Route_Account__c  routeAccount = [SELECT Id, Account__c FROM Route_Account__c LIMIT 1];

        Test.startTest();

        List<Asset> assets = AssetSvc.retrieveAccountVgts(routeAccount.Account__c);
        System.assert(!assets.isEmpty());

        Test.stopTest();
    }


    @IsTest
    static void test_retrieveAccountMachines() {

        Route_Account__c  routeAccount = [SELECT Id, Account__c FROM Route_Account__c LIMIT 1];

        Test.startTest();

        List<Asset> assets = AssetSvc.retrieveAccountMachines(routeAccount.Account__c);
        System.assert(!assets.isEmpty());

        Test.stopTest();
    }

    @IsTest
    static void test_retrieveAccountRts() {

        Route_Account__c  routeAccount = [SELECT Id, Account__c FROM Route_Account__c LIMIT 1];

        Test.startTest();

        List<Asset> assets = AssetSvc.retrieveAccountRts(routeAccount.Account__c);
        //System.assert(!assets.isEmpty());

        Test.stopTest();
    }
}