objects/ServiceAppointment.object
<CustomObject>
    <fields>
        <fullName>Accel_Solution__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Solution</label>
        <referenceTo>Solution__c</referenceTo>
        <relationshipLabel>Service Appointments</relationshipLabel>
        <relationshipName>Service_Appointments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Solution__c</fullName>
        <label>Solution</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Solution</valueSetName>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Service</fullName>
        <active>true</active>
        <label>Service</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Solution__c.object
<CustomObject>
    <description>Used for Lookup field reference as replacement for Solution picklist on Case, WorkOrder, And Service Appointment. Generally Trigger Maintained and synced (one way) ie copies value to corresponding Solution__c picklist value on Case, WorkOrder, ServiceAppointment as it was said that would cause too much reporting rewrite overhead.</description>
    <fields>
        <fullName>Status__c</fullName>
        <defaultValue>&quot;Active&quot;</defaultValue>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>InActive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Accel Solution</label>
    <nameField>
        <label>Solution Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Solutions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

globalValueSets/Solution.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Adjusted part</fullName>
    </customValue>
    <customValue>
        <fullName>Adjusted volume</fullName>
    </customValue>
    <customValue>
        <fullName>Assessed the damages and reported information to superiors</fullName>
    </customValue>
    <customValue>
        <fullName>ATM feature not enabled</fullName>
    </customValue>
    <customValue>
        <fullName>Cash drawer refill process</fullName>
    </customValue>
    <customValue>
        <fullName>Changed cash can / reject bin</fullName>
    </customValue>
    <customValue>
        <fullName>Changed comm port</fullName>
    </customValue>
    <customValue>
        <fullName>Cleaned part</fullName>
    </customValue>
    <customValue>
        <fullName>Cleared cmos</fullName>
    </customValue>
    <customValue>
        <fullName>Cleared jam</fullName>
    </customValue>
    <customValue>
        <fullName>Cleared pending transaction</fullName>
    </customValue>
    <customValue>
        <fullName>Delivered amusement equipment</fullName>
    </customValue>
    <customValue>
        <fullName>Delivered hand pay bag</fullName>
    </customValue>
    <customValue>
        <fullName>Enabled payout parameter</fullName>
    </customValue>
    <customValue>
        <fullName>Enabled validation code manually</fullName>
    </customValue>
    <customValue>
        <fullName>Exited game</fullName>
    </customValue>
    <customValue>
        <fullName>Flashed bill acceptor</fullName>
    </customValue>
    <customValue>
        <fullName>Informed location rm of issue</fullName>
    </customValue>
    <customValue>
        <fullName>Installed nrt patch</fullName>
    </customValue>
    <customValue>
        <fullName>Issued facility pay form</fullName>
    </customValue>
    <customValue>
        <fullName>Issue resolved itself</fullName>
    </customValue>
    <customValue>
        <fullName>Liquor license not in effect</fullName>
    </customValue>
    <customValue>
        <fullName>Machine pending agent appt</fullName>
    </customValue>
    <customValue>
        <fullName>Mass outage</fullName>
    </customValue>
    <customValue>
        <fullName>Move amusement equipment</fullName>
    </customValue>
    <customValue>
        <fullName>No issue</fullName>
    </customValue>
    <customValue>
        <fullName>Open &amp; closed all doors</fullName>
    </customValue>
    <customValue>
        <fullName>Powered machine up</fullName>
    </customValue>
    <customValue>
        <fullName>Provided login info to location</fullName>
    </customValue>
    <customValue>
        <fullName>Provided rm info to location</fullName>
    </customValue>
    <masterLabel>Solution</masterLabel>
</GlobalValueSet>

classes/TEST_BatchSA_HistoricalSolutions.cls
@IsTest
private class TEST_BatchSA_HistoricalSolutions{

    public static String USERNAME_ADMIN             = 'acceltestadmin@accelentertainment.com';

    @TestSetup
    static void setup() {
        User adminUser = TestUtils.getUserForTest(USERNAME_ADMIN);
        System.runAs(adminUser) {
            Test.startTest();
            //  @todo params should be set to use more then 1 record but I'm afraid to do anything in bulk these days
            //  as eventually an additional process builder or flow gets added to the stack and trips CPU
            //  Timeout limits and they arch of those is beyond my control.
            TestSvcAppointmentDataParams params = new TestSvcAppointmentDataParams();
            TestUtils.createAllDataToServiceAppointments( params );
            Test.stopTest();
        }
    }

    @IsTest
    static void test_fireBatchSaHistoricalSolutions_Commit_Success() {
        User adminUser = TestUtils.getUserForTest(USERNAME_ADMIN);

        List<String> plValues = new List<String>();
        List<Schema.PicklistEntry> plEntries = ServiceAppointment.Solution__c.getDescribe().getPicklistValues();
        for (Schema.PicklistEntry plEntry : plEntries) {  //  Dyna find good PL Values.
            if(plEntry.active) {
                plValues.add(plEntry.getValue());
            }
        }
        List<ServiceAppointment> testServiceAppointments = [
                SELECT  Id, Solution__c, Accel_Solution__c, Accel_Solution__r.Name
                FROM    ServiceAppointment
        ];
        for(ServiceAppointment sa : testServiceAppointments) {
            sa.Solution__c = plValues[0];  //  Update the SA to have PL val
            sa.Accel_Solution__c = null;
        }
        update testServiceAppointments;
        insert ( new Solution__c(Name = plValues[0] , Status__c = 'Active' ) );

        Integer iTotalSasThatShouldBeUpdated = testServiceAppointments.size();

        System.runAs(adminUser) {
            Test.startTest();

            List<String> emails = new List<String> {'rick@chicagosalesforceconsulting.com'};
            Boolean bCommit = true;
            BatchSA_HistoricalSolutions b = new BatchSA_HistoricalSolutions(emails,bCommit);
            Id batchJobId = Database.executeBatch(b);
            System.assert(batchJobId != null);

            Test.stopTest();

            List<ServiceAppointment> serviceAppointmentsUpdated = [
                    SELECT Id, Accel_Solution__c, Solution__c
                    FROM   ServiceAppointment
                    WHERE  Accel_Solution__c != NULL
            ];
            System.assertEquals(serviceAppointmentsUpdated.size(), iTotalSasThatShouldBeUpdated,
                    '# of Service appointments updated should eq ' + iTotalSasThatShouldBeUpdated + ' it does not!');
        }
    }

    @IsTest
    static void test_fireBatchSaHistoricalSolutions_Rollback() {
        User adminUser = TestUtils.getUserForTest(USERNAME_ADMIN);

        List<String> plValues = new List<String>();
        List<Schema.PicklistEntry> plEntries = ServiceAppointment.Solution__c.getDescribe().getPicklistValues();
        for (Schema.PicklistEntry plEntry : plEntries) {  //  Dyna find good PL Values.
            if(plEntry.active) {
                plValues.add(plEntry.getValue());
            }
        }
        List<ServiceAppointment> testServiceAppointments = [
                SELECT  Id, Solution__c, Accel_Solution__c, Accel_Solution__r.Name
                FROM    ServiceAppointment
        ];
        for(ServiceAppointment sa : testServiceAppointments) {
            sa.Solution__c = plValues[0];  //  Update the SA to have PL val
            sa.Accel_Solution__c = null;
        }
        update testServiceAppointments;
        insert ( new Solution__c(Name = plValues[0] , Status__c = 'Active' ) );

        System.runAs(adminUser) {
            Test.startTest();

            BatchSA_HistoricalSolutions b = new BatchSA_HistoricalSolutions();
            Id batchJobId = Database.executeBatch(b);
            System.assert(batchJobId != null);

            Test.stopTest();

            List<ServiceAppointment> serviceAppointmentsUpdated = [
                    SELECT Id, Accel_Solution__c, Solution__c
                    FROM   ServiceAppointment
                    WHERE  Accel_Solution__c != NULL
            ];
            System.assert(serviceAppointmentsUpdated.isEmpty(),'We should not have updated any Service' +
                    ' appointments on a rollback. There were updates.');
        }
    }

    @IsTest
    static void test_fireBatchSaHistoricalSolutions_Commit_ForceException() {
        User adminUser = TestUtils.getUserForTest(USERNAME_ADMIN);

        List<String> plValues = new List<String>();
        List<Schema.PicklistEntry> plEntries = ServiceAppointment.Solution__c.getDescribe().getPicklistValues();
        for (Schema.PicklistEntry plEntry : plEntries) {  //  Dyna find good PL Values.
            if(plEntry.active) {
                plValues.add(plEntry.getValue());
            }
        }
        List<ServiceAppointment> testServiceAppointments = [
                SELECT  Id, Solution__c, Accel_Solution__c, Accel_Solution__r.Name
                FROM    ServiceAppointment
        ];
        for(ServiceAppointment sa : testServiceAppointments) {
            sa.Solution__c = plValues[0];  //  Update the SA to have PL val
            sa.Accel_Solution__c = null;
        }
        update testServiceAppointments;
        insert ( new Solution__c(Name = plValues[0] , Status__c = 'Active' ) );

        System.runAs(adminUser) {
            Test.startTest();

            List<String> emails = new List<String> {'rick@chicagosalesforceconsulting.com'};
            Boolean bCommit = true, bFakeException = true;

            BatchSA_HistoricalSolutions b = new BatchSA_HistoricalSolutions(emails,bCommit, 'TEST_ASYNC_JOB_NAME', bFakeException);
            Id batchJobId = Database.executeBatch(b);
            System.assert(batchJobId != null);

            Test.stopTest();

            List<ServiceAppointment> serviceAppointmentsUpdated = [
                    SELECT Id, Accel_Solution__c, Solution__c
                    FROM   ServiceAppointment
                    WHERE  Accel_Solution__c != NULL
            ];
            System.assert(serviceAppointmentsUpdated.isEmpty());
        }
    }
}