objects/ServiceResource.object
<CustomObject>
    <fields>
        <fullName>Accel_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Accel User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Service_Resources</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Shift.object
<CustomObject>
    <fields>
        <fullName>Secondary_Service_Territory__c</fullName>
        <description>Controls the creation, edit, and deletion of Service Territory Membership with Type S via flow.</description>
        <inlineHelpText>Picklist to allow a Service Resource to be assigned Service Appointments from a different Service Territory. May be left as None.</inlineHelpText>
        <label>Secondary Service Territory</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Active_Territories</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

globalValueSets/Active_Territories.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Collinsville</fullName>
    </customValue>
    <customValue>
        <fullName>Watseka</fullName>
    </customValue>
    <customValue>
        <fullName>Champaign</fullName>
    </customValue>
    <customValue>
        <fullName>Rockford</fullName>
    </customValue>
    <customValue>
        <fullName>Springfield</fullName>
    </customValue>
    <customValue>
        <fullName>Peoria</fullName>
    </customValue>
    <masterLabel>Active Territories</masterLabel>
</GlobalValueSet>

classes/ShiftTriggerTest.cls
@isTest
private class ShiftTriggerTest{
    @TestSetup
    static void makeData(){
        Profile p = [select id from profile limit 1];
        
        User u = [select id from user limit 1];
        
        ServiceResource sr = new ServiceResource(Name='test', IsActive=true, RelatedRecordId=u.Id, Accel_User__c=u.Id, ResourceType = 'T');
        insert sr;
        
        Shift s = new Shift(ServiceResource=sr,Status='Tentative', StartTime=Datetime.newInstance(2022,1,1,9,0,0), EndTime=Datetime.newInstance(2022,1,1,10,0,0), TimeSlotType='Normal', Secondary_Service_Territory__c='Rockford');
        insert s;
    }
    
    
    @isTest
    static void testDupe(){
        Test.startTest();
        try{
            ServiceResource sr = [select id from ServiceResource limit 1];
        	Shift s = new Shift(ServiceResource=sr,Status='Tentative', StartTime=Datetime.newInstance(2022,1,1,9,0,0), EndTime=Datetime.newInstance(2022,1,1,10,0,0), TimeSlotType='Normal', Secondary_Service_Territory__c='Rockford');
        	insert s;
        }catch(Exception e){
            System.assertNotEquals(null, e.getMessage());
        }
		Test.stopTest();
       	List<Shift> shifts = [select id from Shift];
        System.assertEquals(1, shifts.size());
    }
    
    @isTest
    static void testSuccess(){
        Test.startTest();
        ServiceResource sr = [select id from ServiceResource limit 1];
        Shift s = new Shift(ServiceResource=sr,Status='Tentative', StartTime=Datetime.newInstance(2022,1,2,9,0,0), EndTime=Datetime.newInstance(2022,1,2,10,0,0), TimeSlotType='Normal', Secondary_Service_Territory__c='Rockford');
        insert s;
		Test.stopTest();
       	List<Shift> shifts = [select id from Shift];
        System.assertEquals(2, shifts.size());
    }
}